.github/workflows/ci.yml
Got no clue, Clippy just doesn't want to go away. (it's merged into the build and test flow)
Improvements are mostly just from added caching. Still some work left to make the macOS builds install sccache faster (not via brew) but moving on for now. It's not perfect yet, but should drop the entire build to ~15 min on avg from 30ish min. On a good run with a full cache hit, takes <10 min. Most of it is just setup that's slow on some platforms.
=> fix: add cache to ci

iroh-gateway/Cargo.toml, iroh-gateway/src/constants.rs, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/metrics.rs, iroh-gateway/src/response.rs
Part of https://github.com/n0-computer/iroh/issues/22
=> feat: add trace id to responses

iroh-gateway/Cargo.toml, iroh-gateway/src/client.rs, iroh-gateway/src/core.rs, iroh-gateway/src/metrics.rs
This is 95% simulated (add a ~10-20 kb file in `test_files/test_big.txt` to play with it) but allows us to get some basics in and get metrics pumping to work on the ops side.
=> impl: cursory metrics & streaming

.github/workflows/ci.yml
builds gateway in release mode and publishes to s3. Currently a very simple setup. Once the rest starts shaping up, the intent is to separate out the job, only run on main and build for all OS & Arch versions we want to support, for each of the services by making a quick matrix of options.
=> feat: upload gateway builds to s3 (linux/amd64)

.github/workflows/ci.yml, iroh-bitswap/Cargo.toml, iroh-gateway/Cargo.toml, iroh-gateway/src/client.rs, iroh-gateway/src/config.rs, iroh-gateway/src/constants.rs, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/headers.rs, iroh-gateway/src/lib.rs, iroh-gateway/src/main.rs, iroh-gateway/src/metrics.rs, iroh-gateway/src/response.rs, iroh-metrics/Cargo.toml, iroh-metrics/src/lib.rs
Does a number of things:
- covers most of our GET flow
- refactor
- metrics/logging now have sane defaults
- fixes CI builds & ignores windows
=> fix: gateway upgrade

Cargo.toml, iroh-bitswap/Cargo.toml, iroh-gateway/Cargo.toml, iroh-p2p/Cargo.toml, iroh-rpc-client/Cargo.toml, iroh-rpc-types/Cargo.toml
Depends on my fork, because it needs https://github.com/libp2p/rust-libp2p/pull/2658
=> feat: switch to libp2p@0.45

iroh-gateway/Cargo.toml, iroh-gateway/src/client.rs, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/main.rs, iroh-gateway/src/metrics.rs, iroh-metrics/Cargo.toml, iroh-metrics/src/config.rs, iroh-metrics/src/lib.rs, iroh-p2p/Cargo.toml, iroh-p2p/src/main.rs, iroh-p2p/src/service.rs
Does:
- move from `metrics` to `prometheus-client`
- brings us in line with what most others use
- compat with libp2p metrics
- libp2p metrics are flowing now
Breaks:
- current dashboards
- needed to drop old counters
- will have to reduce the noise/chatter, libp2p is vv noisy
To do:
- ~~clean it up a bit~~
- ~~gateway metrics registering should use a sub registry~~
- ~~need to mutex lock all the Arc<State> or something along the lines for the metrics component~~ - not needed as of `prometheus-client = 0.16.0`
=> rework: metrics

iroh-gateway/src/client.rs
Obviously these are crappy metrics just to fill in some blanks. We need to disambiguate between cached and non cached responses and segment accordingly.
=> fix: avoid 0 divisions

Cargo.toml, iroh-ctl/Cargo.toml, iroh-ctl/src/README.md, iroh-ctl/src/lib.rs, iroh-ctl/src/main.rs, iroh-ctl/src/status.rs, iroh-gateway/Cargo.toml, iroh-gateway/src/core.rs, iroh-gateway/src/lib.rs, iroh-gateway/src/rpc.rs, iroh-p2p/Cargo.toml, iroh-p2p/src/rpc.rs, iroh-rpc-client/Cargo.toml, iroh-rpc-client/src/client.rs, iroh-rpc-client/src/gateway.rs, iroh-rpc-client/src/lib.rs, iroh-rpc-client/src/network.rs, iroh-rpc-client/src/status.rs, iroh-rpc-client/src/store.rs, iroh-rpc-types/Cargo.toml, iroh-rpc-types/build.rs, iroh-rpc-types/proto/gateway.proto, iroh-rpc-types/proto/test.proto, iroh-rpc-types/src/gateway.rs, iroh-rpc-types/src/lib.rs, iroh-rpc-types/src/test.rs, iroh-store/Cargo.toml, iroh-store/src/rpc.rs
Adds `check` and `watch` methods for the rpc `Client`, that return a `StatusTable` or a stream of `StatusTable`s.
A `StatusTable` is a struct with a set of `StatusRow`s, one for the `gateway`, `p2p`, and `store` rpc servers. This is currently hardcoded as having one "slot" for each process, but in the future should be made more flexible to allow for mulitple `gateway`s, `p2p` nodes, and `store`s.
The status of each row is based on `tonic_health::ServingStatus`, and is received by calling `check` or `watch` on the `HealthServer` of each process. Each rpc server now starts up a `HealthServer` service.
In the future, we may want to implement our own version of `HealthReporter` and `HealthServer`, so we can more finely control and pass through the status of each process.
=> feat: `iroh-ctl status -w` watches the health of each iroh process

iroh-gateway/Cargo.toml, iroh-gateway/src/core.rs, iroh-gateway/src/main.rs
Also, adds `/health` endpoint that returns both status code OK, and string "OK".
closes #106
=> fix: rpc creation no longer blocks the gateway

Cargo.toml, iroh-bitswap/src/behaviour.rs, iroh-bitswap/src/query.rs, iroh-bitswap/src/session.rs, iroh-p2p/src/behaviour.rs, iroh-p2p/src/config.rs, iroh-p2p/src/rpc.rs, iroh-p2p/src/service.rs
Integrates https://github.com/libp2p/rust-libp2p/pull/2712 to fetch providers more quickly. For widely available providers this reduces the fetch time considerably.
=> feat: improve provider fetching

iroh-p2p/Cargo.toml, iroh-p2p/src/behaviour.rs, iroh-p2p/src/config.rs, iroh-p2p/src/service.rs
=> feat(p2p): implement hole punching

iroh-ctl/Cargo.toml, iroh-ctl/src/gateway.rs, iroh-ctl/src/lib.rs, iroh-ctl/src/main.rs, iroh-ctl/src/p2p.rs, iroh-ctl/src/store.rs, iroh-gateway/src/rpc.rs, iroh-p2p/src/rpc.rs, iroh-rpc-client/src/gateway.rs, iroh-rpc-client/src/network.rs, iroh-rpc-client/src/store.rs, iroh-rpc-types/proto/gateway.proto, iroh-rpc-types/proto/p2p.proto, iroh-rpc-types/proto/store.proto, iroh-store/src/rpc.rs
Also stubs in planned commands.
closes #24 
closes #25
=> feat(iroh-ctl): implement available commands

iroh-car/Cargo.toml, iroh-gateway/src/config.rs, iroh-gateway/src/core.rs, iroh-gateway/src/main.rs, iroh-p2p/Cargo.toml, iroh-p2p/src/behaviour.rs, iroh-p2p/src/config.rs, iroh-p2p/src/main.rs, iroh-p2p/src/node.rs, iroh-p2p/src/rpc.rs, iroh-resolver/src/resolver.rs, iroh-rpc-client/Cargo.toml, iroh-rpc-client/src/macros.rs, iroh-rpc-types/Cargo.toml, iroh-rpc-types/src/addr.rs, iroh-rpc-types/src/macros.rs, iroh-share/Cargo.toml, iroh-share/src/lib.rs, iroh-share/src/main.rs, iroh-share/src/p2p_node.rs, iroh-share/src/receiver.rs, iroh-share/src/sender.rs, iroh-store/benches/rpc.rs, iroh-store/benches/store.rs, iroh-store/src/config.rs, iroh-store/src/main.rs, iroh-store/src/store.rs
When sending parallel queries through the rpc transport,
they were not properly mapped to the responses before.
Fixes #165
=> fix: correctly map memory channels

iroh-gateway/src/main.rs, iroh-metrics/src/config.rs, iroh-metrics/src/lib.rs, iroh-p2p/src/main.rs, iroh-p2p/src/node.rs, iroh-share/src/p2p_node.rs, iroh-store/src/main.rs
We can now turn tracing and metrics on independently. 
Also by default now they are off and the expectations is you will know what you're doing if you do want to set it up.
Remains to be able to toggle this at compile time too.
Closes https://github.com/n0-computer/iroh/issues/114 & tracks the compile time config at https://github.com/n0-computer/iroh/issues/149
=> fix: default off metrics & tracing

examples/Cargo.toml, examples/src/bin/importer.rs, iroh-p2p/Cargo.toml, iroh-p2p/src/node.rs, iroh-resolver/Cargo.toml, iroh-resolver/src/lib.rs, iroh-resolver/src/resolver.rs, iroh-util/Cargo.toml, iroh-util/src/lib.rs
The dependency is causing issues when working on a 'all in one' daemon using memory channels
for rpc: we end up with a circular dependency: resolver -> p2p -> resolver.
Since the only use is the 'verify_hash()' function, this patch moves it to the
iroh_util crate and updates the call sites accordingly.
=> Remove resolver dependency from p2p

.circleci/config.yml
I've set up my local box to run builds. 
All builds are now sequential for mac but still:
- it's essentially free
- individual build time down from 40ish min to 7ish min
- total build time down from 40ish min to 15ish min
Will be more congested once we have more PR volume but shouldn't be a biggie for a while. Can always add more boxes.
=> ci: self hosted mac runner

iroh-gateway/src/constants.rs, iroh-gateway/src/headers.rs, iroh-gateway/src/response.rs
This fixes https://github.com/n0-computer/iroh/issues/195
=> iroh-gateway: Don't send application/octet-stream content-type header

iroh-p2p/src/behaviour.rs, iroh-p2p/src/config.rs, iroh-p2p/src/node.rs
I'm not sure what the consequences are to disable it, so maybe we don't want that at all? Eg. would that prevent 2 peers to discover each other and run bitswap with just mdns enabled?
cc @dignifiedquire
=> feat: Make gossipsub configurable

iroh-resolver/src/balanced_tree.rs, iroh-resolver/src/lib.rs, iroh-resolver/src/unixfs.rs, iroh-resolver/src/unixfs_builder.rs, iroh-share/src/lib.rs
When adding content to iroh, create a balanced tree.
Our balanced tree implementation takes a stream of
chunks (`BytesMut`) and returns a stream of Bytes
of the encoded nodes of the dag, and their associated Cids.
`(Cid, Bytes)`
The implementation emits the node as soon as it has
been created.
All the leaves of the tree are encoded as unixfs `Raw`
nodes. All the stems & the root of the tree are encoded
as unixfs `File` nodes.
We've put effort into having our nodes be as similar to
kubo as possible, but we have intentionally differed in
a few ways:
- all of our "stem" nodes have `name: None`. In kubo, the
parents of leaf nodes have the go equivalent of
`name: Some("".to_string())`.
- the `tsize` of our links is the cumulative size of
the encoded tree associated with that link. The …
=> feat(iroh-resolver): create a balanced tree dag

README.md, quickstart.md
we're not ready to launch a full docs site yet, so let's add a bit more to the readme, and move the quickstart guide into the repo while we work toward a release
closes #208, closes #210
=> docs: beef up readme, add quickstart

iroh-gateway/src/core.rs, iroh-one/src/config.rs, iroh-one/src/main.rs, iroh-one/src/uds.rs, iroh-rpc-types/src/macros.rs
Not perfect but improves the situation around the lines of what is discussed in https://github.com/n0-computer/iroh/issues/223
In general the default configuration is created first, and then overridden by other configuration sources so it's a bit annoying to know if we still use a default value or not, without adding flags to track that. I don't think the added complexity would be warranted.
r? @dignifiedquire
=> Improve error management and reporting when using unix domain sockets

.circleci/config.yml, iroh-bitswap/src/behaviour.rs, iroh-bitswap/src/message.rs, iroh-bitswap/src/session.rs, iroh-car/src/header.rs, iroh-gateway/src/response.rs, iroh-metrics/src/config.rs, iroh-metrics/src/lib.rs, iroh-p2p/src/config.rs, iroh-resolver/src/chunker.rs, iroh-resolver/src/unixfs.rs, iroh-share/src/p2p_node.rs, stores/flatfs/src/flatfs.rs
Also, as per
https://rust-lang.github.io/rust-clippy/master/index.html#derive_partial_eq_without_eq derive `Eq` in any public struct that also impls `PartialEq`.
=> refactor: ignore clippy warnings for generated code

iroh-gateway/src/headers.rs
"0" is not a valid value (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Last-Modified) and for ipfs/ fetches the etag header and the immutable cache control value give the proper caching behavior from browsers.
=> Remove invalid If-Modified-Since header

iroh-gateway/Cargo.toml, iroh-metrics/Cargo.toml, iroh-store/Cargo.toml
opentelemetry was pulling in tonic 0.6.2 while iroh uses the latest 0.8. With this update we don't have a 2 versions of tonic in the build anymore.
=> Update opentelemetry to 0.18

iroh-gateway/src/bad_bits.rs, iroh-gateway/src/client.rs, iroh-gateway/src/core.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/main.rs, iroh-one/Cargo.toml, iroh-one/src/content_loader.rs, iroh-one/src/lib.rs, iroh-one/src/main.rs, iroh-one/src/uds.rs
The main change is to switch `iroh-gateway/src/client.rs#Client` to be:
`pub struct Client<T: ContentLoader>` and to sprinkle the generic and
other needed bounds where needed.
`iroh-one/src/content_loader.rs` showcases a custom content loader. For now it's
similar to the regular one without the gateway racing implementation.
=> Allow to pass custom resolvers

iroh-one/Cargo.toml, iroh-one/README.md, iroh-one/src/main.rs, iroh-p2p/Cargo.toml
The current code also turns off the grpc control endpoint, but we need to keep it available in all configurations.
The fix in iroh-p2p/Cargo.toml makes it possible to build iroh-one or iroh-p2p without building the whole workspace.
=> fix: use the uds-gateway feature only to control the http uds endpoint

iroh-one/src/config.rs
- key_store_path was an empty path, instead of the data root as used by iroh-p2p.
- the gateway_addr was still bound to the uds-gateway feature, which was a mistake.
This fixes https://github.com/n0-computer/iroh/issues/255
=> fix: properly setup the default config for iroh-one

iroh-resolver/Cargo.toml, iroh-resolver/src/resolver.rs, iroh-resolver/src/unixfs_builder.rs
This adds roundtrip tests based on randomly generated data, for both files and directories.
=> property based tests for unixfs

iroh-bitswap/README.md, iroh-car/README.md, iroh-ctl/README.md, iroh-gateway/README.md, iroh-metrics/README.md, iroh-one/README.md, iroh-p2p/README.md, iroh-resolver/README.md, iroh-rpc-client/README.md, iroh-rpc-types/README.md, iroh-store/README.md, iroh-util/README.md
When I was going through the iroh crates I noticed that the readmes were rather minimal or absent. Now each iroh crate (except iroh itself which is still empty) contains a basic README with some explanation of what's going on on. This is to the best of my knowledge, so this is also a way to test my knowledge - please comment where I'm wrong to improve my understanding.
This supercedes the PR here: https://github.com/n0-computer/iroh/pull/237 where I got myself in some sort of rebase pickle.
=> docs: write some basic documentation for the various iroh crates

iroh-resolver/src/unixfs_builder.rs
I forgot I fixed this determinism error before and just ran into it again in a stale branch. I did more research and determined it wasn't due to a hashmap but due to the platform not guaranteeing order, so fixed the comment.
=> docs: better comment

iroh-resolver/src/balanced_tree.rs, iroh-resolver/src/unixfs.rs
`filesize` is the cumulative size of all the raw data in the tree
`blocksizes` is an array of the size of the raw data pointed to by the given node's links
closes #200
=> feat(unixfs): add `filesize` and `blocksizes` for `UnixfsNode::File` nodes

iroh-one/src/main.rs, iroh-util/.gitignore, iroh-util/Cargo.toml, iroh-util/src/lib.rs, iroh-util/src/lock.rs
This addresses https://github.com/n0-computer/iroh/issues/177 (and https://github.com/n0-computer/iroh/issues/231)
cc @dignifiedquire : I implemented a non opinionated way to acquire a lock and check its state. The example use in iroh-one works as expected so we can generalize to other binaries if the api is fine.
=> feat: provide a mechanism to check if an iroh program is already running

iroh-one/src/config.rs
use store exported path in iroh-one.
closes #255, closes #309. cc @fabricedesre
=> fix(iroh-one): use default store path when no --store-path flag present

iroh-car/Cargo.toml
Before:
```shell
iroh (main)> cargo tree -i -p prost
error: There are multiple `prost` packages in your project, and the specification `prost` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
prost@0.9.0
prost@0.10.4
prost@0.11.0
```
After:
```shell
iroh (main)> cargo tree -i -p prost
error: There are multiple `prost` packages in your project, and the specification `prost` is ambiguous.
Please re-run this command with `-p <spec>` where `<spec>` is one of the following:
prost@0.10.4
prost@0.11.0
```
I'm trying to get rid of the last dupe in https://github.com/ipld/libipld/pull/152 but windows CI gets in the way...
=> fix: Update ipld in iroh-car to limit prost duplicates

iroh-car/src/header.rs, iroh-gateway/Cargo.toml, iroh-gateway/src/client.rs, iroh-gateway/src/constants.rs, iroh-gateway/src/core.rs, iroh-gateway/src/handlers.rs, iroh-resolver/src/resolver.rs
Hi!
I was looking on how to use iroh from other codebases, and a bit of a precursor to a writable gateway, this PR adds functionality to fetch a DAG recursively into a CAR file. This was already stubbed in the gateway but not implemented.
The implementation works similar to the existing recursive loaders. However to save the cost of reserializing, I added a new `OutRaw` struct in the resolver for this (because the `Out` struct in the resolver currently only keeps the deserialized representation for UnixFS nodes). Currently, the nodes are still fully deserialized anyways for link scraping but that would be fixed with #297.
What's still missing is, I think, a configurable upper limit on DAG sizes that can be requested from the Gateway to avoid DoS attacks. Also misses tests, I can add some …
=> Gateway: Fetch recursive DAG as CAR

iroh-gateway/src/core.rs, iroh-resolver/src/balanced_tree.rs, iroh-resolver/src/resolver.rs, iroh-resolver/src/unixfs.rs, iroh-resolver/src/unixfs_builder.rs, iroh-share/src/sender.rs, iroh-store/src/store.rs
Note that this may lead to decreased performance, since we are doing more work than before. But the store needs this information.
The way links are parsed can be optimized, see #297 . And I am not quite sure if finding links should not be done on the store side. But that is another discussion to be had.
Fixes #287
=> fix: pass links to store when adding data

iroh-p2p/src/behaviour.rs
This allows adding large files without getting an error. It is a stopgap until we have a persistent kad store.
Before:
```
❯ time cargo run --release -p iroh-ctl -- add --no-wrap test1g  
Finished release [optimized] target(s) in 0.17s
Running `target/release/iroh add --no-wrap test1g`
Error: status: Internal, message: "the store cannot contain any more provider records", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc", "date": "Tue, 11 Oct 2022 10:39:21 GMT", "content-length": "0"} }
cargo run --release -p iroh-ctl -- add --no-wrap test1g  0.71s user 0.33s system 7% cpu 13.072 total
```
After:
```
❯ time cargo run --release -p iroh-ctl -- add --no-wrap test1g
Finished release [optimized] target(s) in 0.18s
Running `target/release/iroh add --no-wrap …
```
=> fix(p2p): Increase the size of the kad mem store

iroh-resolver/src/resolver.rs
Acknowledges that a `raw` node is a valid `UnixfsNode` and therefore can be resolved as a file in the gateway
closes #326
=> fix: allow `Raw` as `UnixfsType`

.gitignore
This tripped up some test fixtures I wrote where I had inadvertently created a directory `foo` and hadn't realized they were never actually checked in. Was a bit of a headscratcher we want to prevent in the future.
=> fix: stop preventing any directory or file `foo` from existing in the project

iroh-gateway/src/client.rs, iroh-gateway/src/handlers.rs, iroh-resolver/src/resolver.rs
also reverts previous commit that made a bad assumption about allowing `Raw` as a `UnixfsType` in the resolver
=> fix(iroh-gateway): add `FileType::Raw` option

iroh-store/src/store.rs
This makes the code less verbose, and also will be helpful if we can figure out how to permanently store the cf handles.
See https://github.com/rklaehn/iroh/commit/4c2d3261a8d40cd63686f17aa52996740263cae5 for how that might work, in case the cf handles are thread safe.
=> refactor: DRY store code

iroh-gateway/Cargo.toml, iroh-gateway/src/bad_bits.rs, iroh-gateway/src/client.rs, iroh-gateway/src/config.rs, iroh-gateway/src/constants.rs, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/headers.rs, iroh-gateway/src/response.rs, iroh-one/src/content_loader.rs, iroh-resolver/src/resolver.rs, iroh-share/src/p2p_node.rs
Tackles https://github.com/n0-computer/iroh/issues/277
Closes: 
- https://github.com/n0-computer/iroh/issues/230
- https://github.com/n0-computer/iroh/issues/103
- https://github.com/n0-computer/iroh/issues/197
- https://github.com/n0-computer/iroh/issues/98
- https://github.com/n0-computer/iroh/issues/89
Various other QoL fixes, most of the `ETag` support (missing dir etags), `HEAD` request handling (missing a small bit to be done), ensures headers, params etc are in line with spec.
Remainder of work will continue to be tracked on the tracker issue.
=> gateway: spec parity

iroh/src/run.rs
I've gone through the `add` and `get` command to try to match the text with the issues #269 and #270 
In a few places I took the liberty to tweak the text for clarity.
This goes with "true clap" flags even though they're negatives as I described in #310
=> feat: improve CLI texts and flags

iroh-api/src/api.rs, iroh-gateway/src/client.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/headers.rs, iroh-resolver/src/resolver.rs, iroh-resolver/src/unixfs.rs, iroh-resolver/src/unixfs_builder.rs, iroh-share/src/receiver.rs
Closes https://github.com/n0-computer/iroh/issues/130
=> feat: range request support

xtask/Cargo.toml, xtask/src/main.rs
fixes `private` config in the `xtask` crate (should be `publish = false`).
Adds new `cargo xtask dev-install` that'll copy all binaries to `$HOME/.cargo/bin/`, which is useful while I'm working on `iroh start`.
Optionally run `cargo xtask dev-install --build` to run a build of all binaries first
=> chore: add dev-install xtask

iroh-gateway/src/client.rs, iroh-one/Cargo.toml, iroh-one/src/config.rs, iroh-one/src/content_loader.rs, iroh-one/src/main.rs, iroh-resolver/src/resolver.rs
This adds to iroh-one a new optional configuration item: resolver_gateway
If resolver_gateway is set, the resolver will race the p2p node with fetching a raw block from the gateway.
A new source is also introduced to classify blocks coming from a gateway out from those fetched from p2p or store. Hits from the gateway are considered as not cached for telemetry purposes.
ping @b5
=> feat: race a http gateway with p2p in iroh-one's content loader

iroh-store/Cargo.toml, iroh-store/src/cf.rs, iroh-store/src/store.rs
=> Map id to cid instead of multihash

iroh/src/main.rs, iroh/src/run.rs
I broke the error handling in `iroh add` by inadvertently swallowing an error. This PR fixes this and introduces a `transform_error` strategy which looks for the root cause and tries to create a better error message as in #355
=> Connection error

.github/workflows/ci.yml
Edit, sadly GHA are very resource constrained and a frequent issue (which is already breaking builds) is running out of disk. Doing some "official hacks" to claim back some more on ubuntu. Will follow along for other platforms as needed.
=> fix: gha disk space hacks

iroh-resolver/src/resolver.rs
...without having to create an AST. Should be much faster.
This has been working all the time for dag-cbor since we needed that at actyx, but I have also made the dag-pb case a bit faster in https://github.com/ipld/libipld/pull/155
=> perf: Use the libipld built in way to scrape references

iroh-api/Cargo.toml, iroh-api/src/error.rs, iroh-api/src/lib.rs, iroh-api/src/p2p.rs, iroh/src/main.rs
Work into handling errors related to services that are down. p2p subsytem gets it's own specific error feedback + hint, and clean up the boilerplate error for connection refusal cases we don't specifically handle:
related to #399
=> feat: p2p api service calls with a p2p-specific error, better feedback

iroh-api/src/lib.rs, iroh-api/src/p2p.rs, iroh/src/doc.rs, iroh/src/p2p.rs
```
$ iroh p2p peers --help
List connected peers
Usage: iroh p2p peers
Options:
-h, --help     Print help information
-V, --version  Print version information
'p2p peers' lists the set of peer addresses this node is currently connected to.
The address format is a multiaddress, or 'multiaddr' for short. For example:
/ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
The last element after the '/' is the Peer Identifier or 'PeerID'. Either the
PeerID or the entire multiaddr can be given to the 'p2p lookup' command
for additional details about the peer. For example:
> iroh p2p lookup QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
> iroh p2p lookup /ip4/104.131.131.82/tcp/4001/p2p/QmaCpDMGvV2BGHeYERUEnRQAwe3N8SzbUtfsmvsqQLuvuJ
For more info on multiaddrs see …
```
=> `iroh p2p peers`: command to list peers

iroh-api/Cargo.toml, iroh-api/src/api_ext.rs, iroh-bitswap/src/server.rs, iroh-resolver/benches/unixfs.rs, iroh-resolver/src/unixfs_builder.rs, iroh-store/src/config.rs, iroh/Cargo.toml, iroh/src/fixture.rs, iroh/src/run.rs, iroh/tests/cmd/add_directory.trycmd, iroh/tests/cmd/add_file.trycmd
- parallelize stream processing for raw add
- improve displayed content when using iroh add
=> feat: improve add experience

iroh-gateway/src/cli.rs, iroh-gateway/src/config.rs, iroh-gateway/src/main.rs, iroh-one/src/config.rs, iroh-one/src/lib.rs, iroh-one/src/main.rs, iroh-resolver/Cargo.toml, iroh-resolver/src/lib.rs, iroh-resolver/src/racing.rs
tried to make this as not-terrible as possible, by requiring an array of gateways, and randomly choosing a gateway when more than one is supplied.
=> race on gateway

iroh-resolver/src/balanced_tree.rs
The most expensive thing when adding a file is hashing the content.
This adds parallelism to this hashing by splitting the tree building into two stages. One where the leafs are encoded, and one where the actual tree is being built.
This makes sure that iroh-cli now uses all available cores, and therefore increases perf quite a bit. But we are now limited by the DB.
=> perf: add parallelism to hashing

iroh/src/run.rs, iroh/src/services.rs
I have no idea what this does for our provide story if a user adds content offline then tries to take it online, but this makes our perf measurable.
I still think we should provide the root to the DHT by default. It's usually what users are trying to do, and while it's slower, it's the de-facto use case
=> feat: offline adding

iroh-resolver/src/unixfs_builder.rs, iroh-rpc-client/src/store.rs, iroh-rpc-types/proto/store.proto, iroh-rpc-types/src/store.rs, iroh-store/src/rpc.rs, iroh-store/src/store.rs
This requires getting rid of a lot of async in the store. Async only in the public interface.
I want to do some more reorg here, but in the interest of getting something on main soon I will refrain from it...
=> perf: impl put_many and reuse column families

iroh-resolver/src/unixfs_builder.rs, iroh-store/benches/store.rs, iroh-store/src/rpc.rs, iroh-store/src/store.rs
This separates the store code into a LocalStore where all the things happen, that can properly store column family handles etc. and a Store that is just a forwarder for which RpcStore is implemented.
I think this is much nicer. We might want to use spawn_local at the async -> synchronous boundary though.
This is based on https://github.com/n0-computer/iroh/pull/412 , so once that is merged the diff would get smaller.
=> Cleanup of store code

iroh-bitswap/build.rs, iroh-localops/src/process.rs, iroh-resolver/build.rs, iroh-rpc-types/build.rs, iroh-store/src/store.rs, iroh-util/src/lib.rs, iroh-util/src/lock.rs, stores/flatfs/src/flatfs.rs, xtask/src/main.rs
This applies clippy rules for Rust 1.65.
=> chore(clippy): Update for rust 1.65

iroh-p2p/Cargo.toml, iroh-p2p/benches/lru_cache.rs, iroh-p2p/src/behaviour/peer_manager.rs
Change the LRU cache from the caches crate to the lru crate.  This crate is much simpler and does not depend on a vulnerable version of the time crate, resolving our cargo-audit issues.
A benchmark is included showing our use of the LRU cache to have no notable performance difference between both crates.
Closes #375
=> ref(lru-cache): Change lru cache crate to avoid vulnerable dependency

iroh-p2p/benches/lru_cache.rs
You don't need to install cargo-criterion, it only gives you a nicer
experience.
Also fix up a comment.
=> ref(benches): Describe more ways of running benchmarks

iroh-store/Cargo.toml, iroh-store/src/rpc.rs, iroh-store/src/store.rs
This makes store operations atomic by just using an in memory mutex.
This means that as soon as a db is being opened twice at the same time, it will be corrupted. But that is the case anyway because we are already relying on in process atomicity with the (former) AtomicU64 for the id counter.
I am working on a solution that is using rocksdb transactions on a separate branch, but it seems that this will take a bit longer because I can't get the atomicity test to pass despite using transactions with snapshots.
So this is a stopgap measure that makes our store not break until we sort things out more permanently.
It also implements https://github.com/n0-computer/iroh/issues/426 
Note: I tried using tokio async mutexes, but that gets you into trouble again because LocalStore is not Send.
=> Make store operations atomic

xtask/src/main.rs
Add a warning in case there's no release build to install.
Ideally it'd also warn if the build is out of date, but that's
for another day.
=> chore(xtask): Make dev-install a little friendlier

iroh-api/src/api.rs, iroh-gateway/src/main.rs, iroh-one/src/main.rs, iroh-p2p/src/main.rs, iroh-store/src/main.rs, iroh-util/src/lib.rs, iroh-util/tests/config.rs, iroh/src/run.rs
Changes the file_paths argument of make_config to take &Path
references.  It is not using this allocation and instead only using it
a &Path.  Many callers also had to explicitly allocate this.
---
I started by simplifying the user-facing API by turning it into a
PathBuf, but after checking how this was used that's just a pointless
allocation.  So instead this does the slightly more complex thing.
=> ref(api): Switch argument from PathBuf to &Path

iroh-bitswap/Cargo.toml, iroh-localops/Cargo.toml, iroh-p2p/Cargo.toml, iroh-rpc-client/Cargo.toml, iroh-rpc-types/Cargo.toml, iroh-share/Cargo.toml, iroh-store/Cargo.toml, iroh-util/Cargo.toml, iroh/Cargo.toml, stores/flatfs/Cargo.toml, stores/rocks/Cargo.toml, xtask/Cargo.toml
Since iroh is a library, or will be, we should not have too strict a
version requirement, so simply requiring version 1.
=> chore(deps): Unify the anyhow version dependency

iroh-rpc-client/src/macros.rs, iroh-rpc-types/src/addr.rs, iroh-rpc-types/src/macros.rs
support addrs like `grpc://example:4444`, which is required for DevOps infrastructure that provides hostname resolution as part of service discovery.
This patch uses the heuristic of being able to resolve to disambiguate between `grpc://foo` the lookup address and `grpc://foo` a path to a unix domain socket file location. In practice this shouldn't be too big a deal, but might get tricky if folks start naming UDS paths after domains 😵 .
I need this to make docker compose examples work, which is a good indication this'll be needed by all modern DevOps deployments
=> feat: support lookup names in RPC addrs

iroh-one/src/cli.rs, iroh-one/src/config.rs, iroh-one/src/lib.rs, iroh-one/src/main.rs, iroh-store/benches/rpc.rs
Perhaps it is even desireable to trigger a compilation failure when
trying to enable the feature on windows.  The downside is that the
`--all-features` argument to cargo would no longer work on windows and
this makes the development experience a lot more painful.  For now
this seems a reasonable compromise.
=> chore: Disable uds-gateway feature on windows

docker/docker-compose.yaml, iroh-rpc-client/src/client.rs, iroh-util/src/lib.rs, iroh-util/tests/config.rs, xtask/src/main.rs
and fix env var setting in the process. requires #500
Seeing this work is nice 😄. closes #439
=> docs: add docker compose example

iroh-p2p/Cargo.toml, iroh-p2p/src/node.rs, iroh-p2p/src/rpc.rs, iroh-rpc-client/src/network.rs, iroh-rpc-types/proto/p2p.proto, iroh-rpc-types/src/p2p.rs
covers these `RpcMessages`
- ExternalAddrs
- LocalPeerId
- ProviderRequest
- StartProviding
- StopProviding
- NetListeningAddrs
- NetPeers
- NetConnectByPeerId
- NetConnect
- Gossipsub messages
- FindPeerOnDht
- LookupPeerInfo
- ListenForIdentify
- AddressesOfPeer
The missing tests are for:
- P2pClient::fetch_bitswap
- P2pClient::notify_new_blocks_bitswap
- P2pClient::stop_session_bitswap
- P2pClient::disconnect -> this isn't actually implemented
- P2pClient::shutdown -> this doesn't seem to do anything
The bitswap commands are a bit trickier to fake. I would like to either move on or tackle them in a separate PR.
closes #455
=> test(iroh-p2p): test interactions between multiple nodes

iroh/src/services.rs
This is probably less efficient though, for this size of hashset.  But
it is a higher level abstraction so probably is a bit easier to read.
=> ref: Fix todo by using HashSet::difference

iroh-api/src/api.rs, iroh-gateway/src/main.rs, iroh-one/src/main.rs, iroh-p2p/src/main.rs, iroh-store/src/main.rs, iroh-util/Cargo.toml, iroh-util/src/lib.rs, iroh-util/tests/config.rs, iroh/src/run.rs
Use the --cfg flag to load the configuration file for `iroh`.
This does not affect the config files for any of the managed
processes like iroh-p2p etc.
This flag was not used before.
Also optimises the make_config call a little by taking a slice
rather than a Vec.  And assert and document the priority order.
=> fix(cli): Respect the --cfg flag

iroh-util/Cargo.toml, iroh-util/src/lib.rs
This removes the testdir crate for a temprorary testing directory and
uses the tempfile crate instead.  It seems a transitive dependency for
testdir does not work on mac, which is kind of required for us.
=> fix: Switch to tempfile for temporary test directories

iroh-store/Cargo.toml, iroh-store/src/store.rs
=> fix(iroh-store): `put_many` bug

iroh-p2p/src/node.rs
Really flakey, on new CI runners (m1 mac) it fails consistently.
=> tests: disable flakey test_dht

iroh-gateway/Cargo.toml, iroh-gateway/src/cors.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/lib.rs
Fixes https://github.com/n0-computer/iroh/issues/512
This uses the headers from the gateway config. `access-control-allow-headers` and `access-control-expose-headers` are usually the same so we allow omitting the second, less known one. Without it, headers specified in `access-control-allow-headers` are not visible in `fetch()` responses even if they are sent back.
=> Add a CORS middleware

iroh-resolver/src/content_loader.rs
While doing some local network fetching, I encountered this error: `curl http://localhost:9050/ipfs/CID` failed to return the expected content but returned that:
```html
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty</center>
</body>
</html>
```
This is a combination of 2 errors:
- Failure to verify the CID hash since that's not the expected content!
- Failure to consider non 2xx response from gateways as errors.
This patch fixes both, and we now get the timeout from the local gateway as expected:
```shell
curl http://localhost:9050/ipfs/bafkreibimdxekc6ebparbv3pp2hrcfzib7m42ysvzis3djdlumflidnkky
{"code":504,"message":"request timed out","success":false}
```
=> Verify content fetched from racing http gateways

iroh-resolver/src/content_loader.rs
fixes #511
turns out you can't go straight from v0 -> base32 v1, which makes sense, but is irritating. Better than the alternative of silently converting into cidv1 I guess.
Anyway, fixes the gateway
=> fix: convert v0 -> v1 before base32 conversion

DEVELOPERS.md
Document using --all-targets instead of the --tests --bins etc.  This
is more comprehensive and shorter than trying to list all the targets
by hand.
Closes #514
=> chore(docs): Recommend --all-targets

iroh-bitswap/src/client.rs, iroh-bitswap/src/lib.rs, iroh-p2p/src/behaviour.rs, iroh-p2p/src/config.rs
When setting `bitswap_server: false`, there is no serving of blocks happening, only client requests.
=> feat: bitswap client mode

iroh-gateway/src/bad_bits.rs, iroh-gateway/src/client.rs, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/response.rs
Here I've done several things:
- Added HEAD handler that returns `Content-Length` header as in Kubo
- Refactored handlers to make them slightly more idiomatic
- Fixed [bug](https://github.com/n0-computer/iroh/blob/main/iroh-gateway/src/response.rs#L144) that doesn't set Location in redirect
- Applied Clippy to iroh-gateway
=> [feat] HEAD for CIDs + refactoring of handlers

iroh-api/Cargo.toml, iroh-bitswap/Cargo.toml, iroh-car/Cargo.toml, iroh-gateway/Cargo.toml, iroh-one/Cargo.toml, iroh-p2p/Cargo.toml, iroh-resolver/Cargo.toml, iroh-rpc-client/Cargo.toml, iroh-share/Cargo.toml, iroh-store/Cargo.toml, iroh-util/Cargo.toml
This removes the use of `prost` at build time. `cid` and `multihash` are also updated accordingly.
=> (chore) Update libipld to 0.15

codecov.yml
Apparently the flag is root level. VV confusing config file/options.
=> chore(ci): disable codecov comments

iroh-one/src/main.rs
This copies the mem-addresses in the config to the bits of config that
are used by the individual services before starting them up.  This
should help them talk to each other a little better.
---
Tested this locally and seems to work, I think?
=> fix(iroh-one): Wire up mem addresses to each other

iroh-gateway/src/bad_bits.rs, iroh-gateway/src/client.rs, iroh-gateway/src/config.rs, iroh-gateway/src/core.rs, iroh-gateway/src/main.rs, iroh-one/src/main.rs, iroh-resolver/Cargo.toml, iroh-resolver/src/dns_resolver.rs, iroh-resolver/src/lib.rs, iroh-resolver/src/resolver.rs
This PR does two things:
- Moved DNS resolver to dedicated struct and reused it instead of creation every time
- Added `resolver.cloudflare-eth.com` resolver for `.eth` domains as in Kubo for making possible to resolve Etherium domains. Ip addresses of resolver are hardcoded for avoiding excessive round-trip.
=> feat: Support `eth` domains

iroh-gateway/Cargo.toml, iroh-gateway/src/handlers.rs, iroh-one/Cargo.toml
Add an about page with a bit of package information.
---
I just found this useful locally as I learn how things work.  Maybe
others like it too.  If not, never mind.
=> feat(gateway): Add about page

iroh-bitswap/src/metrics.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/metrics.rs, iroh-p2p/src/metrics.rs, iroh-p2p/src/node.rs, iroh-resolver/Cargo.toml, iroh-store/src/metrics.rs, iroh/src/metrics.rs, iroh/tests/cli_tests.rs, iroh/tests/cmd/version.trycmd
- fix #447 which prevents crates depending on the published crates in some cases
- fix hardcoded version information in tests
=> fixes for issues found during the 0.1.2 release

iroh-gateway/src/config.rs, iroh-p2p/src/config.rs, iroh-p2p/src/node.rs, iroh-rpc-client/src/macros.rs, iroh-rpc-types/src/addr.rs, iroh-rpc-types/src/macros.rs, iroh-store/benches/rpc.rs, iroh-store/src/config.rs
Maybe we will add it again, but this complicates switching the RPC.
Note that only removes the Grpc UDS, not the gateway UDS code path.
=> Remove GrpcUds code path

examples/Cargo.toml, iroh-api/Cargo.toml, iroh-bitswap/Cargo.toml, iroh-gateway/Cargo.toml, iroh-localops/Cargo.toml, iroh-one/Cargo.toml, iroh-p2p/Cargo.toml, iroh-resolver/Cargo.toml, iroh-rpc-client/Cargo.toml, iroh-rpc-types/Cargo.toml, iroh-share/Cargo.toml, iroh-store/Cargo.toml, iroh-util/Cargo.toml, iroh/Cargo.toml, iroh/tests/cli_tests.rs, stores/flatfs/Cargo.toml, stores/rocks/Cargo.toml, xtask/Cargo.toml
This enables backtrace support in anyhow, allowing backtraces to be
enabled when setting RUST_BACKTRACE=1.  This is useful when trying to
find the source of an error.
=> ref: Enable backtrace support in anyhow

iroh-rpc-client/src/lib.rs
Turns out that hyper does not know `irpc://`...
=> fix: use http when creating hyper URL

iroh-gateway/src/rpc.rs, iroh-p2p/src/rpc.rs, iroh-store/src/rpc.rs
Accept errors occasonally happen, and the loop should not stop because of them
=> refactor: Make store RPC more robust

iroh-api/Cargo.toml, iroh-api/benches/add.rs, iroh-api/src/api.rs, iroh-api/src/block_store.rs, iroh-api/src/lib.rs, iroh-api/src/store.rs, iroh-gateway/src/core.rs, iroh-resolver/tests/roundtrip.rs, iroh-share/src/lib.rs, iroh-share/src/sender.rs, iroh-unixfs/Cargo.toml, iroh-unixfs/src/builder.rs, iroh/src/fixture.rs, iroh/src/run.rs
=> refactor(`iroh-api`): add takes a `UnixfsEntry` not a `Path`

iroh-gateway/Cargo.toml, iroh-gateway/src/handlers.rs, iroh-one/Cargo.toml
0.6 is pulled by opentelemetry-otlp -> tonic
=> (chore): de-dupe axum

.github/workflows/weekly.yml
This adds a weekly CI job which run clippy with the rust beta version.
This gives a heads up for failures which we can fix ahead of the next
stable release, instead of all PRs being blocked on release day.
---
I've previously used this without the issue creation, I'm not sure how
well the issue creation part works.
Problem is that without github will email the failure to **the last
committer** of the action file.  Which is a bit suboptimal.
=> chore: Add weekly CI running beta clippy

.github/workflows/weekly.yml
This is used to select the architecture of the protoc compiler to
download.  It doesn't need to be so dynamic in this workflow but
keeping it this way makes it more similar to the main ci workflow and
thus hopefully easier to maintain.
Closes #618
=> fix(ci): Set the protoc-arch matrix for weekly job

iroh-api/src/api.rs, iroh-api/src/store.rs, iroh-unixfs/src/balanced_tree.rs, iroh-unixfs/src/builder.rs, iroh-unixfs/src/chunker.rs, iroh-unixfs/src/chunker/fixed.rs, iroh-unixfs/src/chunker/rabin.rs, iroh/src/fixture.rs
Implements #616
There does not seem to be any fundamental reason why the API stuff has to be non send. Just that we did not do the effort to add Send in a few places.
We might want to DRY the trait bounds at some point...
=> feat: Send all the things

.github/workflows/weekly.yml
This installs the beta toolchain and also ensures to use it for the
clippy run.  Oops.
=> fix(ci): Use beta toolchain for the clippy run

iroh-api/src/api.rs, iroh-api/src/lib.rs, iroh-gateway/Cargo.toml, iroh-gateway/src/lib.rs, iroh-gateway/src/metrics.rs, iroh-gateway/src/rpc.rs, iroh-p2p/src/lib.rs, iroh-p2p/src/metrics.rs, iroh-p2p/src/rpc.rs, iroh-rpc-client/src/client.rs, iroh-rpc-client/src/gateway.rs, iroh-rpc-client/src/lib.rs, iroh-rpc-client/src/network.rs, iroh-rpc-client/src/status.rs, iroh-rpc-client/src/store.rs, iroh-rpc-types/src/gateway.rs, iroh-rpc-types/src/lib.rs, iroh-rpc-types/src/p2p.rs, iroh-rpc-types/src/store.rs, iroh-store/Cargo.toml, iroh-store/src/lib.rs, iroh-store/src/metrics.rs, iroh-store/src/rpc.rs, iroh/src/fixture.rs, iroh/src/run.rs, iroh/src/services.rs, iroh/tests/cmd/start_status_stop.trycmd
=> add back `iroh status -w` feature using new rpc streams

iroh-api/src/api.rs, iroh-gateway/src/bad_bits.rs, iroh-gateway/src/client.rs, iroh-gateway/src/core.rs, iroh-gateway/src/handler_params.rs, iroh-gateway/src/handlers.rs, iroh-gateway/src/headers.rs, iroh-gateway/src/main.rs, iroh-gateway/src/response.rs, iroh-gateway/src/templates.rs, iroh-resolver/src/dns_resolver.rs, iroh-resolver/src/resolver.rs, iroh-resolver/tests/roundtrip.rs, iroh-resolver/tests/unixfs.rs, iroh-rpc-client/src/lib.rs, iroh-share/src/receiver.rs, iroh-store/src/store.rs, iroh-unixfs/src/chunker.rs, iroh-unixfs/src/content_loader.rs, iroh-unixfs/src/lib.rs, iroh-unixfs/src/types.rs, iroh-unixfs/src/unixfs.rs, iroh/src/doc.rs
`ResponseClip` has been deleted but it is better to discuss. I did it because its semantics was not obvious, it was used for clipping both entire response and partial responses from `Node` with non-trivial transitions between them.
Worth to note, now `Range` header with value `start-end` translates to rust struct `Range` with values `start` and `end + 1`. `Range` in rust non-inclusive for right bound, it is more convinient.
=> feat: Refactor unixfs

.github/workflows/weekly.yml
This should be an env var.  Of course.  Debugging ci is just so
painful and slow. :(
Closes #621
=> fix(ci): Call cargo with beta toolchain from env var

Cargo.toml, iroh-rpc-client/src/lib.rs
This should give us better termination and also solve some issues with rpc messages being too large.
It probably allocates needlessly large buffers for each hyper connection, but that is preferable to getting errors. We will get rid of this with a subsequent quic-rpc update.
=> chore: update quic-rpc version

iroh-p2p/src/node.rs, iroh-p2p/src/providers.rs
Also implements final p2p unit test to close #455
Bug fix fixes the flakey dht tests #518
Some notes:
- Before we could get to fixing the flakiness, the test was hanging due to a bug in the `Providers` query manager. To summarize the issue: we weren't reacting to `GetProvidersOk::FinishedWithNoAdditionalRecord` events, which indicate no more records were found. Because this event was never handled, we never removed the `Query` from the `providers` Set, and so the stream of providers never closed, causing the `test_dht` test to hang.
- To test reliability, I looped the `test_dht` 10 times for my initial commits, but removed the loop it once things stabilized.
- I did a whole pass where the node emitted an event whenever the kbuckets were updated, and used that event to ensure everything …
=> fix(iroh-p2p): ensure `providers` stream closes

iroh-gateway/assets/404.html, iroh-gateway/assets/style.css, iroh-gateway/src/core.rs, iroh-gateway/src/error.rs, iroh-gateway/src/handlers.rs, iroh-unixfs/src/content_loader.rs
closes https://github.com/n0-computer/iroh/issues/97
=> feat: html error handling

Cargo.toml
This should at least get rid of the errors when receiving empty frames
=> chore: update quic-rpc

iroh/Cargo.toml, iroh/src/main.rs
Bring back this message when nothings running:
```
$ iroh get foo
Error: Connection refused. Are services running?
hint: see 'iroh start' for more on starting services
```
Also pick up a neat little refactor that drops inner match statements
=> fix(iroh): handle connection refused errors with pretty messages again

iroh-gateway/src/rpc.rs, iroh-p2p/src/rpc.rs, iroh-store/src/rpc.rs
An accept error can happen e.g. when a client starts an RPC request and then immediately cancels it because it has raced it against a local op.
Not that we should do this that often, but it totally happens.
Example when reading a large directory that is present locally:
```
2022-12-21T12:07:25.283756Z ERROR iroh_p2p::rpc: p2p rpc accept error: RecvError(A(NetworkError(hyper::Error(Body, Error { kind: Io(Kind(ConnectionReset)) }))))
at iroh-p2p/src/rpc.rs:582
2022-12-21T12:07:25.283775Z ERROR iroh_p2p::rpc: p2p rpc accept error: RecvError(A(NetworkError(hyper::Error(Body, Error { kind: Io(Kind(ConnectionReset)) }))))
at iroh-p2p/src/rpc.rs:582
```
=> fix(rpc): dial down log level for accept errors

iroh-api/benches/add.rs, iroh-bitswap/src/peer_task_queue.rs, iroh-one/src/main.rs, iroh-p2p/src/keys.rs, iroh-p2p/src/node.rs, iroh-resolver/src/resolver.rs, iroh-resolver/tests/roundtrip.rs, iroh-resolver/tests/unixfs.rs, iroh-share/src/main.rs, iroh-share/src/sender.rs, iroh-store/benches/rpc.rs, iroh-unixfs/src/balanced_tree.rs, iroh/src/fixture.rs, iroh/src/main.rs, iroh/src/p2p.rs, iroh/src/run.rs, iroh/src/services.rs, xtask/src/main.rs
Newer clippy wants the identifiers in the format string when
possible.  Boring change but why not.
Closes #661
=> chore(clippy): Place identifiers in format string

iroh-bitswap/src/client/peer_manager.rs, iroh-bitswap/src/network.rs
This makes sure to await the future from async_channel::Sender::send.
When not awaiting this only makes a struct and noting is ever sent.
Caught by clippy really.
=> fix: Await async_channel::Sender::send

iroh-store/src/config.rs, iroh-store/src/store.rs
The store does not use the RPC client at all.  Remove it.
CI doens't break!  It must be good.  Teach me why not :)
=> ref(store): Remove unused RPC Client

Cargo.lock, src/main.rs
All subcommands take this option, so repeating it like that is a bit
silly.  Move it to the toplevel.
=> feat: Move --keylog to common flags

src/get.rs
We used to limit the maximum amount of data that can be transferred,
both the total size as well as single blob size.  There is no real
benefit to this, we pass through the reader and do not buffer all this
data at once.  And avoiding to fill up the user's disk space is not
our concern.
=> feat: Remove MAX_DATA_LIMIT

src/get.rs, src/protocol.rs, src/provider.rs
Since we now only issue a single request per stream this field was not
used.  Using it in the provider to identify requests would introduce
complexity and overhead for the bookkeeping of request IDs.  Instead
remove the field from the protocol.
The provider still has a use-case for identifying which request events
relate to.  It now uses the QUIC stream ID for this, but does not
promise so on an API-level.  This also simplifies the events since
this new request_id is always known, while previously it was only
known after having decoded the request message.
=> feat: Remove Request.id from the protocol

src/main.rs
This is consistent with the naming for the provide subcommand and is
more descriptive as well.
=> ref: Rename --token to --auth-token for get

src/main.rs
This makes sure the OutWriter writes the newline as part of the same
buffer as the output.  This makes it less likely that the output will
be interrupted between the content and the newline.  E.g. without this
and enabling logging, log messages will be injected between the
content and the newline, making the output garbled.
Unfortunately this isn't entirely correct and is more of a heuristic
because most of our output is small enough that they fit in a single
write.  In the blocking world you'd lock Stderr while printing the
messages, in the tokio world however I don't know how to safely do
this.
=> fix: Avoid other output between contents when printing

src/main.rs, src/provider.rs
This fixes the log message output which had an extraneous newline in
it and needlessly used debug output.
It also adds the listening address to the normal provider output: This
is universally useful since you can specify addresses with -a but
don't otherwise know which one is used if using OS-allocated ports.
This can also be useful for testing.
=> fix: Improve listening addr output

src/main.rs
I think I just don't get why OutWriter exists, so I thought I might as well do a PR to replace it, and you tell me why this is wrong...
I would rename out_println! to something else, maybe progress! Did so.
I checked the code, and it seems that tokio::io::stderr() is meant to be used as a singleton. It calls std::io::stderr() and wraps it into a `Blocking` helper and something else for windows compat, `SplitByUtf8BoundaryIfWindows`, neither of which does anything obviously very expensive.
I don't think it even allocates on creation.
Here is Blocking::new from the tokio guts:
```rust
cfg_io_blocking! {
impl<T> Blocking<T> {
#[cfg_attr(feature = "fs", allow(dead_code))]
pub(crate) fn new(inner: T) -> Blocking<T> {
Blocking {
inner: Some(inner),
state: …
```
=> No out writer

src/get.rs, src/protocol.rs
Seems like we ended up with two bits of code doing exactly the same.
Clean it up.
This settles on read_lp() as name since this is symmetric with
write_lp() which writes bytes.  This implementation inlines the
functions a bit more as well, the entire function is still small and
it is used often.
=> ref: Remove duplicate read_lp implementation

src/provider.rs
The code was accidentally sending this response twice.  send_blob()
already sends NotFound, and it seems like it belongs more there.
=> fix: Do not send duplicate NotFound responses

src/protocol.rs
Before going into the loop we may as well make sure to reserve enough
space for the entire buffer.  Otherwise we could be allocating
multiple times.
This does not change the total allocated size.
=> ref: micro-optimise by reserving buffer size

Cargo.lock, Cargo.toml, src/hp/derp.rs, src/hp/derp/client.rs, src/hp/derp/server.rs, src/hp/disco.rs, src/hp/key/disco.rs, src/hp/key/node.rs, src/hp/magicsock/conn.rs, src/hp/magicsock/rebinding_conn.rs
some general notes about this first attempt (aka "this mess"):
- golang impl uses u32 everywhere, including sending the frame length on the wire.  I assuming we should continue to only use 4 bytes for the frame length, but then we should probably convert to `usize` when we get it, so that we have fewer `as usize`'s littered throughout the code. But I haven't done this yet.
- from looking at the surrounding code that imports the derp client, it looks like we need to be able to use this in many threads. So I've wrapped any "shared data" in an `Arc<Mutex>`
- I don't understand why the go code only wrapped the `writer` in a mutex lock and not the `reader` as well. I followed the same pattern, because maybe I don't understand this yet?
- the rate limiter is gross and maybe we wrap this in a …
=> WIP: impl `derp::client` mod

Cargo.lock, Cargo.toml
A dependency of tempfile had a security issue which could affect us.
Bump the version.
=> deps: New version of tempfile to avoid security issue

src/get.rs
Otherwise you just get `timed out` as error and have no clue what's
going on.
=> ref: Improve error for connection timeout

src/main.rs, src/provider.rs
We might later want to allow rpc port `0` for "choose a free one", but I think for now this is fine. For a rpc port you really want it to be known beforehand.
=> Allow disabling rpc

src/hp/derp.rs, src/hp/derp/client.rs, src/hp/derp/client_conn.rs, src/hp/derp/conn.rs, src/hp/derp/server.rs, src/hp/key/node.rs
Implement structures that manage the connection from the server to the
client: the `ClientConnManager`, the `ClientConnWriter`, `ClientConnReader`.
When the server "accepts" a connection (`accept` is not yet
implemented), it separates the write and read portions of the
connection. It should create a `ClientConnManager` to interact with the
connection. The `ClientConnManager` runs the `ClientConnWriter` and `ClientConnReader` in a loop.
The `ClientConnWriter` accepts notifications & relayed packets from the server & sends them to the client.
The `ClientConnReader` to reads any notifications or packets it wants
the server to relay from the client, & sends them to be processed in the
server.
=> begin impl Server side of derp, starting with the server side of the client connection

Cargo.lock, src/main.rs
Otherwise it is not possible to add things if the add cli has a different $PATH than the daemon.
Fixes #834
=> fix: use absolute paths everywhere

src/lib.rs, src/protocol.rs, src/provider.rs
Creating collections with a larger number of files currently fails with `Error: The serialize buffer is full`.
=> fix: large collections

src/hp/derp.rs, src/hp/derp/client.rs, src/hp/derp/client_conn.rs, src/hp/derp/clients.rs, src/hp/derp/conn.rs, src/hp/derp/server.rs, src/hp/derp/types.rs
Decided I needed to super simplify this, for now. This impl no longer attempts to handle muliple connections with the same key or track if a client is connected to multiple derp servers. 
Both situations are apparently not that common, but will be important to implement in the future in order to capture all situations.
This is the last large piece before turning to the actual server.
=> impl: `Client` and `Clients`, how the server manages the different connected clients

.github/workflows/ci.yml
This changes the cross-compiling targets to use those that are used by
the real android phones.
=> ci(android): Use the real android targets

.github/workflows/ci.yml, .github/workflows/netsim.yml
closes #878 
dtolnay's [rust-toolchain](https://github.com/dtolnay/rust-toolchain) is a nicer, more ergonomic way of installing and using the rust toolchain in the CI - projects within [the issue discussing the unmaintained actions-rs](https://github.com/actions-rs/toolchain/issues/216) already have a few projects switch over to using it.
I ran the CI manually on my own repo, and you can check the results [here](https://github.com/bingcicle/iroh/actions/runs/4509634140)
=> ci: replace actions-rs with dtolnay/rust-toolchain

Cargo.lock, Cargo.toml, src/hp/derp.rs, src/hp/derp/client.rs, src/hp/derp/client_conn.rs, src/hp/derp/clients.rs, src/hp/derp/http.rs, src/hp/derp/http/server.rs, src/hp/derp/server.rs, src/hp/derp/types.rs, src/hp/magicsock/conn.rs
- need `ClientReader` `ClilentWriter`, responsible for reading from the server and writing to the server.
- adjust `ClientBuilder` to return `Client` & `mpsc::Sender<ReceivedMessage>`
=> refactoring `derp::Client`

.github/workflows/netsim.yml
Instead of the usual suite, we now run iroh on multiple latencies and publish those results. The remaining sims are available by direct config in the comment.
=> chore: update netsim sims

Cargo.lock
cargo-deny points out that the current version is yanked.  Update this
dependency.
=> deps: Updated from yanked version

Cargo.lock, src/get.rs, src/lib.rs, src/subnet.rs
This adds a new iroh::get::run_ticket call which will dial all the
addresses in a ticket concurrently, up to a specified concurrency
limit.  The first established connection is returned.
This allows much better fetching of a ticket, without having to know
how it is constructed and speeds up connecting.
When dialing an attempt is made to first try addresses which are
considered to be on the same subnet as any local address.
This doesn't yet update main.rs to use this.  Probably best as a
separate PR.
=> feat: Add run_ticket to dial all addresses stored in a Ticket

src/hp/derp/client.rs, src/hp/derp/http.rs, src/hp/derp/http/client.rs, src/hp/derp/server.rs, src/hp/magicsock/conn.rs
I'd like to merge this and do the next leg of work in another PR.
The only two parts left are:
- some mechanism for keeping track of pings when they go out & the associated pong when it comes back in. This should be a small amount of work
- the actual connection process, this should be much more work.
=> adjust `derp::Client` and start impl on `derp::http::Client`

src/main.rs
This tries to contact the provider on all addresses inside the ticket
when using the get-ticket command.  The first connection will be used.
=> feat(get-ticket): Contact provider on all listening addrs

src/lib.rs, src/main.rs, src/net.rs, src/provider/mod.rs
This primarily renames .available_addresses() to
.listen_addresses() and .listen_addr() to .local_address().  this
makes .local_address() consistent with e.g. quinn's API and avoids the
confusion between available on the machine vs uses by the provider.
=> ref: Clean up public API regarding bound/local/listening addresses

src/get.rs, src/lib.rs, src/main.rs, src/provider/mod.rs, src/provider/ticket.rs
This makes it impossible to have a ticket with an empty address list.
It makes the fields of the ticket private and also makes creating the
ticket fallible.  Both are probably good things for the public API and
the latter e.g. allows us to add further checks like ensure the hash
really exists.
=> feat(ticket): Ensure a ticket always has at least one address

Cargo.toml
Adding iroh to a project that already depended on bytes 1.1 fails to compile with:
```
error[E0599]: no function or associated item named `zeroed` found for struct `BytesMut` in the current scope
--> /home/fabrice/dev/capyloon/api-daemon/third-party/iroh/src/get.rs:273:36
|
273 |     let mut out_buffer = BytesMut::zeroed(std::cmp::max(
|                                    ^^^^^^ function or associated item not found in `BytesMut`
```
Because `BytesMut::zeroed()` was introduced in 1.2 . This PR sets the version to 1.4 which is the current stable version for the `bytes` crate.
=> Bump bytes minimum version to 1.4

Cargo.lock, src/lib.rs, src/provider/mod.rs
I made the test fail by making the file name really long.
Made the file name repeat the number multiple times so a radix tree does not optimize the long name away, just in case we do radix trees in the future.
=> Fix many files bug

Cargo.lock, Cargo.toml, src/blobs.rs, src/get.rs, src/lib.rs, src/protocol.rs, src/provider/mod.rs, src/util.rs
What this gives us:
- async wherever you want (it is pretty easy to implement in bao-tree)
note: I still think that we should not do async everywhere, but we can if we want!
- verified encoding, so validation errors get caught on the server side
- configurable block size, currently set to 4 (= 1024 * 2^4)
and most notably:
- querying for multiple ranges in a single request
=> Use the new bao-tree crate instead of abao

src/protocol.rs, src/provider/collection.rs, src/provider/database.rs, src/provider/mod.rs, src/util.rs
- If a file in a collection did not exist we would get a panic due to
an unwrap, killing the entire task.  Now we correctly error showing
which file was not found.
- We did a bunch of sync and async file operations while in the async
functions.  This is now all moved to a single large spawn_blocking
call avoiding the many small spawn_blocking calls the async
operations give us as well as the potential blocking of the sync
file operations.
- We did not check the maximum size of the serialised collection.
A few other smaller cleanups:
- The CollectionOrBlob::Blob variant is now directly a struct, the
indirection of Data was not used anywhere to any effect and only
distracted.
- The collection creation code is moved to it's own module now,
provider is still huge.
=> ref: Change how a collection is created

Cargo.lock, Cargo.toml, src/get.rs, src/hp/derp/client.rs, src/hp/derp/http.rs, src/hp/derp/http/client.rs, src/hp/derp/server.rs, src/hp/magicsock/conn.rs, src/hp/magicsock/rebinding_conn.rs, src/hp/netcheck.rs, src/provider/mod.rs, src/tls/certificate.rs, src/tls/verifier.rs
This includes updating to `rustls 0.21` and `quinn@0.10`
The actual patch being used is: https://github.com/quinn-rs/quinn/pull/1545
Missing
=> integrate patched quinn

src/get.rs, src/lib.rs, src/main.rs
because StartCollection implies that it is always a collection, which is not the case when requesting a single blob.
Other alternative names would be StartParent, but in case of a single blob it is also not a parent.
Todo once we agree on the name - update the FSM svg drawing.
=> rename StartCollection to StartRoot

src/hp/magicsock/conn.rs, src/hp/magicsock/rebinding_conn.rs, src/lib.rs
- avoid unnecessary vector groups and allocations in the sending path
- use fixed buffer in `IpStream`
- correctly split and set `stride`  and `len` when receiving data, especially when GRO is enabled. (biggest impact on linux)
=> improve performance in the hot path

src/hp/derp/server.rs, src/hp/netcheck.rs
I like to use cargo doc to get an overview of the code.
=> remove some stale refs from docs so cargo doc works

src/hp/hostinfo.rs, src/hp/magicsock/conn.rs, src/hp/magicsock/endpoint.rs
This makes cargo check warning-free which is much nicer to work with.
I'd be happy to just remove it as well.  Just don't know this code yet really.
=> ref: disable to unused code

src/get.rs, src/hp/cfg.rs, src/hp/magicsock/conn.rs, src/hp/magicsock/endpoint.rs, src/hp/magicsock/rebinding_conn.rs, src/hp/netmap.rs
This does a little tidying up of the address we tell the QUIC layer to
use to dial a peer:
- It introduces a newtype for it, making it very clear what you are
working with and avoiding accidentally using it in the wrong place.
- It adds this to the PeerMap, documenting the peer map a bit better.
- It also change the generation of this address a bit: make it an RFC
compliant Unique Local Address assigning out own Global Id.  This
should allow more universally detecting if the address leaks.
=> ref(Conn/PeerMap): Introduce QuicMappedAddress

src/hp/derp/client.rs, src/hp/derp/client_conn.rs, src/hp/derp/server.rs
We now add a length prefix to all packets. We also added this length prefix
to disco packets, meaning that they were no longer disco packets.
In principle I think this is a good thing - you can now transmit any byte
string, including the disco magic string, as a normal packet without it
being accidentally recognized as a disco packet.
But a proper fix for this would involve looking through the code base for
places where the magic byte is used and replacing these with a dedicated
path for disco messages. I tried it, but wasn't sure I got them all.
=> X hp disco fix

src/hp/derp/map.rs, src/hp/netcheck.rs
This is just a PR to keep them smaller.  The main chainge is that the
UDP bind sockets to do STUN on are now directly statically declared.
Functionally this is exactly the same but without the extra state and
function calls involved.
Also adds some doc comments and mostly syntactic refactoring.
=> ref(netcheck): statically declare udp bind addresses

src/hp/derp/client.rs, src/hp/derp/client_conn.rs, src/hp/derp/http.rs, src/hp/derp/http/client.rs, src/hp/derp/server.rs, src/hp/magicsock/conn.rs
As suggested by @ramfox in https://github.com/n0-computer/iroh/pull/830#discussion_r1191830689
This undoes a lot of the changes to tests that were done in the initial batching PR. The packetize and packet split iter moved to the conn.
=> ref: Move packet building into conn

src/hp/disco.rs, src/hp/magicsock/conn.rs, src/hp/netcheck.rs
This fixes receiving STUN packets during an endpoint update. Before they processing of incoming STUN packets would be interrupted due to the main actor loop waiting on the endpoint update.
=> fix: process incoming IP packets in a seperate task

src/hp/netcheck.rs
This makes sure the listener tasks for the STUN sockets are stopped.
Before they just ran forever.
Also tweaks a lot of logging to give more context.
=> ref(netcheck): Log and shut down stun listeners

src/hp/magicsock.rs, src/hp/magicsock/conn.rs, src/hp/magicsock/derp_actor.rs, src/hp/magicsock/endpoint.rs, src/hp/magicsock/rebinding_conn.rs, src/lib.rs, src/provider/mod.rs, tests/cli.rs
- refactor: Cleanup channel usage
- refactor: Move derp receiving into the derp actor
- fix: Make the provider spawning wait for an endpoint update before returning
For details see the commits
=> Various improvements for conn

src/hp/magicsock/conn.rs, src/hp/netcheck.rs, src/hp/netcheck/probe.rs, src/hp/ping.rs
This turns the netcheck into a long running actor:
- The `Client` creates the actor which runs in a background tokio task.
- The `Client` can be cloned to get more handles to the netcheck actor.
- Once `Client` is dropped the actor is stopped.
- Now you can always pass stun packets to to netcheck: it manages the state internally.
This last point is the motivation, it simplifies how things are wired up and makes it easier to keep the right state in the netcheck actor where it belongs.  This will also make future changes to netcheck more contained.
It turns the former netcheck actor into more of a full-scale actor.  The `ReportState` is not following this pattern yet.
=> ref(netcheck): make netcheck a long-running actor

src/hp/magicsock/conn.rs, src/hp/magicsock/derp_actor.rs, src/metrics.rs, src/metrics/core.rs, src/metrics/iroh.rs, src/metrics/macros.rs, src/metrics/magicsock.rs
This improves some documentation by explaining the different metric
types and the difference between record and observe.  It's also a bit
opinionated about metric types.
It also restructures the code a bit to make use of the 2018-edition
macro scoping rules, so macros are not magically available and use can
import them from the metrics module, which gives much better context.
=> ref(metrics): Document metrics and remove macro_use

src/hp/netcheck.rs
This enables logging for this test since it is falky in CI and we need
to debug it somehow.
=> tests: Add logging to flaky google stun test

.github/workflows/ci.yml, src/hp/magicsock/rebinding_conn.rs, src/hp/netcheck.rs
Seems some of the cross environments simply don't do IPv6 at all.  In
that case there's no point in trying IPv6.
=> tests(ipv6): Do not run IPv6 tests if the host doesn't support IPv6

src/hp/magicsock/timer.rs
This is using the deterministic timer facility of tokio to make the timer tests more reliable.
https://docs.rs/tokio/latest/tokio/time/fn.pause.html
Not sure if the tests are still worthwhile with this, but before they would occasionally fail because there are no real guarantees with real timers, and time resolution especially on windows is notoriously coarse.
This is relying on the time "auto advancing" https://docs.rs/tokio/latest/tokio/time/fn.pause.html#auto-advance
=> X hp deterministic timer tests

src/hp/netcheck.rs, src/lib.rs, src/test_utils.rs
This is useful in many tests, not just netcheck.  Make it more globally available.
It also makes it better to enable by default: it just always logs all modules on the TRACE level.  But it is properly captured by the test runner and only shown if the test fails.
Potentially this is too verbose for some tests.  Variants can be built that allow configuring the logging level or even per-modules logging level as required.  But no need for that just yet.
=> tests: Add test utilities to configure logging

Cargo.lock, Cargo.toml, src/provider/ticket.rs, src/tls.rs, src/util.rs
Not multiformats, just base32 all the time. Use the lower case alphabet and no padding.
Implements https://github.com/n0-computer/iroh/issues/842
=> Use base32 encoding for both tickets and peer ids

.github/workflows/ci.yml, src/get.rs, src/main.rs, tests/cli.rs
Not sure if this should even be the same command. Maybe get blob or get-blob? But we have a bit of a feature explosion.
get (hash / ticket) x (collection / blob)
In any case, the single code path is now separate, which makes things simpler. One question I have is how much, if any, progress we should have when getting single or collection to stdout.
If you just get to stdout without redirecting, the stderr progress and stdout content get mixed and will look very confusing...
=> Add back the get --single functionality that has been lost during a refactoring

.github/workflows/ci.yml
We have flaky tests on platforms.  It's best to let them all run on
all platforms so we see all failures and have more debugging tools.
=> ref(ci): Do not use fail-fast strategy

.github/workflows/ci.yml
Sounds like we don't use this format and that makes the failures more
readable for humans.
=> ref(ci): Do not output clippy in json format

src/provider.rs, src/provider/collection.rs, src/provider/database.rs, tests/cli.rs
The distinction is now just whether something is stored internally or externally.
This is the smallest possible thing I can think of that removes the flawed concept of BlobOrCollection. The next step will be making the db fully generic with pluggable storage, but that is a much bigger effort.
=> refactor: remove BlobOrCollection

Cargo.toml
This makes cargo-add respect the sorting as well, it's generally nicer
to find things.
=> ref(build): Sort dependencies in Cargo.toml

.github/workflows/ci.yml
The cargo check runs do not help with any speedup, they cost >20s, do
not test anything that's not already covered by other tests.  So
remove them.
Updates the cargo test invocations to:
- Use --workspace instead of deprecated --all.  We don't have a
workspace crate yet though so could just remove it for now, but this
is a bit more future-proof I guess.
- Use --all-features since we have no features that are incompatible
with each other.  Let's keep it that way!
- Select the --lib --bins and --tests targets, --all-targets would
include the benches which we probably don't want to run as part of the
main test run, but we don't have any yet so that is also just
future-proofing.
=> ref(ci): Do not run cargo check separately and test all features

src/hp/netcheck.rs
This test is now just a best effort, you need to run it with
--nocapture to see if it works or not.  Sad.
=> tests(netcheck): assume udp packets get lost

src/bin/derper.rs, src/hp/netcheck.rs, src/net/interfaces.rs
- bind to IPv6 by default, so that dual stack allows receiving requests on both IPv4 and IPv6
- use spawn and spawn_blocking in the stun handler
=> derper: stun improvements

Cargo.lock, Cargo.toml, src/get.rs
This does not get rid of the ouroboros dependency in bao-tree, just the one directly in iroh. So it does not fix the cargo deny thing.
=> refactor: remove ouroboros and replace it with self_cell

src/config.rs, src/hp/derp/client_conn.rs, src/hp/derp/http/client.rs
Adds test covering issue fixed in #1110 
Fixes bug where the `derp::http:client::recv_detail` method doesn't report back connection errors and instead attempts to reconnect right away. This violates the way the `magicsock::DerpActor` expected the client to be used. It expects to have full control of when we backoff and reconnect.
Adds a test to prove the behavior.
=> fix: don't spam re-connect attempts if something goes wrong when connecting to a derp server

Cargo.lock, Cargo.toml, iroh-io/Cargo.toml, iroh-io/LICENSE-APACHE, iroh-io/LICENSE-MIT, iroh-io/README.md, iroh-io/src/http.rs, iroh-io/src/lib.rs, iroh-io/src/mem.rs, iroh-io/src/tokio_io.rs
Async local io
this does not really make too much sense right now, but will become part of the workspace once the iroh crate split is done.
=> async local io

Cargo.lock, iroh-io/Cargo.toml, iroh-io/src/http.rs, iroh-io/src/lib.rs
this also makes the tests not create a file.
With very friendly and polite support from GPT-4
I had to exclude windows from the range request tests because axum has some issues there. But I think this is OK. The purpose of the test is to make sure we properly deal with range requests etc.
=> refactor: replace warp with axum for the test server

src/lib.rs, src/main.rs, src/protocol.rs, src/provider.rs, src/provider/ticket.rs
You asked about clones in #1109 , so I went `clone` hunting.
- One was not caught by the compiler, no idea why.
- I'm not a fan of functions that clone values in the shadows.. you never know when just a reference is enough and then a clone was made unnecessarily. I changed those to identify places where clones were happening and try to get rid of those.
- In `src/main.rs` there is some code that appears three times and creates a `GetInteractive` "response". I did some refactor  of this code that consumes the ticket and manages to:
- remove the copy of `hash`
- remove the clone of `auth_token`
- remove the copy of `peer_id`
- remove the clone of `addrs` 
- In `src/protocol.rs` moved the `to_bytes` to consume `self`. There used to be a lint suggesting that `to_<bla>` should consume `self` …
=> remove some clones from `b5/opaque_auth`

iroh-net/src/hp/magicsock/endpoint.rs, iroh/tests/cli.rs
see https://github.com/n0-computer/iroh/pull/1128/files#r1242954862
=> (potentially) fix cli bugs

iroh-net/src/hp/netcheck.rs, iroh-net/src/hp/netcheck/probe.rs
On Linux you don't have permission to send ICMP pings by default, so
creating the pinger will fail.  This should not make all of netcheck
fail.
=> fix(netcheck): Make ICMP ping optional

iroh-bytes/src/provider.rs, iroh/src/commands/provide.rs, iroh/src/node.rs
Need this for iroh.network, which listens to an in-process node for provider collection construction.
I'm piggybacking this to also add a test that does minimal node setup, which should form the basis of writing examples later. Learned many things in the process.
=> feat(provider): add 'CollectionAdded' Provider event

Cargo.lock, deny.toml, iroh-net/Cargo.toml, iroh-net/build.rs, iroh-net/src/hp/hostinfo.rs
Simplifies getting the information we actually need, without using another dependency.
Ref #1035
=> fix: remove build-data dependency

Cargo.lock, iroh-bytes/Cargo.toml, iroh/Cargo.toml, iroh/tests/cli.rs
- Bump testdir to 0.8, we use multiple testdir!() calls inside a
single test while expecting to get the same directory.  This was not
the case but now in 0.8 it is.
- When transferring folders do not use testdir!() directly but a
subdirectory.  Using testdir!() directly ends up including e.g. the
iroh_data_dir which should not really be included.
- Simplify make_provider to not require home, all callers used
testdir!() for that anyway.
- Simplify match_provide_output since it did not use Input anyway.
- Fix test_provide_get_loop to not go put the path inside
$CARGO_MANIFEST_DIR/tests/fixtures since we do not store any test
fixtures.  We create all of them on the fly and put them inside
testdir!().  I think we were always testing this with an empty
directory before?
- Improve …
=> ref(tests): Clean up various bits in tests

iroh-net/src/hp/magicsock/endpoint.rs
If we have no endpoints, we use the CallMeMaybe to trigger an exchange of potential UDP addresses.
In my tests this allows localhost and transfers between nats, when only connecting via peer id (and derp region), with no default addresses.
=> fix(iroh-net): allow derp only connections to upgrade

iroh-net/src/net/interfaces.rs, iroh-net/src/net/interfaces/bsd.rs, iroh-net/src/net/interfaces/linux.rs
=> feat(iroh-net): implement `HomeRouter` detection

iroh-bytes/Cargo.toml, iroh-bytes/src/get.rs, iroh-bytes/src/protocol.rs, iroh-bytes/src/provider.rs, iroh/src/commands.rs, iroh/src/commands/provide.rs, iroh/src/node.rs, iroh/tests/provide.rs
This re-adds request authentication tokens to provide, making it optional, and off by default this go-round. Closes #987 
* supply `--token=random` flag to `iroh provide` to get back old behaviour of random token construction
* supply `--token $BASE_32_ENCODED_TOKEN` to use an external opaque token
* either use of the token flag will require the token for _all_ requests to the provider.
=> request token for provide

iroh-net/examples/magic.rs, iroh-net/src/defaults.rs, iroh-net/src/hp/derp/http.rs, iroh-net/src/hp/derp/http/client.rs, iroh-net/src/hp/derp/http/mesh_clients.rs, iroh-net/src/hp/derp/map.rs, iroh-net/src/hp/magicsock/conn.rs, iroh-net/src/hp/netcheck.rs, iroh-net/src/hp/stun.rs, iroh/src/commands/doctor.rs
Now that `DerpNode::host_name` is an URL, the DERP port can be part of that URL, so we don't need a separate `derp_port` field anymore. 
This makes setting custom DERP config or accepting a DERP server from the command line much simpler, because you need only a single URL string and not multiple options.
It looks a bit weird in the test code because oftenly those use `http://derp.invalid:{port}` now. I think we could just put the full IP in the address also and not set `UseIpv4::Some()`.
=> change: use DERP port from host_name URL

iroh-bytes/src/blobs.rs, iroh-bytes/src/get.rs, iroh-bytes/src/protocol.rs, iroh-bytes/src/provider/ticket.rs, iroh-net/src/hp/netcheck.rs, iroh-net/src/magic_endpoint.rs, iroh/src/commands.rs, iroh/src/commands/get.rs, iroh/src/node.rs, iroh/tests/provide.rs
there is now only one dial fn, that basically just passes through the options to the MagicEndpoint. This is used no matter if you use tickets or explicitly given peer and addrs.
=> Get rid of MagicEndpoint::dial_peer and refactor dialing in get

LICENSE-MIT, README.md, iroh-net/src/tls/certificate.rs, iroh-net/src/tls/verifier.rs
Two files in our codebase are largely pulled from `libp2p-tls`, and while both projects are MIT licensed, we should clarify and acknowledge that these two files originated from an MIT license Copy-written by Parity Technologies (UK), Ltd. 
Shoutout to Parity who both originated this code and contributed it to the libp2p project, and the libp2p, team that has extended this code. Also thank you to @divagant-martian for realizing this was missing.
At the same time, I've also added "Copyright N0, INC", to clarify the entity this code has actually been assigned to
=> chore: add explict parity acknowledgement on cert & verifier files, clarify codebase copyright is assigned to n0, inc.

iroh-net/src/defaults.rs, iroh-net/src/hp.rs, iroh-net/src/hp/cfg.rs, iroh-net/src/hp/key.rs, iroh-net/src/hp/key/node.rs, iroh-net/src/hp/magicsock/conn.rs, iroh-net/src/hp/magicsock/endpoint.rs, iroh-net/src/hp/magicsock/timer.rs, iroh-net/src/hp/netcheck.rs, iroh-net/src/hp/netmap.rs, iroh-net/src/hp/ping.rs, iroh-net/src/hp/portmapper.rs, iroh-net/src/hp/stun.rs, iroh-net/src/lib.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/net/interfaces.rs, iroh-net/src/net/interfaces/linux.rs, iroh-net/src/net/interfaces/windows.rs, iroh-net/src/tls/certificate.rs, iroh-net/src/tls/verifier.rs, iroh-net/src/util.rs
the individual `deny` should be moved to the top level once the `derp` is documented
part of #1156
=> docs(iroh-net): deny missing docs and broken links in the crate, except the `derp` mod

iroh/src/commands.rs, iroh/src/commands/get.rs, iroh/tests/cli.rs
you can either use get --ticket <ticket> or get --peer..., but it is all handled by the get subcommand.
The args are configured so that you get decent error messages when misusing. E.g.
```
❯ cargo run get --ticket ebim463bsc4cl3t5vkn7vlacngxvu5wkv5o3fzj5psw2whnxyipfeigxxvopirxcngbsl3eol4a5hchk7tpvzdcwc6qy42equqon2n2w7yaagacsjt2rhzg3amambkabqtsnwayaycuadc7e3mbq --peer 266vz5cg4juygjpmrzpqdu4i5l6n6xemkyl2ddtiscsbzxjxk37a
error: the argument '--ticket <TICKET>' cannot be used with '--peer <PEER>'
```
The netsim test failure is because netsim is using iroh get-ticket instead of iroh get --ticket. I got a branch of chuck where this is corrected. Just replace `get-ticket` with `get --ticket`
=> feature: make get-ticket just a way to use get

iroh-bytes/src/get.rs, iroh-bytes/src/lib.rs, iroh-bytes/src/protocol.rs, iroh-bytes/src/provider.rs, iroh/src/node.rs, iroh/tests/provide.rs
Closes the simple part of #964.
=> refactor(iroh-bytes): remove handshake and rely on ALPN only for protocol negotiation

.github/workflows/ci.yml
Every now and then a cross docker container hangs around (failed job or something gets borked) and it keeps eating up RAM. Worst offender at 75GB for a single lingering container.
This ensures a clean slate and bumps the runners up to a reasonable number, so things should be faster and more stable.
=> fix: cross builds

iroh-bytes/src/provider/ticket.rs, iroh/src/commands.rs, iroh/tests/provide.rs
The derp map was not properly set when using `get --ticket`, which resulted in issues in the netsim tests, as now derp node was known on the `get` side.
=> fix(iroh): pass derp-map on get-options

iroh/src/commands.rs, iroh/src/commands/add.rs, iroh/src/commands/doctor.rs, iroh/src/commands/list.rs, iroh/src/commands/provide.rs, iroh/src/commands/validate.rs, iroh/src/config.rs, iroh/src/lib.rs, iroh/src/main.rs, iroh/src/node.rs
This modifies the modules inside the crate structure and visibility.
Specifically it moves the `config` and `command` modules from the iroh
*crate* into the iroh *binary*.  This could be a little confusing.
This means they are no longer part of the public API of the iroh
crate (and do not need to be documented).
It also fills in a few odd bits of missing doc comments and makes doc
comments required for public APIs on the crate.
When reviewing: the crux are the changes to `main.rs` and `lib.rs`.
=> ref: Change module structure and visibility and require docs

iroh-net/src/magic_endpoint.rs
All other modules are called "tests".  There is one more "test" module
but it provides helpers and not tests.  Might move some time move some
time as well but doing that right now would give merge conflicts with
another of my PRs...
=> ref(tests): consistent test module naming

.github/workflows/ci.yml, iroh-bytes/src/protocol.rs, iroh-net/src/bin/derper.rs, iroh-net/src/hp/derp/types.rs, iroh-net/src/hp/magicsock/conn.rs, iroh-net/src/hp/magicsock/derp_actor.rs, iroh-net/src/hp/magicsock/endpoint.rs, iroh-net/src/hp/netcheck.rs
This makes our docs checking a bit stricter:
- rustdoc warnings are now fatal in ci.
- we test docs of the entire workspace...
- we test private items as well
This includes the fixes needed to make this all work.
=> feat(docs): Check rustdoc more strictly

iroh-bytes/src/provider.rs, iroh/Cargo.toml, iroh/src/commands/provide.rs, iroh/src/node.rs, iroh/tests/provide.rs
Get rid of some type parameters where they do not provide much benefit.
We can not get rid of the database parameter, since that has type members for all the futures, and getting rid of this would mean boxing all futures. But for the request authentication handler and the custom get handler we can just box them.
In the builder, should we leave it up to the caller to create an Arc<dyn ...> or do this ourselves? I prefer to let the caller do it
because this is just during setup, and they might have already arced it for some other reason.
=> Use boxed dyn callbacks to get rid of some type parameters

.github/workflows/ci.yml, Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/tls.rs
- Working on #1209, adding new deps resulted in a `Cargo.lock` update, which brings some incompatible versions between `default-net` and `rtnetlink` as well a a deprecation warning for `rustls`
- New feature flags are needed in `tokio`
- From Ci, also `ucd-parse` needs rust `1.70` or higher
it would be great if `rtnetlink` re-exported the libs that are exposed in its public api
=> chore(iroh-net): fix warnings and errors due to incompatible deps after underlying dep update

iroh-net/src/hp/derp/http/client.rs
We try dialing the derper via both IPv4 and IPv6.  However when the
derper address is looked up via DNS we need to filter the DNS results
for the corresponding address family otherwise we'll end up dialing
the same derper twice on the same address.
Tested by staring at logs.  Can't really wish for more right now.
=> fix(derp): Filter DNS results by address family

.github/workflows/ci.yml
This should help with load on our test runners. Copied from https://stackoverflow.com/questions/66335225/how-to-cancel-previous-runs-in-the-pr-when-you-push-new-commitsupdate-the-curre
How fast will this cancel the jobs on our own boxes? No idea how that works really...
=> ci: cancel workflows when a new commit is pushed

iroh/src/commands/list.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs
Just add some basic docs to the RPC protocol so it does not look so naked in docs.rs. Let's not bikeshed this too much - it is going to change a lot.
=> docs: Add docs to RPC protocol

iroh/src/commands.rs, iroh/src/commands/get.rs
Note that this will lead to the download being repeated from scratch even if the data is already there. We can change that
later. Basically once you get the collection you would have to repeat the step of trying to figure out what is missing, and
then send another request.
- Is this behaviour OK?
- we should probably rethink single blob downloads. They were added as an afterthought, but now it seems they are being used more often.
=> feat: disable bailing out when temp dir is missing

iroh-net/src/bin/derper.rs
Enables serving metrics on the derper. Contingent on enabling the `metrics` feature and setting the `metrics_addr` in the config file.
=> fix: enable derp metrics

iroh-net/src/portmapper.rs, iroh-net/src/portmapper/mapping.rs, iroh-net/src/portmapper/nat_pmp.rs, iroh-net/src/portmapper/nat_pmp/protocol.rs, iroh-net/src/portmapper/nat_pmp/protocol/request.rs, iroh-net/src/portmapper/nat_pmp/protocol/response.rs, iroh-net/src/portmapper/pcp/protocol.rs, iroh-net/src/portmapper/upnp.rs, iroh/src/commands/doctor.rs
- Doctor command port getting a port mapping accepts nat pmp.
- Implement nat pmp protocol's requests and responses for udp mappings and external address queries with their encoding + decoding + tests.
- Connect new mapping protocol with the rest
- Correct some docs.
Suggested way of trying:
```bash
env RUST_LOG=trace cargo run doctor port-map nat_pmp 2446
```
```bash
env RUST_LOG=trace cargo run doctor port-map-probe --enable-nat-pmp
```
=> feat(iroh-net): Nat-PMP probes and mappings

.github/workflows/ci.yml, .github/workflows/netsim.yml
This is required for CI jobs to run in the merge queue.  And if CI
doesn't run in the merge queue it will never have green CI to merge.
See docs for more info:
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue#triggering-merge-group-checks-with-github-actions
It also needs to update the netsim-custom code that extracts the commit hash.
=> chore: Enable CI on merge_group trigger

iroh-net/src/derp/client.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/key/node.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs
This uses the short hex format of the node PublicKey that was used for
the MagicSock logging in all places where we log.  It uses this format
in the Display of the PublicKey to make this convenient.
=> ref(iroh-net): Use a short format for node PublicKey logging

iroh-net/src/bin/derper.rs, iroh-net/src/derp/client.rs, iroh-net/src/derp/clients.rs, iroh-net/src/derp/http.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/derp/http/mesh_clients.rs, iroh-net/src/derp/http/server.rs, iroh-net/src/derp/server.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/metrics.rs, iroh-net/src/magicsock/udp_actor.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh-net/src/netcheck/reportgen/hairpin.rs, iroh-net/src/portmapper.rs, iroh-net/src/test_utils.rs, iroh/src/commands/provide.rs
This is another commit that keeps fine-tuning our logging.
- Most importantly this consistently attaches spans when tasks are
spawned.  This threads togehther a lot more context.
- As a general rule spawned tasks get info_span!(), otther spans get
debug_span!()
- protmapper report is logged on info in reportgen now, just as the
other sub-reports.
- MagicSock::poll_recv logs number of datagrams on trace now instead
of info.  This is expected to be a lot.  A new metric is added to
keep track of this as well.
=> refactor(iroh-net): Always attach tracing spans to spawned tasks

iroh/examples/sync.rs, iroh/src/sync/content.rs
Adds a simple watch command to show notifications when changes come in
=> example(sync): add watch command

.github/workflows/ci.yml, .github/workflows/netsim.yml
Detects if we're running netsim from a fork and doesn't dump reports.
Closes https://github.com/n0-computer/iroh/issues/1297
=> chore(ci): ensure external contributors don't fail CI on report dumps

Cargo.lock, iroh-gossip/Cargo.toml, iroh-gossip/src/lib.rs, iroh-gossip/src/metrics.rs, iroh-gossip/src/net.rs, iroh-gossip/src/proto/plumtree.rs, iroh-gossip/src/proto/state.rs, iroh-gossip/src/proto/topic.rs, iroh/examples/sync.rs, iroh/src/sync.rs, iroh/src/sync/content.rs, iroh/src/sync/live.rs, iroh/src/sync/metrics.rs
This PR adds metrics for iroh-gossip and iroh-sync. The commit on iroh-gossip should move to #1149 but this will happen not today to keep things easy for the demo.
Also adds a `stats` command to the repl to display current metrics.
=> feat: metrics for iroh-gossip and iroh-sync

iroh-sync/src/sync.rs, iroh/src/sync/content.rs, iroh/src/sync/live.rs
uses flume channels to allow for combined sync and async usage
=> fix: remove usage of unbounded channels

iroh/examples/sync.rs
Adds a flag to start serving metrics on an endpoint in OpenMetrics form, makes life easier to plug it into other tooling.
=> feat: enable metrics server on sync REPL

iroh-net/src/portmapper.rs
Noticed that under current configuration options portmapping would always try pcp no matter what. This fixes the logic to first try available protocols and then attempt unavailable but enabled ones 
further work will be required in the future anyway
=> fix(iroh-net): portmapper priority follows described priority strategy

Cargo.lock, Cargo.toml, iroh-bytes/Cargo.toml, iroh-bytes/src/provider.rs, iroh-bytes/src/util.rs, iroh/Cargo.toml, iroh/src/collection.rs, iroh/src/commands/get.rs, iroh/src/database/flat.rs, iroh/src/database/mem.rs, iroh/src/dial.rs, iroh/src/util/io.rs, iroh/tests/cli.rs, iroh/tests/provide.rs
Use the newly published iroh-blake3 and bao-tree to get much faster hashing of 16kb subtrees. Factor of 4 improvement due to SIMD use in blake3.
Ideally we would move back to upstream blake3 eventually, once https://github.com/BLAKE3-team/BLAKE3/pull/329 is merged.
To make the switch and the subsequent switch back easier I removed the dependency on blake3 and instead reexported our forked blake3 as blake3 in bao-tree.
Is there a nicer way to do all this reexport business?
=> Fast bao tree

iroh-net/src/defaults.rs, iroh-net/src/derp/http/mesh_clients.rs, iroh-net/src/derp/map.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh-net/src/netcheck/reportgen/probes.rs, iroh-net/src/stun.rs, iroh-net/src/test_utils.rs, iroh/src/config.rs
The `DerpMap` wasn't being changed anyway at runtime, only for initial config.
Closes #1182
=> refactor(iroh-net): keep `DerpMap` fixed

iroh-net/src/tls.rs, iroh-sync/src/sync.rs, iroh/src/download.rs, iroh/src/lib.rs, iroh/src/metrics.rs, iroh/src/sync.rs, iroh/src/sync/content.rs, iroh/src/sync/live.rs, iroh/src/sync/metrics.rs
Try to download content from the peer that informed us about a change. During set reconciliation that is the peer we're talking to, during gossip it's the next peer in the graph (so not the sender of the message but the peer which forwarded the message to us). 
This is not finished and waiting for a better downloader which will come soon, but might be interesting to try out now still.
* We'll want some infrastructure to easily extend this to download from other peers too if both author and informer failed
* The downloader will definitely need to support retries after timeouts, because right now you will easily get a gossip message before the other peer downloaded the content themselves
=> [WIP] feat(iroh-sync): download from peer that informed us about a change

iroh-net/src/portmapper/current_mapping.rs, iroh-net/src/portmapper/mapping.rs
- Removes the `transparent` attribute from the derived `Debug` implementation for `Mapping`.
- Bump log level where new mapping is logged to `debug`
In hindsight this was the better option all along anyway, since this prints the variant name.
The new log look like this: 
```bash
$ env RUST_LOG=iroh_net::portmapper=debug cargo run doctor port-map upnp 2347
```
=> fix(iroh-net): remove `transparent` attribute from mapping debug + log bump

iroh/src/get.rs, iroh/src/lib.rs, iroh/src/node.rs
This is extracted from #1333. To use the iroh-bytes `get` protocol easily from outside of the `iroh::node::Node`, these functions are moved into a new module `get`. They are used in the new `Downloader` in #1333.
=> refactor: move iroh bytes get handlers out of node into module

iroh/src/commands/get.rs
The `get` code path was unable to handle different regions, as the derp map was not set.
=> fix(iroh): pass derp map when setting up Node for get

iroh/src/commands/doctor.rs, iroh/src/commands/provide.rs, iroh/src/config.rs, iroh/tests/cli.rs
Currently the handling of paths and files within the IROH_DATA_DIR was a bit ad-hoc. This adds an enum in `config.rs` to only use well-defined paths.
=> refactor: improve path handling in iroh dir

iroh/examples/sync.rs, iroh/src/node.rs, iroh/src/sync/engine.rs, iroh/src/sync/live.rs, iroh/tests/sync.rs
Adds `LiveEvent`s when the content of an entry is downloaded. Also adds availability status of content to the live events.
Now the end-to-end sync test passes without any `sleep`!
* I wasn't sure if the entry `RecordIdentifier` should be included in the event, or only the content `Hash`. Right now the PR does the latter, but could easily switch to the former if it makes it more usable.
* The `SyncEngine` now doesn't do anything over the `LiveSync`. We might want to unify the two structs.  But would do in a seperate PR.
* We might want to add more events later
=> feat(sync): emit event when entry content is downloaded from peers

deny.toml
This allows the old ed25519-dalek crate in our cargo-deny config for
now.  IIUC the way we use this is not currently a probelm and PR #1352
is aiming to fix this entirely.
This should be reverted as part of #1352.
=> deps: Allow old ed25519-dalek crate in cargo-deny for now

README.md, iroh/README.md
Use an `=` instead of `:` when importing the iroh crate
=> chore: Update README.md

iroh-gossip/src/net.rs
This test is seen to be flaky on CI and just spins forever until CI
times out and gives up.  By adding timeouts to the test itself we
should see the test fail instead of spin forever.  And as a failed
test we should get logs from CI.  Logs are probably needed to figure
out why this is flaky.
=> test(flaky): Add timeouts to gossip smoke test

iroh-bytes/src/baomap.rs, iroh/src/baomap/flat.rs, iroh/src/baomap/mem.rs, iroh/src/baomap/readonly_mem.rs
This adds the methods `contains_complete` and `contains_partial` to `baomap::Map`, and `is_complete` to `baomap::Map::Entry`.
=> feat: methods to check if a hash is complete or partial

iroh-sync/src/keys.rs, iroh-sync/src/lib.rs, iroh-sync/src/metrics.rs, iroh-sync/src/ranger.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/examples/client.rs, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/node.rs, iroh/src/sync/live.rs, iroh/src/sync/rpc.rs
This PR has a couple of cleanups to `iroh-sync`.
* Adds `deny(missing_docs)`, adds a lot of docs, reduces the public API surface a bit, and a few minor changes to support this
* Adds high-level docs to the `iroh-sync` crate
* Moves `Author`, `AuthorId`, `Namespace` and `NamespaceId` to a new `keys` module
* make `list_namespaces` (was `list_replicas`) and `list_authors` return iterators. the implementations still `collect()` internally, but the surface is fixed. proper fix will need the self-referential dance again.
In a yet-to-be written commit, I'd move the exports from the `sync` and `keys` module to the top level.
=> iroh-sync API cleanup & docs

iroh-net/src/magicsock.rs
this seems to be the safest way to fix possible GSO/GRO issues on all platforms (Linux and ???) that support them.
This is a fix for the possible issues described in https://github.com/n0-computer/iroh/issues/1357 that does the simplest possible thing - just split up the packets before sending them to the derper.
Note that we still get GRO/GSO when we have a direct connection. And since the stream to the derper is a byte stream, unless we flush after each send this should still be rather efficient. The only downside is that the derper has to deal with more individual packets.
Does this fix the issue?
=> fix(iroh-net): split packets on send

Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/derp/http/client.rs
Replaces [`webpki`](https://github.com/briansmith/webpki) with [`rustls-webpki`](https://github.com/rustls/webpki) as a fix to https://rustsec.org/advisories/RUSTSEC-2023-0052. Updates `reqwest` and `tokio-rustls-acme` to latest versions (which include the same change from `webpki` to `rustls-webpki`).
Also updates `webpki-roots` to the latest version.
Did not do any manual testing. Would hope that CI should catch any incompatiblities.
=> deps: update webpki to rustls-webpki and webpki-roots to latest

iroh-net/src/magicsock.rs
The pub(self) visibility specifier is only really meaningful in some
macro situations.  In normal code it just adds unexpected words.
=> refactor(iroh-net): Remove pub(self) visibility specifier

iroh/src/client.rs, iroh/src/rpc_protocol.rs, iroh/src/sync/live.rs, iroh/src/sync/rpc.rs, iroh/tests/sync.rs
So far in #1333, if a RPC or in-memory client called `doc.subscribe()` the event callback would never be dropped, even if the client did drop the event stream. This PR fixes this, by having the event callbacks return whether the callback should stay active or not. We can't use the removal token here, because calling `LiveSync::unsubscribe` from within the event callback would deadlock the actor.
Also adds a a `LiveStatus` to the doc info RPC call. For now only contains the number of subscribers. More info, e.g. on peers, can come later.
* As of #1333 and unchanged by this PR: `doc.subscribe` will fail for documents that are not in the `LiveSync` (they are added via `doc.import` or `doc.start_sync`). This is unfortunate, because you'd often want to setup a subscription before starting …
=> fix(sync): properly drop rpc subscriptions, add doc status

iroh/Cargo.toml, iroh/src/sync.rs, iroh/src/sync/codec.rs
switches to also use tokio::codec under the hood now.
Also introduces a max message length of 1GiB for now.
=> refactor(iroh): simplify and cleanup the sync algorithm

Cargo.toml
All the crates use edition 2021 which use this resolver, but the
workspace itself defaults to resolver 1.  This creates confusion and
it is better to set everything to resolver 2.
This solves the following error since rust 1.72:
cargo-json-read-from-string: warning: some crates are on edition 2021 which defaults to ‘resolver = "2"‘, but virtual workspaces default to ‘resolver = "1"‘
note: to keep the current resolver, specify ‘workspace.resolver = "1"‘ in the workspace root’s manifest
note: to use the edition 2021 resolver, specify ‘workspace.resolver = "2"‘ in the workspace root’s manifest
=> chore: Specify resolver 2 for entire workspace

Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/key.rs, iroh-sync/Cargo.toml, iroh-sync/src/keys.rs, iroh-sync/src/net/codec.rs, iroh-sync/src/ranger.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs
This fixes two bugs:
* Range contains calculation for iroh-sync compound keys was incorrect
* fs store `get_range` implementation (redb) was incorrect for wrap-around ranges
It also contains these refactorings:
* Improve many_authors test to verify all messages are correct
* Simplify the fs store implementation by adding constructor methods to the range iterators
=> fix sync reconcilation bug

iroh-net/src/dns.rs
On at least iOS the resolve.conf is not available, so need to fallback to a default configuration in that case.
Based on the tested approach in DeltaChat
Fixes #1436
=> fix(iroh-net): dns fallback to default config

iroh-sync/src/net/codec.rs, iroh-sync/src/ranger.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/examples/client.rs, iroh/examples/sync.rs, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/live.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
(PR text updated by @Frando)
This is needed, to ensure both sides will end up with the actual latest version. Also stops storing old versions, as they are not used anymore, and things get very complicated otherwise.
This leads to a couple of changes (all in this PR):
* The store always overwrites if an entry with identical (`namespace`, `author`, `key`) and later timestamp than current is inserted
* The `GetFilter` doesn't have `latest` option anymore and is now a enum
* RPC gets `get_one` to select an entry by author and key
* This change should inform our docs and discussion about author sharing: Using the same author privatekey on different nodes now would mean that concurrent writes while offline would result in the older of the entries (by wall clock time) being deleted and lost …
=> feat(iroh-sync) include timestamps in the sync and remove history

Cargo.lock, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs, iroh-net/src/netcheck/reportgen.rs, iroh/Cargo.toml, iroh/src/client.rs, iroh/src/commands.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs
Display connection information for all nodes we have connected with or have supplied our node with addresses for.
Display connection information on a particular node, using its node id.
=> feat: get list of `ConnectionInfo`s or an individual node's `ConnectionInfo`

iroh-sync/src/net/codec.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/examples/client.rs, iroh/examples/sync.rs, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
Changes `Store::get` to `Store::get_many` and `Store::get_by_author_and_key` to `Store::get_one`, in the trait and the RPC interface. Much clearer IMO.
Based on #1445
=> refactor(iroh-sync): `get_many` and `get_one` method names

iroh-sync/src/sync.rs
Builds on #1445. Had an idea - we can make the `RecordIdentifier` be a newtype wrapper around `Bytes`. With this we can expose the `RecordIdentifier` directly as a simple continous byte slice.
I'm not too sure if we gain much over the previous form – Maybe some performance when cloning oftenly. And @rklaehn wanted to have a simple byte representation for store improvements.
=> refactor(iroh-sync): store `RecordIdentifier` as bytes

iroh-net/src/defaults.rs, iroh-net/src/derp/http.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/derp/map.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh-net/src/stun.rs, iroh-net/src/test_utils.rs
The DerpNode had a field to override the IP address of the STUN server
in testing scenarios.  However we do not use this, it is always the
same address as the derp server, just like in production.
Removing this removes some code complexity.
I believe this was an unused left-over from the wireguard conversion.
=> test(iroh-net): Removed unused stun_test_ip field from DerpNode

iroh-sync/src/sync.rs, iroh/examples/sync.rs
The sync example uses the low level API, and was using an outdated call.
Fixes #1451
=> fix(iroh): update example to use correct subscription API

README.md
This slight tweak to the README fixes a grammar issue in using "it's" vs. "its".
N/A
=> docs: Fix grammar in README

README.md
Fixes a link in the README to correctly point to the documentation.
N/A
=> docs: fix link to install URL in README

iroh/src/client.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs
This makes getting blobs over RPC streaming. Before we'd alloc the full blob in-memory, which of course is a no-go.
Client API methods will be renamed in the upcoming API refactor.
=> feat: streaming blob reads over RPC

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
This field is unused and models a concept from tailscale that we don't have. This doesn't mean the peer's info is stale, or that it was last seen long ago, it means that the peer's public key expired based on an explicit `KeyExpiry *time.Time`. 
From their docs
>```
>// Expired is whether this node's key has expired. Control may send
>// this; clients are only allowed to set this from false to true. On
>// the client, this is calculated client-side based on a timestamp sent
>// from control, to avoid clock skew issues.
>```
In tailscale the `Expired` is only set by a `ExpiryManager` based on that timestamp, from local computation; and only when the `NetworkMap` has not updated it based on a `MapResponse` requested to the server. We have none of this concepts. 
If we want to define that a …
=> refactor(iroh-net): remove unused `expired` field from `Endpoint`

iroh-net/src/config.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
the `Node` type contains:
https://github.com/n0-computer/iroh/blob/f2f3ead655dee94bd01c9f4fdcc8730457f51ffd/iroh-net/src/config.rs#L157-L174
from these fields:
- `name` is always `None`, so unused.
- `addresses` is always calculated from the the `endpoints` so it can be removed.
After this, the only remaining fields are the key, endpoints and derp region. This is equivalent to the `NodeAddr` type, making `Node` redundant
https://github.com/n0-computer/iroh/blob/f2f3ead655dee94bd01c9f4fdcc8730457f51ffd/iroh-net/src/magic_endpoint.rs#L20-L29
=> refactor(iroh-net): remove `iroh-net::config::Node` since limited to its used fields it's redundant

iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/examples/sync.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/live.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
Based on #1491 
This adds two related features that were missing so far:
* Add `iroh_sync::store::close_replica` to remove a replica instance from the store-internal cache of open replicas. This is needed because otherwise it grows unbounded (for anchor nodes especially).
* Properly handle open replicas in the `LiveSync`, and through this allow to subscribe to replica events for replicas that are not in the set of actively syncing replicas. This was not possible before (you could only subscribe to replicas that are active for sync)
* Add test for subscribing without sync
=> feat(sync): Add `close_replica` and enable subscriptions without active sync

iroh-bytes/src/provider.rs, iroh-net/src/lib.rs, iroh-net/src/magic_endpoint.rs, iroh/examples/client.rs, iroh/examples/collection.rs, iroh/examples/hello-world.rs, iroh/src/client.rs, iroh/src/client/quic.rs, iroh/src/commands.rs, iroh/src/commands/add.rs, iroh/src/commands/get.rs, iroh/src/commands/list.rs, iroh/src/commands/provide.rs, iroh/src/commands/repl.rs, iroh/src/commands/sync.rs, iroh/src/commands/validate.rs, iroh/src/dial.rs, iroh/src/get.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/tests/cli.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
* Extend Iroh client surface
* Split Iroh client struct into node, blobs, docs
* Use Iroh client in CLI (no more raw RPC calls)
* Improve naming consistency throughout the RPC interface
* Use `iroh_net::NodeAddr` in ticket and get commands
* Improve arguments of `BlobGetRequest`
=> refactor: extend Iroh client, improve API consistency

iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs
Adds an iterator over all content hashes in the document store. Needed for #1496.
=> feat: content hashes iterator for sync store

Cargo.lock, iroh-sync/src/sync.rs, iroh/Cargo.toml, iroh/src/node.rs, iroh/src/rpc_protocol.rs
Right now in the debug logs we print the following for each incoming RPC request:
```
handling rpc request: quic_rpc::transport::flume::FlumeServerEndpoint<iroh::rpc_protocol::ProviderRequest, iroh::rpc_protocol::ProviderResponse>
```
which is very long and not useful because it contains no info at all about incoming request.
Before that, we printed the full Debug impl, which contained too much (especially bytes).
This PR changes it to just print the enum variant name, so e.g.
```
handling rpc request: BlobRead
```
Also removes a debug leftover `println`.
=> fix: print enum variant name for RPC debug logs

Cargo.lock, iroh-net/Cargo.toml
solves https://rustsec.org/advisories/RUSTSEC-2023-0063
na
=> deps(iroh-net): use minimum safe version of quinn-proto

iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-gossip/src/net/util.rs, iroh-net/examples/magic.rs, iroh-net/src/lib.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs, iroh-net/src/test_utils.rs, iroh-sync/src/net.rs, iroh/examples/collection.rs, iroh/examples/hello-world.rs, iroh/src/commands.rs, iroh/src/commands/doctor.rs, iroh/src/dial.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/live.rs, iroh/tests/cli.rs, iroh/tests/provide.rs
- Adds a `AddrInfo` that contains the addressing information of peers. This is necessary as it's own type since it's serialized both in gossip and in #1488 
- Renames `NodeAddr` to `PeerData` (better name suggestions are well received) this helps consolidate the "peer" terminology already present throughout gossip, sync, downloader, and many other places
- Use this type in different parts of the code. Some other types that can be replaced by this are left to #1493 
This applies the suggestion of doing `connect` using the full type. It's debatable if this is better than `connect(PublicKey, AddrInfo)` but both are imo an improvement over the current way since the idea if "what does iroh need to connect to a peer" is now fully described in a type
=> refactor(*):  rework `NodeAddr`

iroh-net/src/key.rs, iroh-sync/src/net.rs, iroh-sync/src/net/codec.rs, iroh-sync/src/sync.rs, iroh/src/sync_engine/live.rs, iroh/tests/sync.rs
On `main` the test `sync_full_basic` is flakey. This PR (hopefully) fixes it.
The reason was: We have the situation that two peers initiate connections to each other at (roughly) the same time. In #1491 this was sometimes prevented, but not reliably.
This PR fixes it by:
* When connecting, we set a `SyncState::Dialing` for the `(namespace, peer)`
* When accepting, if our own state is `Dialing` for the incoming request for `(namespace, peer)` we compare our peer id with that of the incoming request, and abort if ours is higher (doesn't matter which way, we care about a predictable outcome only
* Through this, only one of the two simoultanoues connections will survive
* Also added a `Abort` frame to the wire protocol to transfer to inform the dialer about the reason of the declined request, …
=> fix: avoid double conns, better state tracking

iroh/README.md, iroh/examples/client.rs, iroh/examples/dump-blob-fsm.rs, iroh/examples/dump-blob-stream.rs, iroh/examples/hello-world.rs, iroh/examples/rpc.rs, iroh/examples/sync.rs
discord user `drhongo` pointed out that our example instructions are out of date. This updates.
=> docs: update instructions for running rust examples

iroh-gossip/Cargo.toml, iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-gossip/src/proto.rs, iroh-gossip/src/proto/plumtree.rs, iroh-gossip/src/proto/tests.rs, iroh-gossip/src/proto/topic.rs, iroh-sync/src/ranger.rs, iroh-sync/src/sync.rs, iroh/src/downloader.rs, iroh/src/downloader/test.rs, iroh/src/downloader/test/dialer.rs, iroh/src/node.rs, iroh/src/sync_engine/live.rs
This improves content propagation for document sync by implementing the following features. 
* feat: allow to send gossip to neighbors only
* feat: provider and candidate roles for downloader
* feat: transfer content status during set reconciliation
* feat: inform neighbors about finished content downloads
na
=> feat: Improve content propagation in sync

iroh-gossip/src/net.rs, iroh-gossip/src/proto.rs, iroh/examples/sync.rs, iroh/src/commands/sync.rs, iroh/src/sync_engine/live.rs, iroh/tests/sync.rs
* **fix(gossip): properly encode peer data.** #1506 introduced a bug: The `PeerData` was encoded from the `PeerAddr` (including the peer id) but decoded to `AddrInfo` (without the peer id). So it failed, and dialing peers failed. It only did not matter much because most tests use tickets separately, so do not rely on the `PeerData` gossip.
* **feat: expose neighbor events** through document subscriptions. for now used to write better and less flakey tests. also useful for stats like usecases, and potentially others.
* **tests: improve sync tests** and make `sync_full_basic` not flakey anymore (hopefully). the main change is that for some events, we don't care about the exact order in tests anymore, because the exact order is too unpredictable timing-wise for things that happen …
=> fix(sync): fix `PeerData` encoding, neighbor events, better & predictable tests

iroh-bytes/Cargo.toml, iroh-gossip/Cargo.toml, iroh-metrics/src/core.rs, iroh-sync/Cargo.toml, iroh/Cargo.toml
Unfortunately non default feature builds were broken again, as we don't check them in CI yet.
=> fix: no-default-features builds

iroh/src/commands.rs, iroh/src/commands/get.rs, iroh/tests/cli.rs
This brings the console download GUI in line with iroh get. You get a nice progress bar instead of just an event dump.
In addition I fixed(?) a few other things. The different download stages 1/3 connecting, 2/3 requesting 3/3 downloading are now only shown transiently as the progress bar message. The only thing that is permanent is "requesting <hash>" and the (successful or unsuccessful) outcome.
To make this possible I had to change the test regexes to only look for the permanent output, which I think is not bad. We really don't want to test the transient outputs in all the tests. Maybe there should be one test that does that that is specifically made to test the "console UI".
This is one thing I found that is related to https://github.com/n0-computer/iroh/issues/1498
For debugging the …
=> Console download progress

iroh-metrics/src/core.rs, iroh-sync/src/sync.rs
Adds `cfg expressions` to remove dead-code warnings when testing using `--no-default-features` flag.
=> fix some dead-code warnings when using `--no-default-features`

iroh/src/baomap/flat.rs, iroh/src/baomap/mem.rs
Tiny bugfix for the progress events when adding to a mem node. Before it would send extra ids, causing the progress display logic to panic. Now it is fixed.
To test, cargo run --example rpc and do somehting like add a directory.
=> Mem rpc add

iroh-net/src/magicsock.rs
This response is not critical.  If someone dropped the receiver it's
just fine, it meant they didn't care about the response anymore.
This has occurred during shutdown.
Part of #1528
=> fix(iroh-net): Do not unwrap sending on response channel

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
By default endpoints are now inactive, and will not be pinged. 
Closes #1538
=> fix: mark initially created endpoints inactive

iroh-bytes/src/baomap.rs, iroh-bytes/src/collection.rs, iroh-bytes/src/provider.rs, iroh/examples/collection.rs, iroh/examples/dump-blob-stream.rs, iroh/examples/rpc.rs, iroh/examples/sync.rs, iroh/src/baomap/readonly_mem.rs, iroh/src/collection.rs, iroh/src/commands/get.rs, iroh/src/commands/provide.rs, iroh/src/downloader/get.rs, iroh/src/get.rs, iroh/src/node.rs, iroh/tests/cli.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
As discussed on Friday, this turns collections into just sequences of hashes
~Just wanted to check how much effort this is. Not ready to merge. But the effort seems very manageable...~
How should the two concepts be named.
1. a collection as in a sequence of links
2. a thing that contains names and can therefore be used to map a directory tree
Todo:
=> Collection = Vec<Hash>

iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-net/examples/magic.rs, iroh-net/src/derp.rs, iroh-net/src/derp/map.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh/examples/sync.rs, iroh/src/commands/doctor.rs, iroh/src/commands/get.rs, iroh/src/commands/node.rs, iroh/src/dial.rs, iroh/src/node.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
`node::Builder::disable_derp` is broken. We do not call `MagicEndpointBuilder::disable_derp` for that, and at some point we changed the magic endpoint to default to the default, n0-supplied derp servers.
This fixes this through a `DerpMode` enum that is much more explicit I think.
Fixes #1558
=> fix: actually allow to disable DERP

iroh-gossip/src/net.rs, iroh-gossip/src/proto/hyparview.rs, iroh-net/src/key.rs, iroh-net/src/magicsock.rs, iroh/src/downloader.rs, iroh/src/node.rs, iroh/src/sync_engine/live.rs
second take at #1544 since forced pushed closed prs can't be reopened
```
2023-10-02T18:46:34.455601Z DEBUG magicsock{me=2luekswh7o3a5tz4}:derp.actor:recv_detail:client-connect{key=2luekswh7o3a5tz4enymovsoksgnpb2qpmxlvifp6ywwjnacihya}:connect_0: rustls::client::tls13: TLS1.3 encrypted extensions: [ServerNameAck]
```
```log
2023-09-28T20:51:18.908126Z DEBUG sync{me=oywqb57ovmdry243}: iroh::sync_engine::live: sync[dial]: start namespace=NamespaceId(q47zmyim5r6isz22…) peer=PublicKey(2jnygwapdm26wwa2) reason=DirectJoin last_state=None
```
```logs
2023-09-28T20:58:42.854730Z DEBUG gossip{me=zooj7iazcl7rsoal}: iroh_gossip::net: handle out_event EmitEvent(TopicId(wno5nwxtkhhtnqsm…), Received(GossipEvent { content: <33b>, delivered_from: PublicKey(7a7kkzndvbt6eulu), scope: Neighbors }))
```
``` …
```
=> feat(*): log me

iroh-sync/src/sync.rs
the content of this test is the same as `test_basics_memory` so it;s doing a duplicated test scenario. Name suggests this is what should be here instead
na
=> test(iroh-sync): fix `test_content_hashes_iterator_memory`

iroh/src/baomap/flat.rs, iroh/src/baomap/mem.rs
We've decided that `INFO` logging level & above should be reserved for node operators that are at least familiar with iroh's different subsystems, but _not_ engineering internals.
This is less than ideal on node startup: 
So, drop to debug level.
=> chore(baomap): drop all baomap logging to debug or lower

iroh-gossip/src/net.rs, iroh-net/src/magic_endpoint.rs, iroh/tests/sync.rs
- avoid using `tokio::sync::watch` has it has a history of causing random blockages
- do not recursively call into the magicsocket to retrieve endpoints
Closes #1568
=> fix: avoid blockage in endpoint handling

iroh-gossip/src/metrics.rs, iroh-net/src/derp/metrics.rs, iroh-net/src/magicsock/metrics.rs, iroh-net/src/netcheck/metrics.rs, iroh-net/src/portmapper/metrics.rs, iroh-sync/src/metrics.rs, iroh/src/metrics.rs
The current metrics names/labels are not compatible with the OpenMetrics format and prometheus declines to ingest them.
=> fix(metrics): labels need to be lowercase underscore format

iroh/src/commands/sync.rs
Allows formatting content in different ways in the repl.
There are now three content display modes:
- `hash`: what was previously
- `content`: the whole content. You add a txt novel you get a txt novel
- `auto`: displays the content fully if it's short or shortened if it's long
Display content mode is added to three commands:
- **`doc keys`** uses by default auto mode, but can be set to any mode with `--mode content|auto|hash`
- **`doc get <key>`**  uses by default auto mode, but can be set to any mode with `--mode content|auto|hash`
- **`doc watch`** behaviour is to use `auto` mode for available content and `hash` mode for missing and incomplete content
makes the keys bold because they are a bit hard to read otherwise
Showcase:
```bash
> doc keys
```
=> feat(iroh): improve displaying content in the repl

iroh-net/src/derp/http/client.rs, iroh-net/src/magicsock.rs, iroh-net/src/netcheck/reportgen.rs, iroh-sync/src/sync.rs
ci is unhappy with the new rust release
n/a
=> chore(*): make clippy happy

iroh-net/src/stun.rs
This is run on every packet, and showed up in some profiling as not being as cheap as it should be
=> perf(iroh-net): simplify stun::is check

iroh-bytes/src/baomap.rs, iroh-bytes/src/collection.rs, iroh-bytes/src/get.rs, iroh-bytes/src/hashseq.rs, iroh-bytes/src/lib.rs, iroh-bytes/src/protocol.rs, iroh-bytes/src/protocol/range_spec.rs, iroh-bytes/src/provider.rs, iroh-bytes/src/util.rs, iroh/Cargo.toml, iroh/examples/collection.rs, iroh/examples/dump-blob-fsm.rs, iroh/examples/dump-blob-stream.rs, iroh/examples/sync.rs, iroh/src/collection.rs, iroh/src/commands.rs, iroh/src/commands/add.rs, iroh/src/commands/get.rs, iroh/src/dial.rs, iroh/src/downloader.rs, iroh/src/downloader/get.rs, iroh/src/get.rs, iroh/src/lib.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/tests/provide.rs
As discussed, this removes the custom get request. Fixes https://github.com/n0-computer/iroh/issues/1554
A custom get request is going to be replaced by the following:
- create a connection under another ALPN (not the iroh-bytes one)
- do whatever custom exchange needed to figure out what is to be done
- use the existing quinn stream for a bao sync
Also removes the custom collection parsing. Collections are now just sequences of blake3 hashes. Fixes https://github.com/n0-computer/iroh/issues/1553
Custom collections are going to be replaced by two things: For the purpose of the network protocol, they are going to be replaced with an exchange under a custom ALPN as described above. For the purpose of GC they are going to be replaced by a way to enumerate live nodes.
How detailed will the …
=> Remove custom get and custom collections

iroh-bytes/Cargo.toml
Fixes the dependency to `iroh-io` in `iroh-bytes`. Wasn't caught by CI due to feature unification.
=> fix: feature flags for iroh-io dependency

iroh/src/downloader.rs, iroh/src/downloader/invariants.rs
We weren't removing the hash of a request that was scheduled, became ready but couldn't be executed. This caused getting the next hash for a provider to pop a hash no longer necessary.
I added an invariant check for the provider map and it seems to be we missed a couple removals in #1480 so this fixes removal in cancellation as well
one small change, seemingly unrelated, is that the `debug_assert` now uses the debug version of the hash instead of display. This is because throughout the file we log the kind in debug, which in turn uses the debug impl for the hash. This difference made it a bit harder to follow the logs because the printed hash didn't match those in the rest of the logs. The change makes this consistent
=> fix(`iroh::downloader`): remove hash from `providers` in two missed cases

Cargo.lock, iroh-sync/Cargo.toml, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/src/sync_engine/live.rs
Store peers that have been useful for sync
A live test consisted on:
- `node_a` creates and shares a ticket (with only `node_a` in it)
- `node_b` joins the ticket
- `node_c` joins the ticket. At this point all three peers are aware of the other two
- shutdown all nodes
- bring `node_c` back again
- join `node_c` using the ticket from `node_a` (which is gone)
- `node_c` has cached `node_b` as useful and dials it
=> feat(iroh-sync): store peers per doc

iroh-bytes/src/util.rs
part 1 of my secret masterplan to use hex encoding everywhere...
Allows you to use hex blake3 hashes without any `bafkr4i`
Can we do this for the output as well?
=> Allow using b3sum output to identify hashes

iroh-net/src/bin/derper.rs
Deploying a derper node is a bit cumbersome right now if you don't run with default config. You have to provide a `secret_key` but have no easy path to generate one so either you dance to create a fresh config and then modify it or need to use some external thing to generate keys for you. Either way it's cumbersome.
This just adds an extra handler to inject a secret key if not present already in the supplied config.
=> fix(derper): update config to auto generate keys

iroh-net/src/magicsock/endpoint.rs
There seems to be no reason why we should store more than one `PongReply` since only the last is ever used
If at some point we do need to check back on pong history this can be easily done with a `VecDeque`
=> refactor(iroh-net): store a single pong

Cargo.lock, iroh-sync/src/keys.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/Cargo.toml, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/live.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
In `iroh-sync`:
* feat: Add `Store::remove_replica` to remove a replica (namespace secret key and all entries)
* feat: Adds `closed` atomic bool on `Replica` to ensure no operations can be performed on closed or removed replicas
* refactor: To not add yet another `Arc` for the `closed` marker, move all things into `InnerReplica`
In `iroh`:
* feat: Add `DocDrop` to RPC protocol
* rename `StopSync` to `Leave`
* feat: Add `doc leave` command to CLI / console. `doc leave` runs `DocStopSync` in the RPC layer (we already had that), 
* feat: Add `doc drop` command to delete a document
Fixes #1497
=> feat: leave and drop docs

iroh-bytes/src/baomap.rs, iroh/src/baomap/flat.rs, iroh/src/baomap/mem.rs, iroh/tests/gc.rs
The issue was that a temp tag was not inserted into the live set. This is not a problem if it happens outside a gc. But if it happens right between a gc mark phase and a gc sweep phase, the temp pin will not be considered, and the data associated with the temp pin might be deleted.
I knew that this had to be done, and I think I even did it at some point, but it must have been lost in some refactoring.
There are a number of places where temp pins are not used. See https://github.com/n0-computer/iroh/issues/1611 . But I think this should be done in a separate PR since this definitely fixes something.
This increases the gc frequency so much that gc is running continuously with no pause whatsoever for some tests. That was the only way to get the failure mentioned above at least semi-reliably.
=> Fix flakiness of gc_hashseq test

iroh/src/commands/sync.rs
The purpose of the `doc keys` command is to list keys. Having a default of `auto` that shows content, which makes the output unreadable from a "fast review of the keys in this doc" use case:
one default change keeps both the option, and makes the output useful again:
This leaves `doc get` untouched, which should absolutely keep the `auto` default.
=> fix(cli,console): default to 'hash' mode for the keys command

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
We were storing reverse mappings for `SendAddr::Derp` in the `PeerMap`. This means basically treating the DERP as a peer itself. We concluded this is something we shouldn't do. To fix the issue, the better solution is to enforce it via the type system. As such, we now only do reverse mapping from socket addresses.
As a note, I added a new type `IpPort`. Using `SocketAddr`s as key to hashmaps often goes wrong with ipv6 because of the flow control & class fields it contains. These fields can't be assumed stable even within the same connection: sending a the socket address made from an (ipv6, port) and receiving a response can make it look like the socket address is different (same ip, same port, different flow labels) Ignoring these fields has some limitations in extremely exceptional cases …
=> fix(iroh-net): reverse ip-port mapping stores only direct addresses in the peermap

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
The Endpoint contained `SendAddr` instead of `ip`, `port` pairs. This is problematic for a couple of reasons:
- it makes it harder to reason about direct addresses and relay addresses
- makes it harder to properly update the derp-related information
- in principle, we shouldn't be storing multiple derp regions per peer
So this PR enforces storing a single derp region per peer. Some relevant note with these changes:
- this proves we never ping a peer via their relay address. I left some TODOs that I intend to address in a later PR when it's clear how we should be doing this
- I also noticed updating a peer's region is different between "updating from node" to receiving a ping. Maybe this is the right thing to do but it's also peculiar. If a peer pinged us via relay we update their derp …
=> fix(iroh-net): enforce storing a single derp region per peer

iroh-bytes/src/baomap.rs, iroh-bytes/src/get.rs, iroh-bytes/src/protocol.rs, iroh-bytes/src/protocol/range_spec.rs, iroh-bytes/src/util.rs, iroh/Cargo.toml, iroh/examples/collection.rs, iroh/examples/hello-world.rs, iroh/src/baomap.rs, iroh/src/baomap/flat.rs, iroh/src/baomap/mem.rs, iroh/src/baomap/readonly_mem.rs, iroh/src/collection.rs, iroh/src/commands.rs, iroh/src/commands/add.rs, iroh/src/commands/get.rs, iroh/src/dial.rs, iroh/src/downloader.rs, iroh/src/downloader/get.rs, iroh/src/downloader/test/getter.rs, iroh/src/get.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/gc.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
- Some code sharing between the mem and flat bao stores, and turning BlobFormat into an enum
- Create temp tags in the downloader and keep them alive while the download is ongoing
Fixes https://github.com/n0-computer/iroh/issues/1611
Note: this looks worse than it is. I changed BlobFormat to an enum and changed HashAndFormat from a tuple struct to a normal struct. That is the majority of the changes.
=> Integrate tagging with downloader

iroh/src/client.rs, iroh/src/commands/sync.rs
We currently only export via the latest key & the author id, but in the CLI and console, we don't currently have a way of viewing other authors. 
This needs to be fixed asap for demo purposes, and we should have a longer discussion about how we expose the other peers' author ids to the CLI and console: https://github.com/n0-computer/iroh/issues/1628
=> fix: `doc export` exports the latest entry at a given key

iroh-sync/proptest-regressions/ranger.txt, iroh-sync/src/ranger.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs
We had a bug that just was never tested for: When both peers have an entry with identical ranger keys (i.e. identical namespace, author and key), when peer A received an entry from peer B, it would never send their matching entry, even if their entry has a higher timestamp.
This PR fixes this! The actual fix is a single line: https://github.com/n0-computer/iroh/pull/1630/files#diff-be755583e5a892a8b9a6329e59cfc17e9633447fb7992db74eef670ba1508ccbR378
In addition, the PR adds both a manual test for this and a proptest strategy, which are both properly failing without the change.
It also renames the prefix methods on the ranger store trait that were introduced in #1535 to have a clearer naming (which helped me while tracking this down), and improves naming and logic around the prefix in …
=> fix(iroh-sync): actually transfer newer entries for identical keys

iroh-net/src/magicsock/endpoint.rs
- pings the derp region when we ping the udp addresses
- handles pongs via derp
- enables ping and pongs via relay in derp only mode
I left two nodes in my machine, in derp only mode running and they never became direct peers so I consider this a safe change wrt the derp only env flag
This fixes the second part of #1576 
Output example
```bash
> node connections
```
=> fix(iroh-net): ping via relay, enable relay ping in derp only mode

iroh-net/src/derp/http/client.rs, iroh/src/commands/doctor.rs
- make sure that TLS session resumption is possible, by caching the TLS config in the derper
- parallelise dials to derpers in the same region
- expand the `doctor derp-regions` command
=> perf: improve derp connection establishment

Cargo.lock, iroh-bytes/Cargo.toml, iroh-gossip/src/net.rs, iroh-net/Cargo.toml, iroh-sync/Cargo.toml, iroh-sync/src/actor.rs, iroh-sync/src/net/codec.rs, iroh-sync/src/sync.rs, iroh/Cargo.toml, iroh/examples/sync.rs, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/gossip.rs, iroh/src/sync_engine/live.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
This PR contains changes on top of #1612. Made a separate PR to ease reviewing. I'd merge this into #1612 after a review here, and then hopefully merge #1612 into main right after.
Has the following changes:
* Change the subscription model on `Replica`s to be a `Vec<flume::Sender<Event>>`. This now allows to directly subscribe to replica events from multiple places. This allows us to have subscription to replica events from the client not go through any actor. The replica events are merged together with the events from the `sync_engine::live` actor, and that's it. Should improve latency and ease work on the actors. Because we merge the channels for replica events and live actor events for client subscriptions, this means, that closing a replica from the client does not end the …
=> refactor(iroh-sync): move replica event channels to iroh_sync, track open/close state of replicas

.github/workflows/ci.yml, Cargo.lock, iroh-bytes/Cargo.toml, iroh-gossip/Cargo.toml, iroh-gossip/src/net/util.rs, iroh-metrics/Cargo.toml, iroh-net/Cargo.toml, iroh-net/src/derp/http/client.rs, iroh-net/src/netcheck/reportgen.rs, iroh-sync/Cargo.toml, iroh-test/Cargo.toml, iroh/Cargo.toml, iroh/src/downloader.rs, iroh/src/sync_engine/gossip.rs, iroh/src/sync_engine/live.rs
Workaround for #1646  and likely makes more sense in the context of Tokio usage anyway.
In general `JoinSet` is simply used instead.
=> fix: avoid FuturesUnordered

iroh/src/commands/node.rs, iroh/src/node.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/gc.rs, iroh/tests/sync.rs
With #1612 we moved all operations on replicas into a dedicated actor, with all communication happening over a channel. A nice consequence of this is that the iroh-sync store only lives in the actor thread, and therefore we don't need a generic on the `SyncEngine` and the `Node` anymore. This PR removes the generic.
=> refactor(iroh-sync): remove generic from SyncEngine

iroh-net/src/magic_endpoint.rs
rationale: this way the serialized representation of AddrInfo and all the things that contain AddrInfo is unique instead of constantly toggling when there are 2 or more addrs.)
Is there any place that will only work if the addrs are randomized? I don't think so, and I also don't think we should have it. But you never know...
=> iroh-net: Use BTreeSet for AddrInfo

Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs
I did a local test and noticed that there are a lot of times where there is only a single packet going to the derper. This would prevent allocations in that case.
- I guess 1 is by far the most common case. Should we make it larger?
- This will rarely help on linux, but then again mac needs all the help it can get...
=> Use smallvec to avoid allocation when sending a single message to derp

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/endpoint.rs
Small refactor in iroh-net: Do not send disco messages (pings and pongs) over the main actor channel. Instead, either send them right away if the request comes from a poll function, or use a new, small, dedicated task that just sends out the disco messages over UDP. For Derp we drop messages anyway if the channel is full, so no need to pass over the main actor.
=> refactor(iroh-net): Don't send pings over the actor channel

iroh/src/commands/repl.rs
=> fix(iroh): do not exit on ctrl+c

.github/workflows/ci.yml, Cargo.lock, iroh-bytes/Cargo.toml, iroh-gossip/Cargo.toml, iroh-metrics/Cargo.toml, iroh-net/Cargo.toml, iroh-net/src/bin/derper.rs, iroh-net/src/derp/client.rs, iroh-net/src/derp/client_conn.rs, iroh-net/src/derp/codec.rs, iroh-net/src/derp/http.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/derp/http/mesh_clients.rs, iroh-net/src/derp/server.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh-net/src/magicsock/endpoint.rs, iroh-sync/Cargo.toml, iroh-test/Cargo.toml, iroh/Cargo.toml, iroh/src/commands/doctor.rs
- Currently derp messages can be lost, due to using `tokio::select` and`futures::select_all` over non cancelation safe futures. This refactors the code to fix this.
- Additionally this refactors `derp::http::Client` to an actor like structure and removes the need for locks in it
- Bumps MSRV to `1.72` due to updated dependencies
- Refactor `derp::Client` to not use locks either
With this all of the `derp` code is stripped of locks :)
=> refactor(net): improve derp client handling

iroh-net/src/derp/http/client.rs
Documentation for the `test_run_mesh_client` test
=> docs: `test_run_mesh_client` documentation

iroh-gossip/src/net.rs, iroh-net/src/key.rs, iroh-sync/src/actor.rs, iroh-sync/src/heads.rs, iroh-sync/src/lib.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/src/commands/sync.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/gossip.rs, iroh/src/sync_engine/live.rs, iroh/src/sync_engine/state.rs, iroh/tests/sync.rs
This PR implements sync propagation. 
* When a set-reconcilation sync completes, `iroh-sync` now returns a struct `AuthorHeads` which contains a map with an entry for each author for which we *received* entries in the sync operation, and the *latest timestamp* of all entries we received. So it is a kind of "cheapo vector clock", indicating "what's the latest entry we received in this sync op for each author"
* This `AuthorHeads` struct is then sent as a gossip message * to neighbors only*  as a `SyncReport`
* When receiving a sync report, a node checks if the `AuthorHeads` have any news to offer (i.e. if it contains a timestamp for an author newer than the latest existing entry for this author in the local store). If so, the node starts a sync request *to the node we received the report …
=> feat(iroh-sync): Sync propagation

iroh-bytes/src/protocol/range_spec.rs, iroh-sync/src/lib.rs, iroh-sync/src/net/codec.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh-test/src/hexdump.rs, iroh/examples/dump-blob-stream.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/rpc.rs
Actual issue was a double reexport which went unnoticed in older rustc versions. 
Thanks to @bvanjoi in https://github.com/rust-lang/rust/issues/117120#issuecomment-1777113406 for pointing out the problem
=> fix unused export found in nightly rust

Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/derp/http/client.rs
These are supposed to be dialed in order, not in parallel.
This should also fix the warnings in the logs about aborted dials.
=> fix(net): do not dial regions in parallel

iroh-net/src/derp/http/client.rs, iroh-net/src/derp/http/server.rs, iroh-net/src/derp/server.rs, iroh-net/src/disco.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/best_addr.rs, iroh-net/src/magicsock/peer_map/endpoint.rs, iroh-net/src/test_utils.rs
* refactor: Make the abstractions around `PeerMap` and `Endpoint` more solid:
* Better getter API on `PeerMap`, making sure that no mismatch between the indexes and endpoints can emerge
* No more public acccess to endpoint fields from the peermap (only methods)
* fix: Improvments to tracing spans, fields, levels
* fix: Actually send out pings after handling call-me-maybe messages (we did not do that)
* tests: add a test that recreates a node in a loop and connects to the same server node over derp
The new test passes for me locally but still is super slow (~40 seconds for a loop of 5 times bind & connect & transfer 20 bytes). Something is still not correct. It should never take 10 seconds to connect and transfer 20 bytes.
I think I need some help here - my guess is now that something in …
=> refactor(iroh-net): improve `PeerMap` and `Endpoint` abstractions

iroh/src/commands/doctor.rs, iroh/src/ticket.rs, iroh/tests/cli.rs
removes the separator to keep the ticket alphanumeric entirely
na
=> fix(console): remove ticket separator to improve usability

iroh-net/src/magic_endpoint.rs
In a longer debugging session with @dignifiedquire we found out that `wait_idle` will *always* wait on a close timer for a few 100 ms before actually completing. If application layer protocols always take care of finishing their work (which we do) this is not needed at all. Also the magicsock will very likely stay around long enough to still send out the close frame.
This together with #1752 brings the runtime of the `derp_connect_loop` test down from 15s to 4s on my machine! First round is 2-3s (due to bugs in netcheck making it too slow likely) and subsequent round are all >500ms!
=> fix: do not wait_idle on endpoint close

iroh/src/sync_engine.rs
`SyncReason` is a public enum, but it is never exported from its private module.
We don't use `SyncReason` currently in the cli or console, but if other applications have use for it, we need to make it public. Also, allows us to using it in the ffi bindings.
=> chore: makes `SyncReason` public (as expected)

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/peer_map/best_addr.rs, iroh-net/src/magicsock/peer_map/endpoint.rs
Removes the task spawning for queued call-me-maybes. Instead just keep them in a hashmap. This is possible now because sending call-me-maybes is sync anyway. We will lose them if the derp channel is full, which might be a problem, but that is already a problem on main.
Additionally removes `ActorMessage::ReStun` and instead moves the `EndpointUpdateState` onto `Inner`. One less thing to go over the main channel - not needed, because the `EndpointUpdateState` already is a concurrent data structure (with a mutex added for the `next_update`).
Also improves (hopefully) the logic when receiving a call-me-maybe: It now clears the `recent_pong` for all addresses not included in the call-me-maybe, and clears the `best_addr` trust if not included in the call-me-maybe.
=> refactor(iroh-net): call-me-maybe improvements (no more tasks for queue, better logic on recv)

.github/workflows/ci.yml, .github/workflows/netsim.yml, iroh/tests/cli.rs
😢 this does add ~3 min to the existing 7min of linux runs, but at least it properly checks all crates now.
Closes https://github.com/n0-computer/iroh/issues/1716
You can now click on re run job and in the bottom of the prompt you can check `enable debug logging` to run with `RUST_LOG=DEBUG` & `netsim --debug` for the appropriate tests to get full logging output.
Closes https://github.com/n0-computer/iroh/issues/1717
Linker changes are still up for debate
Closes https://github.com/n0-computer/iroh/issues/1423
We need to maintain the crates list, but shouldn't be too hard. Managed to pull it out into a single var.
=> feat(ci): CI improvements

iroh/src/client.rs, iroh/src/client/quic.rs, iroh/src/commands.rs, iroh/src/main.rs, iroh/src/node.rs
We spawn a tokio task when dropping a client `Doc` handle to notify the node that the document was closed. This does not work in the FFI currently because the FFI does not run in a global tokio context. Instead we now always pass a `runtime::Handle` into the client which can be used to spawn tasks independently of running in a tokio context.
=> feat(iroh): pass a runtime to Doc client to spawn close task on drop

iroh/src/commands.rs, iroh/src/commands/node.rs, iroh/tests/cli.rs
It is now possible to do any of these 
```
> iroh start --rpc-port 1234
> iroh --rpc-port 1234 start
> iroh console --rpc-port 1234
> iroh --rpc-port 1234 console
```
Closes #1639
=> fix(iroh): handle rpc args in any position

.github/workflows/ci.yml
No sccache release binaries for linux aarch64 available, and self building is worse for perf.
=> fix(ci): avoid sccache on linux aarch64 builds

iroh-net/src/config.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/endpoint.rs
=> refactor(iroh-net): remove cli ping

iroh/src/commands.rs
- modifies the `blob download` ux to make it clear, and properly enforce having either a ticket or arguments for a download
- All arguments apply to both ticket and hash but with different constrains. In the case of the ticket options can be used to override/remove ticket parts
- makes sure failures still report the help text
This would previously only show an error
```
> blob download
Download data to the running node's database and provide it
Usage: blob download <COMMAND>
Commands:
ticket  Use a blob ticket to download the data
hash    Supply the content and node-addressing information directly to perform a download
help    Print this message or the help of the given subcommand(s)
Options:
-h, --help  Print help (see more with '--help')
```
```
> blob download ticket …
```
=> fix(console): blob download args

iroh-net/src/magicsock/peer_map/endpoint.rs
These happen whenever any address of a node you've been pinging goes offline, which creates a lot of noise.
=> chore(iroh-net): demote 'pong not received in timeout' message to debug

iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-gossip/src/net/util.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/endpoint.rs, iroh/src/sync_engine/live.rs
incremental followup for #1765 
rename Peer to Node in peer_map related code.
The module renaming should be done at the very end and in another PR to prevent overwriting the file's history
mostly dumb renaming that should be fine. Please push your feedback directly to the PR
=> refactor(*): rename Peer to Node in peer_map related code

iroh/src/sync_engine/live.rs
this was referring to entries by index, which will fail if two items are removed in one iteration.
We are now iterating in reverse order, so removal won't shift the remaining elements.
=> fix(iroh-sync): fix panic in send

iroh-sync/src/actor.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/src/client.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/rpc.rs, iroh/tests/sync.rs
* Renames `get_one` to `get_exact`
* Add flag to `get_exact` whether to include empty entries or not
* Add `get_one` to `iroh::client::Doc` to get a single entry with the same query mechanisms as `get_many`
Based on #1766
=> feat(iroh-sync): Rename get_one to get_exact, add flag to get empty entries, query single entry on client

Cargo.lock, iroh-sync/Cargo.toml, iroh-sync/src/actor.rs, iroh-sync/src/keys.rs, iroh-sync/src/lib.rs, iroh-sync/src/net/codec.rs, iroh-sync/src/store.rs, iroh-sync/src/store/fs.rs, iroh-sync/src/store/memory.rs, iroh-sync/src/sync.rs, iroh/src/client.rs, iroh/src/commands/sync.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine/rpc.rs, iroh/src/ticket/doc.rs
Closes #1767 
Updates sync, the sync db, commands and tickets to enable read only replicas
=> feat(iroh-sync): read only replicas

iroh-sync/src/store/fs/migrations.rs
The migration as commited with #1770 panics when starting iroh with an existing data dir. The reason is that redb panics when deleting table in a transaction  where they were opened as well. See: https://github.com/cberner/redb/issues/715
This fixes this by moving the table deletion to a separate transaction.
The limitation and potential panic in redb was fixed in https://github.com/cberner/redb/pull/716 so once we upgrade to the next (still unreleased) version of redb, this can be removed again.
=> fix(iroh-sync): prevent panic in namespace migration

iroh-bytes/src/store/flat.rs
The content was not always on disk before emitting progress events and returning, resulting in broken progress updates and unfinished writes.
=> fix(iroh-bytes): ensure to flush file to disk

CHANGELOG.md, iroh/release.toml, iroh/src/commands.rs, iroh/src/commands/add.rs, iroh/src/commands/node.rs, iroh/src/commands/rpc.rs, iroh/src/config.rs, iroh/src/node.rs, iroh/src/util/path.rs, iroh/tests/cli.rs
- prevents iroh from being started in the same iroh data dir
- retrieves the rpc port from the rpc.lock file
- removes  the `--rpc-port` argument from all commands other than `start`
This also changes the way in put handling is done on `start`, as I discovered some issues with the current state of things.
The way it works now is
```sh
> iroh start
> iroh start --source STDIN
> iroh start --source ./path/to/file
```
Closes #1281
=> feat(iroh): store rpc port in iroh data dir

iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-net/bench/src/lib.rs, iroh-net/examples/magic.rs, iroh-net/src/derp/client_conn.rs, iroh-net/src/derp/metrics.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-sync/src/net.rs, iroh-sync/src/sync.rs, iroh/examples/client.rs, iroh/examples/collection.rs, iroh/examples/hello-world.rs, iroh/examples/rpc.rs, iroh/src/commands/doctor.rs, iroh/src/commands/node.rs, iroh/src/downloader.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/live.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
some more purging of the term peer id to be consistent
1. There are some structs like PeerIdBytes.
- Do we need them at all, now that PeerId is also 32 bytes?
- Should they also be renamed?
2. There are some places where I kept the term peer id, e.g. the p2p tls stuff. Also change? It is very internal, so maybe leave it?
=> refactor: more renaming of the term peer id to node id

Cargo.lock, iroh/src/client.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/util/fs.rs
closes #1781 
There is now a `canonicalized_path_to_string` method that takes a path (that it expects to be canonicalized already) and turns it into a string.
What was previously `canonicalize_path` is now renamed to `relative_canonicalized_path_to_string`, and calls `canonicalized_path_to_string`, with the `must_be_relative` param set to `true`
=> feat: add `Doc::import_file` and `Doc::export_file`

iroh/src/node.rs
When importing files into docs, the temp tag should only be dropped *after* the hash was inserted into the doc. Otherwise gc could potentially delete the blob if hitting in between the tag drop and the completion of the doc insert.
=> fix: drop temp tag after doc insert

iroh/src/commands.rs, iroh/src/commands/blob.rs, iroh/src/commands/start.rs, iroh/tests/cli.rs
Changes for #1802 
CLI command changes:
* `iroh start` takes `--add` not `--source`
* `iroh blob add` takes required  `SOURCE` arg and not optional `--source` opt
Internal changes:
* reduce code duplication around starting a node
* always start the metrics server (for both `iroh start` and `iroh CMD --start`)
* make sure to remove the rpc lock file if aborting with error
* cleanups
=> refactor: improve code and args for CLI start

.github/workflows/netsim.yml
Just bringing this in line with the PR run config. We used to keep this open due to an issue that took us time to resolve so we unblocked the rest of the pipe. Now the issue crept through again for the same reason.
=> fix: netsim should fail on all failed tests

.github/workflows/netsim.yml, iroh/src/commands/start.rs, iroh/src/node.rs, iroh/tests/cli.rs, iroh/tests/provide.rs, iroh/tests/sync.rs
Removes the add from the start args as discussed internally. Reason for this is that it's currently not used. In reality, the port was not used. If we do add this back, most likely we want to also use the address to allow ipv6 listening nodes. In the spirit of removing code we opt for letting the code reflect how it's actually used in the moment
na
=> refactor(iroh): remove the addr arg from start

iroh-base/src/hash.rs, iroh/tests/cli.rs
This makes ToString for hash just produce the base32 encoded hash
None
=> Remove ipld prefix from to_string

.github/workflows/ci.yml, Cargo.lock, Cargo.toml, deny.toml, src/tls.rs, src/tls/certificate.rs, src/tls/verifier.rs
This updates dependencies of iroh 0.4.1 release, most notably quinn fixes platform support for android without patches.
- Not all dependencies are updated.  Only a few select ones which make things better
for deltachat.
- Note that the base of this PR is `maint-0.4` which is a branch currently pointing
at the 0.4.1 commit.
- This PR also bumps the version number already to 0.4.2, we'd have to publish a new
release with this.
- This ignores a rust advisory, the way iroh uses the code was determined not to be
problematic and adopting the new API is rather invasive and not suitable for a
maintenance branch.  The main branch has updated this code.
- Netsim CI is disabled, provides not much value for a maintenance branch and it
has been updated for newer versions of iroh.  Keeping it …
=> chore(deps): Update dependencies

iroh/src/commands.rs, iroh/src/commands/start.rs, iroh/tests/cli.rs
Removes the rpc-port option from the start args, effectively removing the whole struct
keeping this would be the only work around to #1837. Not having this I think is better and forces us to actually solve this issue
=> refactor(iroh): remove rpc port option

.github/workflows/ci.yml
Due to a bug in redb we are currently not running tets on android.
This is a bit problematic as we break android builds this way.
This makes sure we can at least build, so the linker will also run.
The next step would be to run the tests for android which do not
depend on redb.
Running `cargo check` in a separate step does not provide any benefit,
it is an extra compiler step which does take time and does not result
in catching errors which otherwise aren't caught.  Maybe we should also
remove this step from the non-cross checks, but that belongs better in
a different PR probably.
=> chore(ci): run cargo build for android platforms

iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/net/netmon.rs, iroh-net/src/net/netmon/actor.rs
This allows notifying `iroh-net` when the network has likely changed.
Usually this is only needed on android, as on all other OSes this is automatically detected.
=> feat(net): add `Magicsock::network_change`

Cargo.lock, iroh-net/Cargo.toml, iroh/Cargo.toml
This works well with cargo-nextest.
wasm-bindgen is also bumped as the previous version is yanked.
=> chore(deps): Bump testdir to 0.9

iroh-sync/src/store/fs.rs, iroh-sync/src/store/fs/migrations.rs
The new test fails without the fix. 
Closes #1850
=> fix(sync): handle migration 004 in the empty case

iroh-bytes/src/store/flat.rs, iroh/examples/rpc.rs, iroh/src/commands/start.rs, iroh/src/util/path.rs, iroh/tests/cli.rs, iroh/tests/gc.rs
Have the constructor for the bao db take a single directory. Internally it will still have 3 directories, although this is not strictly speaking necessary because the files can be distinguished by their extension.
Implements https://github.com/n0-computer/iroh/issues/1662
~This does not yet include a migration. Do we need one, or do we declare that the number of changes is just too big for this release? It's not super hard to write, but we would then have to drag it around for a while.~
Added a migration
=> feat(bytes): switch to a single directory for the flat store

Cargo.lock, iroh-metrics/Cargo.toml, iroh-metrics/src/metrics.rs, iroh-metrics/src/service.rs, iroh-net/Cargo.toml, iroh-net/src/bin/derper.rs, iroh-net/src/derp/http.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/derp/http/server.rs
This upgrades our direct use of hyper to version 1.0 of the crate.
This is adds a little duplication to our deps for now since reqwest is still
using hyper 1.0.
=> refactor: Upgrade to hyper 1.0

Cargo.lock, iroh-metrics/Cargo.toml, iroh-metrics/src/core.rs, iroh-metrics/src/lib.rs, iroh-net/src/derp/server.rs
Simple extension to the metrics collector to have a dedicated usage reporting flow.
=> feat: usage metrics reporting

iroh-bytes/src/store/traits.rs, iroh/src/node.rs
The blob GC was logging at info level, filling the info-level log with
tons of repeated messages that are pretty useless.  They probably all
belong on debug, or maybe even below.
Possibly some of these might be info if they carry something useful,
like showing a number that's not 0 or so.  But as a first
approximation reducing everything to debug seems about right.
=> refactor(logging): Reduce loglevel of blob GC

.github/workflows/ci.yml
Because we use self-hosted runners we do not want the sccache action
to query the github action cache service for each compilation request.
Instead it should be using the local cache.
This means the first time something is compiled on a runner it will
not yet be in the cache, even if another runner already did compile
this.  However because the cache size is set reasonably large over
time all the common dependencies will end up cached on each
self-hosted runner.
Maybe it will be possible to run a self-hosted caching service
sometime, but for now relying on a large local cache is expected to be
reasonable.
- This will not start showing results right away, as caches on the
self-hosted runners need to be filled.  They are full by now though
and show improvements across the board.
- Please …
=> chore(ci): Configure sccache to use local caches

.github/workflows/ci.yml
Building multiple combinations of features in the same jobs means they will stomp over the target directory.  This is an approach at avoiding this.
Furthermore by splitting this up into more jobs we can get more parallelism
by adding more workers.  However even without this we already get some
improvements due to no longer stomping over the target directory and thanks
to sccache helping the various runs.
There's an alternative version of this where we change the sequence but don't increase
the runners.
Without sccache working this would be a step backwards, you can observe this
with windows currently.
See https://github.com/n0-computer/iroh/issues/1864 for bigger picture.
=> chore(ci): split jobs so they do not stomp over target directory

Cargo.lock, iroh-gossip/examples/chat.rs, iroh-net/Cargo.toml, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh/src/client.rs, iroh/src/commands/doctor.rs, iroh/src/node.rs
To avoid the issues seen when setting up an `iroh-net` node, this allows to dynamically subscribe to endpoint changes. It also removes the other callbacks on the magicsock, which where unused.
=> refactor: streamline local endpoint discovery

iroh-net/docs/derp_regions.md
Probably due to mismanagement of nodes, but actually really unclear how, we had a derper with the wrong IP address for the eu node.
=> chore(docs): update derp IP for EU region

iroh/examples/client.rs, iroh/src/client.rs, iroh/src/commands/doc.rs, iroh/tests/sync.rs
This adds a `iroh::client::Entry` struct which wraps the `iroh_sync::Entry` and adds methods to read the content of the entry. Reading the entry needs a reference to either a `Doc<C>` or the `Iroh<C>` client (both work equally).
@flub mentioned that this is missing from the expected API. I started this at the hack session but didn't get very far but now it's in a good shape IMO.
=> refactor: client `Entry` with methods to read content

iroh-net/src/netcheck.rs
This test was taking quite a while on CI sometimes and had both the wrong URL and way too many iterations.
=> test(net): use actual derp hostname and reduce iteration count

iroh-net/LICENSE-BSD3
=> chore: add BSD3 license note for code derived from tailscale

.github/workflows/ci.yml, iroh-net/src/derp/client_conn.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh-net/src/magicsock/peer_map/endpoint.rs
There was a deadlock due to the usage of the inner actor message loop in handling network changes, which would trigger a deadlock. 
Additionally the following two fixes are included
- clearing endpoint state when connectivity is changed
- drop incoming messages when the magicsock is overloaded
=> fix: do not block on network change

iroh-net/src/magicsock.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/endpoint.rs
`ControlMsg` is used in a field of the public struct `DirectAddrInfo`, but was previously a private struct.
=> refactor(iroh-net): make `ControlMsg` public

Cargo.lock, iroh-bytes/src/format.rs, iroh-bytes/src/format/collection.rs, iroh-bytes/src/lib.rs, iroh/examples/collection.rs, iroh/src/lib.rs, iroh/src/node.rs, iroh/tests/cli.rs, iroh/tests/provide.rs
This changes the collection type a bit to make it more idiomatic rust. E.g. it now implements traits to use it like a... collection, like FromIterator. It also moves collection (back) to iroh-bytes so it can be used from tools like sendme without having to depend on all of iroh.
This collection format is intended to be a minimum viable metadata format that we can support for a long time - just a sequence of strings with a string for each blob in the HashSeq. It is useful for tools like sendme and for gateways, so I think this is valuable enough to have as a separate format to e.g. document snapshots.
Should this be sequences of blobs? Weirdly, in this case I am OK with a sequence of strings. If somebody wants names to be arbitrary blobs they can always define another metadata format.
=> Move collection to iroh-bytes and add metadata header

iroh/src/commands/blob.rs
Check we the result can be written to, before downloading.
=> fix(iroh): check output for blob get

iroh-base/src/hash.rs, iroh-net/src/key.rs
Also get rid of some unneeded low level serde code for hash. `PublicKey` was serialized as 33 bytes, with a length prefix 0x20.
=> Fix serde for PublicKey

iroh-base/src/base32.rs, iroh-base/src/hash.rs, iroh-net/src/key.rs
Especially for tests I find hex keys nicer. So this does to PublicKey and PrivateKey what we are already doing with Hash: allow parsing as either base32 or hex. There is no potential for mixing these up, since the length will be different except for the case of 1 or 2 bytes, and we got 32 bytes here.
=> Key hex parse

iroh-bytes/src/protocol.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/rebinding_conn.rs, iroh-net/src/ticket/blob.rs, iroh-net/src/ticket/node.rs, iroh/src/dial.rs, iroh/src/downloader.rs, iroh/src/node.rs, iroh/src/ticket/doc.rs
- use a &'static str instead of a sized array for the iroh-bytes ALPN
- make use of the new PublicKey::from_str to make tests a bit nicer
Extracted from https://github.com/n0-computer/iroh/pull/1894 since these two should be uncontroversial.
=> Small fixes

iroh-bytes/src/provider.rs, iroh-bytes/src/util.rs, iroh/src/downloader/get.rs, iroh/src/get.rs
This event needs to be considered when computing how much data needs to be downloaded in case of resume.
Also change hashseq download to assume that at least the hashseq itself is complete. We currently do not support resume if the download of the hashseq itself was interrupted.
1. I think this provides the required info to get good progress bars even in case of resume. But I don't know for sure until I have hacked it into sendme.
2. Sendme does 2 roundtrips and has accurate progress bars. Iroh does 1 request and has a 2 level progress bar because the total size is not known in advance. Should we change iroh to do what sendme does?
=> Add an additional event FoundLocal.

iroh/src/commands.rs, iroh/src/commands/start.rs
This should fix `Ctrl-C` behavior in the console, especially for long running commands like `doc watch` or `blob import`.
=> fix: fix abort on ctrl-c in console

iroh-net/src/magicsock/peer_map/endpoint.rs
This pruning would delete all direct addrs that were just added, as they had no pings or so attached
=> fix(iroh-net): do not prune addrs that are just added

Cargo.lock, iroh-base/Cargo.toml, iroh-bytes/Cargo.toml, iroh-gossip/Cargo.toml, iroh-metrics/Cargo.toml, iroh-net/Cargo.toml, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh/Cargo.toml
This test is flaky because somehow the executor is entirely blocked
for a solid 5 seconds after which the entire netcheck report is timing
out.  Thus the part of the netcheck report that is being tested never
executes.
What blocks the executor however is a mystery to me.  This fix assumes
that it is generating the backtrace in the log, because there simply
isn't anything else that it can be.  Thus the relevant change is no
longer producing the backtrace.  The error message is already pretty
obvious.
To  go further, this disables the anyhow backtrace feature entirely.
This will probably make our lifes a bit harder in some situations but
there are many places where they end up in the log otherwise and each
time this happens it blocks an executor thread for a long time.
This also tweaks the …
=> fix(iroh-net): Try fix flaky udp_blocked test

.github/workflows/ci.yml, .github/workflows/netsim.yml
Netsim runs are failing on PRs due to the old prometheus endpoint being unavailable (I moved some of the old infra around). It's a never used feature so I'm happy to just drop it.
=> chore(netsim): disable netsim prometheus reports

iroh-gossip/src/net.rs, iroh-net/src/test_utils.rs, iroh/src/util/progress.rs
The nightly compiler (rightly I think) identifies the u64 as unread
and suggests changing it with unit instead.
However the nightly compiler wrongly identifies some oneshot senders
as dead code.  Just get main working on CI again for now.
This is the easy way out, not very nice.  We also have a
ProgressReader2 in iroh-bytes that's very similar.  Maybe we should
extract these and put them somewhere common.
=> fix: allow some dead code for the nightly compiler

.github/workflows/ci.yml, .github/workflows/flaky.yaml, .github/workflows/release.yml, .github/workflows/test_derper.yml, .github/workflows/tests.yaml
Jobs are getting canceled because multiple separate flows have the same concurrency group.
=> fix(ci): stop reusing concurrency labels across jobs

Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/magicsock.rs
closes #1931 
Fixes the broken build when building from the vendored tarball produced by `cargo vendor`. The problem was with a config in `watchable v1.1.1` and was fixed in `watchable v1.1.2` (https://github.com/khonsulabs/watchable/releases/tag/v1.1.2).
=> fix: build successfully from `cargo vendor` tarball

.github/workflows/ci.yml
Seems like the lack of job name makes it invisible on the branch protections, hence can't make the step required for the nested runs. Raw `Tests` job is available.  This is just theory for now.
=> chore(ci): add name to tests step

iroh/src/client.rs
This is returned by `DocExportFileProgress::finish` and it's fairly obvious that these fields were intended to be public but weren't. Useful for a variety of things.
None
=> Make the fields of `DocImportFileOutcome` public

.github/workflows/tests.yaml, iroh/tests/cli.rs
We had a bug in the github actions job that resulted in not running
any tests.  Oops.
Running 248 tests again!
Newly marked flaky test already covered by #1935
=> chore(ci): run non-flaky tests again

.github/workflows/beta.yaml, .github/workflows/ci.yml, .github/workflows/tests.yaml
Normal CI jobs for PRs now only run using the stable rust compiler,
this gives fewer surprises to users.
Instead the beta compiler is run in a new workflow which runs once a
week.  When the beta workflow fails we get a post in a discord channel.
The required checks for branch protection have changed again.  We no
longer need the nightly checks in those.
=> chore(ci): Do not test nightly rust on every PR

iroh/src/client.rs
=> fix(iroh): add timestamp method to Entry RPC struct

Cargo.lock
this makes cargo-deny happy again
=> chore: update dependencies in Cargo.lock

iroh-net/src/magicsock/peer_map/best_addr.rs
The best addr is renewed every few seconds, always logging this on
info level floods the info log.  Now we log it on debug if the address
has not changed.  Logging that is still useful since it shows how long
the validity is and the latency.
=> refactor(iroh-net): Log best addr on debug if not changed

iroh/src/client.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs
- add `blobs.read_at`: Allows to efficiently read parts of a blob via RPC
- add `blobs.get_collection`: read a collection
=> feat(iroh): add more rpc methods

.github/workflows/ci.yml, .github/workflows/tests.yaml, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs
This fixes the tests to run from the PR branch and not from main.
Additionally it splits the tests running into three steps:
- Building the tests.
- Listing ignored tests.
- Running tests.
This makes the output easier to consume and does not add any slowdown.
Listing ignored tests is useful since nextest only says how many tests
are ignored rather than listing them all.
Finally it fixes the features testing by moving the CRATES_LIST environment
variable to the right workflow.
Flaky tests tracked in #1966
=> chore(ci): Run tests from the PR branch, not main

iroh-net/src/magic_endpoint.rs, iroh/src/node.rs
Adds a better debug output for AddrInfo.
Before:
AddrInfo { derp_url: Some(Url { scheme: \"https\", cannot_be_a_base: false, username: \"\", password: None, host: Some(Domain(\"derp.example.com\")), port: None, path: \"/\", query: None, fragment: None }), direct_addresses: {1.2.3.4:1234} }
After:
AddrInfo { derp_url: Some(https://derp.example.com/), direct_addresses: {1.2.3.4:1234} }
- Is there a way to make derive_more do this?
- should we make a newtype for DerpUrl that does this and also arc?
=> Add better debug instance for AddrInfo

iroh-bytes/src/get/db.rs, iroh/src/node.rs
Avoid establishing a connection in `blobs.download` if content is already locally available.
Closes #1947
=> fix(iroh): do not establish connection if content already exists locally

.github/workflows/release.yml
Enables windows builds again and uploads artifacts to GH runs, which we can then manually attach to releases.
This is not really feasible to test without merging... (has no impact on general flows, needs to be manually or release triggered anyways)
Covers the first steps to https://github.com/n0-computer/iroh/issues/1986
=> feat: release artifacts & windows builds

.github/workflows/ci.yml, .github/workflows/netsim.yml, .github/workflows/release.yml, .github/workflows/test_derper.yml, .github/workflows/tests.yaml
These actions use a deprecated nodejs version.  The newer versions do
not.
Also moves to released versions of actions/checkout as that's more
stable and the recommended way to use them.
=> chore(ci): Update outdated actions

iroh-gossip/examples/chat.rs, iroh-gossip/src/net.rs, iroh-net/examples/connect-unreliable.rs, iroh-net/examples/connect.rs, iroh-net/src/bin/derper.rs, iroh-net/src/config.rs, iroh-net/src/defaults.rs, iroh-net/src/derp.rs, iroh-net/src/derp/http/client.rs, iroh-net/src/derp/http/mesh_clients.rs, iroh-net/src/derp/map.rs, iroh-net/src/disco.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/derp_actor.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/endpoint.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh-net/src/netcheck/reportgen/probes.rs, iroh-net/src/stun.rs, iroh-net/src/test_utils.rs, iroh-net/src/ticket/node.rs, iroh/src/commands/blob.rs, iroh/src/commands/doctor.rs, iroh/src/node.rs
This addresses two issues for now: some very minimal normalisation and
nicer Debug printing.
The type is purely a wrapper and does extremely minimal extra things
to the underlying Url.  There is no validation happening and no added
contraints to the URLs.  It is still possible to construct a DerpUrl
that will fail, e.g. by using the mailto: scheme.  The users of the
DerpUrl are expected to fail in such cases.
I was initially trying to keep this crate-local to iroh-net.  However
iroh-net has a surprisingly large public API and that would be painful
and largely defeat the point to leave all those public APIs as Url.
Thus it is a public API.
As a consequence there are a few uses of this outside of the iroh-net
crate as well.  I think they are reasonable.
=> refactor(iroh-net): Introduce a minimal DerpUrl

iroh-bytes/src/get/db.rs, iroh-bytes/src/util/progress.rs, iroh/src/downloader/get.rs, iroh/src/util/progress.rs
The `ProgressSliceWriter` is currently duplicated code in `iroh_bytes` and `iroh`. Also there's two versions of it, one that takes a fallible and one that takes an infallible one.
This PR removes the code duplication and makes the naming understandable.
=> refactor: cleanup ProgressSliceWriter

Cargo.lock, iroh-base/Cargo.toml, iroh-base/src/hash.rs
Add optional redb support for foundational iroh-base types Hash, HashAndFormat, BlobFormat
Should this be on by default? It is off now. I think this is mostly for us.
=> Add optional redb support for foundational iroh-base types

iroh-base/src/rpc.rs, iroh-bytes/src/export.rs, iroh-bytes/src/get.rs, iroh-bytes/src/get/db.rs, iroh-bytes/src/lib.rs, iroh-bytes/src/util/progress.rs, iroh/src/client.rs, iroh/src/commands/blob.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/src/util/io.rs
This PR has a number of cleanups regarding download and export functionality:
* We currently have an enum `DownloadProgress` which contains events for both downloading a blob and for exporting a blob from the node's blob store to files on the local filesystem. This PR moves the export progress events into an `ExportProgress` enum.
* The code to export blobs to the local file system is moved from `iroh` to `iroh-bytes`
* Code duplication around export progress is reduced and a couple of RPC and client structs are cleaned up accordingly
=> refactor: download and export structure and progress events

iroh-gossip/src/net.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs, iroh/tests/cli.rs
This was essentially re-implementing the Rust Debug trait.  Now that
DerpUrl has a nice Debug log there really is no need to manually
implement this, instead we rely on Debug.
This is splitting off some peripheral stuff from
https://github.com/n0-computer/iroh/pull/1984
New flaky test marked: https://github.com/n0-computer/iroh/issues/2010 and #1935
=> refactor(iroh-net): Remove manual struct logging

iroh-bytes/src/get.rs, iroh-bytes/src/get/db.rs, iroh-bytes/src/store/flat.rs, iroh-bytes/src/store/mem.rs, iroh-bytes/src/store/readonly_mem.rs, iroh-bytes/src/store/traits.rs, iroh/tests/gc.rs
To take into account the fact that the size we get initially in the iroh-bytes protocol is not verified, I want to lazily move from mem storage to file storage only once some limit is *actually* exceeded.
This requires combining outboard and data file and treating them a bit more as one file to which you write batches.
For now, just add the trait and keep the impl the same.
Should the BaoBatchWriter move to bao-tree io? I think in the long term yes, but for now let's keep it here to make things simple?
Note: this kind of code *really* wants 1.75 impl return types in traits.... I asked on the public discord if somebody has some major objections, otherwise I would just go with it.
=> refactor: Batch write trait

iroh/src/commands.rs, iroh/src/main.rs
This allows you to write log output to a specific filedescriptor in
the shell: iroh --log-fd 3 ... 3>some/file.log
Thus not interfering with normal stdout and stderr output and getting
the full functionality of this.
This is splitting off some peripheral stuff from
https://github.com/n0-computer/iroh/pull/1984
=> feat(iroh): Add --log-fd flag on unix

iroh-net/src/disco.rs, iroh-net/src/magicsock.rs, iroh-net/src/magicsock/peer_map.rs, iroh-net/src/magicsock/peer_map/endpoint.rs
This reads a bit more natural.  It does not affect the on-the-wire
format.
Split off from #1984
=> refactor(iroh-net): Rename CallMeMaybe field

Cargo.lock, iroh-base/Cargo.toml, iroh-bytes/Cargo.toml, iroh-bytes/src/store/flat.rs, iroh-bytes/src/store/mem.rs, iroh-bytes/src/store/readonly_mem.rs, iroh-bytes/src/store/traits.rs, iroh-bytes/src/util/progress.rs, iroh/Cargo.toml
bao-tree and iroh-io have been republished with new versions that require 1.75 and use impl trait in trait. This updates these two dependencies and also refactors the store traits to take advantage of 1.75 features, removing a ton of boxes along the way.
Instead of `BoxFuture<'a, T>` we use `impl Future<Output = T> + Send`
Instead of `LocalBoxFuture<'a, T>` we use `impl Future<Output = T>`
Explicit lifetimes are in some cases no longer necessary because the future returned by impl Future<...> will implicitly capture the lifetimes of all parameters.
See https://rust-lang.github.io/rfcs/3498-lifetime-capture-rules-2024.html
=> refactor(iroh-bytes): Take advantage of impl T in trait, update bao-tree and iroh-io

.github/workflows/commit.yml
Adds a CI check for following the conventional commits in the PR title and body, as those will be used as the commit when merging through the merge queue.
=> ci: add conventional-commit-checker

iroh-net/src/derp/http/client.rs, iroh-net/src/dns.rs, iroh-net/src/netcheck/reportgen.rs
This now races the resolution, with a fixed timeout on each, returning as many results as found during that time.
Ref https://github.com/n0-computer/iroh/issues/2006
=> fix(iroh-net): race ipv4 and ipv6 dns resolution

iroh-net/src/netcheck/reportgen.rs
Once netcheck has managed to establish an external IP address there is
no need to further wait on the portmapper.  The results are already
useful.  If later the portmapper manages to get something done the
magicsock will react to that and make use of it.
Fixes #2021
=> fix(iroh-net): Ensure netcheck finishes once it has results

iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs
This came from the tailscale code but we never seem to have used it
and our routers haven't exploded yet.
Admittedly it would be nice not to keep hitting so many external
things on the network.  But our entire testsuite would need a big
review for that.
=> refactor(iroh-net): Delete some unused testing infrastructure

iroh/src/config.rs
Fixes #2024
This was caused by a read attempt over a lock nested inside a write lock. Thw write lock being `let mut inner = self.0.write()` and the read lock in `self.iroh_data_dir()`
I checked the rest of the code in #2013 and I think `author new --switch` is the only command affected
=> fix(console): prevent deadlock in `author new --switch`

iroh-net/src/net/interfaces.rs, iroh-net/src/netcheck.rs, iroh-net/src/netcheck/reportgen.rs
We were incorrectly identifying globally routable IPv6 addresses as
not routable.  This make netcheck skip IPv6 addresses.
Closes #2022 
The fix in the netcheck, test is curious, it fails on this PR fairly
consistently yet it is really a flaky test introduced in combination with #2027.
Now that we have IPv6 resolving properly we might get an IPv6 result.  Since
this test only has a single DerpUrl it only needs one result to complete.
This could be an IPv4 OR an IPv6 result, we don't know which one will be
faster.  And if the other is slow enough then it won't be received.  I think
this behaviour is fine, we simply can't guarantee that both must have a result
and the point of netcheck is to return something working quickly.
=> fix(iroh-net): Fix in detecting globally routable IPv6 addresses

.github/workflows/ci.yml, Cargo.lock, iroh-net/Cargo.toml, iroh-net/src/dns.rs, iroh-net/src/stun.rs
Same code, different name, for details see https://github.com/hickory-dns/hickory-dns/issues/2051.
=> feat(deps): update from trust-dns-resolver to hickory-resolver

iroh-bytes/src/export.rs, iroh-bytes/src/get/db.rs, iroh-bytes/src/provider.rs, iroh-bytes/src/store/flat.rs, iroh-bytes/src/store/mem.rs, iroh-bytes/src/store/readonly_mem.rs, iroh-bytes/src/store/traits.rs, iroh-net/src/netcheck/reportgen.rs, iroh/src/client.rs, iroh/src/node.rs, iroh/src/rpc_protocol.rs, iroh/tests/gc.rs, iroh/tests/provide.rs
Simplify and rename some store traits, taking advantage of return position impl trait in trait.
The main change is that the map entries are no longer for one specific map impl, but just generic map entries, so the type parameter goes away. Other than that, the PartialXXX traits are renamed to XXXMut, which is more accurate. An immutable entry can be partial. Since MapEntry does not guarantee that it is complete (anymore), the main difference between MapEntry and MapEntryMut is not that the latter allows writing.
Edit: one additional change is to introduce BaoBlobSize, which is a size together with an information about whether the size is validated or not. Why not just (u64, bool)? Because later we might add more info to the unverified enum case.
Note: this is not the end of it. Just …
=> refactor(iroh-bytes): Simplify store traits

.github/workflows/ci.yml, .github/workflows/tests.yaml, iroh-net/src/key.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh-net/src/net/interfaces.rs, iroh-net/src/netcheck/reportgen.rs, iroh-net/src/util.rs, iroh-test/src/logging.rs
Fix flaky tests in iroh-net (hopefully).  The main issue was that the
testing code meshing together the sockets had a race-condition and
would sometimes fail.
Other improvements:
- Logging improvements of various parts.  These tests should now
provide better info on failure.
- Add alternative formatting of NodeId to use the short format.
- Use NodeId in the public API, rather than PublicKey.
- Move multi-threaded logging setup to the testing utils crate now
that it can work properly.  More code will have to switch.
The local_endpoints_change API is really difficult to use correctly.
Even the way this testing code uses it now is wrong.  Instead of the
two current APIs there should be a single API which returns a stream.
I'll do this as a separate followup PR though.
=> fix(iroh-net): Fix some flaky magicsock tests

iroh-net/examples/connect-unreliable.rs, iroh-net/examples/connect.rs, iroh-net/examples/listen-unreliable.rs, iroh-net/examples/listen.rs, iroh-net/src/config.rs, iroh-net/src/dns.rs, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh/src/commands/doctor.rs, iroh/src/node.rs
The API to retrieve local endpoints was split in two between the
current endpoints and updates to it.  This was very hard to use right
without any race conditions.
This replaces it with a single API which returns a stream.  This is a
little bit wordier to use if you just need the current local item, but
much harder to misuse.
It would be possible to add a convenient `.current_local_endpoints()`
API if we wanted.  Not sure this is really worth it.
=> refactor(iroh-net): Improve API to retrieve local endpoints

.github/workflows/flaky.yaml
We always wanted some sort of notification to not completely forget
about these.  Since we now have a discord channel for github beta
tests re-use that here as well.
=> chore(ci): Notify our discord channel for flaky failures

iroh-bytes/src/export.rs, iroh-bytes/src/format/collection.rs, iroh-bytes/src/get/db.rs, iroh-bytes/src/provider.rs, iroh-bytes/src/store/flat.rs, iroh-bytes/src/store/mem.rs, iroh-bytes/src/store/readonly_mem.rs, iroh-bytes/src/store/traits.rs, iroh/src/node.rs, iroh/src/sync_engine.rs, iroh/src/sync_engine/live.rs, iroh/tests/cli.rs, iroh/tests/gc.rs, iroh/tests/provide.rs
Asyncify bao store traits
Asyncify almost the complete surface area of the bao store traits, to make an actor based implementation that lives on its own std::thread::Thread at least theoretically possible.
Note: There is a sync method `fn entry_status_sync` so we don't have to rewrite the document sync algorithm. It should be replaced asap since it will be not very efficient.
Note2: there is 1 unrelated change: get_or_create_partial is renamed to just get_or_create, since you have no control over whether the created entry is partial. If the entry is already complete, what do you do? You return a complete entry.
=> refactor(iroh-bytes): Async bao store

.github/workflows/flaky.yaml
This is better than error, since flaky tests really are expected to be
flaky.  And we don't want to miss other errors in that channel which
are more important.
Maybe warn is even a bit high, but all that matters is that we get
different colours in our channel.  If later we send more notifications
to that channel we can tweak the levels appropriately.
=> chore(ci): Warn in our discord channel on failure

Cargo.lock, iroh/Cargo.toml
Fixes #1499
Current behavior:
run `iroh start` in terminal 1
run `iroh console` in terminal 2
kill and restart the node in terminal 1
run `doc list` (or any other command) in the console and it will fail
Post-update behaviour:
same setup but `doc list` will now function
=> deps(iroh): update quic-rpc

Cargo.lock
This fixes a security advisory in mio.
Do we need more than one line here for the CI check?
=> fix: update deps to avoid cargo-deny warning

Cargo.lock, iroh-net/src/magic_endpoint.rs, iroh-net/src/magicsock.rs, iroh/src/commands/doctor.rs, iroh/src/node.rs
While working on #2056 I spotted that we use the actor inbox with return channels for information that is readily available already on the shared inner magicsock. This removes the unneeded complexity and thus simplifies `get_mapping_addr`, `endpoint_info` and `endpoint_infos` to return the information non-async and infallible. Yay!
=> refactor(iroh-net): remove unneeded async interactions with the magicsock actor

iroh-bytes/Cargo.toml, iroh-bytes/src/store/redb.rs, iroh-bytes/src/store/redb/import_flat_store.rs, iroh-bytes/src/store/redb/tables.rs, iroh-bytes/src/store/redb/validate.rs
Create helper structs for tables
Also separate transaction and table things more from other io. Generic io failures should not cause the actor to stop.
=> refactor(iroh-bytes): Create helper structs for tables

iroh-net/src/netcheck/reportgen.rs
This changes the test slightly to send multiple pings, this should
make it more reliable.
I didn't create a flaky issue for this as I thought I could address it
right away... which I just about managed.
=> tests(iroh-net): Re-enable icmp probe test

iroh-net/src/netcheck/reportgen.rs
test(iroh-net): disable test_icmp_probe_eu_derper as flaky on windows
See for example https://github.com/n0-computer/iroh/actions/runs/8245723076/job/22550253677?pr=2051
Related issue: https://github.com/n0-computer/iroh/issues/2069
=> test(iroh-net): disable test_icmp_probe_eu_derper as flaky on windows

iroh-net/src/magic_endpoint.rs
tests(iroh-net): ignore save_load_peers test as flaky on windows
Issue is https://github.com/n0-computer/iroh/issues/2071
=> tests(iroh-net): ignore save_load_peers test as flaky on windows

iroh-net/src/dns.rs, iroh-net/src/netcheck/reportgen.rs
This actively refuses to use the `fec0:0:0:ffff::1`, `fec0:0:0:ffff::2` and `fec0:0:0:ffff::3` DNS servers if the system has them configured.
Windows by default adds 3 IPv6 site-local anycast addresses to the DNS servers: `fec0:0:0:ffff::1`, `fec0:0:0:ffff::2` and `fec0:0:0:ffff::3`.  Supposedly Microsoft DNS servers by default listen on those.  These are present as soon as there's an IPv6 interface configured it seems, even for a loopback interface which is extremely common if not the default.
Our hickory-resolver loads the system configuration, which includes these 3 IPv6 DNS servers.  When it needs to make a DNS query it selects a random nameserver and tries this.  If that fails it will try another one.  For the next query there is bias, it will remember which servers to avoid or use. …
=> fix(iroh-net): Work around broken windows DNS configuration

iroh-net/src/netcheck/reportgen.rs, iroh-net/src/netcheck/reportgen/hairpin.rs
We've seen 1s not being long enough.  The probes time out after 3s, so
let's match that timeout and see how that goes.
=> refactor(iroh-net): bump netcheck DNS timeout to 3s

iroh-bytes/src/store.rs, iroh-bytes/src/store/bao_file.rs, iroh-bytes/src/store/file.rs, iroh-bytes/src/store/file/tests.rs
refactor(iroh-bytes): Weak entry map
Get rid of some of the drop complexity by storing a weak handle map. The handles themselves have a strong reference, so they are still easy to use.
=> refactor(iroh-bytes): Weak entry map

iroh-net/src/derp/client.rs, iroh-net/src/derp/codec.rs, iroh-net/src/derp/server.rs, iroh-net/src/derp/types.rs
In order to preserve backwards compatibility, we should keep the `ClientInfo` unchanged. The `mesh_key` field is ignored by the server.
=> fix(derp): restore `ClientInfo` `mesh_key` field

Cargo.lock, iroh-base/Cargo.toml, iroh-bytes/Cargo.toml, iroh-sync/Cargo.toml
https://github.com/cberner/redb/releases/tag/v1.5.1
to get a bugfix related to spurious repair of databases. See https://github.com/cberner/redb/releases/tag/v1.5.1
Found by @ppodolsky while trying out the batch branch.
=> chore(iroh-bytes): Increase redb version

iroh-bytes/src/get/db.rs, iroh-bytes/src/store/bao_file.rs, iroh-bytes/src/store/file.rs, iroh-bytes/src/store/file/tests.rs, iroh-bytes/src/store/mem.rs, iroh-bytes/src/store/readonly_mem.rs, iroh-bytes/src/store/traits.rs, iroh/src/node/rpc.rs, iroh/tests/gc.rs, iroh/tests/provide.rs
refactor(iroh-bytes): Remove the size argument from get_or_create
We have *a* size, but we don't know if it is the correct size. At the point where we call get_or_create it could be anything. So we must not use this size for *anything* whatsoever, so we might as well omit it.
The purpose of the size is solely to make sense of the following data, nothing else.
=> refactor(iroh-bytes): Remove the size argument from get_or_create
