n0-computer/iroh

Cargo.lock
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-bytes/src/store/bao_file.rs
iroh-cli/Cargo.toml
iroh/Cargo.toml

Use the latest version of bao-tree that has some bugfixes and a new validate fn.
Due to the bugfix this means that it is no longer compatible with the previous version of iroh-bytes in some rare circumstances involving resume.
We would therefore have to increase the iroh-bytes APLN before the next release.

chore(iroh-bytes): use latest bao tree

---

iroh-bytes/src/get/db.rs
iroh-bytes/src/store.rs
iroh-bytes/src/store/bao_file.rs
iroh-bytes/src/store/file.rs
iroh-bytes/src/store/file/import_flat_store.rs
iroh-bytes/src/store/file/test_support.rs
iroh-bytes/src/store/file/tests.rs
iroh-bytes/src/store/mem.rs
iroh-bytes/src/store/mutable_mem_storage.rs
iroh-bytes/src/store/readonly_mem.rs
iroh-bytes/src/store/traits.rs
iroh-bytes/src/util.rs
iroh/src/node/rpc.rs
iroh/tests/provide.rs

refactor(iroh-bytes): further reduce surface area
Had to do some weird stuff to avoid having a million feature flag annotations, but what can you do.
The entire bao_file module is now split into 2 parts and non pub.

refactor(iroh-bytes): further reduce surface area

---

Cargo.lock
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-bytes/src/store/bao_file.rs
iroh-bytes/src/store/file.rs
iroh-bytes/src/store/mem.rs
iroh-bytes/src/store/readonly_mem.rs
iroh-bytes/src/store/traits.rs
iroh-cli/Cargo.toml
iroh/Cargo.toml
iroh/src/node.rs
iroh/src/node/builder.rs

fix(iroh): Properly shut down the store on control-c
without this, the (flaky) cli_provide_persistence test fails, because
control-c interrupts the store before the write transaction is committed.
Should we change shutdown in node to be async, and remove the impl Future for Node?

fix(iroh): Properly shut down the store on control-c

---

iroh-bytes/src/export.rs
iroh-bytes/src/get/db.rs
iroh-bytes/src/store/traits.rs
iroh-cli/src/commands/blob.rs
iroh/examples/collection-fetch.rs
iroh/examples/hello-world-fetch.rs
iroh/src/client/blobs.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs

This changes two things about how we expose Iroh in the RPC API:
* Add `iroh.blobs.export()` / `BlobExportRequest` to export a blob from the internal blob store to the local filesystem. We prominently missed this in our API.
* Add `blob export` to the CLI. The CLI also keeps the "export after download" functionality, it just issues a second RPC request for the export now.
* Remove the `out: DownloadLocation` field from `BlobDownloadRequest` and thus the functionality to automatically export a blob after the download finishes. Instead, users may call `iroh.blobs.export` themselves now after the download finishes. This does not make a difference performance-wise (apart from a single RPC roundtrip), because the export operation was already running sequentially after the download before this …

refactor: make export a seperate operation from download

---

Cargo.lock
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-cli/Cargo.toml
iroh/Cargo.toml

chore(iroh-bytes): update bao-tree dependency
to fix a bug with validation when the last chunk group is a leaf for the tree. The bugfix was supposed to be in 0.11.0, but I screwed up publishing.
Some indication that this fixes the problem:
main:
```
❯ cargo run -p iroh-cli doctor blob-validate $APP_HOME/iroh/blobs | grep expected
Finished dev [unoptimized + debuginfo] target(s) in 0.18s
Running `target/debug/iroh doctor blob-validate '/Users/rklaehn/Library/Application Support//iroh/blobs'`
EntryDone { id: 32, error: Some("expected chunk ranges RangeSet{0..1387}, got chunk ranges RangeSet{0..1376}") }
EntryDone { id: 9, error: Some("expected chunk ranges RangeSet{0..18856}, got chunk ranges RangeSet{0..18848}") }
```
this branch:
```
❯ cargo run -p iroh-cli doctor blob-validate …
```

chore(iroh-bytes): update bao-tree dependency

---

.github/workflows/tests.yaml

We really ought to use something like cargo-metadata to pull this
information from the cargo.toml file.  Maybe one day one of us will be
motivated enough to do this.

fix(ci): Also test iroh-cli for cargo features

---

iroh-bytes/src/store/traits.rs
iroh-net/src/relay/client_conn.rs
iroh-sync/src/ranger.rs
iroh-sync/src/sync.rs
iroh/src/util/io.rs

The beta compiler identifies these as dead code.

fix: Remove dead code detected by the rust beta compiler

---

iroh-net/src/magicsock.rs

The comment about `grease_quic_bit` was the wrong way round, this fixes it.

fix: comment about grease_quic_bit

---

iroh-bytes/src/protocol.rs

chore(iroh-bytes): Increase iroh-bytes ALPN
this is because there was a bao-tree bug with range requests that resulted in less than optimal encoding for small ranges.

chore(iroh-bytes): Increase iroh-bytes ALPN

---

iroh-cli/src/commands.rs
iroh-cli/src/config.rs

Now metrics default to serving on `localhost:9090` but you can override with a custom port or turn off if you like with `--metrics-port`. If you want to actually expose the metrics endpoint to the world, it's assumed you will set up a config file with a custom `metrics_addr`.
I guess the config override could have been done in a bit more elegant way but didn't want to commit refactoring the `NodeConfig` nor did I want fancy extra task specific fn's.
The configuration is limited to the iroh node start path, the rest are ignored as they are expected to be short lived processes.

refactor(metrics): metrics on by default

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/portmapper.rs
iroh-net/src/portmapper/mapping.rs
iroh-net/src/portmapper/upnp.rs

[`igd`](https://github.com/sbstp/rust-igd) has been archived, [`igd-next`](https://docs.rs/igd-next) it's a replacement. This still does not use hyper 1 but will (hopefully) be [upgraded](https://github.com/dariusc93/rust-igd/issues/4) soon™️
n/a

deps(iroh-next): move from igd to igd-next

---

iroh-cli/src/commands/author.rs
iroh-sync/src/actor.rs
iroh-sync/src/store/fs.rs
iroh/src/client/authors.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs
iroh/src/sync_engine/rpc.rs

- `author.export`
- `author.import`
- `author.delete`

feat(iroh): implement basic author api

---

iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh/src/node/builder.rs

Moved the metrics init into CLI so the lib doesn't init the full metrics collection on its own and block other lib users to do their custom setup on top.

chore: move metrics init into CLI

---

iroh-cli/src/commands/blob.rs
iroh/examples/collection-fetch.rs
iroh/examples/hello-world-fetch.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs

Based on #2085 
The downloader already has the feature to try multiple nodes for a single hash or hashseq. With #2085 we expose the downloader over the RPC protocol, by adding a `DownloadMode { Queued, Direct }` enum to the `BlobDownloadRequest`. 
This PR modifies the `BlobDownloadRequest` to include a list of provider nodes for a hash instead of just a single node. For queued requests that go to the downloader, the nodes are just passed to the downloader. For direct requests, the nodes are tried in-order, until one succeeds.

feat: set more than one node on download requests

---

Cargo.lock

Update h2 to next patch release.
Fixes this cargo-deny warning:
> ID: RUSTSEC-2024-0332
>    = Advisory: https://rustsec.org/advisories/RUSTSEC-2024-0332
>    = An attacker can send a flood of CONTINUATION frames, causing `h2` to process them indefinitely.
>      This results in an increase in CPU usage.

deps: update h2

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/http/client.rs

The `self.connect` call in `Actor::recv_detail` was racing to create a connection with an incoming actor message to do so.
This simplifies `recv_detail` and only attempts to do so if there is already a connection, which is the correct logic in the first place.
Closes #2144

fix(iroh-net): avoid double connections to relays

---

iroh-sync/src/ranger.rs

Ref #1437
This does not optimize for speed yet, but should drastically lower the memory requirements for large documents.

perf(iroh-sync): avoid allocating a full range of values during sync

---

Cargo.lock
Cargo.toml
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-bytes/src/get.rs
iroh-bytes/src/get/db.rs
iroh-bytes/src/get/request.rs
iroh-bytes/src/lib.rs
iroh-bytes/src/provider.rs
iroh-bytes/src/store/bao_file.rs
iroh-bytes/src/store/fs.rs
iroh-bytes/src/store/mem.rs
iroh-bytes/src/store/mutable_mem_storage.rs
iroh-bytes/src/store/readonly_mem.rs
iroh-bytes/src/store/traits.rs
iroh-bytes/src/util.rs
iroh-cli/Cargo.toml
iroh/Cargo.toml
iroh/src/node/rpc.rs
iroh/tests/gc.rs

refactor(iroh-bytes): Update bao-tree to 0.12 and adjust code
bao-tree has some API changes that need to be adapted. Outboard creation is easier, and the ByteNum newtype is gone, replaced by just u64.
~~There is still a test failure. Hopefully nothing major. But hence the draft status.~~

refactor(iroh-bytes): Update bao-tree to 0.12 and adjust code

---

iroh-cli/src/commands.rs
iroh-cli/tests/cli.rs

fix(tests): disable the metrics port of all cli tests
otherwise they won't run due to "Address already in use (os error 48)".
Somehow one is missing... This still does not work:
```
> cargo test -- --ignored cli
running 11 tests
test cli_provide_addresses ... ok
test cli_bao_store_migration ... ok
test cli_provide_one_file_single_stdout ... ok
test cli_provide_one_file_basic ... FAILED
test cli_provide_folder ... FAILED
test cli_provide_persistence ... ok
test cli_provide_one_file_single_path ... ok
test cli_provide_from_stdin_to_stdout ... FAILED
test cli_provide_tree ... FAILED
test cli_rpc_lock_restart ... ok
```

test(iroh-cli): disable metrics

---

iroh-bytes/src/downloader/test/dialer.rs
iroh-bytes/src/downloader/test/getter.rs
iroh-bytes/src/format/collection.rs
iroh-bytes/src/protocol/range_spec.rs
iroh-bytes/src/store/bao_file.rs
iroh-bytes/src/store/fs/tests.rs
iroh-gossip/src/net.rs
iroh-net/bench/src/lib.rs
iroh-net/src/bin/iroh-relay.rs
iroh-net/src/discovery.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map/endpoint.rs
iroh-net/src/netcheck.rs
iroh-net/src/netcheck/reportgen/hairpin.rs
iroh-net/src/netcheck/reportgen/probes.rs
iroh-net/src/relay/client_conn.rs
iroh-net/src/relay/clients.rs
iroh-net/src/relay/codec.rs
iroh-net/src/relay/server.rs
iroh-net/src/stun.rs
iroh-sync/src/store/fs.rs
iroh-sync/src/sync.rs
iroh/src/node.rs
iroh/src/ticket/doc.rs
iroh/src/util/fs.rs
iroh/tests/gc.rs

The rust beta compiler does not like redundant imports and fails on
them.  We have them mostly in tests, likely because of how the code
was grown.  This cleans up the redundant imports.
Let's hope not too many new ones sneak in again, this will be a little
bit a catchup game until this makes it to stable.

fix: Remove redundant imports

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/lib.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/stun.rs
iroh-net/src/test_utils.rs
iroh/Cargo.toml
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/tests/sync.rs

* Add a `test-utils` feature to `iroh-net`. If enabled, expose the `test_utils` crate with `fn run_relay_server` publicly.
* Add option to `iroh_net::MagicEndpointBuilder` to skip relay server SSL certificate verification. The option is behind a `#[cfg(any(test, feature = "test-utils"))]`
* Add the same option to `iroh::NodeBuilder`, behind the same `cfg` option
* Add a test to `iroh` which uses `run_relay_server` and then downloads a blob by connecting to a node with only node id and relay URL (no direct addresses)

tests(iroh-net): expose `run_relay_server` and option to skip cert verification to tests

---

iroh-net/src/discovery.rs
iroh-net/src/discovery/dns.rs
iroh-net/src/discovery/pkarr_publish.rs
iroh-net/src/dns/node_info.rs

Adapts #2045 to match #2149 
* change the DNS and pkarr encoding for the NodeInfo to use one DNS record for each attribue
* remove the node= attribute as the node id is contained in the DNS name

refactor(dns): use one DNS record per attribute

---

iroh-cli/src/commands/doctor.rs

Apparently now metrics work and are attempted to be printed.
Unfortunately they also print a tracing error message to stderr, the
stderr which is also being used by the progress bar.  The result is
that the progress bar ends up with an extra newline and the first line
of it is not being repainted but flows up, resulting in lots of
garbage in the terminal history.
By removing the log message the output is perserved much better.
It could be argued that this is not a good fix, if the loglevel is
changed to info or debug the same problems would occur.  However we
already have the ability to log to a random filedescriptor and will
soon be able to log to files.  So maybe that's just fine for now.

fix(iroh-cli): Fix printing of doctor connect/accept output

---

Cargo.lock
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-bytes/src/get.rs
iroh-bytes/src/get/db.rs
iroh-bytes/src/provider.rs
iroh-bytes/src/store/bao_file.rs
iroh-bytes/src/store/fs/tests.rs
iroh-bytes/src/store/mem.rs
iroh-bytes/src/util/io.rs
iroh-cli/Cargo.toml
iroh/Cargo.toml
iroh/tests/gc.rs

refactor(iroh-bytes): use even newer bao-tree
There is a new version of bao-tree that fixes some long standing api consistency issues and drops the tokio dependency. This updates iroh to use it.
We of course still use tokio, but switching to something else would be easier at least as far as bao-tree is concerned.
The other change is that encode_ranges_validated no longer writes the length prefix, so we have to do this ourselves. This was done to simplify the bao-tree API and make it more flexible.

refactor(iroh-bytes): use even newer bao-tree

---

Cargo.lock
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-cli/Cargo.toml
iroh-gossip/Cargo.toml
iroh-net/Cargo.toml
iroh-net/bench/Cargo.toml
iroh-sync/Cargo.toml
iroh/Cargo.toml

I just stumbled upon the very nice tool [`cargo machete`](https://blog.benj.me/2022/04/27/cargo-machete/) which finds unused dependencies. So let's remove them!
Ran only `cargo check` locally - let's see if CI also says that all is fine.

deps: remove unused dependencies

---

iroh-base/src/node_addr.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/endpoint.rs

`MagicEndpoint::conn_type_stream` returns a `Stream` that reports changes for a `magicsock::Endpoint` with a given `node_id` in a `magicsock::NodeMap`.
It will error if no address information for that `node_id` exists in the `NodeMap`.
This PR also adjusts the `Endpoint::info()` method to use the same `ConnectionType` that gets reported to the stream.

feat(iroh-net): add `MagicEndpoint::conn_type_stream` returns a stream that reports connection type changes for a `node_id`

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh-cli/src/commands/doctor.rs
iroh-cli/src/commands/start.rs
iroh-cli/src/config.rs
iroh-cli/src/logging.rs
iroh-cli/src/main.rs

Adds file logging by default to commands that start a node.
Parameters are:
- the "RUST_LOG" directive, in the form of and env var `IROH_FILE_RUST_LOG` or in the configuration file.
- rotation: how often a new file is created. Either daily, hourly or never.
- max files: Maximum number of files to keep
File logging can be disabled by either setting the max_files to 0 in the configuration file or by setting the rust log statement to off, in either the env var or the config file.
(example config file)
```toml
[file_logs]
rust_log = "iroh=trace"
rotation = "daily"
max_files = 1
```
The files created live the `IROH_DATA_DIR/logs` dir and are named `iroh-2024-03-02.log` (for a daily rotation, or with the hour, for an hourly rotation)
By default, we log everything in debug, rotating hourly, …

feat(iroh-cli): add file logging by default for start commands

---

iroh-net/src/netcheck/reportgen.rs

The reportgen actor was carrying this "incremental" state around in
two ways: as an Option in last_report and as a boolean in incremental.
It's simpler to have less state and only carry it as an Option.

refactor(iroh-net): Remove incremental state from reportgen actor

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh-cli/src/commands/doctor.rs
iroh-cli/src/config.rs

Loads the configuration from either the default path, or the passed in configuration path. Dropping the `config` dependency and simplifying the structure.
Removes unused overrides and detailed configuration via env variables.

feat(iroh-cli): simplify config loading

---

iroh-bytes/examples/fetch-fsm.rs
iroh-bytes/examples/fetch-stream.rs
iroh-net/src/stun.rs

Some more unused code and duplicate imports detected by the beta
compiler.
Are the examples sufficiently tested by CI?

refactor: rustc beta is stricter again wrt imports and unused code

---

Cargo.lock
iroh-cli/src/config.rs
iroh-net/src/defaults.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/codec.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/types.rs
iroh-net/src/tls/verifier.rs

The relay handshake is quite expensive currently
- TLS 1.3 + HTTP 1 UPGRADE
- Server sends FrameType::ServerKey
- Client sends FrameType::ClientInfo
- Server sends FrameType::ServerInfo
This simplifies the protocol to 
- TLS 1.3 + HTTP 1 UPGRADE
- Client sends FrameType::ClientInfo
information changes
- using a signature, instead of a shared secret to ensure the client identity. 
- server key is not sent (use certificate pinning if fixed relays are important)
- remove unused configuration in the info frames
- change magic from `derp` to `relay`
- increase protocol version to `3`
- drop `serverinfo` in favor of fixed config on the client
- enable tcp nodelay
- switch to AES for encryption in favor over chacha
- the server simply aborts when the client version doesn't match (matching what …

perf(iroh-net): simplify relay handshake

---

iroh-cli/src/commands/doctor.rs

`iroh doctor accept` and `iroh doctor connect` will both run with discovery services enabled by default.
Use the `--disable-discovery` flag to disable discovery.
This PR also cleans up some of the output for `iroh doctor accept`

feat: add discovery option to doctor

---

.github/workflows/release.yml
.github/workflows/tests.yaml

Adding this to the stack. Makes deploys and everything much easier.

chore(ci): upload iroh-dns-server binaries

---

iroh-bytes/src/provider.rs

feat(iroh-bytes): add more context to errors
add hash and offset/range as context for LeafHashMismatch and ParentHashMismatch errors
This is what the log looks like now:
```
2024-04-16T07:17:19.613913Z  WARN iroh_bytes::provider: error: Error {
context: "hash 17c8e5a70f69d289105553dfa762064e8cc57ffb9355d76508f557e37ef051db offset 9994240",
source: LeafHashMismatch(
ChunkNum(0x2620),
),
}
2024-04-16T07:17:26.664680Z  INFO magicsock{me=34qdsunbluss4zny}:actor:disco{node=kqn3pxyufuskwsup}: iroh_net::magicsock::node_map::best_addr: clearing best_addr reason=PongTimeout has_relay=true old_addr=192.168.1.131:64604
2024-04-16T07:18:05.507191Z  INFO poll_recv{me=34qdsunbluss4zny}:disco_in{node=kkpbi4eb5h6jcdjz src=Udp(192.168.1.131:62647)}: iroh_net::magicsock::node_map: inserting new node …
```

feat(iroh-bytes): add more context to errors

---

iroh-dns-server/src/config.rs
iroh-dns-server/src/store/signed_packets.rs

Logs the database file path on start, and adds context to some errors if things fail.

fix: better logging for iroh-dns-server

---

iroh-net/src/netcheck/reportgen.rs

Depending on the system and configuration the error retruned for an
unroutable IPv6 address might be slightly different.  But they need to
be treated the same way.
This is hard to test, please verify this manually on the system where
it occurred.

fix(iroh-net): Suppress HostUnreachable network error as well

---

iroh-bytes/src/store/fs/tables.rs

fix(iroh-bytes): do not log when a file can not be deleted...
because it is not there. this makes the delete op idempotent, and also helps in case the file was not there in the first place.
Fixes https://github.com/n0-computer/iroh/issues/2142

fix(iroh-bytes): do not log redundant file delete error

---

iroh-bytes/src/downloader.rs
iroh-bytes/src/downloader/invariants.rs
iroh-bytes/src/downloader/test.rs
iroh-bytes/src/downloader/test/dialer.rs

adds retries to #2085:
* after a node fails to dial, or fails during a transfer  with IO errors, we move the node into a delay queue, with an increasing timeout. once the delay expires, the node may be dialed again.
* if the head of the download queue can only proceed with nodes which are currently in the retry queue, we *park* the download in a separate set from the main queue, and proceed with the next download
* once a retrying node succeeds to reconnect, we unpark all parked hashes for which this node is a candidate
Has a smoke test for retry behavior. Adding more tests would be great.

feat: retry nodes in downloader

---

.github/pull_request_template.md
.github/workflows/ci.yml
.github/workflows/commit.yml
CONTRIBUTING.md
iroh/src/node.rs

- update issue template
- update `CONTRIBUTING.md`
- add semver checker to CI

docs: improve breaking change handling

---

.github/workflows/release.yml

This is a bit hard to test without merging. However merging should be safe as it does nothing unless we trigger a release via push. We can also toy with it then to see if things work.
Moving forward, pushing with a tag matching the pattern `v*` will automatically create a release titled with the tag name and attach all binaries (`iroh`, `iroh-relay`, `iroh-dns-server`) for all platforms we support. Once done you can edit the release to update the title and contents.
Also coveres doing `musl` builds for linux platforms.
Closes: https://github.com/n0-computer/iroh/issues/2174 & https://github.com/n0-computer/iroh/issues/2173

feat: release automation

---

iroh/src/sync_engine.rs
iroh/src/sync_engine/gossip.rs
iroh/src/sync_engine/live.rs
iroh/tests/sync.rs

based on #2085 
* do not start downloads without any known node
* track missing content hashes in the live sync session
* start downloads after content propagation properly
* reenable the sync_big test, let's see what CI says this time (was flakey before)

refactor: improve content downloading in docs

---

iroh-net/src/dns.rs
iroh-net/src/netcheck/reportgen.rs

They have been stable on CI for a while now.  Maybe the DNS config
tweak we did in #2075 made a difference.
Closes #2086 

tests: Remove flaky label from windows-DNS affected tests

---

iroh-cli/src/commands/doctor.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/node_state.rs

We still have too many things named "endpoint", this targets cleaning
up the naming of the state for each node that is stored in the NodeMap.
This is now called `NodeState` instead of `Endpoint`.  All related APIs
now talk about nodes and node states instead of endpoints.
Another minor cleanup is in the `NodeState` we had private fields with
accessor functions, except for one field which was directly
accessible.  This is migrated to accessor functions for consistency as
well.
Finally it marks the visibility of some functions more explicitly, the
visibility of those was already as such.  This makes it easier to work
and realise the impact changes have however.
* `MagicSock::tracked_endpoints` -> `MagicSock::connection_infos`
* `MagicSock::tracked_endpoint` -> `MagicSock::connection_info`
* …

refactor(iroh-net)!: Rename endpoint for nodes to node_state

---

iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs

- Waits for connections to actually be closed by calling `quinn::Endpoint::wait_idle` after close.
- Consumes the `MagicEndpoint` in an effort to express the fact that closing an endpoint is a terminal operation.
- Adds logging to closing the connections in case it's deemed necessary
- Changes `MagicSock::poll_recv` to return `Poll::Pending` on close instead of an error. More info on the logic behind this change below.
- Changes `MagicSock::poll_send` to not error if nothing is being sent.
`MagicEndpoint::close` now consumes the endpoint.
Shutdown `MagicSock` when quinn is done with it has proven something we can't do reliably.
- Drop based solutions (close when the `MagicSock` is dropped) are unreliable because the socket is held by multiple components on `quinn`, including spawned …

fix(iroh-net)!: improve magicsock's shutdown story

---

iroh-net/src/magicsock/node_map/node_state.rs

Merges the `got_ping*` fields since they are bound to be either both `Some` or both `None`
n/a
n/a

refactor(iroh-net): merge related fields regarding incoming pings

---

iroh-net/src/netcheck/reportgen.rs

As described in #2239 
n/a
dns issue? why only the eu_relayer? - discussion for the issue

tests(iroh_net): mark test_icmpk_probe_eu_relayer as flaky on windows

---

iroh-net/src/magicsock/node_map/best_addr.rs
iroh-net/src/magicsock/node_map/node_state.rs

Clears the best address only if within the time the pong should have been received, nothing else was seen so that the address is considered not alive in that period. This should result in less aggressive best_addr clearing.
Specific changes include:
- remove `BestAddr::clear_if_addr_older` since it is no longer needed.
- change `BestAddr::clear*` return since it was never read anyway.
- check for alive withing the `PING_TIMEOUT_DURATION` before clearing the best address on timeout
- misc docs fixes in code related to being alive/active
n/a
n/a

fix(iroh_net): less agressive best_addr clearing on pong timeout

---

iroh-gossip/Cargo.toml

Otherwise it is impossible to disable metrics support in iroh-net
if iroh-gossip is used.

fix(iroh-gossip): do not enable "metrics" feature for iroh-net by default

---

iroh-cli/src/commands/doctor.rs
iroh-cli/src/commands/node.rs
iroh-net/src/disco.rs
iroh-net/src/discovery.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/test_utils.rs

A bug in the discovery flow assumed that if we had a mapped quic address for a `node_id`, then we had at least a relay URL or one direct address available for that node.
This meant there were instances in which discovery should have been launched before attempting to dial the node, but was never launched, leading to `no UDP or relay address available for node` errors.
Now we check if addresses are available for a `node_id` and launch discovery if we do not have any before we attempt to dial.
We also now take into account the "alive" status of any relay URL information we have on a `node_id` when determining if we need to run discovery for that `node_id`
This also refactors the test DNS server and the test Pkarr relay server to use `CleanupDropGuard` for resource cleanup. It also moves the …

fix(iroh-net)!: only call quinn_connect if a send addr is available

---

iroh-bytes/src/store/fs.rs

When encountering a failure in renaming, due to cross mount point issues, fallback to copy and delete.
Closes #2229

feat(iroh-bytes): add copy fallback for Export::TryReference

---

iroh-dns-server/examples/publish.rs
iroh-dns-server/src/lib.rs
iroh-net/src/discovery.rs
iroh-net/src/discovery/pkarr_publish.rs
iroh-net/src/dns/node_info.rs

feat(iroh-net): extend discovery NodeInfo to allow direct addrs
This should be compatible with what is sketched in https://github.com/n0-computer/iroh/issues/2149
For now we leave the direct addresses empty, but having this would allow tools like https://github.com/n0-computer/iroh-examples/tree/main/iroh-pkarr-node-discovery to publish everything (optionally) without having to reimplement the conversion from/to signed packets.

feat(iroh-net): extend discovery NodeInfo to allow direct addrs

---

iroh-base/Cargo.toml
iroh-base/src/node_addr.rs
iroh-base/src/ticket/blob.rs
iroh-base/src/ticket/node.rs
iroh-cli/src/commands/blob.rs
iroh-cli/src/commands/doc.rs
iroh/src/client.rs
iroh/src/client/blobs.rs
iroh/src/client/docs.rs
iroh/src/rpc_protocol.rs
iroh/src/sync_engine/rpc.rs
iroh/tests/sync.rs

This expands on the functionality previously only available to blob tickets, of configuring the information contained in a `NodeAddr`.
- renamed: `iroh::client::blobs::ShareTicketOptions` -> `iroh_base::node_addr::AddrInfoOptions`
- renamed `iroh_cli`: `doc share --ticket-options` -> `doc share --addr-options`
- Default for `AddrInfoOptions` is now `Id`, before it was `RelayandAddresses`
- Added `addr_options` to `iroh::client::docs::Docs.share`
- Added `Id` option to `AddrInfoOptions`
Closes #2187

feat!: implement improved address sharing options

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/src/config.rs
iroh-dns-server/src/lib.rs
iroh-dns-server/src/server.rs
iroh-dns-server/src/store.rs

This adds a test for iroh-dns-server with mainline fallback resolution.
Needed to rework the config structure a little to not duplicate code too much.
are documented in #2180

test: add test for iroh-dns-server with mainline

---

iroh-cli/src/commands/doctor.rs
iroh-cli/src/commands/node.rs
iroh-net/bench/src/lib.rs
iroh-net/src/lib.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/magicsock/timer.rs
iroh-net/src/netcheck.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/tests/provide.rs

`magicsock` main's component, the `MagicSock` is not useful on it's own. Having it on our public API forces us to treat as breaking changes modifications that for a `MagicEndpoint` user are implementation details. To avoid this, this PR makes the following changes:
- expose all types that are part of the public functions of the `MagicSock` as `pub use`
- explicitly re-export every publicly exposed by `magicsock` from `magic_endpoint` (so that the types involved in the prev change can be used from `magic_endpoint` directly)
- changes the description of the `magic_endpoint` module to not include the `MagicSock` and make it more expressive at the same time.
- `MagicSock` had a bunch of methods that were simply methods of `Inner` re-exposed. Now that `MagicSock` is private, we can get rid of …

refactor(iroh-net)!: remove the magicsock module from the public api

---

iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/endpoint.rs

Changes the logic of which addresses are persisted in the magic endpoint:
* For nodes that were used in the current session, only the paths that were successfully used will be saved. This means that invalid paths will be omitted. If all paths are invalid, and no relay URL is known, the node will not be persisted at all.
* For nodes that were not used at all, all known information will be persisted. This is in place to not forget all info if a node starts, loads the addressbook, and then shuts down again without doing anything.
Still needs a test for the new behavior, will do tomorrow

fix(iroh-net): do not persist invalid node addresses

---

iroh-base/src/ticket/blob.rs
iroh-base/src/ticket/node.rs

feat(iroh-base): allow the addr info of tickets to be empty
Without this, a ticket that does not contain any addresses or relay URL can not be parsed. But we need to allow this if we want to use short tickets.
Note: I did not remove the error type Validation. That way we don't have breaking changes, and we might need it again in the future.

feat(iroh-base): allow the addr info of tickets to be empty

---

iroh-net/src/magicsock/node_map/best_addr.rs
iroh-net/src/magicsock/node_map/node_state.rs

When receiving data via UDP, we were not extending the validity of the current `best_addr`. This would trigger expiry of the `best_addr`, even though it was actively being used. 
This fix, extends the validity, everytime we successfully receive a UDP packet on the current `best_addr`.
Closes #2169

fix(iroh-net): reconfirm best addr when receiving data on it

---

Cargo.lock
iroh-base/Cargo.toml
iroh-base/src/hash.rs
iroh-cli/Cargo.toml
iroh-cli/src/commands/doctor.rs

feat(iroh-cli): Make ticket-inspect print full node ids
also add the option to show them in zbase32 format for pkarr interop. I need this in the workshop.
Before:
```
Blob ticket:
BlobTicket {
node: NodeAddr {
node_id: PublicKey(sq46x6htizk6222l),
info: AddrInfo {
relay_url: Some(
RelayUrl(
"https://euw1-1.relay.iroh.network./",
),
),
direct_addresses: {
82.76.245.75:50824,
192.168.1.131:50824,
192.168.1.149:50824,
},
},
},
format: HashSeq,
hash: Hash(
cc4c9cd6bee4e1730447264b8290d83b3f901d88152ff0ecefb5e3050d0c500f,
),
}
```
After:
```
BlobTicket
hash: zrgjzvv64tqxgbchezfyfegyhm7zahmicux7b3hpwxrqkdimkahq
format: HashSeq
Node Info
node-id: sq46x6htizk6222lyz7jc4ofe3tymyw27joi3jzuhskavjczmcya
relay-url: https://euw1-1.relay.iroh.network./
addr: 82.76.245.75:50824
addr: 192.168.1.131:50824 …
```

feat(iroh-cli): Make ticket-inspect print full node ids

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/net/interfaces.rs
iroh-net/src/net/interfaces/bsd.rs
iroh-net/src/net/ip.rs

- Upgrades from `default-net` v0.20 to `netdev` v0.25, which is simply a rebrand of the original default-net
- Allows depending on `system-configuration` version 0.6 instead of 0.5.1 downstream. This fixes iOS compliation for us.
~~Would need to check if/how much the `default-net` types were exposed in the API.~~
@divagant-martian says this is what changes in the API:
> ```diff
> Changed items in the public API
> ===============================
> -pub iroh_net::net::interfaces::IpNet::V4(netdev::ip::Ipv4Net)
> +pub iroh_net::net::interfaces::IpNet::V4(default_net::ip::Ipv4Net)
> -pub iroh_net::net::interfaces::IpNet::V6(netdev::ip::Ipv6Net)
> +pub iroh_net::net::interfaces::IpNet::V6(default_net::ip::Ipv6Net)
> ```
~~Not sure yet if it fixes our iOS problems.~~ It's required to fix our …

feat: Update from `default-net` to rebranded `netdev`

---

iroh-net/src/net.rs
iroh-net/src/net/interfaces.rs

This is leaking 3rd party types into our public interface, since this
really only exists for our own use it probably shouldn't be public to
start with.  So make it private.  As a result cleans up some dead
code.
The `iroh_net::net::interfaces` module has been made private.
There is probably more in `iroh_net::net` that needs to be private.
Maybe even the whole module.  I'm not sure if doing this stepwise or
in one large chunk is better.  This takes the stepwise approach.

refactor(iroh-net)!: Make the interfaces module private

---

iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs

Closes #2162
Adds `watch_home_relay`, which reports the current home relay and any seen change.
n/a
n/a

feat(iroh-net): watch relay changes

---

iroh-net/src/discovery/pkarr_publish.rs

By merging #2188 we unknowingly made `iroh` bind a socket for a mainline DHT.
Pkarr includes code for querying records from the bittorent mainline DHT behind a `dht` feature flag, which is disabled in `iroh-net` but with #2188 is enabled in `iroh-dns-server`, and due to feature unification in cargo workspaces this silently also enabled the feature in `iroh-net`.
The DHT is not used because we only use the `relay_` methods of the pkarr client in iroh-net. It is binding a socket, but not doing anything else because it has no bootstrap node configured.
Still, this is unfortunate - we are shipping code and binding a socket for a feature we don't (yet) use.
From a cursory skim of the source code, this would still be the same with the recently released `pkarr` v2.
We should check the docs on …

fix: do not bind a mainline DHT socket

---

iroh-gossip/examples/chat.rs
iroh-net/examples/connect-unreliable.rs
iroh-net/examples/connect.rs
iroh-net/examples/listen-unreliable.rs
iroh-net/examples/listen.rs
iroh/examples/client.rs

I noticed that in the example code (particularly `iroh-net`'s code), there are a few explicit uses of `base32` encoding and decoding that are unnecessary. In particular, `SecretKey` is manually `base32`-encoded in the networking examples, although the `Display` implementation uses that same encoding. I figure that the examples were just written before the utility encoding/decoding code in the main libraries were and weren't updated when that utility code was added. I hope that catching this is helpful!
None.
None.

examples: minimize use of raw base32 in examples

---

iroh/src/docs_engine/gossip.rs

Changes gossip usage in `iroh::docs_engine` to not use `Gossip::subscribe_all` but subscribe to individual topics instead.

refactor: do not use gossip subscribe_all in iroh sync engine

---

iroh-cli/src/commands/doc.rs
iroh/src/client/docs.rs
iroh/src/docs_engine.rs
iroh/src/docs_engine/live.rs
iroh/src/docs_engine/state.rs
iroh/tests/sync.rs

This adds a new `LiveEvent` variant: `PendingContentReady`.
It is emitted once, after sync was started, the list of pending content blobs becomes empty. This is the case if either all blobs from this sesion have been downloaded, or failed.
I think this could help with simple examples like https://gist.github.com/dignifiedquire/efbd1a7a1da729494adb088d72f1ceaa#file-main-sync-rs-L84
It should not be used as a guarantee that all content is now available locally, and it should be used with a timeout usually, because it may very legally never be emitted (e.g. if the remote does not have all blobs themselves, or closes the connections, etc).
* `LiveEvent` now has a new variant `PendingContentReady`. This event is emitted  after a sync completed and `Self::SyncFinished` was emitted. It signals …

feat: emit PendingContentReady event

---

iroh/src/client/docs.rs
iroh/src/docs_engine/rpc.rs
iroh/src/rpc_protocol.rs

This adds the much-needed `import_and_subscribe` call to make live sync events more reliable.
Did not test much yet but I think it should work as expected!

feat: import and subscribe to a document in a single call

---

iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs
iroh/tests/gc.rs
iroh/tests/provide.rs

These seem to be mostly unused by consumers, and add complexity.
- remove:
-  `iroh::node::Event`
- `iroh::node::Node::subscribe`

feat(iroh)!: remove node events

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/streams.rs
iroh-net/src/relay/server.rs
iroh-net/src/util.rs
iroh-net/src/util/chain.rs
iroh/src/node/builder.rs

Headers are based on how `curl` and env variables on`reqwest`.
Setting any of 
- `HTTP_PROXY`
- `http_proxy`
- `HTTPS_PROXY`
- `https_proxy`
will make all relay code use these to proxy outgoing connections.
Closes #2295 
- Added `iroh_net::endpoint::Builder::proxy_url`
- Added `iroh_net::endpoint::Builder::proxy_from_env`
- Added `iroh_net::relay::http::ClientError::Proxy` enum variant

feat(iroh-net)!: Implement http proxy support

---

.github/workflows/ci.yml
.github/workflows/tests.yaml
Cargo.lock
iroh-net/bench/Cargo.toml
iroh-net/bench/src/bin/bulk.rs
iroh-net/bench/src/iroh.rs
iroh-net/bench/src/lib.rs
iroh-net/bench/src/quinn.rs
iroh-net/bench/src/s2n.rs
iroh-net/bench/src/stats.rs

In progress thing for what should later be `iroh-perf`. For now you can run with `cargo run --release -- iroh` and `cargo run --release -- quinn` to do a simple comparison benchmark.
More knobs are available for tuning with `--help`.
There's a much more stark difference on macOS compared to running on Linux.
Next steps bumping to test against `quinn 0.11`
Sample output:
```
iroh (macOS)
Client 0 stats:
Connect time: 13.788583ms
Overall download stats:
Transferred 1073741824 bytes on 1 streams in 5.47s (187.27 MiB/s)
Time to first byte (TTFB): 1ms
Total chunks: 130319
Average chunk time: 41.936ms
Average chunk size: 8.04KiB
Stream download metrics:
│  Throughput   │ Duration 
──────┼───────────────┼──────────
AVG  │  187.31 MiB/s │     5.47s
P0   │  187.25 MiB/s │     5.46s
P10  │  187.37 …
```

feat: iroh-perf

---

iroh-cli/src/commands.rs
iroh-cli/src/commands/doctor.rs

Folks try to look at metrics while doctor alone is running (note this clashes by default with the iroh node if both are running locally on port :9090). Also kind of inconvenient given if you want to look at a running iroh node when doctor is running.
Suggestions welcome, maybe default off metrics on `doctor`?
Also most metrics are not really used in the `doctor` path, but we can fix that as we figure out what's cool to measure.

feat(cli): add metrics server to iroh doctor

---

iroh-cli/src/commands/console.rs
iroh-cli/src/config.rs

We used to store the console files (history and current author) in a subdirectory `console` under the iroh data dir. This got lost in some refacorings, and the console files currently are created in the iroh data directory directly.
This is bad because the iroh data directory is a single namespace, and we should use it cautiously.
This PR goes back to using a `console` subdirectory. Existing files are migrated on first start of the console.
Based on #2299 because this already made the environment init functions async.

fix: store console files in subdirectory of iroh data dir

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/test_relay_server.yml
Cargo.lock
Cargo.toml
iroh-base/Cargo.toml
iroh-blobs/Cargo.toml
iroh-cli/Cargo.toml
iroh-docs/Cargo.toml
iroh-gossip/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-test/Cargo.toml
iroh/Cargo.toml
iroh/src/client/mem.rs
iroh/src/client/quic.rs
iroh/src/node.rs
iroh/src/node/builder.rs

Adapts iroh for n0-computer/quic-rpc#76
Wit this change, a quic client is
`pub type QuicIroh = Iroh<QuinnConnection<RpcService>>`
instead of
`pub type QuicIroh = Iroh<QuinnConnection<ProviderRequest, ProviderResponse>>`
* Increased mimimal supported rust version (MSRV) from 1.75 to 1.76
* The generics of the iroh clients changed: Instead of taking `ProviderRequest, ProviderResponse` as generics, they now take `RpcService`

feat!: new quic-rpc, simlified generics, bump MSRV to 1.76

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/magicsock.rs
iroh-net/src/net/interfaces/windows.rs

Fix for https://github.com/n0-computer/iroh/issues/2328: Enumerating network devices is slow
on windows and causes delays in the magicsock actor.  This makes sure that this operation
does not block the remainder of the actor.
Also bumps netdev to v0.27.0 , to fix https://github.com/n0-computer/iroh/issues/2327.

fix(iroh-net): fix extra delay

---

iroh-net/src/endpoint.rs
iroh-net/src/lib.rs

This updates the top-level docs for iroh-net to be a general
overview of what the crate provides, since this is effectively the
docs.rs landing page.
None
This should include an examples section as well.  However... the API
is a bit pants and does not lend itself to a nice echo example here.
Let's tackle this separately.
This does not change the README, that is already fairly decent and
seems compatible with this content.

docs(iroh-net): Update toplevel module documentation

---

Cargo.lock
iroh-docs/src/engine/live.rs
iroh-gossip/src/net.rs
iroh-gossip/src/net/util.rs
iroh-gossip/src/proto/state.rs
iroh-gossip/src/proto/topic.rs
iroh-net/src/net/interfaces/bsd.rs

Add configuration option for `max_message_size` for `iroh-gossip::proto::Config`.
This `Config` gets used in `iroh-gossip::Gossip::from_endpoint`.
`iroh-docs` still uses the default 4096 bytes. The `max_message_size` configuration is useful for folks using `iroh-gossip::Gossip` as its own library.
closes #2312
Adds:
`iroh-gossip::Gossip::max_message_size` - that reports the configured maximum message size for the gossip actor.
Changes:
`iroh_gossip::net::util::read_message` now takes a `max_message_size: usize` parameter
`iroh_gossip::net::util::write_message` now takes a `max_message_size: usize` parameter
`iroh_gossip::net::util::read_lp` now takes a `max_message_size: usize` parameter
Removes:
`iroh-gossip::proto:: MAX_MESSAGE_SIZE` const

feat(iroh-gossip): configure the max message size

---

iroh-docs/Cargo.toml
iroh-docs/src/actor.rs
iroh-docs/src/store/fs.rs
iroh-docs/src/store/fs/query.rs
iroh-docs/src/store/fs/ranges.rs
iroh/src/node/rpc/docs.rs
iroh/tests/sync.rs

Fixes #2345 
The iroh-docs actor loop can easily be deadlocked from the client side: If you call any RPC method that returns a stream, and the stream is longer than what the RPC layer buffers, and you call and await any other docs method *while consuming the stream*, the docs actor will deadlock. 
(It will only happen though if the stream is longer than the capacity of the intermediate channel that goes from the actor to the RPC layer, which is why this does not *always* happen)
This is the case for all methods that return iterators. The solution is twofold:
* Run single-threaded executor in iroh-docs actor loop
* For actions returning iterators/streams, spawn a task on that executor to forward the store iterator into the stream, yielding when the receiver is not consuming fast enough
To …

fix(docs): prevent deadlocks with streams returned from docs actor

---

iroh-blobs/src/export.rs
iroh-blobs/src/format/collection.rs
iroh-cli/src/commands/blob.rs
iroh/src/client/blobs.rs
iroh/src/client/tags.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs

A collection is just one particular way to use a hashseq, so it feels a bit weird to have it baked in to the iroh node. With this we can move some of it into the client.
This is a part of https://github.com/n0-computer/iroh/pull/2272 . We can make more similar changes once we have the batch API https://github.com/n0-computer/iroh/pull/2339 .
Note: I closed #2272 because half of the changes in that PR are here, the other half will be part of the batch PR, and moving collections into iroh I am not convinced of yet...

refactor(iroh-blobs)!: implement some collection related things on the client side

---

iroh-net/src/magicsock.rs
iroh-net/src/net/interfaces/bsd.rs

If we have no relay URL or addresses to send transmits for a NodeID in `poll_send`, what do we do?
Returning `Polling::Ready(Err(e))` causes the endpoint to error, which causes all connections to fail.
If we return `Polling::Pending` (in this case), we have no mechanism for waking the waker once the `poll_send` is returned. Also, even if we wake up and continue to poll, we will attempt to send the same transmits that we know we cannot send.
If we return `Polling::Ready(Ok(0))`, we will get into a loop in Quinn that attempts to keep re-sending the same transmits.
However, if we report back to Quinn that we *have* sent those transmits (by returning `Polling::Ready(Ok(n))`), then Quinn will move on and attempt to send new transmits. QUIC mechanisms might cause those transmits to be re-sent …

fix(iroh-net): return `Poll::Read(Ok(n))` when we have no relay URL or direct addresses in `poll_send`

---

iroh-cli/src/commands/author.rs
iroh-cli/src/commands/blob.rs
iroh-cli/src/commands/doc.rs
iroh-cli/src/commands/tag.rs
iroh-cli/src/config.rs
iroh/examples/client.rs
iroh/examples/collection-fetch.rs
iroh/examples/collection-provide.rs
iroh/examples/hello-world-fetch.rs
iroh/examples/hello-world-provide.rs
iroh/src/client.rs
iroh/src/client/authors.rs
iroh/src/client/blobs.rs
iroh/src/client/docs.rs
iroh/src/node.rs
iroh/tests/gc.rs
iroh/tests/provide.rs
iroh/tests/sync.rs

With 4 different clients, the current approach might be OK. But we are going to have more. E.g. gossip, see https://github.com/n0-computer/iroh/pull/2258 .
And in any case it feels weird to store the same thing multiple times.
So this replaces public fields in the iroh client with accessors and use ref-cast to eliminate them entirely. There is now only one rpc field, and you can switch from that to the different subsystem client views without runtime overhead, not even an arc clone.
Everything that uses the iroh client will have to switch from field accesses to accessor fns.

refactor(iroh)!: replace public fields in iroh client with accessors and use ref-cast to eliminate them entirely

---

iroh-blobs/src/downloader.rs
iroh-blobs/src/downloader/invariants.rs
iroh-blobs/src/downloader/test.rs
iroh-blobs/src/util.rs
iroh-docs/src/engine/live.rs
iroh-net/src/net/interfaces/bsd.rs
iroh/src/node/rpc.rs

Remove tags from downloader. Adding temp or persistent tags is now the responsibility of the caller.
- iroh_blobs::downloader::DownloadRequest
- field `tag` is removed
- fn `untagged` is removed
- fn `tag` is removed
Docs are changed to indicate that tagging is now responibility of the caller...

refactor(iroh)!: remove tags from downloader

---

iroh-gossip/src/net.rs
iroh-net/src/endpoint.rs

This removes the Endpoint::my_addr_with_endpoints API.  It is rather
esoteric, very easy to do by hand and uses the dreaded endpoint noun
in the wrong context.
- Endpoing::my_addr_with_endpoints has been removed.

refactor(iroh_net)!: Remove Endpoint::my_addr_with_endpoints

---

iroh-cli/src/commands/doctor.rs
iroh-gossip/src/net.rs
iroh-net/examples/connect-unreliable.rs
iroh-net/examples/connect.rs
iroh-net/examples/listen-unreliable.rs
iroh-net/examples/listen.rs
iroh-net/src/endpoint.rs
iroh/src/node.rs
iroh/src/node/rpc.rs

This renames Endpoint::my_relay to Endpoint::home_relay.  This is more
descriptive, because home relay is how we describe this in other parts
of the documentation.  There is also no real consistency of the `my_`
prefix, there's only one other API currently which I'll independently
propose to remove.
- Endpoint::my_relay -> Endpoint::home_relay

refactor(iroh-net)!: Rename Endpoint::my_relay to home_relay

---

iroh-gossip/examples/chat.rs
iroh-net/src/discovery.rs
iroh-net/src/endpoint.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs
iroh/src/node/rpc/docs.rs

This is in line with e.g. Endpoint::node_id.
- Endpoint::my_addr -> Endpoint::node_addr
Other networking APIs tend to have something like "local_addr",
e.g. UdpSocket::local_addr in the standard library or
Endpoint::local_addr in Quinn.  Sometimes this is because they also
have a "peer_addr" version, e.g. UdpSocket::peer_addr.
In this light perhaps some of our APIs might benefit from using this
for consistency with other API conventions.  In this case this would
become Endpoint::local_node_addr.
We already have Endpoint::local_addr which returns the socket
addresses we are bound to.  Other candidates would be:
- Endpoint::home_relay -> Endpoint::local_home_relay
- Endpoint::node_id -> Endpoint::local_node_id
- Endpoint::secret_key -> Endpoint::local_secret_key
But, you can already see …

refactor(iroh-net)!: Rename Endpoint::my_addr to Endpoint::node_addr

---

iroh-cli/src/commands/doctor.rs
iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/node_state.rs

Some of our APIs take NodeId by reference, some by value.  NodeId
itself however is Copy and takes 32 bytes.  I think it is more
consistent and rusty to pass this by value and use the Copy semantics.
Additionally this renames a few more types from PublicKey to NodeId to
keep in line with our convention of using NodeId when used as
identifier rather than cryptography.  I believe rust-analyser might be
inserting PublicKey by itself which is unfortunate.
QuicMappedAddr and IpPort are also a Copy types and get the same
treatment.
- Endpoint::conn_type_stream takes NodeId by value instead of by reference.

refactor(iroh-net)!: Do not use &NodeId in APIs as this is Copy

---

iroh-net/bench/src/iroh.rs
iroh-net/src/endpoint.rs
iroh/src/node.rs
iroh/src/node/builder.rs

This renames Endpoint::local_addr to Endpoint::bound_sockets.  We have
a lot of different meanings for "addr" and also don't really have a
notion of "local_" prefix, since the endpoint is not 1:1 connected
with a peer.  The "local_" naming comes from connected sockets which
have local_addr and peer_addr, which is not applicable for the
Endpoint.
- Endpoint::local_addr -> Endpoint::bound_sockets

refactor(iroh-net)!: Rename Endpoint::local_addr to bound_sockets

---

iroh-gossip/examples/chat.rs
iroh-net/examples/listen-unreliable.rs
iroh-net/examples/listen.rs
iroh-net/src/endpoint.rs
iroh/src/node/builder.rs

- `iroh_net::endpoint::Connecting::alpn` returns `Vec<u8>` instead of `String`

fix(iroh-net)!: ALPNs can be bytes, not just strings

---

Cargo.lock

Fixes `cargo-deny` warning for [RUSTSEC-2024-0344](https://rustsec.org/advisories/RUSTSEC-2024-0344):
*Timing variability in `curve25519-dalek`'s `Scalar29::sub`/`Scalar52::sub`*
Upstream PR: https://github.com/dalek-cryptography/curve25519-dalek/pull/659

deps: bump curve25519-dalek

---

iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs

This is a cleanup of the node and builder code.
* Move `run` and `gc_loop` from `builder.rs` to `node.rs` - it is not about building but about running.
* Improve the code flow and naming all around the builder, spawn and run functions
* Make sure we shutdown the node correctly while spawning
* Removed `Node::controller`. Use `Node::client` instead. The former was mostly unusable anyway because we made the RPC structs private.

refactor(iroh): move code from builder to node and make things nicer

---

iroh/src/client/docs.rs

We unconditionally sent a `DocClose` RPC message when dropping a `iroh::client::docs::Doc` struct. However, we should only ever send a `DocClose` *once* for each doc instance, because otherwise the reference counter in the backend will decrease *twice*, and thus closing the resource in the backend too soon, affecting other open client instances. This was either an oversight or got lost in refactorings, not sure anymore. In any case: This PR fixes the behavior, and also adds a test that fails without this fix.
Fixes #2381

fix(iroh): do not double-close docs on drop

---

iroh/src/client/authors.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/docs.rs
iroh/src/node/protocol.rs
iroh/src/node/rpc.rs
iroh/src/node/rpc/docs.rs
iroh/src/rpc_protocol.rs
iroh/tests/gc.rs
iroh/tests/provide.rs

Make the docs engine optional on the iroh node.
* Add `Builder::disable_docs()` to disable the docs engine completely
* If called, the docs engine will not be spawned and the docs protocol will not be registered. Incoming docs connnections will be dropped, and all docs-related RPC calls will return an error "docs are disabled".
* `iroh::node::Builder::with_db_and_store` now takes a `DocsStorage` enum instead of a `iroh_docs::store::Store`.

feat(iroh): allow to disable docs engine completely

---

iroh-cli/src/logging.rs

Adds the options to set the directory where logs will be created in the config file.
**Example:**
```toml
[file_logs]
rust_log = "iroh=info"
rotation = "daily"
max_files = 1
dir = "/home/me/my_logs"
```
It is recommended that the path is absolute, otherwise it will be interpreted as relative _to the execution dir_. If this option is not set, the default `<IROH_DATA_DIR>/logs` will be used.
N/a
N/a

feat(iroh): allow setting the logging directory via config file

---

iroh-net/src/magicsock.rs

We've learned that if we return anything other than `Ok` in `poll_send`, we will be blocking the endpoint and ruining all connections. We should not return an error just because we don't have a proper address for the `dest`, instead we should log an error and wait for the connection to timeout. By returning `Poll::Ready(Ok(n))`, we are telling quinn to drop the `n` transmits that are associated with `dest`. When quinn doesn't receive any `ACK`s for those transmits, quinn end the connection with a timeout error.

fix(iroh-net): `poll_send` should drop transmits that we dont have a `dest` for

---

iroh/src/client/blobs.rs
iroh/src/node/rpc.rs

* We `unwrap`ed an `io::Result` in the RPC handler for `BlobsReadAtRequest`. Changed to return an error instead.
* In the blobs client, report the error cases that can occur for reading a blob differently, to help debugging.

fix(iroh): do not panic on blobs IO error

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands/blob.rs
iroh/Cargo.toml
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs

fix(iroh): use two stage accept from quic-rpc to make the accept process cancel-safe
Needs https://github.com/n0-computer/quic-rpc/pull/87

fix(iroh): use two stage accept from quic-rpc

---

iroh-cli/src/commands.rs
iroh-cli/src/commands/doc.rs
iroh-cli/src/commands/node.rs
iroh/src/client/node.rs
iroh/src/client/quic.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs
iroh/src/node/rpc_status.rs

Allows for easier connectivity of RPC, when not having access to the folder, e.g. in a docker setup
- renamed `iroh::client::Iroh::connect` -> `iroh::client::Iroh::connect_path` 
- added `iroh::client::Iroh::connect_addr`
- added `rpc_port` field to `iroh::client::NodeStatus` 
There might be nicer ways, but this works for now

feat(iroh)!: expand ability to connect to RPC

---

iroh/src/node.rs

we currently abort the loop on outer errors (errors from spawn). But we do not look at inner errors (task returns properly but returns an error) at all.
This logs the inner errors as debug! and coninues.
Also checks if the outer error is actually a panic, and continues the loop otherwise.

refactor(iroh): log inner errors

---

Cargo.lock
iroh-blobs/src/downloader/test.rs
iroh-blobs/src/downloader/test/dialer.rs
iroh-blobs/src/downloader/test/getter.rs
iroh-blobs/src/store/bao_file.rs
iroh-cli/src/commands/doctor.rs
iroh-net/Cargo.toml
iroh-net/src/magicsock.rs
iroh-net/src/relay.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client_conn.rs
iroh-net/src/relay/clients.rs
iroh-net/src/relay/codec.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/server.rs
iroh-net/src/relay/iroh_relay.rs
iroh-net/src/relay/metrics.rs
iroh-net/src/relay/server.rs
iroh-test/src/logging.rs
iroh/src/node.rs

Implements the `websocket` protocol upgrade in iroh-relay and changes `iroh-net` clients to connect with `websocket` instead of `iroh derp http`.
State of this is:
- `cargo test -p iroh-net` runs green
- websocket on the relay is supported
- backwards compatibility is tested
- the client also supports connecting using websockets
- (but we're forced to use tungstenites connection establishment, no custom `MaybeTlsStream`.)
- It decides this via the URL scheme (`ws(s)://` vs. `http(s)://`) 
TODO:
- Supports clients connecting to iroh-relay with websockets & running the derp protocol over websocket `Binary` msgs.
- Adds support for the relay answering `Upgrade: websocket` headers instead of `Upgrade: iroh derp http` appropriately.
- Adds support for `ClientBuilder` to dial via websockets, if …

feat(iroh-net): Implement `websocket` protocol upgrade in iroh-relay

---

.github/workflows/ci.yml
.typos.toml
iroh-blobs/src/downloader.rs
iroh-blobs/src/export.rs
iroh-blobs/src/store/bao_file.rs
iroh-blobs/src/store/traits.rs
iroh-dns-server/examples/publish.rs
iroh-dns-server/src/http/doh/extract.rs
iroh-docs/src/engine.rs
iroh-docs/src/store/fs.rs
iroh-gossip/examples/chat.rs
iroh-net/src/bin/iroh-relay.rs
iroh-net/src/discovery.rs
iroh-net/src/discovery/pkarr_publish.rs
iroh-net/src/endpoint.rs
iroh-net/src/lib.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/netcheck/reportgen.rs
iroh-net/src/relay/codec.rs
iroh-net/src/util/chain.rs
iroh/src/node.rs
iroh/src/rpc_protocol.rs

Avoid having typos in the codebase.
Closes #2396
No.

chore: introduce crate-ci/typos

---

iroh/examples/collection-fetch.rs
iroh/examples/hello-world-fetch.rs
iroh/src/client/node.rs
iroh/src/node.rs

Attempt make naming more consistent between iroh-net endpoint, the iroh node, and the iroh client.
- rename iroh::client::Iroh::my_relay to home_relay
- rename iroh::client::Iroh::my_addr to node_addr
- rename iroh::node::Node::my_relay to home_relay

refactor(iroh)!: attempt make naming more consistent

---

iroh/src/client.rs
iroh/src/client/node.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs

Add rpc request to add an addr to an endpoint. Without this it is not possible to write some tests using just the client.
Move all node related fns into a separate "node client" and impl deref for it so the fns remain available on Iroh.
- iroh::client::Iroh: stats only available via deref from iroh::client::node::Client
- iroh::client::Iroh: connections only available via deref from iroh::client::node::Client
- iroh::client::Iroh: connection_info only available via deref from iroh::client::node::Client
- iroh::client::Iroh: status only available via deref from iroh::client::node::Client
- iroh::client::Iroh: node_id only available via deref from iroh::client::node::Client
- iroh::client::Iroh: node_addr only available via deref from iroh::client::node::Client
- iroh::client::Iroh: …

feat(iroh): Add rpc request to add an AddrInfo

---

deny.toml
iroh-cli/src/commands/start.rs

Because of the platforms we support we want to stay with the ring
backend for rustls for now.
https://github.com/n0-computer/iroh/issues/2438 for the flaky test.

chore(ci): Deny aws-lc backend to sneak in

---

iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/server.rs
iroh-net/src/relay/iroh_relay.rs

- Removes `relay_endpoint` config option from `ServerBuilder`
- Makes `iroh-relay` accept both `/derp` and `/relay` as paths for relaying
- Makes `/relay` the default path used in the iroh-net client
TODO:
- `iroh_net::relay::http::ServerBuilder`: Removed `relay_endpoint` function
Closes #2378 
:white_check_mark: Merge this after #2387

refactor(iroh-relay)!: Remove `relay_endpoint` config option & rename `/derp` route to `/relay`

---

.github/workflows/ci.yml

Quoting from #2394 
> Compiling `cross` on CI takes more time compared to pulling the binary directly from a GitHub release.
> We can use [taiki-e/install-action](https://github.com/taiki-e/install-action) to pull the binary directly from the GitHub release. This action supports tagging a specific release or using the latest version.
No.
Closes #2394

chore(ci): use pre-compiled binary on CI

---

iroh/examples/client.rs

Since `iroh/examples/client.rs` is the first example users see, it's likely they will use this file as a starting point for their app skeleton. I find it easier to keep `Doc` in a struct and pass it around rather than using `iroh::client::Iroh`.
I've also added a comment about the `content_bytes()` method, noting its ability to accept either a `Doc` or `client::Iroh`.
Related:
- https://github.com/n0-computer/iroh/blob/17c654e59cc2069522a66b87355f52342b837b8c/iroh-cli/src/commands/doc.rs#L689
- https://github.com/n0-computer/iroh/blob/17c654e59cc2069522a66b87355f52342b837b8c/iroh/tests/sync.rs#L1024
No.

docs: pass `Doc` instead of `Iroh` in example

---

Cargo.lock
iroh-net/Cargo.toml

If there are link-local addresses netdev used to fail to parse those
correctly since they included the interface name.  This resulted in
errors being printed to stderr.  This version fixes this.

deps(iroh-net): bump netdev

---

iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/server.rs
iroh-net/src/relay/iroh_relay.rs

Details in #2442 
- `iroh_net::relay::http::ClientBuilder`: Added `.protocol()` function to the builder for choosing whether to connect to the relay via websockets or not

feat(iroh-net)!: Make relay protocol configurable on `ClientBuilder` instead of defined by the relay url scheme

---

Cargo.lock
iroh-cli/src/commands/doctor.rs
iroh-dns-server/Cargo.toml
iroh-dns-server/examples/convert.rs
iroh-dns-server/examples/publish.rs
iroh-dns-server/src/http/pkarr.rs
iroh-dns-server/src/lib.rs
iroh-dns-server/src/store.rs
iroh-dns-server/src/store/signed_packets.rs
iroh-dns-server/src/util.rs
iroh-net/Cargo.toml
iroh-net/src/discovery.rs
iroh-net/src/discovery/pkarr.rs
iroh-net/src/discovery/pkarr_publish.rs
iroh-net/src/test_utils.rs
iroh/src/node/builder.rs

Tested it, works fine and fixes all my issues.
Closes #2412 and closes #2413 
- *(iroh-net)* `PkarrResolver` adds an alternative discovery mechanism to the existing `DnsResolver`.
- *(iroh-net)* Direct addresses are published when relay mode is set to disabled.
- *(iroh-net)* pkarr_publish module was renamed to pkarr.

feat(iroh-net)!: Add PkarrResolver and publish direct addresses in PkarrPublisher when relay is disabled

---

iroh/README.md
iroh/examples/client.rs
iroh/examples/rpc.rs

You will get this error without passing `--features=examples`.
```bash
🐡 ❯ cargo run --example client
error: target `client` in package `iroh` requires the features: `examples`
Consider enabling them by passing, e.g., `--features="examples"
```
No.
Closes #2431

docs: example requires `example` feature to run

---

.github/pull_request_template.md
CONTRIBUTING.md

It is good for us to follow the common rust documentation style guide,
so explicitly reference this guide.
I'm effectively introducing a new policy here.  Feel free to discuss.

docs: Reference rust doc style guide in contributing guidelines

---

iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs

This removes the flaky marker from a test that I haven't seen being
flaky in a while.
It also tries to put some waiting time in another test to make it less
flaky.

tests(iroh-net): Make some tests less flaky

---

iroh-cli/src/commands.rs

The `--metrics-port disabled` option that works with `iroh start` wasn't respected when running e.g. `iroh --metrics-port disabled node status`.
This caused CLI tests to fail when two or more commands were run concurrently due to port conflicts.
None
1. **Should we mark some tests as non-flaky?**
I think I'll try to run the tests that definitely work through CI a bit
2. **Does this need dedicated tests?**
It's... possible to test that, but technically the tests that were marked as flaky *did* cover this, but they weren't dedicated to the metric port option precisely. Thoughts?
- ~~[ ] Documentation updates following the [style guide](https://rust-lang.github.io/rfcs/1574-more-api-documentation-conventions.html#appendix-a-full-conventions-text), if relevant.~~ None needed really, just a …

fix(cli): Always respect the `--metrics-port disabled` option

---

iroh/src/client.rs
iroh/src/client/blobs.rs
iroh/src/client/gossip.rs
iroh/src/client/node.rs
iroh/src/client/tags.rs
iroh/src/lib.rs
iroh/src/node.rs
iroh/src/node/builder.rs

- Actually export the second stage buider.
- Expand the module level docs for iroh and the various client modules.
None, I am going to do those in a separate PR

docs(iroh): Expand module level documentation in iroh

---

iroh-net/src/util.rs
iroh/src/client/quic.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/rpc.rs

This is a followup to the modularize services PR. I did not want to do it in that one since it was big enough already.
- A `#[must_use]` annotation was added to AbortingJoinHandle
```
Checked [   0.095s] 75 checks; 74 passed, 1 failed, 0 unnecessary
--- failure struct_must_use_added: struct #[must_use] added ---
Description:
A struct is now #[must_use]. Downstream crates that did not use its value will get a compiler lint.
ref: https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute
impl: https://github.com/obi1kenobi/cargo-semver-checks/tree/v0.32.0/src/lints/struct_must_use_added.ron
Failed in:
struct AbortingJoinHandle in /home/runner/work/iroh/iroh/iroh-net/src/util.rs:18
Summary semver requires new minor version: 0 major and 1 minor checks failed
```

refactor(iroh)!: Remove server channel type parameter

---

iroh-dns-server/examples/publish.rs
iroh-dns-server/examples/resolve.rs
iroh-net/src/discovery/pkarr.rs

We switched DNS discovery to a staging server when run with `cfg(test)` but did NOT switch pkarr publish. This means node discovery is not working on main once `cfg(any(test, feature = "test_utils"))` triggers.
This fixes this. It also means that there is no test for this atm (we always run local? which would be good too).
* Renamed `iroh_net::discovery::pkarr::N0_DNS_PKARR_RELAY` to `N0_DNS_PKARR_RELAY_PROD`

fix(iroh-net): use staging URL for pkarr publish in dev mode

---

iroh-cli/src/config.rs
iroh-net/src/defaults.rs

Adds a new relay server to the default production list. `https://aps1-1.relay.iroh.network/` is the address for our newest server, located in Mumbai.
This does not affect any tests, as we do not have a corresponding Asia Pacific staging server, and so an additional server has not been added to our test-only list of default relay servers

feat: add Asia Pacific relay url to the default relay url list in production

---

iroh/examples/custom-protocol.rs
iroh/tests/client.rs

* Changes the `custom-protocol` example to do something a bit more akin to something useful while still being concise
* Add a lot of comments everywhere to really explain what's going on

example(iroh): Improve and document `custom-protocol` example

---

iroh-docs/src/actor.rs
iroh-docs/src/engine.rs

- Add a `flush_store` function to the docs actor/handle
- Use `docs_store.flush_store().await?` before persisting the default author ID file
There's two pieces of data related to the default author:
- The default author ID file
- The actual default author (the secret key) in redb
The code to store these two pieces of data looked like this:
```rust
docs_store.import_author(author).await?;
self.persist(author_id).await?;
```
So it would *look* like we make sure the author is stored before we store the file (which is basically just a reference to the author in the DB).
However, `import_author` is somewhat lazy, because it batches operations together in a bigger transaction.
The store would *actually* only get flushed in e.g. `shutdown`. So most of the time, the actual persisting of the …

fix(iroh-docs): Add `flush_store` and use it to make sure the default author is persisted

---

iroh-cli/tests/cli.rs
iroh-net/src/net/interfaces/bsd.rs

We had some CLI tests that had `#[cfg(feature = "fs-store")]`, but that feature doesn't exist in `iroh-cli`... so they were never compiled (and some related code needed for these tests was deleted. I reintroduced it).
This also fixes what is likely a bug, where `#[cfg(target_arch = "netbsd")]` was used, but there is no "architecture" netbsd. Only an *OS* netbsd.
None
--

fix(iroh-net): unexpected `cfg` condition values / possible fix on netbsd

---

iroh-blobs/src/downloader.rs
iroh-blobs/src/downloader/test/dialer.rs
iroh-gossip/src/net.rs
iroh-net/src/dialer.rs
iroh-net/src/discovery.rs
iroh-net/src/endpoint.rs
iroh/examples/custom-protocol.rs

This updates the documentationfor the dialing and discovery modules.
It also fixes up some signatures to be more consistent with the rest
of iroh-net:
- NodeId is used to identify an iroh-net node that is communicated
with.  PublicKey is only used in contexts where
encryption/decryption happens
- NodeId is Copy and we pass it by value normally.  Not by reference.
Some more changes:
- DialFuture is entirely unused, probably left over from a refactor.
Removed.
- Use pub(super) explicitly, helps clarity of intention as well as
dead-code detection.
The following APIs now take NodeId by value rather than by reference:
- iroh_blobs::downloader::Dialer::is_pending
- iroh_net::dialer::Dialer::abort_dial
- iroh_net::dialer::Dialer::is_pending
- iroh_net::Endpoint::connect_by_node_id
Other changes: …

docs(iroh-net): Update discovery and dialing docs, signatures

---

iroh-gossip/src/dispatcher.rs
iroh/tests/client.rs

This has 2 fixes to the gossip dispatcher:
* When a topic is joined, it can currently happen that the first few events on the newly joined topic are missed, because the events can start to arrive at the dispatcher's global subscription before the dispatcher's join task finished and changed the protocol state. If this happens, we now change the topic state to live before processing the incoming event. This should make the existing smoke test non-flaky.
* Currently a topic subscription is quitted when either the command stream (from client to gossip) or the event stream (from gossip to client) is dropped. Now we only quit the subscription if both the command and the event channels are dropped. This should fix the test in iroh-ffi.

fix(iroh-gossip): gossip dispatcher: reliable events on join, allow dropping sinks or streams

---

iroh-net/src/lib.rs
iroh/tests/client.rs

Also make it non-monospace as it is not a crate
name or source code identifier.

docs(iroh-net): fix broken HTTP/3 link

---

iroh-net/src/relay/http/client.rs

Split out from #2419 
Splitting this out means we can deploy the relay changes one release in advance to the changes in the client.
Otherwise, we'd need to update the relays ASAP when we release 0.20, as clients will expect to be able to connect to the `/relay` route (which may not be deployed immediately after the release).
- Switches the client to connect to `/relay` instead of `/derp`.
None
Also a PR related to #2378 
I allowed myself to add in another `derive_more::Debug` instance instead of a custom, outdated `impl Debug`, if that's okay with you :grin:

refactor(iroh-net): Switch to new iroh-relay route `/relay` instead of `/derp`

---

Cargo.lock

GitHub Actions `cargo deny` is failing at https://github.com/n0-computer/iroh/actions/runs/9928231752/job/27438879671
% `cargo update -p bytes`
```
Updating crates.io index
Locking 1 package to latest compatible version
Updating bytes v1.6.0 -> v1.6.1
note: pass `--verbose` to see 152 unchanged dependencies behind latest
```
https://github.com/tokio-rs/bytes/blob/master/CHANGELOG.md to get the fix in
* tokio-rs/bytes#718

deps(bytes): bytes v1.6.0 was yanked so upgrade to bytes v1.6.1

---

iroh-net/README.md
iroh-net/src/disco.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/relay/http/client.rs

The aim here is to make users' reports about holepunching problems
actionable.  For this it creates a curated set of events.  This is
much more efficient than trawling through the entire logfile.
The events are emitted for logical reasons.  This means they might not
be emitted in a place where they are guaranteed to have happened, but
rather are emitted where it logically makes sense and all the information
is available.  This is fine since they are not meant to debug the code
itself.  E.g. after a `call-me-maybe.sent` event has been emitted the
packet could still be dropped in the queue of the relay client.  From
the event point of view this is fine, the event happened but the peer
may not have seen the result of this event, which will be visible in the
peer's own events.
Events have all …

feat(iroh-net): Add holepunching events

---

iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/endpoint.rs

It did not explain the return type sufficiently.
None
Fixes #2488.
See #2505 for the flaky test.

docs(iroh-net): Improve Endpoint::accept docs

---

.github/workflows/flaky.yaml
.github/workflows/tests.yaml
iroh-cli/tests/cli.rs

Modifies the `flaky` workflow to generate a report with all the tests that failed per matrix combo, so that we can receive it on discord. This requires to modify the `tests` workflow as well to generate `libtest` json reports.
Reports are uploaded as job artifacts with an unique name, and retained for a day.
From my last commit at the time of writing, this is the report we get:
```md
Flaky tests failure:
- **ubuntu-latest all stable**
iroh-net::iroh_net::discovery::local_swarm_discovery::tests::test_local_swarm_discovery
ubuntu-latest default stable
iroh-cli::cli::cli_bao_store_migration
- **windows-latest all stable**
iroh-cli::cli::cli_provide_file_resume
iroh-cli::cli::cli_provide_tree_resume
- **windows-latest default stable**
iroh-cli::cli::cli_provide_file_resume …
```

ci: add a flaky tests failure report to our discord notification

---

iroh-metrics/src/service.rs

When a bind fails you get a generic error that is hard to track down
for users.  Adding the bind address to the error will help a lot.
none
Fixes #2507.

fix(iroh-metrics): Add the bind addr in errors for bind failures

---

iroh-cli/tests/cli.rs

We didn't get good logs on the `cli_bao_store_migration` test so far. Here's what it's output was in a failure case:
```
--- STDOUT:              iroh-cli::cli cli_bao_store_migration ---
running 1 test
|Iroh is running
|Node ID: cnzuojj4sbo2ulpqoo2riyrdsn2j4pnp3b5bgrjubsft72nutlca
iroh started up.
test cli_bao_store_migration ... FAILED
failures:
failures:
cli_bao_store_migration
test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 12 filtered out; finished in 2.71s
--- STDERR:              iroh-cli::cli cli_bao_store_migration ---
thread 'cli_bao_store_migration' panicked at iroh-cli/tests/cli.rs:394:5:
assertion `left == right` failed
left: ""
right: "4yny3v7anmzzsajv2amm3nxpqd2owfw4dqnjwq6anv7nj2djmt2q (0 B)\n"
```
This was only capturing stdout from one of the four iroh …

test(iroh-cli): Improve `bao_store_migration` test logging

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/relay.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/server.rs

We had an `iroh-relay` cfg flag, but it was unused.
Enabling it is useful for working towards building iroh-net for Wasm (we won't be able to compile the server bits to Wasm, sorry :stuck_out_tongue:  )
This moves the `axum` and `tokio-rustls-acme` dependencies behind that feature flag as well as the modules `iroh_net::relay::http::server` and `iroh_net::relay::iroh_relay`.
I also had to move the `relay::http::server::Protocol` one module up.
- iroh-relay *implementation*-specific features are now behind an `iroh-relay` feature flag in iroh-net.
LMK!
- ~~[ ] Tests if relevant.~~ I ran `cargo test -p …

refactor(iroh-net)!: Move relay implemention in `iroh-net` behind `iroh-relay` cfg flag

---

.github/dependabot.yml

Fixes software supply chain safety warnings like at the bottom right of
https://github.com/n0-computer/iroh/actions/runs/9869350246
* [Keeping your actions up to date with Dependabot](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot)
* [Configuration options for the dependabot.yml file - package-ecosystem](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem)

ci: keep GitHub Actions up to date with GitHub's Dependabot

---

iroh-net/src/bin/iroh-relay.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/metrics.rs

The name "endpoint" is overloaded and we decided a while ago to not
use it for things other than `iroh_net::Endpoint`.  This further
renames more places that were called endpoint with the new name we
already introduced for them: direct address.  The direct address
naming is already used consistently on public APIs, this is only for
internal consistency.
metric changed: `magicsock::metrics::Metrics::update_endpoints` -> `Metrics::update_direct_addrs`.

refactor(iroh-net): More renaming of endpoint to direct address

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh/tests/sync.rs

When we had any direct addresses but not yet a best address we would
randomly try to pick one and send to it on the off chance it worked.
This required to always pick the same direct addr to send to which was
not happening and a bug.
However the scenarios in which this would speed up holepunching were
very unlikely: only really if a single direct addr known to work was
added manually would this improve things.
Simply removing this feature is rather nice:
- The direct connection still happens very quickly in the best-case
scenario: a single ping-pong roundtrip is all it costs.  No relay
server or discovery mechanism needed so no functionality change.
- In all other scenarios there is no change.  Connection establishment
behaves exactly the same as before.
- There are no more confusing …

refactor(iroh-net): remove random choice of direct addr

---

iroh/src/client.rs
iroh/src/lib.rs

Remove type aliases for the mem and quic node types that are no longer necessary due to boxing of the rpc channel.
Also document reexports
- iroh: remove client::MemIroh
- iroh: remove client::QuicIroh
- iroh: remove client::MemDoc
- iroh: remove client::QuicDoc

deprecation(iroh)!: remove deprecated type aliases

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh-cli/src/commands/doctor.rs
iroh-cli/src/commands/start.rs
iroh-cli/src/config.rs
iroh-metrics/Cargo.toml
iroh-metrics/src/core.rs
iroh-metrics/src/lib.rs
iroh-metrics/src/metrics.rs
iroh-metrics/src/service.rs
iroh-net/src/relay/metrics.rs
iroh-net/src/relay/server.rs

Extends several pieces:
- introduces a "metric dumper" which is just a way of saying you can sample the internal metrics and write them to a CSV file (which should come in handy for 3 pieces that should come down the line; 1) CI using these to validate behavior, 2) debug dumps from 3rd parties, 3) local debugging)
- along with the dumper the `doctor plot` has been extended to be able to read those dumps and also just generally improved some rough edges so it's less error prone.
- node counts are here for relays. You now have a derived metric which simply counts unique daily node connections.
Sample usage for the metrics dumper:
`cargo run --bin iroh --all-features -- --metrics-dump-path test.metrics.csv start`
Sample of the plotter:
`cargo run --bin iroh --all-features -- doctor plot …

feat: metrics dumps & extended metrics

---

Cargo.lock
iroh-blobs/Cargo.toml
iroh-blobs/src/downloader.rs
iroh-blobs/src/lib.rs
iroh-blobs/src/metrics.rs
iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh-cli/src/commands/doctor.rs
iroh-cli/src/commands/start.rs
iroh-cli/src/config.rs
iroh-dns-server/src/metrics.rs
iroh-docs/Cargo.toml
iroh-docs/src/actor.rs
iroh-docs/src/engine/gossip.rs
iroh-docs/src/engine/live.rs
iroh-docs/src/lib.rs
iroh-docs/src/metrics.rs
iroh-gossip/src/metrics.rs
iroh-gossip/src/net.rs
iroh-metrics/Cargo.toml
iroh-metrics/src/core.rs
iroh-metrics/src/lib.rs
iroh-metrics/src/metrics.rs
iroh-metrics/src/service.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/metrics.rs
iroh-net/src/netcheck/metrics.rs
iroh-net/src/relay/metrics.rs
iroh-net/src/relay/server.rs
iroh/src/metrics.rs

- Cleans up stale counters
- Introduces unique daily node counts on relays
- Introduces a metrics dumper so we can create dumps of metrics and also view them in doctor plot
- Introduces new trace level counters
- Introduces `metrics_dump_path` on the top level CLI parameters, which if set will make sure metrics are collected at regular intervals and written to the provided path in CSV format.

refactor!: metrics

---

.github/workflows/docker.yaml
.github/workflows/release.yml

This will allow us to trigger manual builds (we can re-build old releases) and should fix the issue moving forward with building the docker images. 
The original failure in https://github.com/n0-computer/iroh/actions/runs/10046498425/job/27766736564 was due to the fact that the `needs` variables are not propagated down the graph but only seem to be directly passed from parent to child.

fix: docker image builds

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/udp_conn.rs
iroh-net/src/net/netmon/actor.rs
iroh-net/src/net/netmon/android.rs
iroh-net/src/net/netmon/bsd.rs
iroh-net/src/net/netmon/linux.rs
iroh-net/src/net/netmon/windows.rs

refactor(iroh-net): replace flume in iroh-net with async_channel
Rationale: see https://github.com/n0-computer/iroh/pull/2536
This is the first in a series of PRs that will replace flume with async_channel. In this case it is very close to a drop in replacement without any need for changes.
Only noteable changes:
send_async becomes send
send becomes send_blocking
Receiver implements Stream, so no need for .into_stream()
Receiver is not Unpin, so to make it unpin you need to do `Box::pin(recv)` or use `.boxed()`
None
- Anything specific from flume we were relying on here?

refactor(iroh-net): replace flume in iroh-net with async_channel

---

Cargo.lock
iroh-gossip/Cargo.toml
iroh-gossip/src/dispatcher.rs

refactor(iroh): Remove flume from iroh gossip
Yes, I know there is a PR that touches gossip. But just let me do my purge.
None
None

refactor(iroh): Remove flume from iroh gossip

---

iroh-base/src/ticket.rs
iroh-blobs/src/get/db.rs
iroh-blobs/src/protocol.rs
iroh-blobs/src/store/fs.rs
iroh-docs/src/lib.rs
iroh-docs/src/ranger.rs
iroh-gossip/src/proto/hyparview.rs
iroh-gossip/src/proto/plumtree.rs
iroh-net/src/endpoint.rs
iroh-net/src/relay/client_conn.rs
iroh-net/src/relay/codec.rs

Fixes clippy warnings:
- [needless borrows for generic args](https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args)
- [md lazy continuation](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation)
which simply means clippy wants us to use consistent indentation for lists so
that it can be sure how to format docs.
n/a
n/a

chore: fix clippy warnings

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands.rs
iroh-cli/src/commands/start.rs
iroh-cli/src/config.rs
iroh-cli/src/logging.rs
iroh-net/src/relay/map.rs
iroh/src/node/builder.rs

The configuration file behaviour is improved:
- Unknown fields will now cause an error rather than be silently ignored.
- Make it possible to express GcPolicy in the TOML config file.  This
was not possible before.  It was possible to disable it before, but
it was disabled by default so that was rather moot.
The --help output is improved:
- Update header of iroh.
- Directly point to config file docs.
- Use consistent style.
- Unknown fields in the configuration file will now cause an error.
- Configuring the GC Policy in the configuration file has changed.

fix(iroh-cli)!: Improve cli and configuration file

---

.github/workflows/docs.yaml

Added a `docs.yaml` workflow that makes the github action bot reply to PRs with a link to built docs to your PRs.
It only does so once, and then just updates the comment (although actually it doesn't necessarily need to, the link is always the same, but it's still nice in case someone changes the workflow).
This is using the nightly toolchain, because we're using [`#[feature(doc_cfg)]`](https://doc.rust-lang.org/unstable-book/language-features/doc-cfg.html).
I personally wanted this. Every now and then we get a PR with the description saying "the best way to review this is to start by looking at the generated docs". But then I need to checkout the PR, build the docs and open them. Having a link directly to the docs would be *amazing* IMO.
I *also* think that having easy access to docs on …

ci: Generate docs for each PR

---

iroh-cli/src/config.rs
iroh-net/src/endpoint.rs
iroh-net/src/relay/map.rs

While I'm not a huge fan of this piece of code, I don't really see much of an alternative as we want to be able to force the override to use staging relays even in "prod" environments or when it's deeply integrated such as the FFI library cases. 
This should allow us to override the default relay maps for all of our CI setups in all of our repos.

feat: override to staging relays

---

iroh/src/client.rs
iroh/src/client/authors.rs
iroh/src/client/blobs.rs
iroh/src/client/docs.rs
iroh/src/client/gossip.rs
iroh/src/client/node.rs
iroh/src/client/quic.rs
iroh/src/client/tags.rs
iroh/src/lib.rs

- More pointers between individual modules to help people understand how they go from `A` to `B` (e.g. `Node` -> `Iroh`, `Iroh` -> `blobs::Client`, etc.)
- Documentation on how to initialize `client::Iroh`
- Generally make methods adhere to our documentation style.
- Expose the type alias `iroh::client::RpcClient`, so it doesn't show up as `RpcClient<RpcService, Connection<RpcService>>` everywhere it's used in the docs.
None, but noteworthy:
- Expose the type alias `iroh::client::RpcClient`.

feat(iroh): Improve documentation and canonicalize docs in `iroh::client`

---

.github/workflows/docs.yaml

We disable docs previews on forks because otherwise external contributors cant get a ✅  on CI. The reason for it being is that those forks don't get write permissions to the branch where docs are hosted and the alternative would be to manually juggle a lot of tokens for each user.

fix: disable docs preview on forks

---

iroh-cli/tests/cli.rs

I have not seen these tests fail for at least the past two weeks. I think they might no longer be flaky. I suspect much of the flakiness came from quinn's logging errors on shutdown, which no longer happens.
n/a
n/a

tests(iroh-cli): remove flaky mark from 5 tests and improve logs

---

iroh-cli/tests/cli.rs
iroh-net/src/netcheck.rs
iroh-net/src/netcheck/reportgen.rs

In windows there is no way to copy a file being accessed by another process in an accessible way. This is what makes this test fail since it attempt to copy the blobs.db folder a couple of times while the iroh instance that handles is running.
The change is simple: shutdown the provider, copy the files, re-start the provider. From my perspective, this does not affect what the test is attempting to assert.
Now, since this includes re-starting the iroh instance that provides the files several times, and we match on output, sometimes we can get weird logs related to shutdown. One of those (and the only one I have seen so far) is for a netcheck report and didn't finish on time. Instead of logging this in the reportgen actor, the error is bubbled up to be handled by the netcheck actor (which …

test(iroh-cli): reduce flakyness of cli_provide_file_resume

---

iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client_conn.rs
iroh-net/src/relay/clients.rs
iroh-net/src/relay/codec.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/http/client.rs
iroh-net/src/relay/http/server.rs
iroh-net/src/relay/iroh_relay.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/types.rs

This moves more relay server code behind the `iroh-relay` feature flag.
This is a continuation of #2516 
Unfortunately I didn't quite catch "all server things".
I'm fairly confident I do have all covered now, because this is extracted from a branch where server-side code wouldn't compile (to Wasm).
Also:
- Makes use of `MaybeTlsStream` instead of the `MaybeTlsStreamServer` alias. Using the original definition instead of the alias confuses rust-analyzer a lot less. And the aliasing back-and-forth was silly.
None

refactor(iroh-net): Move more server code behind `iroh-relay` feature flag

---

iroh-blobs/src/util/local_pool.rs
iroh/tests/client.rs

There's this test that was introduced in [the `local_pool` PR](https://github.com/n0-computer/iroh/pull/2517).
It was ignored via `#[ignore = "todo"]`. Notably, it's *not flaky*, it always fails.
Our flaky tests are run with `cargo nextest run --run-ignored all [...]`. We can't be more specific with the `ignore`d tests. The only options are `default`, `ignored-only` and `all`.
This kind of test is really hard to write. IIUC, `#[should_panic]` can only test for the panic happening in the thread that the test is initiated in, it doesn't detect panics that are thrown in threads spawned from the test. I assume this is the reason writing this test was abandoned.
Keeping this test with the `#[ignore = "todo"]` on it means we're always running it in our flaky test suite, which is confusing. We …

test(iroh-blobs): comment out ignored test (that is not a flaky test)

---

iroh-cli/src/commands.rs
iroh-cli/src/commands/rpc.rs

#2537 mentions someone not finding the configuration options after running `iroh start --help`. `iroh --help` already mentions both <https://iroh.computer/docs> in the second line and <https://iroh.computer/docs/reference/config> in the config flag (this one
being fairly recent addition to the help text). I'd say the only thing missing here is to be able to see the docs from the subcommands, which is what this pr does.
n/a
n/a

docs(iroh-cli): point to the configuration refernce from each iroh subcommand

---

Cargo.lock
iroh-docs/src/store/fs/tables.rs
iroh-net/src/endpoint.rs

The `#[derive(Debug)]` used to generate an impl like this:
```rust
#[automatically_derived]
impl<'a> ::core::fmt::Debug for Accept<'a>
where
quinn::Accept<'a>: ::core::fmt::Debug,
Endpoint: ::core::fmt::Debug,
{
// ...
}
```
But `quinn::Accept` doesn't implement `Debug`.
None
I'm... Really stumped on what changed in `derive_more`. When I expand the macro, in both versions there's a `Debug` bound on `quinn::Accept`, which just can't be right... Anyhow.

fix(iroh-net): Fix a compiler error with newer `derive_more` versions

---

iroh-net/src/magicsock/node_map/best_addr.rs
iroh-net/src/magicsock/node_map/node_state.rs

This moves metrics for when switches between direct connections and
relayed connections to the NodeState.  This is after all where this
decision is made.  BestAddr only knows about the best UDP address, it
has no business keeping track of relays.
Cleaning this up enables further refactoring of BestAddr and PathState
which need to improve because they depend on each other, but are
hindered by the relay state sneaking into there.
None
These metrics ignore the fact that we have mixed as a possibility so
over-simplify the situation.  This makes the logic to increment them
complex, which in turn makes it no one will really know what they
mean.
I need this to move on with #2546 so don't really want to get into
designing our metrics though.  I believe this way the keep the same
behaviour.

ref(iroh-net): Remove need for relay info in best_addr

---

iroh-base/Cargo.toml
iroh-blobs/Cargo.toml
iroh-cli/Cargo.toml
iroh-dns-server/Cargo.toml
iroh-docs/Cargo.toml
iroh-gossip/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

To avoid sudden breakages in new releases, pin `deriver_more` to a specific `beta`

fix: pin derive_more to avoid sudden breakages

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/magicsock/node_map/udp_paths.rs

In #2509 (c1c3539c0a07d8659979ffacdb5bd1fc23d6939c) we removed chosing
a random unconfirmed direct address and through both it and the relay
if we did not yet have any confirmed direct address.  This required
any direct address passed in via a NodeAddr to do a DISCO Ping-Pong
round trip before it would be used.
It turns out this is used a lot in the sense that a common socket
address is used: when you know an IP is reachable.  Requiring a ping
would mean the first QUIC packets would be dropped, Quinn would wait
to detect this before retrying and connections are delayed by an
observable second by the end of it all.  Not great for this scenario,
even if it can be argued that outside of tests this is not a common
scenario.
So this brings back the random selection of unconfirmed addresses.
It …

fix(iroh-net): Make a single direct address in NodeAddr instant

---

iroh-blobs/src/downloader.rs
iroh-blobs/src/downloader/get.rs
iroh-blobs/src/downloader/invariants.rs
iroh-blobs/src/downloader/progress.rs
iroh-blobs/src/downloader/test.rs
iroh-blobs/src/downloader/test/dialer.rs
iroh-blobs/src/downloader/test/getter.rs
iroh-blobs/src/get/db.rs
iroh-net/src/dialer.rs
iroh/src/client/blobs.rs
iroh/src/node/rpc.rs

Two changes to the downloader:
* Never try to download from ourselves. If the only provider node added is our own node, fail with error "no providers".
* The actual download request flow is turned into a generator (while keeping API compatibility for the existing `get_to_db` public function). A new `get_to_db_in_steps` function either runs to completion if the requested data is fully available locally, or yields a `NeedsConn` struct at the point where it needs a network connection to proceed. The `NeedsConn` has an `async proceed(self, conn: Connection)`, which must be called with a connection for the actual download to start.
This two-step process allows the downloader to check if we should dial nodes at all, or are already done without doing anything, while emitting the exact same flow …

fix(iroh-blobs): do not hit the network when downloading blobs which are complete

---

Cargo.lock
iroh/Cargo.toml
iroh/src/client/node.rs

Happy Docs Day! Added documentation to the `iroh::node::Client`, including examples.

docs(iroh): add documentations and examples for the `iroh::node::Client`

---

iroh/src/node/builder.rs

This removes the max streams in the builder.  This makes little sense
when users are allowed to create their custom protocol.
right now both uni and bidirectional streams default to 100 max, which
is reasonable for now.  We should allow fully customising the
TransportConfig later.
I don't think this counts as a breaking change.  If we want to lower
one of these later it would be, but we're probably fine with 100 by
default?
See #2592

fix(iroh): Do not set low max streams in builder

---

iroh-willow/src/auth.rs
iroh-willow/src/engine.rs
iroh-willow/src/engine/actor.rs
iroh-willow/src/engine/peer_manager.rs
iroh-willow/src/lib.rs
iroh-willow/src/net.rs
iroh-willow/src/proto/sync.rs
iroh-willow/src/session.rs
iroh-willow/src/session/data.rs
iroh-willow/src/session/error.rs
iroh-willow/src/session/intents.rs
iroh-willow/src/session/reconciler.rs
iroh-willow/src/session/run.rs
iroh-willow/src/util/channel.rs
iroh-willow/src/util/stream.rs
iroh-willow/tests/basic.rs

Major refactor of `net` and `peer_manager` modules to enable the following:
* Properly terminate connections gracefully 
* Properly deal with simultaenous connections by only using one of them deterministically
* Do not drop intents if the session is about to be closed when submitting a new intent 
Plus other fixes and cleanups.

[wip] feat(iroh-willow): refactor peer manager to properly close connections and drop duplicates

---

iroh-blobs/src/store/fs/import_flat_store.rs
iroh-cli/tests/cli.rs

When a blob found during migration is missing an outboard, according to the
`cli_bao_store_migration` test, we should still migrate it. Before this change
the blob would be ignored. This makes the test no longer broken.
n/a
1. I can reproduce the failure 100% of the time, so before this change **I consider the test broken, not flaky.**
2. I reproduced the failure by running an iroh node with the exact v0 data the test uses. After the change, I did this again, and also ran both `validate` and `consistency-check` and got no errors.

fix(iroh-blobs): do not skip empty partial blobs in migration

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/discovery/local_swarm_discovery.rs

The new `swarm-discovery` api allows you to remove and add addresses you want to publish, without needing to restart the swarm-discovery service.
There is a chance that this process (restarting the swarm-discovery service) caused flaky-ness in our `test_local_swarm_discovery` test.

feat(iroh-net): upgrade to new `swarm-discovery` api

---

iroh-cli/tests/cli.rs

The `cli_provide_one_file_large` test takes multiple minutes to complete.
We talked about removing it altogether in the discord.
The reasoning for removing it is that we already exercise big file provide & get loops via netsim. So there is no need to run the same code in debug mode taking >3 minutes in CI.
However, I ended up not removing the test but instead changing it, because the other tests test really small file sizes, e.g. `1000` bytes. At those sizes, outboards aren't even generated and files are put inline into the database.
So instead I worked out the file size required for exercising the whole external-outboard (and external-file) machinery of iroh-blobs.
The cutoff point is at ~4.1MB, which is really far away from the 1GB size and should transfer within seconds.
None
Should we …

test(iroh-cli): Replace `cli_provide_one_file_large` with a faster test

---

iroh-net/src/discovery/dns.rs
iroh-net/src/discovery/pkarr.rs
iroh-net/src/relay/map.rs
iroh-net/src/test_utils.rs
iroh/src/node/builder.rs

Because the Node builder by default configures DNS discovery the tests
all do a lookup.  This went to the staging DNS server, but even so, we
hit 429 Too Many Requests on this sometimes.
Instead this configures a domain under `.test.`.  This domain is
reserved for tests and any DNS server should return an emtpy response
without going through upstream DNS servers - unless the records were
directly added to the DNS server receiving the query in which case it
will respond.
So now all our default DNS discovery just doesn't discover anything,
which is fine as all tests have other mechanisms to find the nodes.
The tests that do use DNS discovery run their own local DNS server for
this, which is also switched to `.test.`, because that's the right
domain to use for this.
When using …

fix(tests): For DNS discovery only use a local DNS server

---

iroh/tests/sync.rs

The test currently runs 55s on our windows CI machines, it runs 40s when I run it on my laptop locally.
If anyone is curious: In release mode, the test runs 0.4s. :upside_down_face: 
The test basically sync 1000 entries twice. The number is configurable and the default was arbitrarily chosen according to @Frando, so I've reduced it by a factor of 10. With `n_entries = 100` the test runs ~4.5s for me, much more reasonable.
None

test(iroh): Reduce entry amount in `sync_gossip_bulk`

---

iroh-gossip/src/net.rs
iroh-gossip/src/net/handles.rs

Improves documentation around the `GossipEvent::Joined` event: It is only emitted once at the beginning of the stream, and the event will not be emitted when awaiting `GossipReceiver::joined`.
Also makes sure that the event is actually only emitted once per intent (it potentially could have been emitted multiple times before if the neighbor count first got down to 0 and then up again for `GossipTopics` subscribing inbetween).
Inspired by the discussion in https://github.com/deltachat/deltachat-core-rust/pull/5860

fix(iroh-gossip): clarify docs and semantics of gossip joined event

---

iroh-cli/src/commands/blobs.rs

Aligns the help text for `blobs list incomplete-blobs` with the docs in iroh.computer.
n/a
n/a

docs(iroh-cli): fix help text for incomplete blobs

---

Cargo.lock
iroh-willow/Cargo.toml
iroh-willow/src/engine/peer_manager.rs
iroh-willow/src/net.rs
iroh-willow/tests/basic.rs

It appeared to me that we can very much simplify the graceful connection termination logic. We do not need the information which peer started the termination. We can simply ..
* send a goodbye byte
* wait until we either a) receive the goodbye byte, or b) the peer closes the connection with our  graceful error code
* only now close the connection with the graceful error code
On both sides, we only close  the connection after either receiving the goodbye byte or a graceful connection termination. This makes sure that neither peer ever closes the connection gracefully prematurely.

fix(iroh-willow): simplify graceful connection termination

---

.config/nextest.toml
.github/workflows/tests.yaml
iroh-net/src/discovery/local_swarm_discovery.rs

After a lot of debugging we realized the integrations tests (`gc` tests, for
example) run with swarm discovery on since they are not technically using test
iroh, so they bypass the cfg that prevents it from being turned on. This causes
the `test_local_swarm_discovery` test to be flooded with nodes from other
tests, making it flaky. Isolating the test should make it no longer flaky
anymore
n/a
We should still create a test that creates a bunch of nodes and makes sure they
all can find each other within reasonable time. There is still reason to
believe swarm discovery is slow, particularly in linux, but we should address
it in a test under our countrol, not via the non-deterministic nature of
concurrent tests in ci.

chore(ci): use nextests groups to isolate some tests

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/udp_conn.rs
iroh-net/src/net/netmon/actor.rs
iroh-net/src/net/netmon/android.rs
iroh-net/src/net/netmon/bsd.rs
iroh-net/src/net/netmon/linux.rs
iroh-net/src/net/netmon/windows.rs
iroh-net/src/util.rs

Removes async-channel from iroh-net and replaces it with the tokio mpsc channel.
This is a mergeable version of https://github.com/n0-computer/iroh/pull/2614
LocalSwarmDiscovery is no longer UnwindSafe
Open question: I am using blocking_send from inside the windows RouteMonitor. This depends on that the callback thread is not a tokio thread. I have no idea if this is a reasonable assumption to make. Otherwise we would have to bring back the runtime check condition or just capture a runtime handle and spawn a task.
Note: what even is this? The only message there is is NetworkMessage::Change, and there is no timestamp or anything. So could I just use try_send? If the queue is full, there is already a Change in it, so it is as good as the new one...

refactor(iroh-net)!: remove async channel

---

.config/nextest.toml
.github/workflows/flaky.yaml
iroh-net/src/discovery/local_swarm_discovery.rs

In pro of being a bit more positive, this PR makes the notify action tell us when there were no ci failures as well.
n/a
Also increases the required threads for the isolation tests

feat(ci): notify discord of successfull flaky runs

---

iroh-blobs/src/store/fs.rs
iroh-blobs/src/store/fs/tests.rs
iroh-blobs/src/store/fs/util.rs
iroh-blobs/src/store/mem.rs
iroh-blobs/src/store/mutable_mem_storage.rs
iroh-blobs/src/util.rs

Add outboard creation progress to the mem store
just move compute_outboard from fs to util and use it from both fs and mem.
None, hopefully

feat(iroh-blobs): Add outboard creation progress to the mem store

---

.github/workflows/flaky.yaml

in #2623 the condition for `notify` is not being cancelled, but a job can also be skipped. This is the output when a PR is not even running the tests. So, we get a good report in cases where there was no output. This fixes that issue
n/a
n/a

fix(ci): report flaky outupt only on success and failure

---

iroh-blobs/src/store/fs.rs
iroh/src/node/builder.rs

In vein of promoting doing things TheRightWay™, this PR deprecates flat stores for their removal in a later iroh version. This is probably a low stakes deprecation and removal but imo gets us in the flow of being kind(er) with our users. Issue #2630 is created as a reminder to remove this.
- `iroh_blobs::store::fs::Store::import_flat_store` is deprecated. Ensure all data is migrated before future versions, which won't support this.
- `iroh_blobs::store::fs::FlatStorePaths` is deprecated. Ensure all data is migrated before future versions, which won't support this.
- `iroh`: Flat stores are deprecated. Ensure all data is migrated before future versions, which won't support this.
n/a

refactor(iroh-blobs, iroh)!: deprecate flat stores

---

iroh-net/Cargo.toml
iroh-net/src/discovery.rs
iroh/Cargo.toml
iroh/examples/local_swarm_discovery.rs

All feature names should be named with `-`.
- `iroh-net/local_swarm_discovery` -> `iroh-net/local-swarm-discovery`
- `iroh/local_swarm_discovery` -> `iroh/local-swarm-discovery`

refactor: normalize feature names

---

.github/workflows/ci.yml

cargo-ndk has [known issues](https://github.com/bbqsrc/cargo-ndk/issues/137) with workspace setups for versions 3.5.5 and up.
Ensuring docker test runs start with a fresh docker setup.

ci: fix deps issues

---

iroh-cli/src/commands/node.rs
iroh-net/src/endpoint.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh/src/client/node.rs
iroh/src/node.rs
iroh/src/node/rpc.rs

This renames remote_infos_iter to remote_info_iter.  This returns an
iterator of remote_info items.  Using plural for "info" adds a double
plural together with "iter", creating something of a pleonasm.
None right now, this is unreleased.
But `Endpoint::remote_infos_iter` -> `Endpoint::remote_info_iter` from
previous breaking changes.

refactor(iroh-net,iroh)!: rename to remote_info_iter, fixup some docs

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands/doctor.rs
iroh-net/src/discovery/pkarr/dht.rs

The pkarr dht publisher has two delays, the initial delay and the republish delay. These were constants so far, but now are configurable in the builder.
This allows us to set the delay to 0s in the dht_discovery_smoke test.
None
Will this fix the flakiness?

feat(iroh-net): allow customizing republish delay for the pkarr publisher

---

iroh-net/Cargo.toml
iroh-net/src/discovery.rs
iroh/Cargo.toml
iroh/examples/local_swarm_discovery.rs

Rename the local-swarm-discovery feature to discovery-local-network to be consistent with discovery-pkarr-dht
renames the `local-swarm-discovery` feature flag in iroh-net to `discovery-local-network`
Naming is hard. Pretty sure the ff should start with `discovery-`, but should it be `discovery-local-network` or `discovery-local-swarm` or just -local...?

refactor(iroh-net)!: Rename the local-swarm-discovery feature to discovery-local-network

---

.github/workflows/ci.yml
iroh-cli/src/commands.rs
iroh-cli/src/commands/blobs.rs
iroh-cli/src/commands/net.rs
iroh-cli/src/commands/rpc.rs
iroh-cli/tests/cli.rs
iroh/examples/collection-fetch.rs
iroh/examples/hello-world-fetch.rs
iroh/examples/rpc.rs
iroh/src/client.rs
iroh/src/client/blobs.rs
iroh/src/client/net.rs
iroh/src/lib.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol.rs
iroh/src/rpc_protocol/net.rs
iroh/src/rpc_protocol/node.rs
iroh/tests/client.rs

Converts the `node` module to the `net` module (`iroh` and `iroh-cli`)
Closes #2639
- No more `deref` of `iroh::net::Client` to `iroh::client::node::Node`
- `iroh::client::node` -> `iroh::client::net`
- `iroh::client::node::Node::shutdown` -> `iroh::client::Client::shutdown`

refactor(iroh)!: convert node to net module

---

iroh-net/src/defaults.rs
iroh-net/src/magicsock.rs
iroh-net/src/netcheck/reportgen.rs
iroh-net/src/netcheck/reportgen/hairpin.rs
iroh-net/src/ping.rs
iroh-net/src/portmapper/nat_pmp.rs
iroh-net/src/portmapper/pcp.rs
iroh-net/src/portmapper/upnp.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client/conn.rs
iroh-net/src/relay/server/actor.rs

Co-locates all timeout defaults that have to do with making connections or running netcheck.
closes #2602
I nested some of the timeouts in another module (specifically the ones pertaining to the relay) but I could do this more for other sections, ie, the portmapper timeouts could be nested in a `portmapper` module.

refactor(iroh-net): move all timeouts into one file

---

iroh-blobs/src/lib.rs
iroh-blobs/src/provider.rs
iroh-gossip/src/lib.rs
iroh/src/client/blobs.rs
iroh/src/client/blobs/batch.rs
iroh/tests/sync.rs

Extend iroh-blobs docs a bit
- There are some fn name changes, but they are for unpublished fns.
- transfer_collection has been removed. It was very lowlevel and used in none of the examples, so I doubt anybody was using it outside.

refactor(iroh-blobs)!: expand docs

---

iroh-cli/tests/cli.rs

`iroh node status` changed to `iroh status` after https://github.com/n0-computer/iroh/pull/2642
The `cli_provide_addresses` command wasn't set up correctly for that.

fix(iroh-cli): `cli_provide_addresses` to use the correct `iroh status` command

---

iroh-net/src/endpoint.rs
iroh-net/src/tls.rs

Also log the fact this is enabled on WARN level.  This is pretty
important to notice.
none

fix(iroh-net): Document the keylog environment variable correctly

---

.github/workflows/ci.yml
.github/workflows/docker.yaml
.github/workflows/release.yml
Cargo.toml
docker/Dockerfile.ci

- We now build the docker test CI jobs in a way that more closely resembles the release process. It should compile the binaries and build the image significantly faster now. (down from 8+ min to 2 min)
- Secrets are properly passed in to the reusable workflow so [release docker builds should no longer fail](https://github.com/n0-computer/iroh/actions/runs/10473026816/job/29005092378)

fix: docker CI performance & release builds

---

Cargo.lock
iroh-blobs/src/store/traits.rs
iroh-willow/Cargo.toml
iroh-willow/src/proto/wgps.rs
iroh-willow/src/session/data.rs
iroh-willow/src/session/payload.rs
iroh-willow/src/session/reconciler.rs
iroh-willow/src/util.rs
iroh-willow/src/util/pipe.rs
iroh-willow/tests/basic.rs

* In `iroh_blobs` adds `Store::import_verifiable_stream` and `MapEntry::write_verifiable_stream` to import and export a stream of data with bao metadata interleaved. The format is the same as in the iroh blobs protocol. (@rklaehn is the format written down somewhere?). So it switches between parent nodes and leaf nodes as needed by the bao tree.
* Uses these to encode the payload for `DataSendEntry` and `ReconciliationSendEntry` with proper support for offsets. The verifiable stream of bytes is cut into chunks after each 32KiB and wrapped in the WGPS message.

feat(iroh-willow): verified payoad streaming

---

iroh-gossip/src/net.rs

Just a tiny change that improves performance from ~1s -> ~0.4s on my machine.
None
One could argue we shouldn't make this change, because it doesn't cause that much erratic behavior. We should rather write tests that fail on "more bugs".
I'm not sure. Perhaps the gossip smoke test shouldn't be the test that we use to stress network edge cases.

test(iroh-gossip): Wait for the relay to make `gossip_net_smoke` faster.

---

Cargo.lock
iroh-net/bench/Cargo.toml
iroh-net/bench/src/bin/bulk.rs
iroh-net/bench/src/iroh.rs
iroh-net/bench/src/lib.rs

I did these changes to allow me to test relay throughput differences between the `dig/quinn11` and `main` branches.
The way I test relay throughput now is:
```sh
$ cd iroh-net/bench
$ DEV_RELAY_ONLY=true cargo run --release -- iroh --with-relay
```
Otherwise it simply allows testing iroh with a relay enabled, too, which is nice I think.
None
I think it's pretty obvious one could expand this to enable testing throughput not only with local relays, but also with any relay one wants to test with (e.g. testing euw1 relay for fun). I worked on this for a couple of minutes, then deemed it out of scope.
- ~~[ ] …

feat(bench): Add `--with-relay` option to allow testing relay throughput

---

iroh-net/src/magicsock.rs

Previously, when I edited the iroh-net benchmark to print metrics, it'd show (on a 1GB transfer):
```rs
// ...
send_ipv4: 1104880201,
// ...
recv_data_ipv4: 88912756736,
```
Clearly, the 89GB received data is wrong. The reason is that we record the *buffer size* when we record metrics instead of recording the *received packet size*.
The buffer tends to be around ~90kB for me, while the received packets are around 1-2kB. This explains the 90x factor.
With this fix, I now get:
```rs
// ...
send_ipv4: 1104885110,
// ...
recv_data_ipv4: 1104882621,
```
None.

fix(iroh-net): Magic sock `recv_data_ipv4` and `recv_data_ipv6` metrics numbers

---

Cargo.lock
iroh-net/bench/Cargo.toml
iroh-net/bench/src/bin/bulk.rs
iroh-net/bench/src/iroh.rs
iroh-net/bench/src/lib.rs
iroh-net/src/discovery/pkarr/dht.rs

Used these changes to test #2667.
I think this is a decent tool. Output looks like this:
<details>
<summary><code>$ cd iroh-net/bench && cargo run --release -- iroh --metrics --with-relay</code></summary>
```
Compiling iroh-net-bench v0.23.0 (/home/philipp/program/work/iroh/iroh-net/bench)
Finished `release` profile [optimized + debuginfo] target(s) in 28.47s
Running `/home/philipp/program/work/iroh/target/release/bulk iroh --metrics --with-relay`
Client 0 stats:
Connect time: 1008.829553ms
Overall download stats:
Transferred 1073741824 bytes on 1 streams in 1.70s (603.46 MiB/s)
Time to first byte (TTFB): 105.312ms
Total chunks: 36445
Average chunk time: 46.544ms
Average chunk size: 28.77KiB
Stream download metrics:
│  Throughput   │ Duration 
──────┼───────────────┼──────────
AVG  │ …
```

feat(bench): Add `--metrics` option printing iroh-net library metrics

---

iroh-net/src/magicsock.rs

We had two paths that handled not sending a transmit at all.  This meant the 2nd path was never triggered.  This instead removes the early-returns making it easier to reason about the paths taken.  Now only an error is logged if there was nothing sent.

Simplify handling of no sending

---

Cargo.lock
iroh-willow/Cargo.toml
iroh-willow/src/engine/actor.rs
iroh-willow/src/session/pai_finder.rs

Purging `flume` as a dependency from `iroh-willow`.
Well, there's the whole "make a last send in `impl Drop`" thing.

fix(iroh-willow): Remove `flume` dependency

---

iroh-net/src/magicsock.rs

Since we have made MagicSock private it should always be created via the Endpoint, unless we are internally messing around with tests or so.  Because of this we can make sure that the Endpoint always attaches the correct "me" field to the span.  Reducing the amount of noise in the default log output.
None
Please do not merge before #2595 is merged.  I'm trying to not add any further changes to that PR.

ref(iroh-net): Do not add the NodeId in the magicsock span field

---

Cargo.lock
iroh-gossip/Cargo.toml

iroh-gossip has a direct dependency on Quinn but does not need it. Remove this.
none
Please do not merge before #2595 is merged.  I'm trying to not modify that PR any further.

deps(iroh-gossip): Do not depend directly on Quinn

---

iroh-willow/src/form.rs
iroh-willow/src/store/auth.rs
iroh-willow/tests/basic.rs

Subspace capabilities were not created when creating owned namespaces. Fixed that.
Also adds a test written by @Voronar, thanks!

fix(iroh-willow): actually create subspace capability

---

iroh-blobs/src/downloader.rs
iroh-net/src/discovery/local_swarm_discovery.rs

Since republish occurs more or less every second, for every peer in the local network, every second we insert it in the node_map (which includes locking), print a debug line, and for requesters, re-send a value that was previously sent (since every time a new sender is added we immediately send known values). This pr makes it so that we do all this only when new values are found.
- swarm discovery will no longer send consecutive repeated values
the typo is unrelated to the pr but was flagged by ci

fix(iroh-net): reduce noise in swarm discovery due to republish

---

iroh-blobs/src/downloader/progress.rs

I don't think these logs were meant to be `warn!` logs. I suspect those were originally added for debugging.
None.
Should we remove them altogether?

fix(iroh-blobs): Demote `warn!` to `trace!` logs

---

iroh-blobs/src/store/fs.rs

@divagant-martian noticed there's a `println!` in iroh-blobs. I turned this into a `tracing::debug!` instead.
None

fix(iroh-blobs): Turn `println!` into `tracing::debug!`

---

iroh-blobs/src/store/fs.rs

This fixes a small copy and paste bug that was introduced in #2622, here: https://github.com/n0-computer/iroh/pull/2622/files?diff=unified&w=0#diff-bbe46ca272a808bb1c94619ab3264586a47a6ec6e0f7cd5a63dba5e99099241bL1521-R1526 (You need to load the diff for the `fs.rs` file) 
None
Tests would be nice, but I'm looking at other things right now, so I'd prefer to merge this first :S

fix(iroh-blobs): Timeout based on correct `max_write_duration` option

---

iroh-blobs/src/store/fs.rs
iroh-blobs/src/store/mem.rs
iroh-blobs/src/store/readonly_mem.rs
iroh-blobs/src/store/traits.rs
iroh/src/client/blobs.rs
iroh/src/node.rs

- always delete hashes, even if they are protected when calling `Store::delete`
- move gc loop implementation into the stores
- removed `Store::gc_sweep`
- removed `Store::gc_mark`
- removed `Store::gc_start`
- added `Store::gc_run` which starts the full gc schedule
Closes #2657

fix(iroh-blobs): unconditionally delete blobs

---

iroh-net/src/netcheck/reportgen.rs

When all the probes time out the reportgen actor went into a hot-loop.
We slow this down by resetting the timer to be in the future again.
This way the actor loop can finish normally from the probes without
entering a hot-loop.  The actual timeout doesn't matter too much,
normally it should not happen twice as the actor should be finished by
the time another PROBES_TIMEOUT expires.
None
Fixes #2684.
I've never been very happy with the mainloop of the reportgen actor.
There is too much manual state-tracking also with the way
self.outstanding_tasks is structured.  Also the way that
Message::ProbeWouldHelp exists is not nice, the actor should be able
to abort any probes on it's own when they are no longer needed.  Maybe
I should sit down again sometime and think better about how to
structure …

fix(iroh-net): Fix a hot-loop when the probes time out

---

iroh-net/bench/Cargo.toml
iroh-net/bench/src/bin/bulk.rs
iroh-net/bench/src/iroh.rs

Now, to test relay-only throughput do this:
```sh
$ cd iroh-net/bench
$ DEV_RELAY_ONLY=t cargo run --features local-relay --release -- iroh --with-relay
```
Putting this behind a feature flag means we don't get weird feature flag workspace unification with the `test-utils` feature. Before this change, we would basically disable DNS discovery for everything in the workspace.
None.
Quite a few toggles now with `DEV_RELAY_ONLY`, the `local-relay` feature and the `--with-relay` cli flag. I think each has its own meaning though (the `--with-relay` meaning can be expanded in the future).
- ~~[ ] Tests if …

fix: Put `--with-relay` feature in iroh-net bench behind `local-relay` feature flag

---

iroh-cli/src/commands/doctor.rs
iroh-gossip/examples/chat.rs
iroh-gossip/src/net.rs
iroh-net/bench/src/iroh.rs
iroh-net/examples/connect-unreliable.rs
iroh-net/examples/connect.rs
iroh-net/examples/dht_discovery.rs
iroh-net/examples/listen-unreliable.rs
iroh-net/examples/listen.rs
iroh-net/src/discovery.rs
iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/discovery/pkarr/dht.rs
iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/udp_conn.rs
iroh/examples/local_swarm_discovery.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/tests/provide.rs
iroh/tests/sync.rs

Allows to specify the IPv4 and IPv6 addresses where iroh should bind to.
Closes #2565
- changed 
- `iroh_net::endpoint::Endpoint::bind` now takes  no arguments
- removed
-  `iroh::node::Builder::bind_port`
- added
-  `iroh_net::endpoint::Builder::bind_addr_v4`
-  `iroh_net::endpoint::Builder::bind_addr_v6`
-  `iroh::node::Builder::bind_addr_v4`
-  `iroh::node::Builder::bind_addr_v6`
-  `iroh::node::Builder::bind_random_port`

feat: allow to bind to a specific address

---

Cargo.lock
iroh-cli/Cargo.toml
iroh-cli/src/commands/doctor.rs
iroh-docs/Cargo.toml
iroh-docs/src/engine.rs
iroh-gossip/Cargo.toml
iroh-gossip/src/net.rs
iroh-net/Cargo.toml
iroh-net/src/discovery.rs
iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/discovery/pkarr/dht.rs
iroh-net/src/lib.rs
iroh-net/src/magicsock.rs
iroh-net/src/netcheck.rs
iroh-net/src/netcheck/reportgen.rs
iroh-net/src/netcheck/reportgen/hairpin.rs
iroh-net/src/portmapper.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client/conn.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/server/actor.rs
iroh-net/src/relay/server/client_conn.rs
iroh-net/src/relay/server/http_server.rs
iroh-net/src/util.rs
iroh-net/src/util/chain.rs
iroh/src/node.rs

This migrates us to tokio's AbortOnDropHandle from the various
versions we had for this ourselves.  Only for iroh::node::Node we keep
a local version around since it is both Clone *and* awaits the tasks.
Generally it's probably better to not make this kind of design though,
if possible.
Removes the `iroh_net::util` module.  This only contained utilities
that should have been internal in the first place.  If you were using
one of the tools to abort tasks on drop, we recommend migrating to
`tokio_util::task::AbortOnDropHandle`.

refactor!: Migrate to tokio's AbortOnDropHandle

---

iroh-cli/src/commands.rs

Add documentation to undocumented items in the entrypoint for the `iroh-cli` at `iroh/iroh-cli/src/commands.rs`.
No breaking changes.
No additional notes.

docs(iroh-cli): add docs to entrypoint

---

iroh-cli/src/commands/doctor.rs

Update documentation to `doctor` command submodule.

docs(iroh-cli): udpate `doctor` command documentation

---

iroh-cli/src/commands/authors.rs

Update documentation to RPC's subcommand `authors`.
The imports have been formatted to join similar `use` paths.

docs(iroh-cli): update `authors` command documentation

---

iroh-cli/src/commands/console.rs

Update documentation to `console` command.

docs(iroh-cli): update `console` command documentation

---

iroh-cli/src/commands/net.rs

Update documentation to `net` command.

docs(iroh-cli): update `net` command documentation

---

iroh-cli/src/commands.rs
iroh-cli/src/commands/start.rs

Update documentation to `start` command.

docs(iroh-cli): update `start` command documentation

---

iroh/src/node.rs
iroh/src/node/builder.rs

Removes our custom implementation of `SharedAbortingJoinHandle` in favor of a combination of
- `futures_util::future::Shared`
- `futures_util::future::MapErr` and
- `tokio_util::task::AbortOnDropHandle`
Should all be internal, so none.
We need to turn the `JoinError` to a `String`, because `JoinError` is `!Send`, but `String` is.
This is exactly the same behavior as what our custom `SharedAbortingJoinHandle` was doing before.

refactor(iroh): Remove custom impl of `SharedAbortingJoinHandle`

---

iroh-cli/src/commands/blobs.rs

Update documentation to RPC's subcommand `blobs`.

docs(iroh-cli): update `blobs` command documentation

---

iroh-cli/src/commands/docs.rs

Update documentation to RPC's subcommand `docs`.

docs(iroh-cli): update `docs` command documentation

---

.github/workflows/ci.yml

We somehow have 2 spellcheck actions.  Keep the 2nd one added as
apparently it found more stuff.
But switch it to use the checkout action from a tag, we should not be
using actions from @master (unless they're specifically designed for
this like the rust-toolchain one).

ci: Remove double spellchecks

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/endpoint.rs

This is small and doesn't really affect anything, but removes the
direct dependency on rand_core.  There's no need for it.
None
I was looking for easy wins on the dependencies.  I guess this wasn't 
really it...

deps(iroh-net): Remove direct dependency on rand_core

---

.github/workflows/release.yml

Time to retire the x64 box. It's both slow and limits our bandwidth on the main CI pipe. This job is a relic from a time where we didn't yet have m1 runners.
I've tested the workflow manually and things seem to be fine.

chore(ci): move mac builds over to arm box

---

iroh/examples/custom-protocol.rs
iroh/src/node/builder.rs
iroh/src/node/protocol.rs

Otherwise it is not possible to dynamically assign ALPN names.
- `ProtocolBuilder::accept` uses a `Vec<u8>` instead of `&'static [u8]`

feat!(iroh): Vec<u8> instead of static bytes for ALPNs

---

iroh/src/node.rs
iroh/src/node/builder.rs
iroh/src/node/docs.rs
iroh/src/node/protocol.rs
iroh/src/node/rpc.rs

- refactor(iroh): store gossip in protocolmap
- refactor(iroh): avoid duplicate SecretKey storage
- refactor(iroh): store downloader as part of the blobs
- refactor(iroh): store DocsEngine in protocols
- refactor(iroh): move blobs store into BlobsProtocol
- refactor(iroh): move BlobsBatches into BlobsProtocol
- removed
- `iroh::node::ProtocolBuilder::downloader`
- `iroh::node::ProtocolBuilder::blobs_db`
- `iroh::node::ProtocolBuilder::gossip`

refactor!(iroh): move protocol specific fields in NodeInner into protocols

---

iroh-willow/src/proto/wgps/messages.rs
iroh-willow/src/session/reconciler.rs

@AljoschaMeyer on Discord:
> Drafted the changes for peers to not have to specify the number of entries they will send in a 3dRange in advance.
>
> The [ReconciliationAnnounceEntries](https://macromania--channelclosing.deno.dev/specs/sync/index.html#ReconciliationAnnounceEntries) now does not specify the number of entries, but merely states whether there are zero or more. If there are more, then the [ReconciliationTerminatePayload](https://macromania--channelclosing.deno.dev/specs/sync/index.html#ReconciliationTerminatePayload) indicates for each entry whether it was the final one or whether there are more to follow. This should make @Frando (and now, by proxy, Philipp) happy.
> 
This PR adapts for these changes.

refactor: remove count field from ReconciliationAnnounceEntries

---

iroh/src/client/blobs.rs
iroh/src/node/rpc.rs

fix(iroh): handle out of bounds requests for blobs read_at

---

iroh-gossip/src/net.rs
iroh/src/node.rs

`iroh_gossip::net::Gossip` had a method to update the direct addresses of the iroh_net::Endpoint. IIRC that dates back when the Endpoint only exposed a single, non-cloneable stream of endpoint events, which was handled in the iroh Node and thus had to be forwarded to consumers like Gossip. This was long ago and by now the Endpoint provides a capable API for this. Therefore there is no need to expose this as a method (because Gossip always contains an Endpoint).
`Gossip::update_direct_addresses` is removed. Updating the direct addresses is now handled by `Gossip` automatically.
To react to all updates to the endpoint's `NodeAddr`, I am watching both `Endpoint::direct_addresses` and `Endpoint::watch_home_relay`. A simpler API for this usecase would be `Endpoint::watch_node_addr`.

refactor(iroh-gossip): make use of Endpoint::direct_addresses in iroh_gossip::net

---

iroh-blobs/src/util/local_pool.rs

This preserves the tracing subscriber that is installed in the current
thread when the LocalPool is created.  It then installs it into every
thread managed by the pool, ensuring that tracing output from the pool
is preserved.
Why is this even pub?  But fine:
`iroh_blobs::util::local_pool::LocalPool` will now install the tracing
subscriber of the thread creating the pool, into each thread managed
by the pool.  Practically this should not break any code already
managing their tracing subscribers either manually inside tasks or by
setting a global subscriber before creating the pool.  But if you
really liked the behaviour of swallowing the logs on doing this it's a
breaking change.
Maybe this should be configurable, though since this is just an
internal tool for us I think we're fine just …

fix(iroh-blobs): preserve tracing subscriber in the LocalPool

---

Cargo.lock
iroh-base/Cargo.toml
iroh-blobs/Cargo.toml
iroh-cli/Cargo.toml
iroh-dns-server/Cargo.toml
iroh-docs/Cargo.toml
iroh-gossip/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

Apparently, derive_more is out of beta.
Please, update your deps.

feat(deps): use derive_more@1.0.0 (no more beta!)

---

iroh-net/src/endpoint.rs
iroh-net/src/lib.rs

These were just some places where I was looking for this information
but did not find it easily.
None
It is docs Friday after all!

docs(iroh-net): Document default relay servers a bit more

---

iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/magicsock/node_map/path_state.rs

- Attach the spans when spawning the local-swarm-discovery.  We should
always use .instrument() when spawning.
- Clearly log the start and end of connection establishment.
- In the events.net.* events always use remote_node when showing the
NodeId of the remote node.  These were introduced before we settled
on the "remote node" terminology, now it makes more sense to double
down on this as it makes the logs clearer.
None, events.net is not considered part of the public API.

refactor(iroh-net): Various logging improvements

---

iroh-net/src/magicsock/node_map/node_state.rs
iroh-net/src/magicsock/node_map/path_state.rs
iroh-net/src/magicsock/node_map/udp_paths.rs

The field itself is also directly accessible with the same visibility
as this function.  Having two ways to get to this value is a bit
confusing.  And directly using the field makes it easier when checking
users by following the references from rust-analyzer.
None
None

refactor(iroh-net): Remove PathState::recent_pong()

---

iroh-net/src/magicsock/node_map/node_state.rs

When we do not receive a pong in the timeframe we should have, we remove the last ping time and clear the best_addr.  However the path will be re-selected from the candidates as long as the pong time is set.
This additionally clears the pong time so that there is no longer an indication this path works.  While the DISCO ping-pong is not loss-protected there is already an existing check that ensures this clear is not triggered when there are still other signs of life from the remote node.
None
Note that when sending call-me-maybe the pong times are also cleared. So while I'm not a particular fan of this, it is the intended way to use this.  Ideally the PathState would be clearer about this data and store this as separately.  But the PathState data needs a general cleanup and I do not want …

fix(iroh-net): Clear the recent pong time when pong is lost

---

iroh-net/src/magicsock/node_map/path_state.rs

This is a bit confusing, at least this description is closer to the
reality.
None
Not mentioning PING_TIMEOUT_DURATION since that is not strictly true,
if the socket has signs of being alive but a pong is lost it will
still be considered alive and the pong timeout will not be cleared.
-  ~~[ ] All breaking changes documented.~~

docs(iroh-net): Improve last_pong field docs

---

iroh-blobs/src/downloader.rs
iroh-blobs/src/downloader/get.rs
iroh-blobs/src/downloader/progress.rs
iroh-blobs/src/get/db.rs
iroh-blobs/src/get/progress.rs

More stuff to clean up I came across while trying to debug an issue.
Also, this makes it so that errors from `iroh_blobs::get::db::get_blob` that happen *before* the `get_conn` step get printed.
None.
I decided to just remove the tracing logs in `downloader/progress.rs`. They never really helped us surface the bug, they mostly polluted the logs, to be honest.
The only thing they surfaced was that we didn't properly clean up `TransferState::progress_id_to_blob` when there's an error in `iroh_blobs::get::db::get_blob` that causes us to not send the `DownloadProgress::Done` event.

fix(iroh-blobs): Remove debugging logs & more cleanup

---

iroh-cli/src/commands/start.rs
iroh/examples/client.rs
iroh/src/client/authors.rs
iroh/src/client/docs.rs
iroh/src/node.rs
iroh/src/node/builder.rs
iroh/tests/sync.rs

- removed: `iroh::node::Builder::disable_docs`
- added: `iroh::node::Builder::enable_docs`
- by default `iroh::node::Node::memory` & `persistent` have docs disabled

feat(iroh): disable docs by default

---

.github/workflows/ci.yml
iroh/src/client/blobs.rs
iroh/src/node/rpc.rs
iroh/src/rpc_protocol/blobs.rs

Introduces `ReadAtLen` which allows to specify the behaviour of `read_at` more closely
- `All` - reads until the end (formerly `None`)
- `Exact(size)` - Reads exactly this many bytes (formerly `Some(size)`
- `AtMost(size)` - Reads at most this many bytes, but allows for a shorter response if not enough data is available
Closes #2738
- `iroh::client::Blobs::read_at` and `read_at_to_bytes` now take `ReadAtLen` instead of `Option<usize>`

feat(iroh)!: make blobs::read_at more flexible

---

iroh-net/src/discovery.rs
iroh-net/src/discovery/pkarr.rs
iroh-net/src/discovery/pkarr/dht.rs

This tries to improve the pkarr discovery docs by trying to describe
enough about how it works that users do not need to go looking
elsewhere.
none
There are so many code overlaps and naming inconsistencies here.  But this was
part of docs friday so I'm just documenting things for now.
- Discovery mechanisms are not named particularly consistent:
- `PkarrPublisher` is probably a `PkarrRelayPublisher`
- `PkarrResolver` is also a `PkarrRelayResolver`
- `DnsDiscovery` only does resolving -> `DnsResolver`
- `DhtDiscovery` can also use relay server, but at least it does both publish and resolve
- The `DhtDiscovery` is pretty generic, it can probably be made to do both replace `PkarrResolver` and `PkarrPublisher`, maybe with custom constructors.
- ~~[ ] All breaking …

docs(iroh-net): Improve pkarr discovery docs

---

.github/workflows/cleanup.yaml
.github/workflows/docs.yaml

fix(ci): add cleanup workflow to retain `generated-docs-preview` for only the last 25 PRs

---

.github/workflows/ci.yml
.github/workflows/docs.yaml
.github/workflows/netsim.yml
.github/workflows/netsim_runner.yaml

Adjusts permissions, uses proper input vars & the search & replace for comments is now aligned.
Also adds examples to the list of possible executables for the job.
Note: Docs still seem to fail in this PR with the set permissions. However write-all in a public repo is very constrained so it should be perfectly fine. The GITHUB_TOKEN has it by default, however I think since we're running sub jobs etc it's not propagating correctly.

fix(ci): netsim commenting fixes

---

iroh-base/src/ticket.rs
iroh-base/src/ticket/node.rs
iroh-net/src/ticket.rs

This exports the Ticket trait, which is kind of needed to work with
the NodeTicket.  Since NodeTicket is already provided directly in
iroh-net it is very strange to force users to pull in iroh-base to get
the ticket trait.
Also updates the docs of tickets a little.
None
None

feat(iroh-net): Export the Ticket trait

---

iroh-base/Cargo.toml
iroh-base/src/hash.rs
iroh-base/src/lib.rs
iroh-base/src/ticket.rs
iroh-blobs/Cargo.toml
iroh-blobs/src/lib.rs
iroh-docs/Cargo.toml
iroh-docs/src/lib.rs
iroh-gossip/Cargo.toml
iroh-gossip/src/lib.rs

This adds the features needed for an API to the generated docs for the
remaining workspace crates.  Only the iroh crate itself does not yet
document this.
none
I can for the life of me not get this to work for the iroh crate
itself...  No idea why.  Feel free to give it a try.

docs(*): Document cargo features in docs

---

iroh-base/src/ticket/node.rs

There is no need for this to have a Result.  Also there's a From impl
anyway.  So clean this up.
`NodeTicket::new` no longer returns `Result` but always succeeds (as
it already did).  This matches it's `From<NodeAddr>` impl which also
never fails.

refactor(iroh-base)!: No Result for creating new NodeTicket

---

iroh-net/examples/dht_discovery.rs
iroh-net/src/dialer.rs
iroh-net/src/discovery.rs
iroh-net/src/endpoint.rs
iroh/examples/custom-protocol.rs

Allow using anything can be converted to a NodeAddr when connecting. This means that we can directly connect with NodeIds, and connect_by_node_id is no longer needed.
Also deprecate connect_by_node_id since it is no longer needed.
- iroh-net: Endpoint::connect now takes an `impl Into<NodeAddr>` instead of a `NodeAddr`
- iroh-net: Endpoint::connect_by_node_id is deprecated (to be removed next release)
Note: Doing this means that the instrumentation of connect no longer contains the remote, which is bad I guess. Not sure how to work around this. One way would be to have connect and connect_impl - connect_impl is like the current connect and can be instrumented as before. Any other way to do this? 
Note: since there is a From<NodeTicket> for NodeAddr, you can also directly dial using a …

feat(iroh-net)!: Allow using a NodeId directly in connect.

---

iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client/conn.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/server/http_server.rs

These are two cleanups in the relay client:
- The `relay::Client` hands out a connection object when asked to
connect.  This `Conn` was imported with rename to `RelayClient`
which was a bit confusing as this was already the relay client.  It
is now left at it's original name which makes a lot more sense.  The
related builder struct etc are renamed to match.
- The `relay::Client` had a counter for the number of connections made
to the relay.  That seems fun, but was entirely unused.  If this is
a useful thing to have it should probably be a counter metric
instead but let's not add anything that no one is using.  Removing
this makes a lot of APIs a bit simpler and removes some state
tracking.
None hopefully, please let this all  be internal APIs.

refactor(iroh-net): Keep connection name, remove connection count

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/client.rs
iroh-net/src/relay/client/conn.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/server/http_server.rs

The ActiveRelay actor keeps track of which remote nodes are present on the relay connection so that we can optimise relay connections to remote nodes.  This does two main optimisations:
- There were two sets of these nodes kept, they could easily be unified.
- The set is best stored in a BTreeSet since they are simple NodeIds stored in them.
- Bonus: rename peer to node to match our naming convention.
- Bonus: identify nodes by NodeId since this is a routing key here.
Still none if all is well.
This targets #2779 as base.

refactor(iroh-net): Optimise present nodes in ActiveRelay

---

iroh-net/src/endpoint.rs

This adds a DEBUG-level log logging the crate version number.
None
This is not the first log message appearing, the MagicSock and a few
other pieces already have been logging by this time.  Also I'm not
particularly bound to this wording.  Maybe there are other things that
should be added to this line?

feat(iroh-net): Log the crate version number

---

iroh/src/client/blobs.rs

Only observed on windows, probably because this machine is always
slower and triggers some race condition easier.  We can change this to
be flaky everywhere if we notice it happening on other platforms too.
See #2783.

tests(iroh): Mark test_blob_delete_mem as flaky

---

iroh-net/src/discovery.rs

This at least documents how to do the normal setup for discovery.

docs(iroh-net): Add examples to discovery

---

iroh-net/src/magicsock.rs

When the call-me-maybe is queued this event was not being emitted.

fix(iroh-net): Emit the call-me-maybe.sent event in all cases

---

iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/magicsock/node_map/node_state.rs

Each time a `ConnectionType::Mixed` has a different SocketAddr or RelayUrl, we correctly resend a `ConnectionType::Mixed` event to `Endpoint::conn_type_stream`. However, when we print those changes in something like `iroh doctor`, we only print the name of the connection type, we don't print the socket address or relay url, so it looke like we are sending extra `Mixed` events erroneously.
Adding more details to the `Display` of `ConnectionType`, so that it prints the socket addrs and or relay urls.

refactor: display the socket addr and relay for a `ConnectionType::Mixed`

---

iroh-net/src/discovery.rs
iroh-net/src/discovery/local_swarm_discovery.rs

Using `subscriber.send().await` could block the entire discovery service if one of the subscribers polls too slow. Change to `try_send` that will drop the discovery item from that stream if it is closed.
Added a line in the documentation to mention that if you do not poll enough, you may miss messages.

fix(iroh-net): use `try_send` rather than `send` so we dont block the local swarm discovery service

---

Cargo.lock
iroh-net/Cargo.toml

This finally removes the last use of a pre-1.0 hyper version,
eliminating our duplicate hyper dependencies.
None
Closes #1863.

deps(iroh-net): Upgrade igd-next, remove hyper 0.14

---

.github/workflows/netsim_runner.yaml

Seems like permissions are still messy and the netsim job fails on forks whenever it interacts with a PR from a fork, even though it's on our own repo and we allow it to run.
This simply drops any type of commenting on the PR from a fork.
Need to add back the required check for this job once it's merged.

fix(ci): netsim does not interact with PR comments on forks

---

.github/workflows/netsim_runner.yaml

When our netsim jobs fail, we have little visibility into the why of it. Logs can be inspected manually on the machine but that's really not convenient. This should make sure logs always get uploaded and attached to the job.

fix(ci): make sure logs get uploaded on netsim failure

---

iroh-net/src/endpoint.rs

Add a helper fn to configure n0 default discovery without having to resort to having to combine a custom discovery service.
```rust
let secret_key = SecretKey::generate();
let discovery = ConcurrentDiscovery::from_services(vec![
Box::new(PkarrPublisher::n0_dns(secret_key.clone())),
Box::new(DnsDiscovery::n0_dns()),
Box::new(LocalSwarmDiscovery::new(secret_key.public())?),
]);
let ep = iroh_net::Endpoint::builder()
.secret_key(secret_key)
.discovery(Box::new(discovery))
.alpns(vec![EXAMPLE_ALPN.to_vec()])
.bind()
.await
```
becomes
```rust
let ep = iroh_net::Endpoint::builder()
.discovery_n0() // still have to do this to enable discovery!
.alpns(vec![EXAMPLE_ALPN.to_vec()])
.bind()
.await
```
None
Should this be on or off by default?
Does anybody hate the name?
Should we also add fns for …

feat(iroh-net): Add helper fn to enable n0 discovery publishing and resolving

---

iroh-net/src/magicsock/udp_conn.rs

If the bind is required the call stack already makes sure that this is
surfaced correctly.  It is in fact entirely normal if IPv6 to fail to
bind and this is already logged on INFO level.  We do not need an
additional WARN log for this.
This also doesn't need to debug-log the error, anyhow's alternate
logging mechanism is perfect for this.
None

refactor(iroh-net): Failing to bind is not a Warning log

---

iroh-net/src/relay/client.rs

The client already has a connecting span tying together everything
that is happening for connect.  But it doesn't yet say which relay
this is for.  Add the RelayURL as a span field.
None

refactor(iroh-net): Attach Relay URL to a connecting client span

---

iroh-net/src/magicsock/relay_actor.rs
iroh-net/src/relay/client.rs

These are logged for each packet on the relay path.  That's not what
we do on debug logging.  One case is already covered by other trace
logging, so just move the "why", the other case can be a trace log.
None

refactor(iroh-net): Debug logging should not be per packet set

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/bin/iroh-relay.rs
iroh-net/src/relay/server.rs
iroh-net/src/relay/server/actor.rs
iroh-net/src/relay/server/http_server.rs
iroh-net/src/test_utils.rs

The `secret_key` configuration of the relay server was actually dead code at this point, this removes it from the config and all associated dead code.
This also removes the need to write to the config file of the `iroh-relay`, making deployments easier to secure.
- removed 
- the `secret_key` property of the `iroh-relay` config
- `iroh_net::relay::server::ServerActorTask::secret_key`
- `iroh_net::relay::server::ServerActorTask::public_key`
- `iroh_net::relay::server::ServerActorTask::meta_cert`
- field `secret_key` in `iroh_net::relay::server::RelayConfig`
- changed
- `iroh_net::relay::server::ServerActorTask::new` now takes no arguments
Closes https://github.com/n0-computer/iroh/issues/2845

refactor!(iroh-net): remove relay secret key

---

.github/workflows/ci.yml
.github/workflows/tests.yaml

I forgot this when adding `iroh-router`

ci: add iroh-router to crates list

---

iroh-net/src/endpoint.rs

On windows this sometimes times out.  But the timeout was only 5
seconds and we know our windows CI runners are slow usually.  5s
really isn't enough.  If this timeout still occurs with a 30s timeout
maybe we can do some more debugging, but it is rather likely just a
slow machine.

tests(iroh-net): Give this a longer timeout

---

iroh-dns-server/config.dev.toml
iroh-dns-server/config.prod.toml
iroh-dns-server/src/config.rs
iroh-dns-server/src/http.rs
iroh-dns-server/src/http/rate_limiting.rs
iroh-dns-server/src/server.rs

Hello,
We are currently testing some new cloud features at [Spacedrive](https://github.com/spacedriveapp/spacedrive), and our implementation relies heavily on iroh. As part of this, we are deploying our own iroh-dns-server. However, since all of our backend services operate behind a reverse proxy, we noticed that the iroh-dns-server was frequently hitting its rate limit because it wasn’t aware of the proxy setup. To address this, I decided to implement a configurable rate limit for the iroh-dns-server.
This PR adds a new entry to the `iroh-dns-server` TOML file for configuring the HTTP rate limit. The new configuration allows for disabling the rate limit and also supports configuring it to use the [SmartIPKeyExtract](https://github.com/benwis/tower-governor/blob/v0.4.2/src/key_extractor.rs …

feat(iroh-dns-server)!: Make http rate limit configurable

---

iroh-net/src/lib.rs

The Endpoint is the central struct.  I think it should be linked
really early on as the most obvious link to follow.
I myself rely on this link being at the start of docs page, but
introducing this early example moved it down rather far.  So move it
back up.

docs(iroh-net): Link to Endpoint in the first few paragraphs

---

iroh-net/src/bin/iroh-relay.rs

Previously, the `Config::enable_stun` value was written but never read, so you couldn't actually disable stun using your iroh config.
- For anyone deploying their relay server: The relay server now *actually* respects the `enable_stun` config value. If you set it to `false` previously, that did not have an effect, but now *will* have an effect.
LMK if you hate my `Option::filter` fuckery :P

fix(iroh-relay): Respect `enable_stun` setting in `iroh-relay::Config`

---

iroh-metrics/src/core.rs

Allows external crates to easily encode metrics.

fix(metrics): allow external crates to encode their metrics

---

iroh-net/src/endpoint.rs

This explains when the UDP sockets are closed in the Endpoint::close
docs.

docs(iroh-net): Explain when sockets are closed

---

Makefile.toml
iroh-cli/tests/cli.rs
iroh-dns-server/src/http.rs
iroh-metrics/src/metrics.rs
iroh-net/src/discovery.rs
iroh-net/src/discovery/local_swarm_discovery.rs
iroh-net/src/endpoint.rs
iroh-net/src/lib.rs
iroh-net/src/relay/codec.rs
iroh-net/src/relay/server/clients.rs
iroh/src/client/net.rs
iroh/src/lib.rs
iroh/src/node/builder.rs
iroh/src/util/fs.rs
net-tools/portmapper/src/pcp/protocol/request.rs
net-tools/portmapper/src/pcp/protocol/response.rs

This enables the unstable rustfmt option to format the code in docs.
Should make our examples a lot more consistent.
This is unstable, so there might be some churn or bad results.  But I
don't think the churn should be much of an issue for us.

docs: Format code in doc comments

---

iroh-net/src/netcheck/reportgen.rs
iroh-net/src/relay/http.rs
iroh-net/src/relay/server.rs
iroh-net/src/test_utils.rs

This implements the https probe.
There does not need to be separate IPv4 or IPv6 HTTPS probes, because we just go with whatever the HTTPS connection works over.  This is what we need to establish a relay connection after all, this also does not care.  The only reason for this is to get some kind of latency to be able to chose a relay server.
Luckily the https probes have been integrated in the probe plan a long time so nothing to do there.
The URLs served by the relay changed:
- `/relay/probe` has moved to `/ping`
- `/derp/probe` has been removed.
Unless you were manually using those URLs you will not notice these changes, nothing in the iroh codebase ever used the changed URLs.
Currently this uses reqwest with it's default DNS resolution.  This is not great as it is not the same DNS …

feat(iroh-net): Implement the https probe

---

iroh-cli/tests/cli.rs

These tests fail when windows is too slow writing and copying the files needed. To avoid ignoring the tests, this PR increases the time we give it to be ready on windows runs to double the original value.
n/a
It would still be good to try to identify if anything changed in our code to make iroh slower on windows. This is however very low priority so this offers a workaround.

test(iroh-cli): increase wait on windows resumption tests

---

iroh-relay/src/lib.rs

This is needed to make the `cfg_attry` work.

chore(iroh-relay): fixup docs feature config

---

iroh-relay/src/server.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/http_server.rs

We observed continous memory increase on the relays, this fixes the main offenders we have found. Mainly the issue was not cleaning up tasks that were spawned into `JoinSet`s.

fix(iroh-net): fix memory leaks in the iroh-relay server

---

Cargo.lock
net-tools/netwatch/Cargo.toml
net-tools/netwatch/src/netmon.rs
net-tools/netwatch/src/netmon/actor.rs
net-tools/netwatch/src/netmon/bsd.rs

also uses `AbortOnDropHandle` to better cleanup tasks
Closes #2909

fix(netwatch): BSD rebind socket on errors

---

.config/nextest.toml
iroh-net/src/endpoint.rs

By using nextest to kill slow tests we get logs when a test is killed. This is better than the github timeout kicking in as then we get no feedback on what was stuck.
Tests are now marked as slow after 20s and killed after 60s.
discovery::tests::endpoint_discovery_combined_wrong_only seems like it is a slow tests needing about 30s to complete.  To be fair I think it's fine to call that out as a slow test, so I'm fine with that.
It is possible that this 60s timeout will introduce some new flakyness to the slow CI machines.  We'll have to see and potentially tweak this a bit.

ci: Kill tests after 60s using nextest

---

net-tools/netwatch/src/netmon/android.rs

With #2913, the netmon actor properly exits when the channel sender is dropped, but the android implementation never kept the sender around. The magicsock actor would then error when trying to subscribe to the network monitor, and the `Endpoint` would be unusable.

fix(netwatch): hold on to netmon sender reference in android

---

Cargo.lock
iroh/src/node/rpc.rs

adapt to latest main in iroh-gossip and iroh-docs
still not sure if handle_rpc_request should take an `Arc<Self>`, but for now just make it work
none
Should all fns that take self take an `Arc<Self>` in a protocol handler? The Arc kinda infects the entire code base. But maybe we have to do it.

chore: adapt to latest main in iroh-gossip and iroh-docs

---

iroh-dns-server/src/http/tls.rs
iroh-dns-server/src/main.rs

Just some things I found while reading the code
- avoid spawn-blocking
- remove unused imports
None

chore(iroh-dns-server): cleanup some code

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/relay_actor.rs
iroh-relay/src/client.rs
iroh-router/src/router.rs
iroh/src/node.rs

Fixed some more cases of `else` branches in `tokio::select!`s that would never actually run. I noticed because the relay actor would start logging `recv error Receive(shut down)` when I dropped the `Endpoint`.
There's 2 cases where the `else` branch still would never run but I wasn't sure of what the intended behaviour was, so I left a todo comment.
In the `RelayActor` it seems like it would make sense to exit in both cases - the `ping_tasks` `JoinSet` being empty and the `receiver` being closed.
The magicsock actor I'm much less sure of - I suspect the `else` branch could just be removed?

fix:  remove problematic usage of `else` branches in `tokio::select`s

---

iroh-dns-server/src/http/tls.rs

Fix up the missed change from https://github.com/n0-computer/iroh/pull/2941/files#r1846266661

fix(iroh-dns-server): actually use async fs in load_secret_key

---

.github/workflows/tests.yaml

According to https://github.com/msys2/setup-msys2?tab=readme-ov-file#release this should try to reuse an existing msys2 installation (though seems to reference a default fallback to the one installed on the GH hosted runners, unsure if it works for self hosted)
Edit: seems to be working

fix(ci): try to reuse msys2 dep

---

.github/workflows/ci.yml
.github/workflows/netsim.yml
.github/workflows/netsim_runner.yaml
Cargo.lock
iroh-net/bench/src/lib.rs
iroh/Cargo.toml
iroh/examples/new.rs
iroh/examples/transfer.rs

Moves our netsim tests to run from an example and only test the lib part of the code, not the full CLI & blobs.
Things left to do:

fix: make netsim run from examples

---

Cargo.lock
Cargo.toml
deny.toml
iroh-base/Cargo.toml
iroh-dns-server/Cargo.toml
iroh-dns-server/src/http/rate_limiting.rs
iroh-dns-server/src/lib.rs
iroh-dns-server/src/store.rs
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-net/bench/Cargo.toml
iroh-net/src/discovery/pkarr/dht.rs
iroh-net/src/test_utils.rs
iroh-relay/Cargo.toml
iroh-relay/src/server.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/streams.rs
iroh-router/Cargo.toml
iroh/Cargo.toml
net-tools/netwatch/Cargo.toml
net-tools/netwatch/src/interfaces.rs
net-tools/netwatch/src/interfaces/linux.rs
net-tools/netwatch/src/ip.rs
net-tools/netwatch/src/netmon/linux.rs
net-tools/netwatch/src/netmon/windows.rs
net-tools/portmapper/Cargo.toml

Getting started on cleaning up our deps tree as much as possible. 
Closes https://github.com/n0-computer/iroh/issues/2883
This will continue to be an ongoing thing. We have a couple deps that are pending on releases from further deps. We've managed to clear out most of our own repos and iroh dependencies.

chore: prune some deps

---

Cargo.lock
iroh-base/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

This was getting in my way when I was trying to install both iroh & iroh-blobs from their main branches in a project.
<details>
<summary>cargo check output</summary>
```sh
$ cargo check
Updating git repository `https://github.com/n0-computer/iroh`
Updating git repository `https://github.com/n0-computer/iroh-blobs`
Updating crates.io index
error: failed to select a version for `cc`.
... required by package `ring v0.17.8`
... which satisfies dependency `ring = "^0.17"` (locked to 0.17.8) of package `iroh-net v0.28.1`
... which satisfies dependency `iroh-net = "^0.28.1"` (locked to 0.28.1) of package `iroh v0.28.1 (https://github.com/n0-computer/iroh?branch=main#e675bbaf)`
... which satisfies dependency `iroh = "^0.28.1"` (locked to 0.28.1) of package `quickstart-iroh v0.1.0 …
```

chore: Remove `cc` version requirement & update lockfile to cc v1.2.1

---

Cargo.lock
Cargo.toml
iroh-base/src/relay_url.rs
iroh-dns-server/Cargo.toml
iroh-net-report/Cargo.toml
iroh-node-util/Cargo.toml
iroh-relay/Cargo.toml
iroh-relay/src/protos/relay.rs
iroh/Cargo.toml
iroh/src/endpoint.rs
net-tools/portmapper/Cargo.toml

- no more patching
- always use local path deps for workspace dependencies
- fix clippy complaints on rust `1.83`
None

refactor: cleanup internal dependency references

---

iroh-relay/src/client.rs
iroh/README.md
iroh/src/magicsock.rs
iroh/src/magicsock/node_map/node_state.rs
iroh/src/magicsock/node_map/path_state.rs

Turns out people will configure logs with `RUST_LOG=iroh=debug` and then the `events` target is completely lost.  That's bad!
This changes the events to be in the main crate target, so users don't have to separately enable them.
It also changes the separators to use the `::`.  The driver for this is compatible with the `EnvFliter` syntax, allowing you do do e.g. `RUST_LOG=iroh::events=debug` to enable just events.
The main downside is that it is harder to enable events across different crates.  But then we only use this in one crate so far, so perhaps that's not an issue yet.
Another downside is that `iroh::events` could quite easily become a module name, in which case the targets would conflict.
- Events are emitted on different tracing targets: `iroh::events` instead of `events.net`.
- …

ref(iroh): Rename target for events

---

Cargo.lock
example.config.toml
iroh-base/src/relay_map.rs
iroh-net-report/src/lib.rs
iroh-relay/Cargo.toml
iroh-relay/README.md
iroh-relay/src/client.rs
iroh-relay/src/defaults.rs
iroh-relay/src/lib.rs
iroh-relay/src/main.rs
iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh-relay/src/server/testing.rs
iroh/src/defaults.rs
iroh/src/endpoint.rs
iroh/src/test_utils.rs

This PR adds a QUIC endpoint to the relay server that can do QUIC address discovery. It also contains structs/functions for properly doing the Client side interaction for this process.
Also, this adjust the `RelayNode` to include configuration on how to speak to the QUIC endpoint on the relay server.
QUIC is disabled by default and requires a `TlsConfig` to be configured in order to work.
closes #2964 
- `iroh_base::relay_map::RelayNode` now has field `quic` that takes a `Option<iroh_base::relay_map::QuicConfig>`
- `iroh::test_utils::run_relay_server_with(stun: Option<StunConfig>)` => `iroh::test_utils::run_relay_server_with(stun: Option<StunConfig>, quic: bool)`
- when `quic` is `true`, it will start a quic server for QUIC address discovery, that has self signed tls certs for testing.
- …

feat(iroh-relay)!: add a QUIC server for QUIC address discovery to the iroh relay.

---

iroh/src/magicsock.rs

It seems this function is entirely unused?  Why did the compiler not
pick this up?  ??

ref(iroh): Remove unused function

---

.github/workflows/ci.yml
.github/workflows/tests.yaml
iroh-relay/src/server.rs
iroh/src/discovery.rs

This test can only work if the feature is enabled.  Feature-flag the
entire test contents.
Closes #2950.

tests(iroh): Feature-flag the doc test

---

README.md
iroh/bench/src/lib.rs
iroh/examples/connect.rs
iroh/examples/echo.rs
iroh/examples/transfer.rs
iroh/src/discovery.rs
iroh/src/endpoint.rs
iroh/src/lib.rs
iroh/src/magicsock.rs
iroh/src/protocol.rs

- ties the cancellation tokens between `Router` and `Endpoint` closer together
- closing `Endpoint` is now idempotent
- added `iroh::Endpoint::close` that takes no arguments anymore, it default to using code `0` and an empty message
- added `iroh::Endpoint::is_closed`

feat(iroh): improve shutdown interactions

---

iroh-dns-server/src/store.rs
iroh-dns-server/src/store/signed_packets.rs

I found this during investigations of #2972. It turned out that both blocking locks and blocking IO calls are being made in the dns servers store implementation
None
This might be not optimal, but it is the safest way to get rid of blocking the whole runtime for now.

fix(iroh-dns-server): remove accidental blocking from store

---

iroh/src/magicsock.rs

The existing AsyncUdpSocket::poll_recv polled the UDP IPv4 socket
first, only if that has no datagrams would it poll UDP IPv6 and only
also that had no datagrams to deliver was the relay socket polled.
This highly favoured IPv4 relay traffic, potentially starving the
relay traffic.
This change makes it prefer a different source on each poll.  Meaning
if multiple sockets have data to deliver a fairer delivery happens.
Closes #2981.
- Using Ordering::Relaxed is probably fine.  I believe normally
this polling would only happen from a single task (the Quinn
endpoint driver) and even if it was polled concurrently from
different threads it would not be that bad and still an improvement
on the current order.
- I'm not particularly fond of the implementation, but the macros is
the best I could …

fix(iroh): Poll all AsyncUdpSocket sources fairly

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/benches/write.rs
iroh-dns-server/src/lib.rs

Looking at the code paths I think this should give a decent benchmark for publishing dns records. 
On my M1 Max I get about 3k IOPS and 25-30 MB/s written in all the test runs and sit at ~165-170 publishes per second, which is far from ideal. This holds true even without the fixes in the parent branch.

feat(benchmark): iroh-dns-server write benchmark

---

Cargo.lock
iroh-relay/Cargo.toml
iroh/Cargo.toml

Before we used to depend on both tungstenite version 0.21 as well as 0.24, because:
```
tungstenite v0.21.0
└── tokio-tungstenite v0.21.0
└── tokio-tungstenite-wasm v0.3.1
├── iroh v0.29.0 (/home/philipp/program/work/iroh/iroh)
└── iroh-relay v0.29.0 (/home/philipp/program/work/iroh/iroh-relay)
├── iroh v0.29.0 (/home/philipp/program/work/iroh/iroh)
└── iroh-net-report v0.29.0 (/home/philipp/program/work/iroh/iroh-net-report)
└── iroh v0.29.0 (/home/philipp/program/work/iroh/iroh)
tungstenite v0.24.0
└── tokio-tungstenite v0.24.0
├── iroh v0.29.0 (/home/philipp/program/work/iroh/iroh)
└── iroh-relay v0.29.0 (/home/philipp/program/work/iroh/iroh-relay)
├── iroh v0.29.0 (/home/philipp/program/work/iroh/iroh)
└── iroh-net-report v0.29.0 (/home/philipp/program/work/iroh/iroh-net-report)
└── …
```

chore(iroh, iroh-relay): Avoid a duplicate tungstenite dependency

---

iroh-relay/src/client/conn.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/client_conn.rs

This was a rate limiter which seems like the intention was to slow
down how fast it sends to a particular relay server.  This is the
wrong place to rate-limit.  If the server limits that it should read
slower from the TCP stream (it does this now!) and that blocks up the
TCP-stream and in turn slows down the relay client.  In no world does
a socket internally rate-limit to one of it's destinations, that's not
how sockets work.  And this client exists for the MagicSock.

refactor(iroh): Remove unused rate limiter

---

.github/workflows/ci.yml
.github/workflows/netsim.yml

The sims on `netsim` have been promoted and are replacing the old ones. PRs older than 2 weeks from main no longer work with netsim. A simple rebase should fix it where necessary. I'll leave this as is for another 2 weeks and then do the cleanup pass. 
This has the neat benefit of also dropping old fixture generation scripts which should drop netsim execution time by ~1 min.

chore: bump netsim setup

---

Cargo.lock
iroh/Cargo.toml
iroh/src/magicsock.rs
iroh/src/magicsock/relay_actor.rs

Based on #2986 
Replaces `RelayRecvReceiver` and `RelayRecvSender` with the (clonable & shared) `RelayDatagramsQueue`.
This queue contains a `ConcurrentQueue` (from the smol library `concurrent-queue`) and an `AtomicWaker`.
It should only be polled from one task.
If polled from multiple tasks, then tasks will overwrite each other's wakers.
Unfortunately we can't make it use `&mut Self` in `poll_recv` because `quinn` expects the `AsyncUdpSocket`s `poll_recv` interface to be `&self`.
This (un)fortunately doesn't have an effect on performance for me.
(The benchmark is completely broken half the time for some reason, but when it runs it produces normal numbers:)
```sh
$ DEV_RELAY_ONLY=true cargo run -p iroh-net-bench --release --features=local-relay -- iroh --with-relay --download-size=100M
│ …
```

feat: Implement `RelayDatagramsQueue`

---

iroh/src/protocol.rs

Remove get_protocol and the plumbing required for it
it has not turned out to be as useful as originally expected
- iroh::protocol::Router::get_protocol is removed
- iroh::protocol::RouterBuilder::get_protocol is removed
- iroh::protocol::ProtocolMap::get_typed is removed
- iroh::protocol::IntoArcAny is removed

feat(iroh)!: remove get_protocol and the plumbing required for it

---

iroh-relay/src/client.rs
iroh/src/magicsock/relay_actor.rs

The Client has a feature that stops it from sending pongs, it is
unused and I'm not sure when you'd need that functionality.  Remove it.
- `ClientBuilder::can_ack_pings` is removed, sending pong messages is
always allowed.

refactor(iroh-relay)!: Always allow acking pings

---

iroh-relay/src/client.rs

A whole bunch of these errors are unused.  But they are all pub so the
compiler doesn't tell us. :'(
- `ClientError` has a number of unused variants removed.

refactor(iroh-relay)!: Remove usesed errors.

---

iroh/src/magicsock.rs
iroh/src/magicsock/relay_actor.rs

I thought I was going to put in a queue or channel of some sort... but
not yet.  Still, let's rename this for now.

refactor(iroh): Rename the relay-is-ready-to-send waker

---

iroh/examples/echo.rs
iroh/examples/search.rs
iroh/src/protocol.rs

- `iroh::protocol::ProtocolHandler::accept` now takes `&self` instead of `Arc<Self>`
- `iroh::protocol::ProtocolHandler::shutdown` now takes `&self` instead of `Arc<Self>`
- `iroh::protocol::RouterBuilder::accept` now takes `T: ProtocolHandler` instead of `Arc<dyn ProtocolHandler>`
- `iroh::protocol::ProtocolMap` is now private

feat(iroh): remove `Arc` requirements from `ProtocolHandler`

---

iroh-net-report/Cargo.toml
iroh-net-report/src/lib.rs
iroh-relay/Cargo.toml
iroh-relay/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh/Cargo.toml

- remove `relay/server` default feature
- set `metrics` feature as necessary
- `server` is not a default feature in `iroh-relay` anymore

feat!: reduce default feature dependents

---

iroh-relay/src/protos/relay.rs
iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh/src/endpoint.rs

We've deprecated this method a while ago, said to remove it in v0.28.0, but didn't. Let's do that now.
Also, I noticed some `#[doc(cfg(..))]`s were missing, I tried to find and add all missing ones.
- Removed deprecated `iroh::Endpoint::connect_by_node_id`. Use `iroh::Endpoint::connect` with a `NodeId` instead.

feat(iroh, iroh-relay)!: Remove `Endpoint::connect_by_node_id` and add `#[doc(cfg(...))]` annotations

---

Cargo.lock
deny.toml
iroh/Cargo.toml

- Updates to latest `swarm-discovery` alpha, so that `cargo deny` is happy again
None, swarm-discovery isn't exposed in the API.
It might be questionable if we want to depend on *more* alphas, but IMHO, this case is fine to avoid a security vulnerability.
Hopefully this is the last alpha. The next version of hickory we depend on should be 0.25.

chore: (Deps) Update swarm-discovery to avoid idna <= 0.5 dep

---

Cargo.toml
iroh-base/src/hash.rs
iroh-base/src/lib.rs
iroh-base/src/ticket.rs
iroh-relay/src/client.rs
iroh-relay/src/defaults.rs
iroh-relay/src/http.rs
iroh-relay/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh/src/discovery.rs
iroh/src/discovery/pkarr.rs
iroh/src/endpoint.rs
iroh/src/lib.rs
iroh/src/magicsock.rs
iroh/src/metrics.rs

This switches from the doc-cfg feature which needs an explicit
annotation to the doc-auto-cfg feature which does not need this.  We
already had several places where the docs and actual features were out
of sync.  So hopefully this will work better.
doc-auto-cfg does not seem perfect and may miss some things.  E.g. one
difference I noticed is that it does not seem to surface the "test"
feature when we do `any(test, feature = "something")`.  But I'm
thinking that might be a reasonable price to pay here.

docs(*): Use doc-auto-cfg feature

---

iroh-base/Cargo.toml
iroh-base/src/lib.rs
iroh-base/src/node_addr.rs
iroh-base/src/ticket.rs
iroh-base/src/ticket/blob.rs
iroh-base/src/ticket/node.rs
iroh-dns-server/src/lib.rs
iroh/Cargo.toml
iroh/src/discovery.rs
iroh/src/discovery/dns.rs
iroh/src/discovery/local_swarm_discovery.rs
iroh/src/discovery/pkarr.rs
iroh/src/discovery/pkarr/dht.rs
iroh/src/discovery/static_provider.rs
iroh/src/dns/node_info.rs
iroh/src/endpoint.rs
iroh/src/lib.rs
iroh/src/magicsock.rs
iroh/src/magicsock/node_map.rs
iroh/src/magicsock/node_map/node_state.rs

Simplify type structures
TODO
- remove `iroh_base::node_addr::AddrInfo`
- remove `iroh_base::node_addr::AddrInfoOptions`
- introduce `ticket` feature for `iroh_base`, to use `iroh_base::ticket`

refactor: remove `AddrInfo`

---

iroh/src/magicsock/relay_actor.rs

Yes, that's (almost) back to what it was called...
The name has grown on me and it is better because the relay is not always connected.  This does also fit better with what it should be doing: keep the connection alive if possible.  Currently this functionality is mixed up in the RelayActor itself.
- Just a plain rename.
- Base is `flub/relay-send-channel-1`, be aware of github when merging things.

refactor(iroh): rename ConnectedRelayActor to ActiveRelayActor

---

iroh/src/magicsock/relay_actor.rs

There is a difference between the datagrams that the MagicSock sends and the packets that contain datagrams that gets sent to relay servers.  But this was all just Bytes.
This newtypes the packets explicitly and makes it a sibling of the existing RelayRecvDatagram.  Now the PacketizeIter at least does not both consume and produce the same type, because they're not the same things.
This clones the RelayUrl (usually) twice per packet sent now, instead of (usually) once.  That's the only thing I don't like about this really.
I still wonder whether RelayUrl should not be some sort of interned and cloned thing.
Watch out, the base of this PR is `flub/active-relay-again`.

refactor(iroh): Newtype the packet sent over relay servers

---

iroh-base/src/key.rs
iroh-base/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh/src/disco.rs
iroh/src/magicsock/relay_actor.rs

Make PUBLIC_KEY_LENGTH a const that is on PublicKey
that way it is not so in your face
- PUBLIC_KEY_LENGTH is moved from a top level constant to PublicKey::LENGTH

refactor!: Make PUBLIC_KEY_LENGTH a const that is on PublicKey

---

Cargo.lock
deny.toml
iroh/Cargo.toml
iroh/src/discovery/pkarr/dht.rs

One less dependency in the core of iroh

refactor(iroh): remove genawaiter usage from dht discovery

---

iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh-relay/src/server/http_server.rs
iroh/src/protocol.rs

This changes the disabling of JoinSet::join_next branches in
tokio::select! calls to rely on pattern matching alone.  This changes
nothing to the logic executing in the select! call, but often results
in less code.
A branch is disabled if the pattern does not match, and the remaining
futures are still awaited.  Once the branch is disabled the logic of
tokio::select! is exactly the same regardless of whether it was
disabled because of an if condition or because of a mismatched pattern.

refactor(iroh, iroh-relay): JoinSet disabling in tokio::select!

---

iroh-dns-server/src/store.rs
iroh-net-report/Cargo.toml
iroh-net-report/src/lib.rs
iroh-net-report/src/reportgen.rs
iroh-net-report/src/reportgen/probes.rs
iroh-relay/src/quic.rs
iroh/src/magicsock.rs

Breaking change that allows you to specify which probe protocols you would like to run.
Really written so it is easier to test QUIC address discovery on `iroh doctor`, but this also allows us to test specific protocols in isolation.
- `iroh-net-report`
- added
- `net_report::Client::get_report_with_options`
- changed
- `net_report::Client::get_report_channel` now takes an `opts: net_report::Options`
- `net_report::Client` will no longer bind `UdpSocket`s when one is not provided for both STUN over IPv4 or STUN over IPv6.
I'm open to adjustments on the `Options`. The whole "we build a UDP socket for you if one isn't provided" bit means that I couldn't rely on, for example, `stun_sock_v4 == None` to know whether the user wanted to run a stun ipv4 probe, so I needed the `protocols: …

feat(net-report)!: add `net_report::Options` to specify which probes you want to run

---

Cargo.lock
Cargo.toml
iroh-dns-server/Cargo.toml
iroh-net-report/Cargo.toml
iroh-relay/Cargo.toml
iroh-relay/src/server.rs
iroh/Cargo.toml
iroh/bench/Cargo.toml

Updates `iroh-metrics` to `0.30.0` and `portmapper` to `0.3.0`
- `iroh-metrics` needs now to be `0.30.0`

feat!: update to iroh-metrics@0.30.0 and portmapper@0.3.0

---

iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/client_conn.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/streams.rs

The module is already called relay and all the text talks about the
relay protocol.  Might as well rename this.
The "RelayCodec protocol" is pretty lame for a name.  Any
music-inspired bikeshedding welcome.

refactor(iroh-relay): Rename DerpCodec to RelayCodec

---

iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/server/actor.rs
iroh/src/magicsock/relay_actor.rs

This moves the reconnection logic ingo ActiveRelayActor instead of
doing this in the RelayActor.  The logic itself is not really changed.
This does simplify things a fair bit though, it is a lot easier to do
this in one place where all the state needs to be.
In the grand scheme of things this moves "logical" control over the
relay Client entirely into the ActiveRelayActor.
Some small side effects:
- The ActiveRelayMessage::Ping and ActiveRelayMessage::GetLocalAddr
messages are no longer needed.  Though I decided to keep the latter
for testing purposes.
- ActiveRelayMessage::NotePreferred has been rename to SetHomeRelay.
Since the ActiveRelayActor now reconnects to relays on its own it
needs to keep track of whether it is the home relay itself as well.
- The duplicate ping task tracking in …

refactor(iroh, iroh-relay)!: Do reconnection in ActiveRelayActor

---

iroh/src/magicsock/relay_actor.rs
iroh/src/util.rs

Avoids the `Box::pin` inside of the loop

refactor(iroh): magical pin projections

---

iroh-base/Cargo.toml
iroh-base/src/relay_url.rs
iroh-net-report/src/lib.rs

This makes the `clone`ing of `RelayUrl` much cheaper. 
It turned out the whole code base was already using the `RelayUrl` as an immutable type already, so no changes otherwise necessary.

refactor(iroh-base): introduce an `Arc` into `RelayUrl`

---

iroh/src/magicsock/relay_actor.rs

This moves the logic of terminating an ActiveRelayActor from the
RelayActor to the ActiveRelayActor itself.  This is nice for two
reasons:
- The interactions between ActiveRelayActor and RelayActor are even
simpler.  RelayActor logic is now easy to reason about.
- It will allow ActiveRelayActor to manage reconnections with
exponential backoff better.  Currently this behaviour is not changed
but the RelayActor getting involved meant the backoff behaviour was
influcenced in two places.
Now that the ActiveRelayActor lifecyle is much more straight forward
the RelayActor's terminating is tidied up as well.

refactor(iroh): ActiveRelayActor terminates itself

---

.github/workflows/tests.yaml

Also fix building of tests to use --profile ci which is used to run
the tests.  The test run did not trigger a re-build.  So mosly likely
the profile is not encoded in the build artifacts and we were running
tests on the normal dev profile rather than the ci profile.

ci(*): Run flaky tests with --verbose and use ci profile

---

Cargo.lock
iroh/Cargo.toml
iroh/src/endpoint/rtt_actor.rs

also removes the `futures-concurrency` dep, which was adding a noticable slow down during compiles.
The cleanup now happens automatically when the stream ends, finished streams get removed and cleand up from `MergeUnbounded`.

refactor(iroh): simplify RTT actor

---

iroh/src/discovery/pkarr.rs
iroh/src/magicsock.rs
iroh/src/magicsock/node_map.rs
iroh/src/magicsock/node_map/node_state.rs

Cleanup some changes from #3024
- Cleans up some `is_empty` logic and naming
- fixes DNS publishing to only publish the relay url if one is available, and not the IP addresses
Manual testing confirms, this fixes a regression of connections flip flopping between mixed and direct
Closes #3081

fix: correctly set publishing details for pkarr records

---

.github/workflows/tests.yaml

We get very weird errors from nextest, I suspect this is a regression.
This version is 3 months old, which is probably something nice to try.
This does not yet do this everywhere, e.g. windows still installs the
latest.  But this is enough to see if it helps.

ci: Pin an older nextest version

---

Cargo.lock
iroh-relay/Cargo.toml
iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/client/streams.rs
iroh-relay/src/defaults.rs
iroh-relay/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/client_conn.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/metrics.rs
iroh-relay/src/server/streams.rs
iroh/Cargo.toml
iroh/src/endpoint.rs
iroh/src/magicsock/relay_actor.rs
iroh/src/util.rs

- local_addr is directly stored
- `Conn` is not clone anymore, and is only used via mutable reference
- no more buffering of writes
- removes `ClientConnBuilder` in favor of just a function `Conn::new`
- `Conn` is now private
- `Conn` is no longer an actor
- no more splitting of the TcpStream
- no more splitting of the Websocket stream
- `Client` is no longer an actor
Reworks the relay client and ActiveRelayActor.
- The relay Client is now a Stream and Sink, but a thin layer over the internal Conn.
- Most of the client work is now deferred to the ActiveRelayActor which can behave much better around this.
- The ActiveRelayActor now sends to the relay server in a future, so it can still respond to other events while sending.
- The ActiveRelayActor now handles HasNodeRoute without blocking, …

refactor(iroh-relay)!: Client without actors

---

Cargo.lock
iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/client/streams.rs
iroh-relay/src/defaults.rs
iroh-relay/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/client_conn.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/metrics.rs
iroh-relay/src/server/streams.rs
iroh/Cargo.toml
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/magicsock/relay_actor.rs
iroh/src/util.rs

This removes an actor by making it a stream.
The main (temporary) downside is that a read error no longer shuts down the Conn WriterTasks.  This will not be an issue for that long as the WriterTasks are going away next and then the Client can manage this.
The RelayDatagramRecvQueue is grown to 512 datagrams.  We used to keep this many frames in the per-relay stream.  Though that's potentially an awful lot.  For datagrams we can assume that they will at max settle close to 1500 bytes each, so this buffer will end up being 750KiB max.  That seems somewhat reasonable, though we could probably double it still.
There will effectively no longer be a per-relay buffer - other than inside the relay's TCP stream.
This does some other renaming, e.g. `ConnReader` is now a `ConnFrameStream` which is a …

refactor(iroh-relay): Make the ConnReceiver actor a ConnMessageStream

---

Cargo.lock
iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/client/streams.rs
iroh-relay/src/defaults.rs
iroh-relay/src/lib.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server.rs
iroh-relay/src/server/actor.rs
iroh-relay/src/server/client_conn.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/metrics.rs
iroh-relay/src/server/streams.rs
iroh/Cargo.toml
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/magicsock/relay_actor.rs
iroh/src/util.rs

This refactors how datagrams flow from the MagicSock (AsyncUdpSocket) to relay server and back.  It also vastly simplifies the actors involved in communicating with a relay server.
- The `RelayActor` managed all connections to relay servers.
- It starts a new `ActiveRelayActor` for each relay server needed.
- The `ActiveRelayActor` will exit when unused.
- Unless it is for the home relay, this one never exits.
- Each `ActiveRelayActor` uses a relay `Client`.
- The relay `Client` is now a `Stream` and `Sink` directly connected to the `TcpStream` connected to the relay server.  This eliminates several actors previously used here in the `Client` and `Conn`.
- Each `ActiveRelayActor` will try and maintain a connection with the relay server.
- If connections fail, exponential backoff is used …

fix(iroh, iroh-relay)!: Optimise the relay datagram path through the MagicSock

---

iroh/bench/src/bin/bulk.rs
iroh/bench/src/iroh.rs
iroh/bench/src/lib.rs
iroh/examples/transfer.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/magicsock/node_map.rs
iroh/src/magicsock/node_map/node_state.rs
iroh/src/util.rs

This will allow us to configure relay only mode at runtime. ~~Useful for easy testing without having to rebuild with the `DEV_RELAY_ONLY` environment variable set.~~
The `DEV_RELAY_ONLY` compile time env var has been completely dropped and a `relay_only` option has been threaded through the entire stack when `test-utils` is enabled. An example of it can be followed with the `iroh/examples/transfer.rs` where you can set up a provide and fetch node with `--relay-only`.

feat(relay)!: relay only mode now configurable

---

iroh-relay/src/server/clients.rs

refactor(iroh-relay): simplify structure in clients

---

iroh/src/discovery.rs
iroh/src/endpoint.rs
iroh/src/protocol.rs

The internal CancellationToke was used to know by other parts of the
code when the endpoint is shut down.  But those bits of code already
have mechanisms to do so.  This bit of API makes is a bit of extra
complexity that is not needed.
None, this is internal.
Closes #3096.
Closes #3098 (replaces).
Maybe not directly but now there's an example of how to write an
accept loop without having to rely on the CancellationToken.

refactor(iroh): Remove CancellationToken from Endpoint

---

iroh-relay/src/server/client.rs
iroh-relay/src/server/clients.rs

Bring back `connection_id`s and ensure that client connections remove themselves from the clients list when they are done.
Before, as pointed out in #3103 connections would not be cleaned up if no messages were sent to them anymore.
Based on #3103

fix(iroh-relay): cleanup client connections in all cases

---

iroh/src/dns/node_info.rs

Running `iroh-doctor` this morning with flub I wasn't able to connect. Flub was on iroh 0.30, I was on iroh main (commit c650ea83).
I noticed this in the logs:
```
2025-01-08T08:09:59.939435Z DEBUG connect{me=cabd2a9e0b alpn="n0/drderp/1"}:discovery{me=cabd2a9e0b node=1992d53c02}: hickory_proto::error: response: ; header 65474:RESPONSE:RD,RA:NoError:QUERY:3/0/0
; query
;; _iroh.dgjpkxyn3zyrk3zfads5duwdgbqpkwbjxfj4yt7rezidr3fijccy.dns.iroh.link. IN TXT
; answers 3
_iroh.dgjpkxyn3zyrk3zfads5duwdgbqpkwbjxfj4yt7rezidr3fijccy.dns.iroh.link. 30 IN TXT addr=192.168.96.145:60165
_iroh.dgjpkxyn3zyrk3zfads5duwdgbqpkwbjxfj4yt7rezidr3fijccy.dns.iroh.link. 30 IN TXT addr=213.208.157.87:60165
_iroh.dgjpkxyn3zyrk3zfads5duwdgbqpkwbjxfj4yt7rezidr3fijccy.dns.iroh.link. 30 IN TXT …
```

fix(iroh): Parse DNS answer with multiple records into a proper `NodeAddr`

---

iroh-relay/src/main.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server.rs
iroh-relay/src/server/client.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/testing.rs
iroh/src/test_utils.rs

Design RFC:  https://www.notion.so/number-zero/Relay-Authentication-16f5df1306fb80ac9e31c1ccb04e026b?pvs=4
- added: field `access` to `iroh_relay::server::RelayConfig`
- This reuses the `health` frame in the relay protocol to indicate the authentcation issue. The frame was previously never sent in our code, but is now more explicitly interpreted to disconnect from the server. 
- ~~Should the callback be `async`? If this does more complex things like access a DB we probably want this to be `async`.~~ it is now async

feat(iroh-relay)!: implement authentication

---

iroh/src/magicsock.rs

I've seen `test_relay_datagram_queue` fail on windows recently: https://github.com/n0-computer/iroh/actions/runs/12669553316/job/35307313406
Given that
- when the test failed, it took 720ms,
- when the test succeeded, it took 150ms and 320ms,
- we've got a 100ms timeout on one of the futures, and
- the tokio scheduler (I think) doesn't optimize for average job time,
I'm not convinced there's a race condition.
So, instead I'm rewriting the test to be less timing-dependent. And less confusing as well *and* have better logging.

test(iroh): Make `test_relay_datagram_queue` less timing dependent

---

iroh/src/discovery.rs

The flaky tests are being super weird and making no sense.  This is
clutching at straws for any hint.
/cc @ramfox 
Two slightly odd things I spotted while looking at this:
- The use of 240.0.0.1 as "bad" IP address returned in discovery.  Maybe one from the test nets in RFC 5737 would be better?
- The endpoints accept a connection and immediately drop it.  This could potentially send the CONNECTION_CLOSE before the ACK from the connection resulting in the connect call returning an error (BUT THAT WOULD BE A NORMAL READABLE TEST FAILURE).  This probably doesn't happen because it's all local and very fast and Quinn has already ACKed the connection before the code manages to drop it.  Still, essentially racy code.
Fine, I added a fix for the 2nd.  But it's not the issue.

tests(iroh): Add some context to test errors

---

README.md
iroh-relay/src/server/clients.rs
iroh/bench/src/lib.rs
iroh/examples/connect.rs
iroh/examples/transfer.rs
iroh/src/endpoint.rs
iroh/src/lib.rs
iroh/src/magicsock.rs

The only source for a `Result::Err` in `Endpoint::close` was a failed magic sock actor `Shutdown` message send.
This send should basically shutdown the actor, and sending only fails when the actor dropped the receiver, which only happens when the actor already shut down, gracefully or otherwise. In any case, it can't react to that anyways and it's not worth surfacing that error to the user.
- `iroh::Endpoint::close`'s future is now infallible, instead of returning a `Result`.

feat: Make `Endpoint::close` infallible

---

iroh/src/magicsock.rs

Closes #3067 
Since multiple `Connection`s can have multiple `AsyncUdpSocket` `IpPollers`, it's incorrect to assume that a single `AtomicWaker` can wake up these tasks correctly.
Instead, if there's only one `AtomicWaker` for all of them, only the last registered waker will be woken when there's capacity again.
I'm changing this such that `poll_writable` will actually add the current task's waker to a list, if it hasn't been added yet.
And successfully `recv`ing an item will wake all tasks.
A second issue was that *between* the call to `self.sender.capacity()` (it being 0) and `self.waker.register`, another thread might have successfully `recv`d an item *and* called `self.waker.wake()`.
This means that the first thread could've registered a waker, while the capacity is actually non-zero. …

fix: Try improving `relay_datagram_send_channel()`

---

iroh/src/discovery.rs

Nothing in the trait stops it from working for discovery structs which
are Arc'ed.  Not all discovery types are in control of the users so
this is helpful.
I stumbled upon this because StaticProvider is not Clone.

feat(iroh): implement Discovery for Arc'ed Discovery types

---

Cargo.lock
iroh-dns-server/Cargo.toml

`simple-dns` had a number of risky parsing calls that could go out of bounds and produce a segfault. Through the power of OSS and the daisy chain of bumped dependencies this should now be fixed.
Closes https://github.com/n0-computer/iroh/issues/2844

fix(dns): segfaults in pkarr

---

iroh/src/discovery.rs
iroh/src/discovery/static_provider.rs

This is not very useful without Clone, it already is Arc<RwLock<T>> on the inside so this clearly was intended.  Write a test demonstrating why this is needed.

fix(iroh): Implement Clone for StaticProvider discovery

---

.github/workflows/ci.yml
iroh/README.md
iroh/src/discovery.rs
iroh/src/discovery/static_provider.rs
iroh/src/endpoint.rs

Updates a bunch of docs around StaticProvider and links from the right places.
This also removes the ability to build docs without using --all-features.  The conditionals made things build but are not correct, items that should be documented on docs.rs were not.  This goes back to the simpler solution and documents for everyone how they should build docs.

docs(iroh): Update discovery docs, mostly StaticProvider

---

iroh-relay/src/lib.rs
iroh-relay/src/ping_tracker.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server/client.rs
iroh/src/magicsock/relay_actor.rs

Because of issues with TCP, we now send regular ping-pongs from client to server and vice versa.

feat(iroh-relay): send regular pings to check the connection

---

iroh-relay/README.md

config.toml must use [tls] instead of [tlsconfig]

docs(iroh-relay): README.md: config.toml must use [tls] instead of [tlsconfig]

---

iroh/src/magicsock/relay_actor.rs

The problem is that while the connection to the relay server is still
being established sent packets are already being dropped while being
queued to send.  This means when the connection is finally established
they are not there to be sent and depending on some scheduling luck
connections will often fail.  Extending this timeout makes
establishing connections via the relay only much more reliable.
"depending on scheduling luck" is a bit hand-wavy.  I would have
expected QUIC to recover from this and re-send the packets.  I think
it depends on exactly how long it takes to establish the connection,
re-tries could still end up being dropped in this queue if badly
timed.
It is hard to say if 3*PTO is sufficient.  There is an argument for
even longer, but it is a trade-off of blocking the …

fix(iroh): Queue sent datagrams longer

---

iroh/src/magicsock.rs

The signature of this function expects an error if the send fails, but
the relay part did not do this.  The impact of this is that you might
silently drop a packet, which makes debugging a bit harder.  Returning
an error should propagate this correctly and the failures will be
noticed and logged.

fix(iroh): Return error if disco send via relay fails

---

iroh-net-report/src/reportgen/probes.rs

Just what it says on the tin. From pattern matching the rest of the code, this seems like what it should be.

fix(iroh-net-report): Only add QUIC ipv6 probes if we have an ipv6 interface

---

Cargo.lock
iroh-dns-server/examples/convert.rs
iroh-dns-server/examples/publish.rs
iroh-dns-server/examples/resolve.rs
iroh-dns-server/src/lib.rs
iroh-net/Cargo.toml
iroh-net/README.md
iroh-net/bench/src/bin/bulk.rs
iroh-net/bench/src/lib.rs
iroh-net/examples/connect-unreliable.rs
iroh-net/examples/connect.rs
iroh-net/examples/dht_discovery.rs
iroh-net/examples/listen-unreliable.rs
iroh-net/examples/listen.rs
iroh-net/examples/locally-discovered-nodes.rs
iroh-net/src/bin/iroh-relay.rs
iroh-net/src/lib.rs
iroh-router/examples/custom-protocol.rs
iroh-router/src/lib.rs

Too many users are finding this crate and trying to use it.  Make it obvious where they should be looking instead.
Closes #3075.
- This targets the new `maint-0.28` branch which starts off the `v0.28.1` tag.
- Only the iroh-net crate has a new version number, I believe only publishing this crate makes the most sense.

feat(iroh-net): add deprecation notice, bump to 0.28.2

---

README.md

This PR fixes two trivial typos in the README file.
None
None

docs: Fix typos in README

---

iroh/src/endpoint.rs

Previously the TransportConfig was hardcoded for the
client (client/server in QUIC terminology: client initiates the
connection, server accepts the connection).  This rendered some
customisations on the server-side, as supported by the Builder,
impossible since the client would negotiate different limits.
Specifically the QUIC keep-alives were at a 1s or faster interval
while the connection timeout was at 30s or less.
This adds a new API marked as experimental which allows customising
the transport config for clients.
Secondly it also respects any custom TransportConfig set in the
Builder for clients as well as servers.  This is not a behaviour
change since the parameters set by default are now moved to the
Builder and due to how these are negotiated it does not matter that
the server …

feat(iroh): Allow customising the TransportConfig for connections

---

iroh/examples/listen-unreliable.rs
iroh/examples/listen.rs
iroh/examples/transfer.rs
iroh/src/endpoint.rs

The Connecting and Connection structs exposed IP addresses, these are
probably the NodeIdMappedAddresses rather than real ones.  We address
based on NodeId, so let's remove this stuff.
- `Connecting::local_ip` is removed.
- `Connecting::remote_address` is removed.
- `Connection::local_ip` is removed.
- `Connection::remote_address` is removed.
I didn't think long about this.  Getting this PR out so someone else
can think carefully about this.  :)

feat(iroh)!: Remove access to local and remote IP addresses

---

iroh/Cargo.toml

What it says on the tin.
Reasoning:
- We mostly advertise using `Endpoint::discovery_n0`, and none of our examples use `Endpoint::discovery_dht`.
- For the default case we stop depending on `mainline` needlessly (we can disable the `pkarr/dht` feature).
- The `discovery-pkarr-dht` feature became non-default (moved from opt-out to opt-in).

refactor!(iroh): Make `discovery-pkarr-dht` feature non-default

---

iroh-base/src/key.rs

This avoids a panic when calling `decode_mut` with an invalid input length.
Closes #3153

fix: handle invalid input length when parsing a node id

---

iroh/src/endpoint.rs
iroh/src/magicsock.rs

`quinn::Endpoint::wait_idle` adds a minimum 3 second closing time to `iroh::Endpoint::close` if you have any connections that have not closed gracefully. 
While we *want* users to close connections gracefully, we should also not be forcing users to wait 3 seconds to close the `iroh::Endpoint` if a connection has "gone wrong" if they don't want to.
So instead, we are taking out `quinn::Endpoint::wait_idle` and adding more context for how to close a connection gracefully.
Before 1.0 we will be re-visiting closing to make sure the APIs make sense.

fix(iroh): remove `quinn::Endpoint::wait_idle` from `iroh::Endpoint::close` process

---

iroh/src/magicsock.rs

This will result in a panic otherwise, if no default crypto provider is setup for rustls.

fix(iroh): ensure passing a crpyto provider to rustls clients

---

iroh-net-report/src/lib.rs
iroh/src/magicsock.rs

refactor(iroh): store quic config, instead of recreating

---

iroh-net-report/src/ping.rs

No matter what we do, pinging hosts on the internet is flaky, packets
do get lost.  We only care that we manage to send and receive pings
correctly, which we fully do by pinging localhost.

tests(iroh-net-report): Do not ping hosts on the internet

---

.github/workflows/ci.yml
Cargo.lock
iroh-net-report/Cargo.toml
iroh-net-report/build.rs
iroh-net-report/src/lib.rs
iroh-net-report/src/options.rs
iroh-net-report/src/ping.rs
iroh-net-report/src/reportgen.rs
iroh-net-report/src/reportgen/probes.rs
iroh-relay/Cargo.toml

This makes iroh-net-report compile to Wasm. We make sure it's likely to work by grepping the generated Wasm file for "env" imports (which would make it not work in browsers).
Mostly this will disable functionality in iroh-net-report for the browser target - specifically, it disables STUN, QAD, ICMP and all other probes besides HTTPS to relays.
I've experimentally verified this code works with an integration test, it's really hard to come up with a good strategy for automating this testing due to requiring running cross-languages.
I'd like to do that as a follow-up once #3145 is merged.

feat(iroh-net-report): Support wasm32 building & running

---

iroh-relay/src/quic.rs

Fix the test by not using a fixed port: that's asking for flakyness.
Add test ensuring that the connection still succeeds even after that
1s deadline exceeds.

Fix test, add test

---

iroh-relay/src/quic.rs

We reduce the RTT estimate for QAD connections. This means we don't wait as long for close frame acknowledgements when we abort these connection attempts.
Sooo no more 3s `Endpoint::close` time due to QAD probes never closing properly because they're sent into a black hole somewhere in the network path.
The 111ms is arbitrarily chosen to give us a 1s probe timeout. Let me know if I'm missing something important here.
Keep in mind this doesn't prevent us from connecting if the *actual* RTT is longer. The test ensures that.

feat(iroh-relay): Make `Endpoint::close` faster by aborting QAD connections faster

---

iroh/src/endpoint.rs
iroh/src/magicsock.rs

This adds a test case that checks that we can call `Connection::close` and actually receive the close code on the other side, indicating we've gracefully closed the connection.
Even though in the test we call `Endpoint::close` and wait for that, with current iroh 0.32, we don't receive the close frame. The only way I can see to make it work with iroh's 0.32 API, is to choose some time to sleep before calling `Endpoint::close`.
I've also attached a revert of #3165 which fixes the test, as that makes `Endpoint::close` wait for the close frames to be acknowledged again (by calling `quinn::Endpoint::wait_idle`).
There might be other ways to fix this, I welcome feedback on that. I do believe this is the right way to fix it, though.
Given that the `Endpoint::wait_idle` call has been introduced …

fix(iroh): Allow gracefully closing connections

---

iroh-dns-server/benches/write.rs
iroh-dns-server/examples/publish.rs
iroh-dns-server/examples/resolve.rs
iroh-dns-server/src/lib.rs
iroh-relay/src/dns.rs
iroh-relay/src/dns/node_info.rs
iroh/src/discovery.rs
iroh/src/discovery/dns.rs
iroh/src/discovery/local_swarm_discovery.rs
iroh/src/discovery/pkarr.rs
iroh/src/discovery/pkarr/dht.rs
iroh/src/discovery/static_provider.rs
iroh/src/magicsock.rs

Adds a `NodeData` struct that contains the information about a node that can be published in discovery services. This struct is both used in `iroh_relay::dns::NodeInfo` and in `iroh::discovery::Discovery`. Also, `iroh::discovery::DiscoveryItem` has no public fields anymore and uses `NodeInfo` internally to again reduce duplication. With these changes, the fields published about a node in discovery now are only defined in a single place.
This PR also serves these prupsoes:
* We want to add some "user defined data" to discovery (see #3176). This would add a third argument to `Discovery::publish`; with this PR instead we can just add it as an optional field to `NodeData`.
* It makes it possible to potentially add data to discovery after 1.0. The fields of `NodeData` are private, so we can …

refactor!: streamline discovery and node info types

---

iroh-relay/src/server/client.rs
iroh-relay/src/server/http_server.rs

The disconnects metric was accidentally removed and this has been
giving us wrong numbers since forever and it is so painful yet so easy
to fix.

fix(iroh-relay): Fix the number of active relay connections

---

.github/pull_request_template.md

In order to be better prepared for releases, we are trying to "front load" more work on understanding the effects of breaking changes in our downstream dependencies. Part of this is to remind folks to take a look at the downstream dependencies when they make a breaking change, and file an issue (or they have capacity), open a PR on how to deal with those breaking changes in that dependency.
The PR template looks like this now:

chore: add additional todos in the "change checklist"

---

iroh-dns-server/examples/publish.rs
iroh-dns-server/examples/resolve.rs
iroh-relay/src/dns/node_info.rs
iroh/src/discovery.rs
iroh/src/discovery/local_swarm_discovery.rs
iroh/src/discovery/static_provider.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs

**Based on #3175**
Adds support for publishing and resolving a string of user-defined data through Iroh's discovery services.
This gives applications a way to add additional information to the records published and resolved through discovery, in addition to the addressing information (relay URL and direct addresses). Iroh itself does not parse or use this user-defined data string in any way.
All existing discovery services are updated to support the user data. All DNS-based discovery services encode the user-defined data in a TXT record, in the same way as the DNS/pkarr services already encode the relay URL and direct addresses. Therefore, the length of the `user-data=<user-data>` string is limited to 255 bytes, which is the max length for a single character string in DNS messages. Thus, …

feat(iroh): publish and resolve user-defined data in discovery

---

Cargo.lock
deny.toml

Licensing details got updated for ring

chore(deps): update locked ring and deny.toml

---

Cargo.lock
iroh-relay/Cargo.toml
iroh-relay/src/server/client.rs

This got lost in https://github.com/n0-computer/iroh/pull/3093 and wasn't covered in https://github.com/n0-computer/iroh/pull/3194

fix(iroh-relay): bring back unique node counts

---

iroh-net-report/src/lib.rs
iroh/src/magicsock.rs
iroh/src/magicsock/udp_conn.rs

This factors out the socket & related state from `MagicSock` into a `SocketState` struct, as well as from the `Actor` struct into an `ActorSocketState` struct.
This helps reduce line noise in the `magicsock::Handle::with_name` function related to all the `#[cfg(not(wasm_browser))]`. 
In order to do this I needed to slightly modify how `UdpConn` is used.
We now work *more* with `Arc<UdpSocket>` rather than `UdpConn`, and treat `UdpConn` only as a wrapper to allow us to implement `quinn::AsyncUdpSocket` for `Arc<UdpSocket>`.
I've also moved the socket binding logic from `udp_conn.rs` to `magicsock.rs` and cleaned it up.
The main difference between `SocketState` and `ActorSocketState` is that the former stores `UdpConn` and the latter stores `Arc<UdpSocket>`, as the former uses its sockets …

refactor(iroh): Factor out socket-related state & construction into `magicsock::SocketState` and `ActorSocketState`

---

iroh-net-report/src/ip_mapped_addrs.rs
iroh-net-report/src/lib.rs
iroh-net-report/src/reportgen.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs

I find this whole port business of these mapped addresses very
confusing.  This attempts to document them better, make it clearer
that these SocketAddrs are made up and are not routable.
- `MAPPED_ADDR_PORT` is removed.
- `IpMappedAddr::socket_addr` -> `IpMappedAddr::private_socket_addr`

refactor(iroh, iroh-net-report)!: Make ports more private

---

.github/workflows/project_sync.yaml

Remove `iroh-s3` which is not tracked and add `iroh-roq`

fix: update project_sync

---

Cargo.lock
deny.toml
iroh/Cargo.toml
iroh/src/magicsock/relay_actor.rs

`backoff` is no longer maintained, upgrade path in cargo-deny indicates switching to `backon`.
There are some options in `backon` for using sleepers in the retry that are Wasm compatible: https://docs.rs/backon/1.4.0/backon/#sleep
I'm curious if we should be taking advantage.
Further questions:
~how do I resolve the `paste` cargo-deny issue?~
I don't: added `paste` and `humantime` advisories to the "allow" list

chore: switch from `backoff` to `backon`

---

README.md
iroh/examples/echo.rs
iroh/examples/search.rs
iroh/src/protocol.rs

Changes the `ProtocolHandler` trait to allow for intercepting `connecting` and `connection` states explicitly
- changed: `iroh::protocol::ProtocolHandler::accept` now takes `Connection` instead of `Connecting`
The new limiter could also just be part of the test code/an example, instead of giving users an API, unclear to me

feat(iroh)!: allow for limiting incoming connections on the router

---

iroh-relay/src/quic.rs

Switches QAD latency to be round-trip instead of single-trip to match STUN latencies.
Fixes #3225

fix(iroh-relay): Report round-trip-latency instead of single-trip for QAD

---

iroh/src/magicsock.rs
iroh/src/magicsock/node_map/node_state.rs

- Always return `false` in `want_call_me_maybe` in browsers, as we never actually want to send call me maybes, since there's no direct addresses we can put into these messages.
- Fix the shutdown logging in magicsock. Redundant warning were printed on graceful shutdown, and one was skipped in non-graceful shutdown.
Closes #3232

fix(iroh): Don't cause re-stuns all the time in browsers

---

iroh-relay/README.md

add feature "server" while running iroh-relay via cargo run

chore(iroh-relay): Fix README.md instuctions to enable `server` feature

---

iroh/src/magicsock/node_map/node_state.rs

Turns out we get this normally when they are just delayed due to
saturated traffic.  That's not something that's worth spamming WARN
all over the placed for.

fix(iroh): Reduce log-level of unknown pong message

---

Cargo.lock
Cargo.toml
iroh-dns-server/Cargo.toml
iroh-dns-server/src/util.rs
iroh-net-report/Cargo.toml
iroh-relay/Cargo.toml
iroh-relay/src/dns.rs
iroh-relay/src/server.rs
iroh/Cargo.toml

Updates hickory from 0.25-alpha.5 to hickory 0.25.1.
Depends on https://github.com/rkuhn/swarm-discovery/pull/15

chore(iroh): Update from alpha to release 0.25 hickory

---

iroh/Cargo.toml

We used to depend on `rustls-platform-verifier` through `quinn` via its `platform-verifier` feature.
We don't actually use that feature (it only provides `ClientConfig::with_platform_verifier()` as a fn, but we don't use it).
There's no changes to `Cargo.lock`, because we still pull in rustls-platform-verifier as a dev-dependency.

chore(iroh): Don't depend on unused `rustls-platform-verifier` dependency

---

Cargo.lock

We have a cargo-deny warning on main due to this tokio rustsec advisory: https://rustsec.org/advisories/RUSTSEC-2025-0023
Fix is to bump tokio, which this PR does.

deps: bump tokio to 1.44.2

---

Cargo.lock
Cargo.toml
iroh-dns-server/src/metrics.rs
iroh-relay/src/server/metrics.rs
iroh/Cargo.toml
iroh/bench/src/bin/bulk.rs
iroh/src/endpoint.rs
iroh/src/magicsock/metrics.rs
iroh/src/metrics.rs
iroh/src/net_report/metrics.rs

Based on #3262 
Depends on https://github.com/n0-computer/iroh-metrics/pull/18

refactor: use new derive macros from `iroh-metrics`

---

.github/workflows/ci.yml
.github/workflows/docs.yaml
.github/workflows/netsim_runner.yaml
.github/workflows/test_relay_server.yml
.github/workflows/tests.yaml
Cargo.lock

This is needed because of
https://github.blog/changelog/2025-03-20-notification-of-upcoming-breaking-changes-in-github-actions/#decommissioned-cache-service-brownouts

ci: update to mozilla-actions/sccache-action@v0.0.9

---

Cargo.lock
iroh-relay/Cargo.toml
iroh-relay/src/client.rs

Use a new macro from nested-enum-utils to DRY the strum error enums. One example.
Adds a dependency.
Should we reexport common_fields from n0_snafu?

use macro to DRY the snafu error enum

---

Cargo.lock
Cargo.toml
deny.toml
iroh-dns-server/Cargo.toml
iroh-dns-server/src/http.rs
iroh-dns-server/src/http/doh/extract.rs
iroh-relay/Cargo.toml
iroh/Cargo.toml
iroh/src/test_utils.rs

Depends on https://github.com/n0-computer/tokio-rustls-acme/pull/25
Closes #3273

feat: update to axum@0.8

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/src/metrics.rs
iroh-dns-server/src/server.rs
iroh-relay/Cargo.toml
iroh-relay/src/server.rs
iroh-relay/src/server/metrics.rs
iroh/Cargo.toml
iroh/bench/Cargo.toml
iroh/src/endpoint.rs
iroh/src/magicsock/metrics.rs
iroh/src/metrics.rs
iroh/src/net_report/metrics.rs

Updates #3262 to the latest changes in iroh-metrics (see PRs below)
Depends on #3262
Depends on https://github.com/n0-computer/net-tools/pull/23
Depends on https://github.com/n0-computer/iroh-metrics/pull/22
Depends on https://github.com/n0-computer/iroh-metrics/pull/23
- https://github.com/n0-computer/iroh-gossip/pull/62
- https://github.com/n0-computer/iroh-blobs/pull/85

refactor: update to latest iroh-metrics branch

---

iroh-relay/Cargo.toml
iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/client/tls.rs
iroh-relay/src/dns.rs
iroh-relay/src/node_info.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/protos/stun.rs
iroh-relay/src/quic.rs
iroh/src/magicsock/relay_actor.rs

- Converts more relay client side errors to snafu
- Removes thiserror dependency, unless server feature is enabled
- Completely removed `HandshakeError` and simply pass through the `relay::protos::Error`
Yes, the error types.
Renamed `ConnSendError` to `SendError`, to align with `RecvError`.

feat(iroh-relay): Convert all client-side errors to snafu

---

iroh/src/endpoint.rs

Allows connecting with multiple ALPNs so you can actually take advantage of ALPN also on the connecting side to support connections with older accept sides.
This only implements this via the `ConnectOptions`, which I think is fair? I generally like the pattern of `connect` -> `connect_with_opts`, and I don't think this is worth changing `connect` for.
Closes #2949

feat(iroh): Allow connecting with "fallback" ALPNs

---

Cargo.lock
deny.toml
iroh/examples/echo.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/protocol.rs
iroh/src/tls.rs
iroh/src/tls/name.rs
iroh/src/tls/resolver.rs
iroh/src/tls/verifier.rs

This is code that will both update deps like #3288 but also makes 0-RTT tests pass again. 
They were failing due to a [change in `rustls`](https://github.com/rustls/rustls/releases/tag/v%2F0.23.24):
> Behavior change: Clients no longer offer resumption between different `ClientConfig`s that share a resumption store but do not share server certificate verification and client authentication credentials. If you share a resumption store between multiple `ClientConfig`s, please ensure their server certificate verification and client authentication credentials are also shared. Please read the new documentation on the `ClientConfig::resumption` item for details.
>
> Additionally, if you share a resumption store or ticketer between multiple `ServerConfig`s, please see the new documentation on …

fix(iroh)!: Update dependencies & fix 0-RTT with newer rustls by pulling the expected `NodeId` out of the `ServerName` in verifiers

---

iroh-relay/src/relay_map.rs
iroh/bench/src/iroh.rs
iroh/examples/transfer.rs
iroh/src/defaults.rs
iroh/src/net_report.rs
iroh/src/net_report/reportgen.rs
iroh/src/test_utils.rs

In our examples and tests, it is enough to build `RelayMap`s from a single `RelayUrl`, but our users will more likely be in the situation where they have multiple relays.
Now we have `From<RelayUrl>`, `From<(RelayUrl, u16)>`, `FromIterator<RelayUrl>` `FromIterator<(RelayUrl, u16)>` impls to create a `RelayMap`.
Also, `From<RelayUrl>` and `From<(RelayUrl, u16)>` to create a `RelayNode`.
- iroh
- remove
- `pub fn default_from_node(url: RelayUrl, stun_port: u16) -> RelayMap`
- change
- `pub fn from_url(url: RelayUrl) -> RelayMap`, use `From<RelayUrl>` instead

feat(iroh-relay)!: adjust APIs to make it easier to create `RelayMap`s from lists of `RelayUrls`

---

iroh-relay/src/server.rs
iroh-relay/src/server/client.rs
iroh-relay/src/server/clients.rs

This is a fix to the iroh-relay server.
Current situation: If a client stream becomes full (because the client is not reading fast enough from the network), the internal queue where messages to that client are queued becomes full too. Now, when another client wants to send a message to the filled-up client, instead of skipping over the message we propagate the error such that the sending client's actor dies. This is bad, we should instead just drop the message.
This PR changes the behavior to log the failed forward (at WARN level) but does not stop the sending client's actor.
It also adds a test that fails without the change and passes with the change.

fix(iroh-relay): don't stop relay client actor if queues become full

---

iroh-dns-server/examples/publish.rs
iroh-dns-server/src/store.rs
iroh-dns-server/src/store/signed_packets.rs
iroh/src/discovery/pkarr.rs

#3186 introduced a backwards-incompatible change to the iroh-dns-server database that went uncaught so far.
The serialization format for SignedPackets changed between pkarr v2 and pkarr v3: pkarr v3 prepends a `last_seen` timestamp (8 bytes) to the serialized representation of a SignedPacket. Therefore, parsing packets stored in the the database with pkarr v2 (iroh-dns-server v0.34 and lower) fails with an error. The error also stops the store actor, and thus all subsequent requests will fail as well.
This PR changes this by attempting to parse the packet in the pkarr v2 format if parsing as pkarr v3 packet fails. Parsing as pkarr v2 is achieved by prepending 8 zero bytes to the payload (an empty last_seen timestamp).
The PR also improves the tracing logging at various places.
There's no …

fix(iroh-dns-server): Backwards compatibility for packets stored with iroh-dns-server v0.34 or lower

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/examples/publish.rs
iroh-dns-server/src/store.rs
iroh-dns-server/src/store/signed_packets.rs
iroh/src/discovery/pkarr.rs

Based on #3295 
I noticed in the debug logs of our staging server that some entries in the expiry table were never deleted, and thus they were processed again and again on each expiry tick.
This PR has the following changes:
* Bugfix: When upserting a packet, we were not properly clearing the *old* expiry entry! [This line](https://github.com/n0-computer/iroh/blob/f3c9af35542a7f2e00303090d1ca5273f86bc375/iroh-dns-server/src/store/signed_packets.rs#L148) is wrong: It should be `existing.timestamp()`, because that's the entry we want to remove, not the (not-yet-existing) entry for the timestamp of the *new* packet.
* Improve type handling and debug formatting around expiry timestamps, to make logs better readable and be less error prone to bad type conversions
* When an expiry entry is …

fix(iroh-dns-server): Fixes for packet expiry

---

iroh-relay/src/client/conn.rs
iroh-relay/src/client/streams.rs
iroh-relay/src/server/streams.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/net_report.rs

The newly released Rust 1.87 apparently makes some clippy lints for large enum or error variants tick earlier than before, and some other lints got stronger too.
See any recent PR run, e.g. https://github.com/n0-computer/iroh/actions/runs/15063556139/job/42343263605?pr=3309
This adds the fixes as applied by `clippy --fix`, and adds `allow`s for the large variants. Not sure if we actually would want to care about these large variants?

chore: make clippy 1.87 happy

---

iroh/src/protocol.rs

Currently, when `Router::shutdown` is called, we shutdown the endpoint and await the futures returned from `ProtocolHandler::shutdown` concurrently. This means that `ProtocolHandler::shutdown` cannot actually gracefully close their connections, because `Endpoint::close` is already called at the same time, which closes all connections immediately with an error code `0`.
This PR changes the shutdown order such that `ProtocolHandler::shutdown` is called and awaited first, and `Endpoint::close` afterwards.
I also added a test that fails without this change and passes now.

feat(iroh): Allow protocols to gracefully shutdown connections

---

iroh/Cargo.toml
iroh/examples/0rtt.rs
iroh/src/tls.rs

A simple 0rtt ping protocol client and server.
None
Note: we need a way to wait for a TLS session ticket. A fixed delay is quite crude.
Note: it would be nice to be able to configure how many NewSessionTicket messages get emitted

example: Example for 0rtt that can also serve as a benchmark

---

README.md
iroh/examples/echo.rs
iroh/examples/search.rs
iroh/src/endpoint.rs
iroh/src/protocol.rs

This changes the `ProtocolHandler` trait so that the functions return `impl Future` instead of `BoxFuture`, which means implementors can simply implement the trait with `async fn`. We don't even need a `'static` bound on these futures, so you can use `&self` freely without cloning and moving.
Internally, we still box the futures return by `accept`, `on_connecting` and `shutdown`. So performance wise this change should not have any effects. But the boxing is hidden from the user and implementing the trait now feels a lot more normal and simpler.
* `iroh::protocol::ProtocolHandler` methods now return `impl Future` instead of `BoxFuture`. You can simply remove the `Box::pin(async move {})` from the implementations and instead implement the methods as `async fn`. See the updated documentation …

feat(iroh)!: make ProtocolHandler use async functions

---

iroh-relay/src/quic.rs

The linux runner can sometimes be very slow. This test is currently flaky, but only in that it takes a few more milliseconds to complete. Added some time to the duration to remove the flaky-ness.

test(iroh-relay): add 300ms timeout to the `test_qad_client_closes_unresponsive_fast` test

---

iroh/src/discovery.rs
iroh/src/discovery/pkarr.rs

A couple of variants where only used internally, and the the `NodeId` variant had the same semantics as `NoResults`, so they can be merged.
- Some variants of the `iroh::discovery::DiscoveryError` have been changed

refactor(iroh)!: simplify discovery errors

---

iroh/examples/echo.rs
iroh/examples/search.rs
iroh/src/protocol.rs

To me, this reads much nicer in the examples etc. 
- `iroh::endpoint::ProtocolError` -> `AcceptError`

refactor(iroh)!: rename ProtocolError to AcceptError

---

iroh/src/endpoint.rs

The return type of `Endpoint::node_addr` has a lifetime bound on `&self`, only in the wasm_browser version. I think this is an oversight, we should not have different signatures for different targets. This PR fixes it.

fix: remove unneeded lifetime bound for watcher in wasm

---

iroh/src/lib.rs

Re-export the `n0_watcher::Watcher` so it is easier for our users to use heavily relied on methods like `Endpoint::node_addr`.
This becomes especially painful when you are working on any protocols using iroh.
Should this be exported from a different module? `iroh::endpoint::Watcher`?

feat(iroh): re-export `n0_watcher::Watcher` trait

---

Cargo.lock
iroh-base/src/key.rs
iroh-dns-server/Cargo.toml
iroh-dns-server/examples/publish.rs
iroh/examples/0rtt.rs
iroh/examples/connect-unreliable.rs
iroh/examples/connect.rs
iroh/examples/listen-unreliable.rs
iroh/examples/listen.rs
iroh/examples/transfer.rs

Closes #3363
- `Display` implementation was removed for `SecretKey`, use `.to_bytes()` and encode as hex to get the previous bytes explicitly

fix(iroh-base)!: remove display impl for SecretKey

---

iroh-base/src/ticket.rs
iroh-base/src/ticket/node.rs

Adds a `From` impl for `postcard::Error`, and adds `ParseError::verification_failed` and `ParseError::wrong_prefix` methods.
Should we add a variant to `ParseError` for a more "open ended" error, like we do for `protocol::AcceptError`? Something like `ParseError::Custom`?

feat: add methods to create variants of the `iroh-base::ticket::ParseError` enum.

---

iroh/src/magicsock/transports/relay/actor.rs

This adds the timeout used to the error.  This error ends up being logged, knowing the actual timeout exceeded is kind of useful.
None
My first attempt at using snafu.  Hopefully this is about right.

feat: Add the timeout duration to the relay dial error

---

iroh/src/magicsock/node_map/udp_paths.rs
iroh/src/net_report.rs

If an endpoint only has a single relay URL configured in its relay map, we currently abort the QAD net reports after a single successful report. However, we also decide whether an endpoint supports IPv6 on the fact if a QAD IPv6 report completed successfully or not. Those are *two* reports though, and if we abort after the first one, we falsely assume that the endpoint has no IPv6 connectivity.
This PR changes this in a rather simple way: If we did start both IPv4 and IPv6 reports, we always wait at least until one of each completed.
Unrelated to this change, the PR also adds logging when the best address changes.

fix: wait for at least one ipv6 and ipv4 qad report

---

iroh/src/lib.rs

Really small grammar check, no breaking issues I'm aware of. "allows to" isn't a phrase that is technically correct.
"To address this, the thing allows for the configuration of a discovery service." could work too, but I prefer using "you" in instructions to make things just the littlest bit less abstract.

docs: grammar nitpick

---

Cargo.lock
iroh-relay/src/server/http_server.rs
iroh/src/discovery/pkarr/dht.rs

- Wrote a test checking that accepts == disconnects in relay metrics
- Fixed duplicate accept counts
Bug was originally introduced in #3384: We used to `metrics.relay_accepts.inc()` or `metrics.websocket_accepts.inc()` and I thought there should be a replacement for these calls, `metrics.accepts.inc()` (along with removing the above two).
Turns out the accepts are already tracked somewhere else, so I ended up counting them twice.

fix(iroh-relay): Don't double-count connection accepts

---

iroh-relay/src/protos/relay.rs
iroh/src/magicsock.rs
iroh/src/magicsock/transports.rs
iroh/src/magicsock/transports/relay.rs
iroh/src/magicsock/transports/relay/actor.rs

This does the re-batching inside `RelayTransport` by storing a `pending_item: Option<RelayRecvDatagram>`.
When we `poll_recv`, we first try to use that pending item instead of polling a new one.
Once we've got a pending item, we try to split off as much from it as can possibly fit into our receive buffer and handle that.
- `iroh_relay::protos::relay::Datagrams::take_segments` now return `Datagrams` instead of `Option<Datagrams>`, not distinguishing the case where `Datagrams` might be empty.
Probably needs some test.
I'd love to test two `RelayTransport`s talking to each other with different `max_transmit_segments`/`max_receive_segments`, but I'm not sure I can make such a test setup happen easily.

refactor(iroh): Re-batch datagrams inside `RelayTransport` instead of the `ActiveRelayActor`

---

iroh-relay/src/dns.rs

Adds a random jitter to DNS retries called with the `stagger_call` function.
N/A
Further research can determine if additional timeout jitters are needed when calling the other DnsResolver public functions.
Nominal 20% of default delay time as maximum deviation from original timeout delay.  Real world and lab testing can dermine if this is sufficient.
Partially addresses #3017.

fix(iroh): add jitter to dns retry calls

---

iroh-base/src/key.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/magicsock/transports/relay/actor.rs

Currently, fmt_short allocates a String. It is used quite a few times in trace! statements. This makes it not allocate.
Not sure if it is worth it.

feat: Make fmt_short return an impl Display so we can avoid an allocation.

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/src/store/signed_packets.rs

We are using redb in iroh-dns-server. The recently released redb v3 has incompatible changes to the database format. The recommended upgrade procedure is to upgrade the database with `Database::upgrade` on redb v2.6+. The upgrade has to be done on redb v2, not v3. See https://github.com/cberner/redb/blob/master/CHANGELOG.md#removes-support-for-file-format-v2.
This updates redb to 2.6 and performs the upgrade when opening the database. Calling upgrade on an already upgraded database is a no-op.
With this merged in the next release, we can then update redb to v3 in the version after.

feat: upgrade redb to v3 compatible format

---

iroh-relay/src/dns.rs
iroh-relay/src/node_info.rs

Replaces #2116 
Fixes #3468
This adds a `Resolver` trait to abstract over DNS resolution. It contains methods to resolve IPv4 or IPv6 addresses, and TXT records. Because the trait needs to be dyn-compatible for our usage (we don't want to have a generic for the DNS resolver on the Endpoint), all methods return boxed futures that contain boxed iterators. 
To not pay the cost of boxing when using the default hickory-based resolver, the iroh `DnsResolver` internally contains an enum which is either the default resolver or the boxed custom resolver.
Users can implement the `Resolver` trait on whatever struct to use a completely custom DNS resolver.
Changes in `iroh_relay::dns` (reexported from `iroh::dns`):
*  `DnsResolver::lookup_txt` now returns `impl Iterator<Item = TxtRecord>`
* …

feat: add a DNS resolver trait

---

iroh/src/endpoint.rs
iroh/src/magicsock/node_map/node_state.rs

So rough description of what was happening:
- the errors got swallowed but nuked the loop so it failed silently - fixed that
- the 0rtt tries connecting on the new port/addr but still prefers the old path so needs to wait out for the path invalidation to do it's job before it continues to work
Being slow enough made it sometimes pass. Locally now tests pass ~instantly vs 15 seconds or so after the fix to gracefully handle errors.
I'm unsure if this is safe at all, like handling path updates from other angles or partial updates etc.
If it turns out too risky, we can drop the path invalidation changes and just keep the graceful error handling. Tests will pass.

fix: 0rtt flakes

---

iroh/examples/0rtt.rs
iroh/examples/transfer.rs
iroh/src/discovery.rs
iroh/src/endpoint.rs
iroh/src/magicsock.rs
iroh/src/protocol.rs

Turns out we just need to call the init early enough. 
Thanks to @flub for reminding me of this
- changed
- `iroh::Endpoint::watch_node_addr` now returns a watchable for `NodeAddr` not `Option<NodeAddr>`
Currently this means that in wasm we have a different signature for `watch_node_addr()` because it can be empty, need some feedback on how to solve this

feat(iroh)!: make direct_addresses always be initialised
