n0-computer/iroh

iroh-metrics/src/lib.rs

lol I was dumb and while working on it just tested the tracing part. Uncommented metrics before push...

fix: prom metrics no longer ping on --no-metrics

---

iroh-gateway/Cargo.toml
iroh-p2p/Cargo.toml
iroh-p2p/src/main.rs

We need to move to configs/repos soon.

fix: add --no-metrics support to p2p

---

iroh-metrics/Cargo.toml

Closes https://github.com/n0-computer/iroh/issues/54

fix: drop openssl requirement

---

iroh-gateway/src/client.rs
iroh-p2p/src/rpc.rs
iroh-resolver/src/resolver.rs
iroh-rpc-client/src/network.rs
iroh-rpc-types/proto/p2p.proto

fix: require passing providers to fetch_bitswap

---

Cargo.toml
examples/Cargo.toml
examples/src/bin/importer.rs
iroh-resolver/src/lib.rs
iroh-resolver/src/resolver.rs
iroh-rpc-client/src/store.rs
iroh-rpc-types/proto/store.proto
iroh-store/src/rpc.rs
iroh-store/src/store.rs

Allows for easy importing of car files into `iroh-store`
Also adds
- `store.has` to check for existence
- checks for stored elements before writing when calling `store.put`

feat: add car importer

---

iroh-gateway/Cargo.toml
iroh-gateway/src/core.rs

closes https://github.com/n0-computer/iroh/issues/74

fix: tracing on request level

---

iroh-gateway/Cargo.toml
iroh-gateway/README.md
iroh-gateway/src/client.rs
iroh-gateway/src/config.rs
iroh-gateway/src/constants.rs
iroh-gateway/src/core.rs
iroh-gateway/src/headers.rs
iroh-gateway/src/lib.rs
iroh-gateway/src/response.rs
iroh-gateway/src/templates.rs
iroh-gateway/templates/dir_list.hbs
iroh-resolver/src/resolver.rs

Closes https://github.com/n0-computer/iroh/issues/61

feat: gateway upgrade

---

Cargo.toml
iroh-bitswap/Cargo.toml
iroh-gateway/Cargo.toml
iroh-p2p/Cargo.toml
iroh-p2p/src/keys.rs
iroh-p2p/src/main.rs
iroh-p2p/src/service.rs
iroh-rpc-client/Cargo.toml

Includes https://github.com/libp2p/rust-libp2p/pull/2714 for metrics fixes

fix: add missing metrics and update to fixed libp2p

---

iroh-gateway/src/core.rs

closes https://github.com/n0-computer/iroh/issues/122

fix: params

---

iroh-p2p/src/behaviour.rs
iroh-p2p/src/behaviour/event.rs
iroh-p2p/src/node.rs
iroh-p2p/src/rpc.rs
iroh-rpc-client/Cargo.toml
iroh-rpc-client/src/network.rs
iroh-rpc-types/build.rs
iroh-rpc-types/proto/gossipsub.proto
iroh-rpc-types/proto/p2p.proto
iroh-rpc-types/src/gossipsub.rs

feat(p2p): add `gossipsub` to p2p node & `gossipsub` rpc methods

---

iroh-p2p/src/behaviour.rs
iroh-p2p/src/node.rs
iroh-p2p/src/swarm.rs
iroh-rpc-client/src/network.rs

- NICE optimization based on https://www.diva-portal.org/smash/get/diva2:436670/FULLTEXT01.pdf

feat(p2p): refresh kad buckets & rebootstrap regularly

---

iroh-gateway/src/config.rs
iroh-p2p/src/config.rs
iroh-store/src/config.rs

🤷 ~~guess this fixes it?~~ or not, worked locally...

fix: fix builds

---

LICENSE-APACHE
LICENSE-MIT
README.md

add license files, update readme

---

README.md

This PR includes some minor readme improvements:
- Grammar fixes
- More details for iroh cloud and mobile, pulled from prior literature

Readme kaizen

---

README.md

Add a bit of text on how to build iroh; what I bumped into.

Explain a bit about how to build it

---

iroh-gateway/Cargo.toml
iroh-gateway/src/handlers.rs

Verified with Firefox's devtools.

Enable the CompressionLayer middleware

---

CONTRIBUTOR.md
DEVELOPERS.md
README.md
code_of_conduct.md

docs: instructions and tips for contributors and developers

---

DEVELOPERS.md

When setting up a freshly installed Linux laptop with Fedora I ran into a few more issues building. I've documented them here.

docs: a few more build notes

---

iroh-gateway/Cargo.toml
iroh-gateway/src/bad_bits.rs
iroh-gateway/src/config.rs
iroh-gateway/src/error.rs
iroh-gateway/src/handlers.rs
iroh-gateway/src/headers.rs

Closes https://github.com/n0-computer/iroh/issues/96 & https://github.com/n0-computer/iroh/issues/93 along with some auxiliary bits.
Part of https://github.com/n0-computer/iroh/issues/277

gateway: spec compliance part 2

---

iroh-store/src/store.rs

As discussed on discord. Implements #352

Remove record level versioning

---

.github/workflows/ci.yml
iroh-util/src/lock.rs

found the source of the issue: the source is process forking on macOS after High Sierra. Solution: https://github.com/rails/rails/issues/38560#issuecomment-1159834445
Asmir, feel free to just merge this one upon approval

fix broken macos github action

---

iroh-resolver/src/resolver.rs

fix(resolver): ipld, double-fetching, and trailing slash fixes

---

DEVELOPERS.md
quickstart.md

rename iroh-ctl to iroh in quickstarter.md

fix : binary name iroh-ctl

---

DEVELOPERS.md

Improve wording for a minor typo.

docs(developers): Minor typo fix

---

xtask/src/main.rs

much easier to do multi-arch builds with buildx, at the cost of taking eons & needing every resource the computer has. This is mainly here to document the technique for later inclusion in CI, and for my own quality of life

chore: add docker buildx xtask

---

iroh-gateway/src/handlers.rs

fix: breadcrumb links in gateway directory template

---

.github/workflows/ci.yml

@fabricedesre based on the discussion in https://github.com/n0-computer/iroh/pull/221

chore(ci): add iroh-one to binary builds

---

Cargo.toml
iroh-p2p/src/node.rs

The PR you all have been waiting for

feat: switch to released libp2p@0.50

---

iroh-p2p/Cargo.toml
iroh-p2p/src/config.rs
iroh-p2p/src/node.rs
iroh-p2p/src/swarm.rs
iroh-rpc-types/src/addr.rs
iroh-share/src/p2p_node.rs

feat: enable quic transport

---

iroh-one/src/uds.rs

That should never have been in...

(chore) Remove dead code

---

iroh-unixfs/src/chunker.rs

chore(ci): make clippy happy again

---

iroh-gateway/src/client.rs
iroh-gateway/src/handlers.rs

We never really completed resolving a path at the top and verifying some checks against it. 
Also threaded it through so we don't re-resolve.

fix: actually resolve and check paths

---

iroh-bitswap/src/client.rs
iroh-gateway/src/config.rs
iroh-gateway/src/constants.rs

Fix may address #369 but extra tests are required. It helped for my case.
Also, I've added some headers for CORS. Opened to discussion
I'm not sure every header is needed but all headers I have taken from kubo.

feat: Refine headers and block channel size

---

iroh-util/src/lock.rs
stores/flatfs/examples/read.rs
stores/flatfs/examples/stats.rs
stores/flatfs/src/flatfs.rs
stores/rocks/examples/importer.rs
stores/rocks/src/fs.rs

This not fully fix beta clippy right now yet because par-stream
breaks.
Part of #626

chore(clippy): Fix new clippy errors

---

src/protocol.rs
src/provider.rs

The implementation uses a BytesMut buffer to efficiently read protocol
messages from the network connections.  The way read_lp was combining
both reading the length-prefixed message and decoding it resulted in
the caller having to remember to advance the BytesMut buffer before
using it again.  That is error prone.
This reduces the function of the read_lp() function to only read the
raw message from the network.  It returns a new Bytes object and the
passed in BytesMut is in a safe state with all internal indexes
correctly advanced.
The caller is now responsible for calling postcard::from_bytes using
the returned Bytes, read_lp() can not both create the Bytes and return
a parsed struct from it due to lifetimes.  Overall this isn't any more
complicated to use and results in less error-prone …

ref: Improve safety of BytesMut buffer usage

---

.github/workflows/netsim.yml

depends on https://github.com/n0-computer/chuck/pull/3

fix(ci): move from sendme to iroh

---

src/main.rs

This shows sizes in KiB, MiB etc.  Also adds a few totals and transfer
summaries.

feat: Show more numbers in human readable form

---

tests/cli.rs

- adds context in `assert_matches_line` about which line failed to be read
- this... shouldn't really make a difference, but just in case: make sure the `getter` command is dropped before testing the output
- test the success of the `get` command before testing the progress output
Hopefully with these combined, we can get more information out of the flakey failing linux tests seen here:
https://github.com/n0-computer/iroh/actions/runs/4282332291/jobs/7456474101
-----
Edit:
flakey tests were fixed by #804 
This is now just a PR to improve the error reporting

add more context for `cli_provide` test errors

---

Cargo.lock
Cargo.toml
deny.toml
src/lib.rs
src/net.rs

Based on the work done in `x-hp`.

feat(net): implement local address detection

---

Cargo.lock
Cargo.toml

caution: this is not compatible with existing iroh/sendme

feat: use chunk groups feature

---

src/main.rs
src/provider.rs
src/rpc_protocol.rs

Implements https://github.com/n0-computer/iroh/issues/806
What about events? Should we expose those as well?

Id and shutdown

---

Cargo.lock
Cargo.toml
proptest-regressions/provider.txt
src/main.rs
src/main_util.rs
src/provider.rs
src/provider/database.rs
src/provider/mod.rs
src/util.rs
tests/cli.rs

Persists
- outboards in files named by their hash, in $IROH_DATA_DIR/outboard
- collections in files named by their hash, in $IROH_DATA_DIR/collections
- metadata in $IROH_DATA_DIR/paths.bin
- keypair in $IROH_DATA_DIR/keypair unless explicitly passed via key
Persistence is manual for now, gets triggered on control-c.

Basic persistence

---

src/lib.rs
src/provider/mod.rs

This is needed to improve the UX in DeltaChat from the sender side.

feat(provider): emit events about outgoing transfers

---

.github/workflows/netsim.yml

- Fixes some edge cases for the CI (not detecting the branch or commit correctly)
- Ensure all data is properly dumped
- Allows to supply a custom config to run against netsim by posting a comment on a PR with `/netsim config ```...``` `

feat: custom configs for netsim

---

src/hp/derp/client_conn.rs
src/hp/derp/clients.rs
src/hp/derp/server.rs
src/hp/derp/types.rs

impl the ServerActor, that does all the work of coordinating traffic on the server, including sending packets, forwarding packets, adding & removing clients, adding & removing packet forwarders, adding "watchers" (verified peers in the mesh that need to be kept informed about the topology of the network),  and shutting down the server.

impl derp `ServerActor`

---

.github/workflows/ci.yml
src/blobs.rs
src/get.rs
src/lib.rs
src/main.rs
src/provider/mod.rs
tests/cli.rs

And a bunch of other things
- make collection fields private so that creation has to be via a constructor
- make docs creation use stable toolchain

Remove collection name

---

Cargo.lock
Cargo.toml
src/main.rs
src/provider/mod.rs
src/rpc_protocol.rs
src/util.rs

Use an indicativ multiprogress bar.

Progress for adding files

---

Cargo.lock
Cargo.toml
src/main.rs
src/provider/database.rs
src/provider/mod.rs
src/rpc_protocol.rs
src/util.rs

Also give validate some progress niceness...

Validate progress

---

Cargo.lock
src/get.rs
src/main.rs
src/net.rs
src/provider/mod.rs
src/rpc_protocol.rs
tests/cli.rs

@dignifiedquire this also includes a quick and dirty test for the IPs. Think this is more stable & sufficient compared to the netsim integration tests.
@flub I used pieces from your PR on https://github.com/n0-computer/iroh/pull/820 and made a utility function. Potentially you can reuse (or I depending who merges first).
Closes https://github.com/n0-computer/iroh/issues/858

feat: cmd to list provide addrs

---

Cargo.lock
Cargo.toml
src/hp/derp/client.rs
src/hp/derp/client_conn.rs
src/hp/derp/clients.rs
src/hp/derp/http.rs
src/hp/derp/http/server.rs
src/hp/derp/server.rs
src/hp/derp/types.rs
src/hp/magicsock/conn.rs

also remove the unneeded `Conn` trait and its implementations!

impl httpderp connection handler

---

Cargo.lock
Cargo.toml
src/bin/derper.rs
src/hp/key/disco.rs
src/hp/key/node.rs

Implementation of bin/derper

---

src/get.rs
src/lib.rs
src/main.rs
src/protocol/mod.rs
src/provider/mod.rs

For now Request has only got 1 case, but this is in preparation for the custom request

Provider refactor and protocol change in preparation to introducing custom requests

---

Cargo.lock
Cargo.toml
src/get.rs
src/lib.rs
src/main.rs
src/protocol/mod.rs
src/provider/mod.rs

This builds on the refactor to make multiple requests possible, and actually does add the custom request.

Actually add the custom request handler

---

src/hp/derp/clients.rs
src/hp/derp/http/client.rs
src/hp/derp/server.rs
src/hp/magicsock/conn.rs

Current state: hangs on trying to establish a connection (most of the time)

fix magic tests on linux

---

src/hp/derp.rs
src/hp/magicsock/conn.rs
src/hp/magicsock/endpoint.rs
src/hp/netcheck.rs

fix connection rebind

---

src/hp/derp/client.rs
src/hp/derp/client_conn.rs
src/hp/derp/http/client.rs
src/hp/magicsock/conn.rs
src/hp/magicsock/endpoint.rs
src/hp/netcheck.rs

The remainder can be fixed as the code is being worked on.

ref: shut up clippy

---

src/hp/disco.rs
src/hp/magicsock/conn.rs
src/hp/netcheck.rs
src/lib.rs
tests/cli.rs

With this tests pass at least on my machine.

X hp test fix

---

src/hp/netcheck.rs

When no STUN sockets are supplied the netcheck actor needs to bind its
own sockets.  However this binding should be allowed to fail, and the
other probes should carry on.
Also fix a bug (again) that the socket listeners are terminated if the
actor binds its own sockets.
---
I'm still mulling if I can add a few tests for these bits.  Though
that should not stop review or approval :)
Closes #1025

fix(netcheck): If no STUN sockets supplied allow bind to fail

---

src/hp/magicsock/conn.rs

Note that I really don't know if this is a good idea, I just don't see how ping can work at all otherwise...

fix: add entry in peer_map for unknown ping sender

---

src/doctor.rs

- by default, use config
- if explicitily provided, use stun_host and stun_port
- fail if config does not contain a derp map and nothing was explicitly provided

fix: make sure to use the config by default in iroh doctor report

---

tests/cli.rs

Clippy seems to have regressed again.

fix(clippy): Clean up clippy again

---

src/blobs.rs
src/main.rs
src/provider/database.rs
src/provider/mod.rs
src/rpc_protocol.rs

This splits out listing content by blobs and collections

feat: add api to list collections

---

src/bin/derper.rs
src/hp/netcheck.rs
src/hp/netcheck/probe.rs

maybe it helps against test flakiness of `test_google_stun`
Servers from https://gist.github.com/mondain/b0ec1cf5f60ae726202e

fix: online stun test

---

src/bin/derper.rs

- use rooted fqdn
- use .context()? instead of .expect()
- typo

fix(derper): small derper fixes

---

.github/workflows/ci.yml

These are not run by default.  And you can not mix them with normal
tests apparently.

fix(ci): Also run doc tests

---

src/lib.rs
src/main.rs
src/provider.rs
src/runtime.rs
src/util.rs
tests/cli.rs

The exact place where we switch on a single threaded io runtime is TBD, but this at least seems to work...

Feat: Add iroh runtime wrapper and actually use thread per core

---

Cargo.lock
Cargo.toml
src/metrics/core.rs
src/metrics/macros.rs
src/tls/certificate.rs

Fortunately removes various duplicate deps

chore: update dependencies

---

Cargo.lock
Cargo.toml
iroh-bytes/Cargo.toml
iroh-bytes/src/get.rs
iroh-bytes/src/provider.rs
iroh-bytes/src/tokio_util.rs
iroh-io/src/http.rs
iroh-io/src/lib.rs
iroh-io/src/tokio_io.rs
iroh/Cargo.toml
iroh/src/main.rs

this is the first step of pluggable IO

use iroh-io everywhere

---

iroh/src/node.rs

alright CI, let's see how bad this breaks

refactor: change default bind port to iroh leet port: 11204

---

iroh/src/commands/provide.rs

fix(iroh): error when path does not exist

---

Cargo.lock
Cargo.toml
deny.toml
iroh-net/Cargo.toml
iroh-net/src/hp/key/node.rs

deps: update ed25519 and friends to released versions

---

iroh-net/src/bin/derper.rs
iroh-net/src/hp/derp/client.rs
iroh-net/src/hp/derp/http.rs
iroh-net/src/hp/derp/http/client.rs
iroh-net/src/hp/derp/http/mesh_clients.rs
iroh-net/src/hp/derp/http/server.rs
iroh-net/src/hp/derp/server.rs
iroh-net/src/hp/magicsock/conn.rs
iroh-net/src/hp/magicsock/derp_actor.rs

closes #913 
closes #1153 
TODO:

feat: derp mesh network & derper cli cleanup

---

Cargo.lock
iroh-net/Cargo.toml

hopefully makes cargo deny happy again

deps: update

---

iroh-net/src/hp/magicsock.rs
iroh-net/src/magic_endpoint.rs

ref https://github.com/n0-computer/iroh/issues/1183

test(iroh-net): disable flaky MagicEndpoint tests

---

iroh-net/src/lib.rs

Add some top-level docs for iroh-net

docs: iroh-net toplevel

---

.github/workflows/netsim.yml

For some reason the env var mappings have not been set correctly (presumably due to different scopes).
Moved to a more direct approach. This should bring CI back in order.

fix: netsim branch CI default

---

.github/workflows/netsim.yml

fix: default netsim branch

---

iroh-bytes/src/provider.rs
iroh/src/node.rs
iroh/tests/provide.rs

This allows buffer management and channel construction to be more flexible on the callers side.
Closes #1139

feat(iroh): pass a callback to subscribe

---

.github/workflows/ci.yml

We disabled release builds to speed up CI. Time to bring em back.
Closes https://github.com/n0-computer/iroh/issues/1207

chore(ci): bring back release builds

---

iroh-metrics/src/derpserver.rs
iroh-metrics/src/lib.rs
iroh-metrics/src/metrics.rs
iroh-net/docs/derp_regions.md
iroh-net/docs/local_derper.md
iroh-net/src/hp/derp.rs
iroh-net/src/hp/derp/client_conn.rs
iroh-net/src/hp/derp/clients.rs
iroh-net/src/hp/derp/http/client.rs
iroh-net/src/hp/derp/metrics.rs
iroh-net/src/hp/derp/server.rs
iroh-net/src/hp/magicsock.rs
iroh-net/src/hp/magicsock/conn.rs
iroh-net/src/hp/magicsock/derp_actor.rs
iroh-net/src/hp/magicsock/metrics.rs
iroh-net/src/hp/netcheck.rs
iroh-net/src/hp/netcheck/metrics.rs
iroh-net/src/hp/netcheck/reportgen.rs
iroh-net/src/hp/portmapper.rs
iroh-net/src/hp/portmapper/mapping.rs
iroh-net/src/hp/portmapper/metrics.rs
iroh-net/src/hp/portmapper/upnp.rs
iroh-net/src/lib.rs
iroh-net/src/metrics.rs
iroh/src/commands.rs
iroh/src/commands/doctor.rs

feat: add metrics to the derp server

---

iroh-net/src/hp/derp.rs
iroh-net/src/hp/derp/http.rs

Changes to some of the DERP documentation in the code.
This plus https://number-zero.notion.site/Iroh-Hole-Punching-b9a38cc228fb47328a73e71d10520418?pvs=4 rounds out the last documentation issues for the 0.5.0 milestone
closes #919
closes #918

Nits in the derp docs

---

CONTRIBUTING.md
code_of_conduct.md

Adds a `CONTRIBUTORS.md` and `code_of_conduct.md`
part of #1189 
Made to be as concise but complete as possible

chore(*): contributors guide

---

iroh-net/src/magic_endpoint.rs

I have sufficient information for now to work on improving this.  No
point in keeping a known flaky test in CI for now.
Part of #1183

test(iroh-net): Ignore MagicEndpoint test again

---

iroh-net/src/net/interfaces/bsd.rs

Fixes the panic we have seen in `bsd.rs` and should allow at least see the issue in logging, if there are more problems.
- https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctl.3.html
- https://doc.rust-lang.org/std/io/struct.Error.html#method.last_os_error

fix(iroh-net): do not panic on RIB issues

---

iroh/examples/sync.rs

feat: hammer sync example

---

iroh-gossip/src/proto/plumtree.rs

Add docs to plumtree types and functions
it seemed easier to contribute to your efforts @Frando this way vs a bunch of "pls add docs ty". Also helpful for me to do a better review

docs(iroh-gossip): plumtree

---

iroh-net/src/bin/derper.rs

Implements collecting metrics specifically about STUN requests on the Derper.
Should be straightforward.

add stun specific metrics to the Derper

---

.github/workflows/ci.yml

Main PR for https://github.com/n0-computer/iroh/pull/1326. 
Closes https://github.com/n0-computer/iroh/issues/1297.

fix(ci): correctly detect forks

---

iroh-sync/src/store.rs
iroh-sync/src/store/fs.rs
iroh-sync/src/store/memory.rs
iroh-sync/src/sync.rs
iroh/src/sync.rs
iroh/tests/sync.rs

refactor: simplify iroh-sync store trait

---

iroh/src/commands.rs

merging into the repl branch b/c it's affecting the CLI the most rn.
will close #1368 when it lands into main

remove outdated help text

---

iroh-gossip/src/net.rs

chore: improve code style of tracing calls

---

iroh-sync/src/store/fs.rs
iroh-sync/src/sync.rs
iroh/examples/client.rs
iroh/examples/sync.rs
iroh/src/client.rs
iroh/src/commands/sync.rs
iroh/src/sync_engine/live.rs
iroh/tests/sync.rs

Some quality of live improvements

refactor: improve client sync api

---

iroh-bytes/src/protocol/range_spec.rs

fix(iroh-bytes): range spec seq identification of single blobs

---

CHANGELOG.md

Release v0.6.0 alpha

---

Cargo.lock
iroh-sync/Cargo.toml
iroh-sync/proptest-regressions/ranger.txt
iroh-sync/src/ranger.rs
iroh-sync/src/sync.rs

This adds some property based tests for the ranger and fixes a bug in the pivot selection when splitting ranges

tests(iroh-sync): initial batch of property based tests for the ranger and store

---

.github/workflows/ci.yml
iroh-bytes/Cargo.toml
iroh-gossip/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-sync/Cargo.toml
iroh-test/Cargo.toml
iroh/Cargo.toml

Bump our rust versionfrom `1.67` to `1.70`.
closes #1441

bump `rust-version` and `MSRV` in ci to `1.70`

---

iroh-bytes/src/util/runtime.rs
iroh/examples/client.rs
iroh/examples/collection.rs
iroh/examples/hello-world.rs
iroh/examples/rpc.rs
iroh/examples/sync.rs
iroh/src/commands/get.rs
iroh/src/node.rs
iroh/tests/provide.rs
iroh/tests/sync.rs

refactor(iroh,iroh-bytes): replace `currrent` with `current`

---

LICENSE-APACHE
iroh-sync/LICENSE-APACHE

chore(iroh, iroh-sync): fill licence info

---

iroh/src/client.rs

fix: Debug for BlobReader

---

iroh-net/src/magicsock.rs
iroh-net/src/magicsock/endpoint.rs

While trying to understand the information we store for peers for #1481 I noticed this can be removed. It's more efficient in space in a couple of ways:
- It's not duplicated for every known peer
- Does not need to be cloned for every sent ping
- The `ActorMessage::SendDiscoMessage` that was removed had a size of 512bytes, making it the largest message of the enum. By replacing it with the two new ones the size of the `ActorMessage` size is reduced from 512 to 248. The whole change reduces the size of `Endpoint` from 784 to 560.
One place where this might be potentially less efficient is in calling `public_key()` on the `secret_key` for every sent ping. If this computation is expensive we can just cache the public key and use it there. Maybe @dignifiedquire knows if this should be done or …

(iroh-net): remove our public key from the endpoint

---

iroh/src/config.rs

Make the `IrohPaths` code easier to maintain using `strum` since it was recently added as a dependency
na

refactor(iroh): leverage `strum` for `IrohPaths`

---

Cargo.lock
iroh-bytes/Cargo.toml
iroh/Cargo.toml

increase bao-tree version number

increase bao-tree version number

---

CHANGELOG.md

chore: release v0.6.0

---

iroh-gossip/src/net/util.rs

Correctly remove peers that have been already dialed
na

fix(iroh-net): dialer bug

---

iroh-net/src/magic_endpoint.rs

Adds an e2e test for #1488 
na

tests(iroh-net): e2e saving and loading of peer data

---

Cargo.lock
iroh-net/src/derp/http/client.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/endpoint.rs

fix(net): avoid deadlock on stayin_alive calls

---

iroh-bytes/src/baomap.rs
iroh/examples/sync.rs
iroh/src/baomap.rs
iroh/src/baomap/flat.rs
iroh/src/baomap/mem.rs
iroh/src/baomap/readonly_mem.rs
iroh/src/client.rs
iroh/src/node.rs
iroh/src/rpc_protocol.rs

This adds methods in the client, RPC and node to add blobs from byte streams.

feat: add blobs from byte streams

---

iroh-net/src/magicsock/endpoint.rs

also simplifies the general logic around endpoint management

fix(net): stop deleting endpoints we want to keep

---

iroh/Cargo.toml
iroh/src/commands/doctor.rs
iroh/src/commands/node.rs
iroh/src/config.rs
iroh/src/util.rs
iroh/src/util/fs.rs
iroh/src/util/path.rs

Need this for the work on iroh-ffi to avoid duplicating code.

feat(iroh): export path and config related tooling

---

Cargo.lock
iroh/Cargo.toml
iroh/src/baomap/flat.rs

reflink-copy is a clone of the abandoned reflink crate. Last time there were some failures on android, so let's see if it works now...

feat(iroh): use reflink if possible

---

iroh-bytes/src/protocol.rs

the last place these were used in was CustomGet, which is gone now
Just some dead code elimination after removing CustomGet

remove write_lp and read_lp from iroh-bytes

---

iroh/src/commands.rs

Smoke testing a bit prior to release, found a few small wins on the docs frontier

docs: tune up docs before release

---

iroh-gossip/Cargo.toml
iroh-net/Cargo.toml
iroh-sync/Cargo.toml
iroh-sync/src/sync.rs
iroh/Cargo.toml

small fixes for the release

---

iroh-net/src/defaults.rs

We have a new set of derpers that are now on a more properly managed stack. We should default to those and will aim to keep them fresh.

chore(derp): update default derpers

---

iroh/tests/gc.rs

reduce number of iterations and also run in debug mode
The GC stress test was bitrotted because it was not adapted when moving the blob stores to iroh-bytes.
Why are tests not run in release mode at all?

Fix GC stress test

---

iroh/src/commands/doctor.rs

- print derp region to allow connecting by peer and region
- use the Display/FromStr of PublicKey directly
Before, we were dialing without derp region, which of course would never work.

fix(iroh-net): bring the doctor command up to date

---

iroh-bytes/src/get.rs
iroh-bytes/src/protocol/range_spec.rs
iroh-bytes/src/util.rs
iroh/src/commands/get.rs

A number of small improvements of the get side of the iroh-bytes API, needed for the tracker and the progress rework
I want to get those in separately to the above 2 PRs

iroh-bytes: Get api improvements

---

Cargo.lock
iroh-net/Cargo.toml
iroh-net/src/dns.rs
iroh-net/src/magicsock.rs
iroh-sync/Cargo.toml
iroh/Cargo.toml

- removes unused dep `wg`
- fixes #1442 by updating `default-net`

feat: update dependencies

---

iroh/src/commands/doctor.rs

- doctor accept can accept multiple connections at the same time (only the first one will get a GUI).
- gui on server side is properly cleared
This is useful when running doctor accept on a server, for async dogfooding.

iroh-net: doctor improvements

---

iroh-net/src/magicsock.rs

the previous code was confusing and had error states that should never occur

refactor(iroh-net): simplify handling of disco message sources

---

iroh/src/commands/doctor.rs

Gives some info about the connection status in the accept and connect gui:
```
Accepted connection from cxzdmvkbdiktcg24ojqrl7gydm6jzg2l6jo4v77d25gkio6czraa
derp region: 2, latency: 0.000432s, connection type: direct, addrs: [86.123.229.197:51103 (unknown); 192.168.1.132:51103 (0.000432s)]
send: 67.27 MiB/s
recv: 66.22 MiB/s
echo: 39.64 MiB/s
⠄ [█████████████████████████████▎                                                  ] send 5.84 MiB/16.00 MiB (81.29 MiB/s)          
```

iroh-bytes: Show connection status in doctor accept / connect GUI

---

Cargo.lock
iroh-gossip/Cargo.toml
iroh-net/bench/Cargo.toml

the locked version of tracing was yanked

deps(*): update tracing to fix audit failure

---

iroh-net/src/derp/client.rs
iroh-net/src/magicsock.rs

test(iroh-net): do not use fixed ports

---

iroh/src/commands/repl.rs

fix(iroh): cleanly exit on Eof

---

iroh-net/src/magicsock.rs

- `meta.len` is the length of the actually received data (not `buf.len()`)
- `meta.stride` is the length of an individual packet (not `meta.len`)
This was triggering https://github.com/n0-computer/iroh/issues/1696 because for STUN packets the additional (empty) buffer was considered to be QUIC packets, resulting in the warning.

fix(net): correct packet math for poll_recv

---

Cargo.lock
iroh-bytes/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-sync/Cargo.toml
iroh/Cargo.toml

removes unused dependencies from our crates

deps(*): remove unused deps

---

iroh-net/src/magicsock/endpoint.rs
iroh-net/src/magicsock/endpoint/best_addr.rs

This refactors how we use and calculate `best_addr`. It should not have any functional changes, only refactoring to make things more robust for the future.

refactor(iroh-net): Proper abstraction around `best_addr`

---

iroh-net/src/derp/http/client.rs

fix(net): correctly track dial errors

---

Cargo.lock

Closes #1707
Ref https://github.com/tkaitchuck/aHash/pull/171

fix: update ahash

---

iroh-net/examples/magic.rs

I don't think it can be used without this
Related to connectivity testing

make arguments to magic.rs connect named

---

iroh/tests/sync.rs

for now disable until it is less flaky

test: disable sync_big

---

.github/workflows/ci.yml
.github/workflows/test.sh
iroh-bytes/Cargo.toml

Should keep CI run time lower and let us still check per crate builds.

chore: split test and check steps into workspace and per crate

---

.github/workflows/ci.yml

fix: release builds

---

iroh/src/commands/sync.rs

this allows to view the full hash of the value

feat(iroh): allow full and short hash printing in the cli

---

Cargo.lock
iroh-sync/src/store/fs.rs

Closes https://github.com/n0-computer/iroh/issues/1806

fix(iroh-sync): ensure the authors table exists

---

iroh/src/commands.rs
iroh/src/commands/rpc.rs
iroh/src/commands/start.rs
iroh/src/config.rs

Some small refactors and code improvements on top of #1802

refactor: small code improvements and cleanups in CLI

---

.github/workflows/netsim.yml

Should close https://github.com/n0-computer/iroh/issues/1832

fix(ci): enable forks to run netsim manually

---

iroh-bytes/src/protocol.rs
iroh-bytes/src/provider.rs
iroh/src/commands.rs
iroh/src/commands/blob.rs
iroh/src/commands/start.rs
iroh/src/node.rs
iroh/src/rpc_protocol.rs
iroh/src/ticket/blob.rs
iroh/tests/provide.rs

Removes the request token from iroh-bytes, and everywhere else
Ticket format changes. Do we care?

refactor(iroh): remove request token

---

iroh/src/get.rs
iroh/src/util/fs.rs

This fails CI currently.
See
https://github.com/n0-computer/iroh/actions/runs/7085234394/job/19281076207
for a failure.  Locally I don't see this for some reason though?

chore(clippy): Fix some warnings

---

iroh/src/bootstrap.js
iroh/src/commands/runtime.rs

moar methods for runtime

---

iroh-bytes/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

Add a few keywords to the crates
Not sure which keywords to use here. But some are definitely better than none...

Add a few keywords to the crates

---

.github/workflows/ci.yml

Latest nightly panics.  That's no good.

chore(ci): Pin clippy to specific nightly version

---

.github/workflows/ci.yml

This enables sccache for the windows self-hosted runners, which are
now configured for this.
See https://github.com/n0-computer/iroh/issues/1864

chore(ci): Windows sccache

---

iroh-net/src/magicsock/peer_map/endpoint.rs

fix(iroh-net): fix display of mixed type connections

---

iroh-bytes/Cargo.toml
iroh/Cargo.toml

chore(iroh,iroh-bytes): fix manifest keywords

---

iroh/tests/gc.rs

Disable gc_partial test and increase timeouts

---

.github/ansible/redeploy-derper.yml
.github/workflows/test_derper.yml

Deploys the test derper on a daily basis at 4am. Can also be manually triggered to bump.

chore(ci): test derper deploy flow

---

iroh/src/commands/rpc.rs

Otherwise the console exits after each command

fix(iroh): do not exit after commands

---

iroh-net/src/magicsock.rs

This was an extremely hot loop, hammering the netcheck actor with
requests and flooding the logs.

refactor(tests): Slow down a hot loop

---

iroh/tests/sync.rs

tests(iroh): sort output in test for download policies

---

.github/workflows/release.yml
.github/workflows/test.sh
.github/workflows/test_derper.yml

Latest release was not pushed with the tag latest, also did some cleanup.

fix(ci): cleanup and fix bugs

---

iroh/tests/cli.rs
iroh/tests/provide.rs

I think all of these are filesystem related.
Issue filed in #1935

tests: Mark a bunch of flaky tests

---

iroh-bytes/src/format/collection.rs
iroh/src/client.rs
iroh/src/node.rs
iroh/src/rpc_protocol.rs

feat(iroh): add blobs.create_collection api endpoint

---

iroh-gossip/src/proto.rs

docs(iroh-gossip): fix typo in proto.rs

---

iroh/Cargo.toml
iroh/src/client.rs
iroh/src/commands/blob.rs

- adds `iroh.blobs.share`
- adds `iroh.blobs.status`
Closes #1978

fix(iroh): improve and test blob share

---

Cargo.lock

Update dance because crate got yanked.

chore(deps): Update yanked crate

---

.github/workflows/ci.yml
.github/workflows/release.yml
.github/workflows/test_derper.yml
iroh-base/Cargo.toml
iroh-bytes/Cargo.toml
iroh-gossip/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh-sync/Cargo.toml
iroh-test/Cargo.toml
iroh/Cargo.toml

Switch to MSRV 1.75
Just the switch, nothing else.

Switch to MSRV 1.75

---

iroh-net/src/dns.rs

feat(iroh-net): DNS queries: lookup ipv6 & ipv4 in parallel

---

iroh-net/src/magicsock.rs

If udp and derp errored (or are not available) but we have sent pings, this would wrongly report that all transmits were sent.

fix(iroh-net): correctly report sent transmits in poll_send

---

iroh-net/src/netcheck/reportgen.rs

Now that we start supporting IPv6 we see this a lot more.  If we have
a dual-stack machine it does not mean the IPv6 network is routable.
If the network is not routable there is no point in trying more
attempts in the probeset, this just delays the failure.  This results
in a visible speed up on my local machine.
Tested on routed and unrouted dual-stack machines

fix(iroh-net): Handle unreachable IPv6 networks better

---

Cargo.lock

cargo-deny is unhappy with this yanked version currently.

deps: Upgrade away from yanked bumpalo version

---

iroh-net/src/dns.rs

This is extremely likely to be related to #2069, so not filing a new
issue.

tests(iroh-net): Mark some DNS tests as flaky as well

---

iroh/Cargo.toml
iroh/src/node.rs
iroh/src/node/builder.rs

- make sure the sync engine is shutdown in time
- enable `fs-store` by default

fix(iroh): shutdown sync engine on iroh node shutdown

---

iroh-gossip/src/net.rs

This would have spared me some debugging if I knew beforehand.

docs(gossip): add comment about message uniqueness

---

iroh-bytes/src/get/db.rs
iroh-bytes/src/store/fs.rs
iroh-bytes/src/store/fs/import_flat_store.rs
iroh-bytes/src/store/fs/tables.rs

fix(iroh-bytes): reduce log level from info to debug for most uncritical operations
implements https://github.com/n0-computer/iroh/issues/2194

fix(iroh-bytes): reduce log level from info to debug for most uncritical operations

---

iroh-net/src/discovery/pkarr_publish.rs

log the info we publish to pkarr, and a span for identification in tests

fix(iroh-net): better logging for pkarr publish

---

.github/workflows/ci.yml

Provides the `HEAD_COMMIT_SHA` var also on merge group/push events so that it correctly does this on main too.

fix: semver check on main

---

.github/workflows/release.yml

fix(ci): minor corrections for manual release runs

---

Cargo.lock
iroh-bytes/Cargo.toml
iroh-dns-server/Cargo.toml
iroh-net/Cargo.toml

Ref https://github.com/rustls/rustls/security/advisories/GHSA-6g7w-8wpp-frhj

fix(deps): update rustls

---

iroh-bytes/src/downloader/invariants.rs
iroh-bytes/src/util/progress.rs
iroh-net/src/netcheck.rs
iroh-net/src/relay/clients.rs
iroh-sync/src/store/fs/tables.rs
iroh/src/node/builder.rs
iroh/tests/gc.rs

new beta clippy has more to fix :)

refactor: happy clippy

---

iroh-net/src/magicsock.rs

Now tracks `Magicsock::Metrics::recv_data_ipv4` and `Magicsock::Metrics::recv_data_ivp6`.
closes #2184

fix(iroh_net): track `recv_data_ipv4` & `recv_data_ipv6`

---

iroh/tests/sync.rs

See https://github.com/n0-computer/iroh/issues/2244 for reference

test: mark iroh::sync_big flaky

---

iroh-net/src/relay/http/server.rs

In the relay server, we currently log all connection failures with `error` severity. This means that whenever a node disconnects while still in the TLS handshaking phase, we get an error log.:
```
2024-05-02T09:00:38.443215Z ERROR relay server{me=svfacrfjgmv7fjeu}:relay-http-serve:conn{peer=127.0.0.1:33596}: iroh_net::relay::http::server: [HTTPS] relay: failed to handl
e connection: TLS[manual] accept
```
This however is a perfectly fine thing, a node may decide to abort the connection to a relay whenever it pleases. Especially in tests we often shutdown while still in the process of connecting to a relay. This is annoying, because the `error` severity indicates things being wrong (especially with the stack traces we print on error logs in the CI).
This PR checks if the error is a EOF and …

fix(iroh-net): do not log as error if client disconnects from relay

---

iroh-net/Cargo.toml
iroh-net/src/discovery.rs
iroh-net/src/magic_endpoint.rs
iroh-net/src/test_utils.rs
iroh/src/node.rs
iroh/src/node/builder.rs

* allow to set a custom DNS resolver in the node builder
* slight refactor of pkarr/dns test utils
* add test using test servers for node discovery to `iroh`

feat(iroh-net): Expose DNS resolver

---

iroh-net/src/dns.rs
iroh-net/src/netcheck/reportgen.rs

This reverts commit 93bcaa5a6adf92856eeb9938b4c4921aa6e3dfae.
Re-opens #2086

tests: Disable flaky tests on windowns again

---

iroh-gossip/Cargo.toml
iroh-gossip/src/net.rs

* Use shared test setup code from `iroh_net`
* Fix stupid typo

tests(iroh-gossip): fix `net` smoke test 

---

iroh-gossip/src/net.rs

Fixes https://github.com/n0-computer/iroh/issues/2307

fix(iroh-gossip): do not drop existing connection on incoming one

---

.github/workflows/ci.yml

ensure we use the latest version of clippy in CI

chore(ci): update clippy

---

iroh-base/src/key.rs
iroh-base/src/node_addr.rs

This follows
https://github.com/rust-lang/rfcs/blob/master/text/1574-more-api-documentation-conventions.md#appendix-a-full-conventions-text
and updates the doc comments in an attempt to be more user-friendly.

docs(iroh-net): Update NodeAddr docs

---

iroh-net/src/endpoint.rs
iroh/src/node/builder.rs
iroh/src/node/protocol.rs

Addresses review by @flub on #2358 (which is already merged).

docs: fix spelling in new protocol handler docs

---

iroh-cli/src/commands/start.rs

test: increase timeout test_run_rpc_lock_file

---

Cargo.lock
iroh-blobs/Cargo.toml
iroh-blobs/src/format/collection.rs

Fix https://github.com/n0-computer/iroh-ffi/issues/152
None

fix(iroh-bytes): Fix off-by-one error in Collection::load

---

iroh/src/client/gossip.rs
iroh/src/lib.rs

Otherwise the api is painful to work with

feat(iroh): add missing gossip reexports

---

iroh-net/src/bin/iroh-relay.rs
iroh-net/src/relay/http/server.rs

This improves the error output for the binary.

feat(iroh-relay): add more context to iroh-relay errors

---

Cargo.lock
iroh-net/Cargo.toml

Closes https://github.com/n0-computer/iroh/issues/2448

feat(iroh-net):  update netdev to 0.30

---

.github/workflows/ci.yml
CHANGELOG.md
CONTRIBUTING.md
iroh-dns-server/src/store.rs
iroh-docs/src/engine.rs
iroh-net/bench/src/iroh.rs
iroh-net/bench/src/quinn.rs
iroh-net/src/dns.rs
iroh-net/src/magicsock.rs
iroh-net/src/netcheck/reportgen.rs
iroh-net/src/netcheck/reportgen/probes.rs
iroh-net/src/portmapper/pcp/protocol.rs
iroh-net/src/tls/certificate.rs
iroh/src/util/fs.rs

% `codespell --ignore-words-list=ans,crate,inout,ratatui,ser,stayin,swarmin,worl`
* https://github.com/codespell-project/codespell

docs: fix typos discovered by codespell

---

iroh-gossip/src/net.rs

The connection loop of iroh-gossip misused tokio-select by selecting over a future that is not cancellation safe. This means that if the timings are bad, the message reading future would be aborted midway in a message, and then restart by reading a length, which would then yield some random number because it would be reading some random bytes in the middle of a message. This means it would lead to random connection drops.
Backport from #2570

fix(iroh-gossip): connection loop misuses `tokio::select!` leading to read errors

---

iroh-net/src/magicsock/node_map/node_state.rs

This makes it a bit earier to read.  It's harder to figure out if thre
are changes to the ConnectionType though, but let's assume that
doesn't happen too often.
None
I'm open to other ways of structuring this code.  Not entirely sure
what the best shape would be.

ref(iroh-net): Don't write the match as fully exhaustive

---

iroh/src/lib.rs

Just a missing doc change that I noticed when trying to answer a Q on discord.
None

docs: Also list `iroh-gossip` as a re-export

---

iroh-net/src/endpoint.rs
iroh-net/src/magicsock.rs
iroh-net/src/magicsock/node_map.rs

My NodeMap is completely empty when calling `msock_2.get_mapping_addr()` and I am stumped.

Start adding tests for some odd paths in try_send

---

.github/workflows/docker.yaml
.github/workflows/release.yml

Allows us to rebuild binaries for a release and attach them again.
Fixes docker input passing when doing a workflow call.

fix(ci): fix docker builds on release & release rebuilds

---

deny.toml
iroh-blobs/src/get/db.rs
iroh-net/src/netcheck.rs

chore: fix clippy@1.81.0 and cargo deny

---

iroh-cli/src/commands/rpc.rs

Update documentation to tags command.

docs(iroh-cli): update `rpc` command documentation

---

iroh-cli/src/commands/gossip.rs

Update documentation to `console` commands.

docs(iroh-cli): update `gossip` command documentation

---

iroh-cli/src/commands/tags.rs

Update documentation to `tags` command.

docs(iroh-cli): update `tags` command documentation

---

iroh-cli/src/commands/docs.rs

Fixes a typo introduced in a previous PR.

docs(iroh-cli): fix typo

---

.github/workflows/netsim_runner.yaml

Simply skips the troublesome step if it's not configured properly (due to missing org secrets).

fix(ci): make netsim work on forks

---

iroh-net/src/discovery/pkarr.rs

That makes the log message so much more useful

refactor(iroh-net): log the pkarr relay when publishing

---

iroh-net/src/netcheck/reportgen.rs

This spawned task was missing tracing span context.  We should always
call .instrument().
None
I wish this wouldn't be such a manual thing.  I guess we could create
a spawn API that always does this, but even then we have to remember
to use that API and not this one.  You could probably do something
with linting for not allowing some APIs.  Anyway, not now.

refactor(iroh-net): Add tracing span context to spawned tasks

---

iroh-net/src/relay/map.rs

docs(relay): fix typos in map.rs

---

iroh-net/src/magicsock/relay_actor.rs

When the connection to the relay server fails the read channel will return a read error.  At this point the ActiveRelay actor will passively wait until it has been asked to send something again before it will re-establish a connection.
However if the local node has no reason to send anything to the relay server, the connection is never re-established.  This is problematic when the relay has remote nodes trying to send to this node.  This doubly problematic when the connection is to the home relay: the node just sits there thinking everything is healty and quiet, but no traffic is reaching it.
In a node with active traffic this doesn't really show up, since a send will be triggered quickly for an active connection and the connection with the relay server would be re-established.
The start …

fix(iroh-net): Keep the relay connection alive on read errors

---

iroh-net/src/endpoint.rs
iroh-net/src/magicsock/metrics.rs
iroh-net/src/magicsock/node_map/node_state.rs

New metrics:
- `nodes_contacted`
- `nodes_contacted_directly`

feat(iroh-net): Add metrics for directly contacted nodes

---

iroh-net/src/lib.rs

This gives at least some quick indication of how to make things work.

docs(iroh-net): Add examples to the module docs

---

Cargo.lock

Update postcard to get rid of yanked critical-section dep
None
None

fix(deps): update postcard to get rid of yanked critical-section

---

iroh-base/src/node_addr.rs

A user did get confused about this, so fair enough.
None
Closes #2802 
Please review my comman use.  I feel entirely incompetent in using
commas.

docs(iroh-base): clarify AddrInfoOptions a little

---

iroh-net/src/relay/server/streams.rs

It seems the newer rust release enforces missing docs on this as well.
None

docs(iroh-net): Document cfg(test) items as well

---

Cargo.lock
iroh-base/Cargo.toml
iroh-blobs/Cargo.toml
iroh-cli/Cargo.toml
iroh-dns-server/Cargo.toml
iroh-docs/Cargo.toml
iroh-gossip/Cargo.toml
iroh-metrics/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

increases version numbers for `iroh-base` and `iroh-metrics`, which have been published, and updates references to them

chore: increase version numbers and update

---

.github/workflows/flaky.yaml

Just prefixes the discord message with the repository name. See [this msg](https://discord.com/channels/949724860232392765/1194275793220665375/1298560426392555601) generated from this PR.

chore(ci): Identify which repository the flakes are reported for

---

iroh-net/src/endpoint.rs
iroh-net/src/test_utils.rs

test(iroh-net): Write a regression test for connecting to a relay without STUN

---

iroh-net/src/relay/client.rs

Reverse proxies that map multiple virtual hosts need some help to know where to forward requests to.
That's what the [`HOST` header](https://datatracker.ietf.org/doc/html/rfc2616#section-14.23) is for, and it's mandatory for HTTP/1.1 requests.
Closes #2870 

feat(iroh-net): Send HTTP/1.1 `HOST` header on requests to relay

---

iroh-net/src/discovery/pkarr/dht.rs

This test had a hardcoded sleep(1) in there, which is a recipe for
flaky tests on CI.  Write this more defensively.
I'm kind of tempted to also remove the flaky marker, but who knows.

tests(iroh-net): Make dht_discovery_smoke test less flaky

---

.github/workflows/netsim_runner.yaml

This bug actually hid some of the netsim failures. The PR fixes that and gives a link to some logs so you can debug.

fix(ci): better error reporting on netsim fails

---

deny.toml

icu switched from some draft unicode licence to unicode-3.0. It's basically MIT with some seasoning.

chore: update deny.toml

---

.github/workflows/release.yml

Can now be used to generate artifacts without having to batch it together with making a release.

chore(ci): easy manual builds for binaries

---

.github/workflows/release.yml

This is getting very annoying but very inconvenient to test and docs & alignment between GHA and platform is less than ideal.

chore(ci): fix uploads of release artifacts again

---

iroh-dns-server/src/http/rate_limiting.rs

Cargo docs was complaining about the links being incorrect.  Also the
style guide was not being followed.
Not sure how the incorrect links made it in.
Also, when will we have a linter for the style guide...

docs(iroh-dns-server): Fixup rate limit config docs

---

.github/workflows/release.yml

This is it, as tested manually in https://github.com/n0-computer/iroh/pull/2897
https://github.com/n0-computer/iroh/actions/runs/11682746623/job/32530542557?pr=2897

chore(ci): fix for asset bundles

---

iroh-net/src/netcheck/reportgen.rs

A non-zero port is interpreted as overriding the port specified or
implied by the URL.  Despite the docs not telling you this.  That's
not really what we want here.
https://github.com/seanmonstar/reqwest/issues/2413#issuecomment-2405545067

fix(iroh-net): Do not return a port for reqwest DNS resolver

---

Cargo.lock
iroh-base/Cargo.toml
iroh-net/Cargo.toml
iroh/Cargo.toml

All later versions are broken
https://github.com/rust-lang/cc-rs/issues/1278

fix: enforce cc@1.1.31

---

deny.toml

This crate is unmaintained, but used indirectly by some dependencies.
No big deal.

deps: Accept unmaintained crate for now

---

iroh-net/src/endpoint/rtt_actor.rs

When the endpoint is dropped the rtt-actor should be shut down.  This
makes sure this actually happens.
Fixes #2911
Also make sure the task is aborted on drop.  We should always do this anyway.

fix(iroh-net): Make sure the rtt-actor is shutdown correctly

---

iroh-relay/src/server.rs

This resulted in memory accumulation , due to blocking threads not getting shutdown, once started. According to the docs from tokio, there is no way to cleanup these tasks/threads, once they have been started.
From the docs: https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html
> Be aware that tasks spawned using spawn_blocking cannot be aborted because they are not async. If you call [abort](https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#method.abort) on a spawn_blocking task, then this will not have any effect, and the task will continue running normally. The exception is if the task has not started running yet; in that case, calling abort may prevent the task from starting.
> 
> When you shut down the executor, it will wait indefinitely for all blocking …

fix(iroh-relay): do not use spawn_blocking in stun handler

---

.github/workflows/release.yml

Allows us to build and push builds without affecting scripts user use to install or pull the latest release. Useful for testing spin off builds.

chore: extend CI build job config

---

.github/workflows/ci.yml
.github/workflows/tests.yaml

add iroh-node-util to tests
none

chore(iroh-node-util): add iroh-node-util to tests

---

Cargo.lock
iroh/Cargo.toml

fix(iroh): remove iroh dev self dep

---

iroh/src/endpoint.rs
iroh/src/lib.rs
iroh/src/ticket.rs

Otherwise one has to pull in some things from `iroh-base` and some from here
None, just additions

feat(iroh): make all important iroh_base types available

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-net-report/Cargo.toml
iroh-relay/Cargo.toml
iroh/Cargo.toml
iroh/bench/Cargo.toml

`iroh-metrics@0.29.0` was just published

feat: update to iroh-metrics@0.29.0

---

iroh/src/magicsock/relay_actor.rs

We manually created a function that was already provided by the
CancellationToken.  Use the one from the library for consistency.

refactor(iroh): Remove with_cancel, use run_until_cancelled

---

iroh/src/magicsock/relay_actor.rs

refactor(iroh): improve get active_relay path

---

iroh/src/util.rs

This removes a footgun where after polling the future it is easy to
forget to call MaybeFuture::set_none, which can result in a panic if
the inner future is not fused.

fix-or-feat(iroh): Set MaybeFuture to None on Poll::Ready

---

.github/workflows/beta.yaml
.github/workflows/flaky.yaml

ci: Use variable to construct URL

---

Cargo.lock
Cargo.toml
iroh-dns-server/Cargo.toml
iroh-net-report/Cargo.toml
iroh-relay/Cargo.toml
iroh/Cargo.toml
iroh/bench/Cargo.toml

chore: upgrade `portmapper` and `netwatch` deps

---

README.md

chore: update broken echo.rs link

---

iroh-relay/src/dns.rs

Removes `IntoName` trait from `hickory_proto` from the public API of `iroh::dns` module, to not commit to hickory types in our potential 1.0 API. Replaces the `impl IntoName` with `impl ToString`, which covers all our existing usages.
This might incur a small perfomance penalty if you already have a hickory `Name` at the call site, but I don't think it will matter in practice.
* The methods in `iroh::dns::DnsResolver` now take an `impl ToString` instead of `impl hickory_proto::rr::domain::IntoName` for their `host` argument

refactor: Remove `hickory_proto`s `IntoName` from public API surface of `iroh`, replace with `ToString`

---

iroh/src/lib.rs

Fixes a documentation link.
Closes #3231

docs(iroh): Fix quicwg.org link

---

Cargo.lock
iroh-base/Cargo.toml
iroh-base/src/key.rs
iroh-base/src/ticket.rs
iroh-relay/Cargo.toml

Basically what it says on the tin.

Make `iroh-base` use snafu more similar to other code

---

iroh-relay/src/main.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh-relay/src/server/client.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs
iroh-relay/src/server/resolver.rs
iroh/src/net_report/reportgen/probes.rs

replace anyhow with snafu in the server side of the iroh-relay library code

feat(iroh-relay): replace `anyhow` with `snafu` in the server side of the `iroh-relay` library code

---

iroh/src/discovery.rs
iroh/src/discovery/dns.rs
iroh/src/discovery/mdns.rs
iroh/src/discovery/pkarr.rs
iroh/src/discovery/pkarr/dht.rs
iroh/src/discovery/static_provider.rs
iroh/src/endpoint.rs

convert the errors in `discovery` from `anyhow` to `snafu`

feat(iroh): convert `discovery` module to use `snafu` errors

---

iroh-relay/src/client.rs
iroh-relay/src/client/conn.rs
iroh-relay/src/node_info.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/protos/stun.rs
iroh-relay/src/quic.rs
iroh-relay/src/server.rs
iroh-relay/src/server/client.rs
iroh-relay/src/server/clients.rs
iroh-relay/src/server/http_server.rs

I used to add `snafu(visibility(pub(crate)))` for no reason apart from consistency. Not worth doing that!

Cleanup unused `snafu(visibility(pub(crate)))`

---

Cargo.lock
iroh/src/endpoint.rs

chore(iroh): Convert tests to using `n0_snafu::TestResult`

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-relay/Cargo.toml
iroh-relay/src/main.rs
iroh-relay/src/quic.rs
iroh/Cargo.toml
iroh/src/tls/resolver.rs
iroh/src/tls/verifier.rs

Dedupe a couple of crates, because why not.

iroh(deps): Dedupe lru and webpki

---

iroh/src/net_report/reportgen.rs

This bug was likely introduced in the error refactoring, by myself..

fix(iroh): correctly hook up ipv6 addr lookups

---

Cargo.lock
iroh-dns-server/Cargo.toml
iroh-dns-server/examples/convert.rs
iroh-dns-server/examples/publish.rs
iroh-dns-server/src/dns.rs
iroh-dns-server/src/http/doh/extract.rs
iroh-relay/Cargo.toml
iroh-relay/src/client/tls.rs
iroh-relay/src/main.rs
iroh-relay/src/node_info.rs
iroh-relay/src/protos/relay.rs
iroh-relay/src/server.rs
iroh-relay/src/server/http_server.rs
iroh/Cargo.toml
iroh/bench/Cargo.toml
iroh/examples/0rtt.rs
iroh/examples/dht_discovery.rs
iroh/examples/search.rs
iroh/src/disco.rs
iroh/src/discovery.rs
iroh/src/discovery/mdns.rs
iroh/src/discovery/static_provider.rs
iroh/src/magicsock/transports/relay/actor.rs
iroh/src/net_report.rs
iroh/src/net_report/reportgen.rs
iroh/src/protocol.rs
iroh/src/test_utils.rs

Upgrade to the latest `iroh-metrics`, `portmapper`, and `swarm-discovery`.
We can finally remove our `anyhow` direct dependency!

chore(*): upgrade to the latest `iroh-metrics`, `portmapper`, and `swarm-discovery`

---

iroh/src/defaults.rs

These are the ones with the new `0.91` relay code

feat(iroh): update to new relay servers

---

iroh-base/src/node_addr.rs

Fixes #3425 
Derives `Hash` for `NodeAddr`

feat(iroh-base): derive Hash for NodeAddr

---

.github/ISSUE_TEMPLATE/bug_report.md

Ask users for the iroh version, commit hash and some configuration
setup.
The hints might need to be tweaked further, feel free to suggest changes.

chore(github): Update issue template

---

iroh-relay/src/main.rs

fix(relay): respect enable_relay flag
